  INFO root [0x00001b6c] [2018-08-23 10:59:18,561] - 
  INFO root [0x00001b6c] [2018-08-23 10:59:18,650] - -----------------------------------------------------------------------------------------


  INFO root [0x00001b6c] [2018-08-23 10:59:20,453] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [0x00001b6c] [2018-08-23 10:59:20,455] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [0x00001b6c] [2018-08-23 10:59:20,455] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [0x00001b6c] [2018-08-23 10:59:21,090] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:20015 )
  INFO root [0x00001b6c] [2018-08-23 10:59:21,110] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.106:20015, SOMAXCONN=128.
  INFO root [0x00001b6c] [2018-08-23 10:59:21,116] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:50045 )
  INFO root [0x00001b6c] [2018-08-23 10:59:21,116] - NetworkInterface::initialize(INTERNAL): address 192.168.0.106:50045, SOMAXCONN=128.
  INFO root [0x00001b6c] [2018-08-23 10:59:21,117] - server-configs:
  INFO root [0x00001b6c] [2018-08-23 10:59:21,117] - 	gameUpdateHertz : 10
  INFO root [0x00001b6c] [2018-08-23 10:59:21,117] - 	entryScriptFile : kbemain
  INFO root [0x00001b6c] [2018-08-23 10:59:21,118] - 	internalAddr : 192.168.0.106:50045
  INFO root [0x00001b6c] [2018-08-23 10:59:21,118] - 	externalAddr : 192.168.0.106:20015
  INFO root [0x00001b6c] [2018-08-23 10:59:21,118] - 	componentID : 7001
  INFO root [0x00001b6c] [2018-08-23 10:59:21,978] - Components::findLogger: found logger, addr:192.168.0.106:50029
  INFO root [0x00001b6c] [2018-08-23 10:59:21,978] - Components::addComponent: reset orderLog, uid=22428!
  INFO root [0x00001b6c] [2018-08-23 10:59:21,979] - Components::addComponent[logger], uid=22428, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00001b6c] [2018-08-23 10:59:22,278] - ---- baseapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: F9DFFB319FBADF35943ADF4D42C4718C. Config: Debug X86. Built: 15:53:31 Apr 29 2018. AppID: 7001. UID: 22428. PID: 7312 ----
  INFO root [0x00001b6c] [2018-08-23 10:59:22,278] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [0x00001b6c] [2018-08-23 10:59:22,488] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00001b6c] [2018-08-23 10:59:22,541] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x00001b6c] [2018-08-23 10:59:27,357] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00001b6c] [2018-08-23 10:59:27,407] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x00001b6c] [2018-08-23 10:59:27,480] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x00001b6c] [2018-08-23 10:59:27,892] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x00001b6c] [2018-08-23 10:59:27,970] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x00001b6c] [2018-08-23 10:59:28,028] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x00001b6c] [2018-08-23 10:59:28,078] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x00001b6c] [2018-08-23 10:59:28,459] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x00001b6c] [2018-08-23 10:59:28,981] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x00001b6c] [2018-08-23 10:59:28,982] - Script::install(): KBExtra is successfully!
 DEBUG root [0x00001b6c] [2018-08-23 10:59:29,749] - loaded entity-script:Account(1).
 DEBUG root [0x00001b6c] [2018-08-23 10:59:29,751] - loaded entity-script:CheckName(2).
 DEBUG root [0x00001b6c] [2018-08-23 10:59:29,791] - loaded entity-script:Halls(3).
 DEBUG root [0x00001b6c] [2018-08-23 10:59:29,811] - loaded entity-script:Room(4).
  INFO root [0x00001b6c] [2018-08-23 10:59:29,811] - Baseapp::initializeEnd: started resmgr tick(60s)!
  INFO root [0x00001b6c] [2018-08-23 10:59:29,896] - TelnetServer server is running on port 40000
  INFO root [0x00001b6c] [2018-08-23 10:59:30,317] - ---- baseapp is running ----
 DEBUG root [0x00001b6c] [2018-08-23 10:59:30,317] - Components::process(): Request for the process of identity...
  WARN root [0x00001b6c] [2018-08-23 10:59:36,466] - Forwarding logs to logger[192.168.0.106:50029/0/0/0]...
 ERROR root [0x00001b6c] [2018-08-23 11:00:10,017] - Account::onRemoteMethodCall: onLeaveRoom not is exposed, call is illegal! srcEntityID:2002! 
 ERROR root [0x00001b6c] [2018-08-23 11:21:07,032] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x00001b6c] [2018-08-23 11:21:07,037] - The following logs sent to logger failed:
  WARN root [0x00001b6c] [2018-08-23 11:21:07,037] - ==> [2018-08-23 11:21:07 031] TCPPacketReceiver::processPendingEvents(192.168.0.106:50029): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00001b6c] [2018-08-23 11:21:07,037] - ==> [2018-08-23 11:21:07 033] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x00001b6c] [2018-08-23 11:21:07,084] - TCPPacketReceiver::processPendingEvents(192.168.0.106:50031): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00001b6c] [2018-08-23 11:21:07,086] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x00001b6c] [2018-08-23 11:21:07,106] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [0x00001b6c] [2018-08-23 11:21:07,107] - onBaseAppShutDown: state=0
  INFO root [0x00001b6c] [2018-08-23 11:21:07,107] - Shutdowner::onShutdown: shutting down
S_INFO root [0x00001b6c] [2018-08-23 11:21:07,107] - onBaseAppShutDown: state=1
  INFO root [0x00001b6c] [2018-08-23 11:21:07,107] - Shutdowner::onShutdownEnd: shutting down
S_INFO root [0x00001b6c] [2018-08-23 11:21:07,107] - onBaseAppShutDown: state=2
 ERROR root [0x00001b6c] [2018-08-23 11:21:07,200] - Account::onCellWriteToDBCompleted(2002): not found dbmgr!
 ERROR root [0x00001b6c] [2018-08-23 11:21:07,201] - Entity::onDestroy: not found dbmgr!
 ERROR root [0x00001b6c] [2018-08-23 11:21:07,202] - Account::onCellWriteToDBCompleted(2004): not found dbmgr!
 ERROR root [0x00001b6c] [2018-08-23 11:21:07,203] - Entity::onDestroy: not found dbmgr!
 DEBUG root [0x00001b6c] [2018-08-23 11:21:07,204] - Account::~Account(): 2002
 DEBUG root [0x00001b6c] [2018-08-23 11:21:07,204] - Account::~Account(): 2004
 DEBUG root [0x00001b6c] [2018-08-23 11:21:07,205] - Room::~Room(): 2003
 DEBUG root [0x00001b6c] [2018-08-23 11:21:07,205] - Halls::~Halls(): 2001
 DEBUG root [0x00001b6c] [2018-08-23 11:21:07,222] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00001b6c] [2018-08-23 11:21:07,222] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x00001b6c] [2018-08-23 11:21:07,222] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x00001b6c] [2018-08-23 11:21:07,222] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x00001b6c] [2018-08-23 11:21:07,222] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x00001b6c] [2018-08-23 11:21:07,222] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x00001b6c] [2018-08-23 11:21:07,222] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x00001b6c] [2018-08-23 11:21:07,222] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x00001b6c] [2018-08-23 11:21:07,261] - Script::uninstall(): is successfully!
 DEBUG root [0x00001b6c] [2018-08-23 11:21:07,261] - ThreadPool::destroy(): starting size 2.
  INFO root [0x00002e40] [2018-08-23 11:21:08,249] - 
  INFO root [0x00002e40] [2018-08-23 11:21:08,251] - -----------------------------------------------------------------------------------------


  INFO root [0x00002e40] [2018-08-23 11:21:08,251] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [0x00002e40] [2018-08-23 11:21:08,251] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [0x00002e40] [2018-08-23 11:21:08,252] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [0x00002e40] [2018-08-23 11:21:08,257] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:20015 )
  INFO root [0x00002e40] [2018-08-23 11:21:08,257] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.106:20015, SOMAXCONN=128.
  INFO root [0x00002e40] [2018-08-23 11:21:08,264] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:50299 )
  INFO root [0x00002e40] [2018-08-23 11:21:08,264] - NetworkInterface::initialize(INTERNAL): address 192.168.0.106:50299, SOMAXCONN=128.
  INFO root [0x00002e40] [2018-08-23 11:21:08,264] - server-configs:
  INFO root [0x00002e40] [2018-08-23 11:21:08,264] - 	gameUpdateHertz : 10
  INFO root [0x00002e40] [2018-08-23 11:21:08,264] - 	entryScriptFile : kbemain
  INFO root [0x00002e40] [2018-08-23 11:21:08,264] - 	internalAddr : 192.168.0.106:50299
  INFO root [0x00002e40] [2018-08-23 11:21:08,264] - 	externalAddr : 192.168.0.106:20015
  INFO root [0x00002e40] [2018-08-23 11:21:08,264] - 	componentID : 7001
  INFO root [0x00002e40] [2018-08-23 11:21:09,967] - ---- baseapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: F9DFFB319FBADF35943ADF4D42C4718C. Config: Debug X86. Built: 15:53:31 Apr 29 2018. AppID: 7001. UID: 26811. PID: 11068 ----
  INFO root [0x00002e40] [2018-08-23 11:21:09,968] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [0x00002e40] [2018-08-23 11:21:09,968] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00002e40] [2018-08-23 11:21:09,968] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x00002e40] [2018-08-23 11:21:10,091] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00002e40] [2018-08-23 11:21:10,091] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x00002e40] [2018-08-23 11:21:10,092] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x00002e40] [2018-08-23 11:21:10,095] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x00002e40] [2018-08-23 11:21:10,095] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x00002e40] [2018-08-23 11:21:10,095] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x00002e40] [2018-08-23 11:21:10,096] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x00002e40] [2018-08-23 11:21:10,128] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x00002e40] [2018-08-23 11:21:10,158] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x00002e40] [2018-08-23 11:21:10,158] - Script::install(): KBExtra is successfully!
 DEBUG root [0x00002e40] [2018-08-23 11:21:10,178] - loaded entity-script:Account(1).
 DEBUG root [0x00002e40] [2018-08-23 11:21:10,179] - loaded entity-script:CheckName(2).
 DEBUG root [0x00002e40] [2018-08-23 11:21:10,185] - loaded entity-script:Halls(3).
 DEBUG root [0x00002e40] [2018-08-23 11:21:10,186] - loaded entity-script:Room(4).
  INFO root [0x00002e40] [2018-08-23 11:21:10,186] - Baseapp::initializeEnd: started resmgr tick(60s)!
  INFO root [0x00002e40] [2018-08-23 11:21:10,187] - TelnetServer server is running on port 40000
  INFO root [0x00002e40] [2018-08-23 11:21:10,479] - ---- baseapp is running ----
 DEBUG root [0x00002e40] [2018-08-23 11:21:10,479] - Components::process(): Request for the process of identity...
  WARN root [0x00002e40] [2018-08-23 11:21:16,574] - EntityApp::checkTickPeriod: tick took 6095% (6.09 seconds)!
  INFO root [0x00002e40] [2018-08-23 11:21:17,656] - Components::findComponents: find logger(1)...
  INFO root [0x00002e40] [2018-08-23 11:21:17,752] - Components::findComponents: found logger, addr:192.168.0.106:50298
  INFO root [0x00002e40] [2018-08-23 11:21:17,753] - Components::addComponent: reset orderLog, uid=26811!
  INFO root [0x00002e40] [2018-08-23 11:21:17,753] - Components::addComponent[logger], uid=26811, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00002e40] [2018-08-23 11:21:17,754] - Components::findComponents: find dbmgr(2)...
  INFO root [0x00002e40] [2018-08-23 11:21:17,857] - Components::findComponents: found dbmgr, addr:192.168.0.106:50296
  INFO root [0x00002e40] [2018-08-23 11:21:17,858] - Components::addComponent: reset orderLog, uid=26811!
  INFO root [0x00002e40] [2018-08-23 11:21:17,858] - Components::addComponent[dbmgr], uid=26811, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00002e40] [2018-08-23 11:21:17,859] - Components::findComponents: found dbmgr, addr:192.168.0.106:50296
  WARN root [0x00002e40] [2018-08-23 11:21:18,859] - Forwarding logs to logger[192.168.0.106:50298/0/0/0]...
 ERROR root [0x00002e40] [2018-08-23 11:35:16,758] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x00002e40] [2018-08-23 11:35:16,762] - The following logs sent to logger failed:
  WARN root [0x00002e40] [2018-08-23 11:35:16,762] - ==> [2018-08-23 11:35:16 755] TCPPacketReceiver::processPendingEvents(192.168.0.106:50298): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00002e40] [2018-08-23 11:35:16,762] - ==> [2018-08-23 11:35:16 758] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x00002e40] [2018-08-23 11:35:16,809] - TCPPacketReceiver::processPendingEvents(192.168.0.106:50296): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00002e40] [2018-08-23 11:35:16,812] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x00002e40] [2018-08-23 11:35:16,815] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [0x00002e40] [2018-08-23 11:35:16,816] - onBaseAppShutDown: state=0
  INFO root [0x00002e40] [2018-08-23 11:35:16,816] - Shutdowner::onShutdown: shutting down
S_INFO root [0x00002e40] [2018-08-23 11:35:16,816] - onBaseAppShutDown: state=1
  INFO root [0x00002e40] [2018-08-23 11:35:16,816] - Shutdowner::onShutdownEnd: shutting down
S_INFO root [0x00002e40] [2018-08-23 11:35:16,817] - onBaseAppShutDown: state=2
 ERROR root [0x00002e40] [2018-08-23 11:35:16,825] - Account::onCellWriteToDBCompleted(2002): not found dbmgr!
 ERROR root [0x00002e40] [2018-08-23 11:35:16,826] - Entity::onDestroy: not found dbmgr!
 ERROR root [0x00002e40] [2018-08-23 11:35:16,826] - Account::onCellWriteToDBCompleted(2004): not found dbmgr!
 ERROR root [0x00002e40] [2018-08-23 11:35:16,827] - Entity::onDestroy: not found dbmgr!
 DEBUG root [0x00002e40] [2018-08-23 11:35:16,827] - Account::~Account(): 2002
 DEBUG root [0x00002e40] [2018-08-23 11:35:16,827] - Account::~Account(): 2004
 DEBUG root [0x00002e40] [2018-08-23 11:35:16,827] - Room::~Room(): 2003
 DEBUG root [0x00002e40] [2018-08-23 11:35:16,827] - Halls::~Halls(): 2001
 DEBUG root [0x00002e40] [2018-08-23 11:35:16,829] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00002e40] [2018-08-23 11:35:16,829] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x00002e40] [2018-08-23 11:35:16,829] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x00002e40] [2018-08-23 11:35:16,829] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x00002e40] [2018-08-23 11:35:16,829] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x00002e40] [2018-08-23 11:35:16,829] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x00002e40] [2018-08-23 11:35:16,829] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x00002e40] [2018-08-23 11:35:16,829] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x00002e40] [2018-08-23 11:35:16,839] - Script::uninstall(): is successfully!
 DEBUG root [0x00002e40] [2018-08-23 11:35:16,839] - ThreadPool::destroy(): starting size 2.
  INFO root [0x000021dc] [2018-08-23 11:35:17,948] - 
  INFO root [0x000021dc] [2018-08-23 11:35:17,949] - -----------------------------------------------------------------------------------------


  INFO root [0x000021dc] [2018-08-23 11:35:17,949] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [0x000021dc] [2018-08-23 11:35:17,949] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [0x000021dc] [2018-08-23 11:35:17,950] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [0x000021dc] [2018-08-23 11:35:17,956] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:20015 )
  INFO root [0x000021dc] [2018-08-23 11:35:17,956] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.106:20015, SOMAXCONN=128.
  INFO root [0x000021dc] [2018-08-23 11:35:17,958] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:50471 )
  INFO root [0x000021dc] [2018-08-23 11:35:17,958] - NetworkInterface::initialize(INTERNAL): address 192.168.0.106:50471, SOMAXCONN=128.
  INFO root [0x000021dc] [2018-08-23 11:35:17,958] - server-configs:
  INFO root [0x000021dc] [2018-08-23 11:35:17,958] - 	gameUpdateHertz : 10
  INFO root [0x000021dc] [2018-08-23 11:35:17,958] - 	entryScriptFile : kbemain
  INFO root [0x000021dc] [2018-08-23 11:35:17,958] - 	internalAddr : 192.168.0.106:50471
  INFO root [0x000021dc] [2018-08-23 11:35:17,958] - 	externalAddr : 192.168.0.106:20015
  INFO root [0x000021dc] [2018-08-23 11:35:17,959] - 	componentID : 7001
  INFO root [0x000021dc] [2018-08-23 11:35:19,651] - ---- baseapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: F9DFFB319FBADF35943ADF4D42C4718C. Config: Debug X86. Built: 15:53:31 Apr 29 2018. AppID: 7001. UID: 29586. PID: 9444 ----
  INFO root [0x000021dc] [2018-08-23 11:35:19,651] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [0x000021dc] [2018-08-23 11:35:19,651] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x000021dc] [2018-08-23 11:35:19,652] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x000021dc] [2018-08-23 11:35:19,779] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x000021dc] [2018-08-23 11:35:19,779] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x000021dc] [2018-08-23 11:35:19,780] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x000021dc] [2018-08-23 11:35:19,784] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x000021dc] [2018-08-23 11:35:19,784] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x000021dc] [2018-08-23 11:35:19,785] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x000021dc] [2018-08-23 11:35:19,785] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x000021dc] [2018-08-23 11:35:19,829] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x000021dc] [2018-08-23 11:35:19,872] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x000021dc] [2018-08-23 11:35:19,873] - Script::install(): KBExtra is successfully!
 DEBUG root [0x000021dc] [2018-08-23 11:35:19,898] - loaded entity-script:Account(1).
 DEBUG root [0x000021dc] [2018-08-23 11:35:19,900] - loaded entity-script:CheckName(2).
 DEBUG root [0x000021dc] [2018-08-23 11:35:19,906] - loaded entity-script:Halls(3).
 DEBUG root [0x000021dc] [2018-08-23 11:35:19,907] - loaded entity-script:Room(4).
  INFO root [0x000021dc] [2018-08-23 11:35:19,908] - Baseapp::initializeEnd: started resmgr tick(60s)!
  INFO root [0x000021dc] [2018-08-23 11:35:19,908] - TelnetServer server is running on port 40000
  INFO root [0x000021dc] [2018-08-23 11:35:20,240] - ---- baseapp is running ----
 DEBUG root [0x000021dc] [2018-08-23 11:35:20,240] - Components::process(): Request for the process of identity...
  WARN root [0x000021dc] [2018-08-23 11:35:26,305] - EntityApp::checkTickPeriod: tick took 6064% (6.06 seconds)!
  INFO root [0x000021dc] [2018-08-23 11:35:27,341] - Components::findComponents: find logger(1)...
  INFO root [0x000021dc] [2018-08-23 11:35:27,406] - Components::findComponents: found logger, addr:192.168.0.106:50475
  INFO root [0x000021dc] [2018-08-23 11:35:27,406] - Components::addComponent: reset orderLog, uid=29586!
  INFO root [0x000021dc] [2018-08-23 11:35:27,406] - Components::addComponent[logger], uid=29586, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x000021dc] [2018-08-23 11:35:27,407] - Components::findComponents: find dbmgr(2)...
  INFO root [0x000021dc] [2018-08-23 11:35:27,512] - Components::findComponents: found dbmgr, addr:192.168.0.106:50469
  INFO root [0x000021dc] [2018-08-23 11:35:27,513] - Components::addComponent: reset orderLog, uid=29586!
  INFO root [0x000021dc] [2018-08-23 11:35:27,513] - Components::addComponent[dbmgr], uid=29586, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x000021dc] [2018-08-23 11:35:27,514] - Components::findComponents: found dbmgr, addr:192.168.0.106:50469
  WARN root [0x000021dc] [2018-08-23 11:35:28,514] - EntityApp::checkTickPeriod: tick took 1273% (1.27 seconds)!
  WARN root [0x000021dc] [2018-08-23 11:35:28,516] - Forwarding logs to logger[192.168.0.106:50475/0/0/0]...
 ERROR root [0x000021dc] [2018-08-23 11:52:27,155] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x000021dc] [2018-08-23 11:52:27,160] - The following logs sent to logger failed:
  WARN root [0x000021dc] [2018-08-23 11:52:27,160] - ==> [2018-08-23 11:52:27 152] TCPPacketReceiver::processPendingEvents(192.168.0.106:50475): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x000021dc] [2018-08-23 11:52:27,160] - ==> [2018-08-23 11:52:27 155] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x000021dc] [2018-08-23 11:52:27,208] - TCPPacketReceiver::processPendingEvents(192.168.0.106:50469): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x000021dc] [2018-08-23 11:52:27,211] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x000021dc] [2018-08-23 11:52:27,214] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [0x000021dc] [2018-08-23 11:52:27,215] - onBaseAppShutDown: state=0
  INFO root [0x000021dc] [2018-08-23 11:52:27,216] - Shutdowner::onShutdown: shutting down
S_INFO root [0x000021dc] [2018-08-23 11:52:27,216] - onBaseAppShutDown: state=1
  INFO root [0x000021dc] [2018-08-23 11:52:27,216] - Shutdowner::onShutdownEnd: shutting down
S_INFO root [0x000021dc] [2018-08-23 11:52:27,216] - onBaseAppShutDown: state=2
 ERROR root [0x000021dc] [2018-08-23 11:52:27,224] - Account::onCellWriteToDBCompleted(2002): not found dbmgr!
 ERROR root [0x000021dc] [2018-08-23 11:52:27,225] - Entity::onDestroy: not found dbmgr!
 ERROR root [0x000021dc] [2018-08-23 11:52:27,226] - Account::onCellWriteToDBCompleted(2004): not found dbmgr!
 ERROR root [0x000021dc] [2018-08-23 11:52:27,227] - Entity::onDestroy: not found dbmgr!
 DEBUG root [0x000021dc] [2018-08-23 11:52:27,227] - Account::~Account(): 2002
 DEBUG root [0x000021dc] [2018-08-23 11:52:27,227] - Account::~Account(): 2004
 DEBUG root [0x000021dc] [2018-08-23 11:52:27,227] - Room::~Room(): 2003
 DEBUG root [0x000021dc] [2018-08-23 11:52:27,228] - Halls::~Halls(): 2001
 DEBUG root [0x000021dc] [2018-08-23 11:52:27,229] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x000021dc] [2018-08-23 11:52:27,229] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x000021dc] [2018-08-23 11:52:27,229] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x000021dc] [2018-08-23 11:52:27,229] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x000021dc] [2018-08-23 11:52:27,229] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x000021dc] [2018-08-23 11:52:27,229] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x000021dc] [2018-08-23 11:52:27,229] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x000021dc] [2018-08-23 11:52:27,229] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x000021dc] [2018-08-23 11:52:27,239] - Script::uninstall(): is successfully!
 DEBUG root [0x000021dc] [2018-08-23 11:52:27,240] - ThreadPool::destroy(): starting size 2.
  INFO root [0x00002650] [2018-08-23 11:52:28,359] - 
  INFO root [0x00002650] [2018-08-23 11:52:28,360] - -----------------------------------------------------------------------------------------


  INFO root [0x00002650] [2018-08-23 11:52:28,361] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [0x00002650] [2018-08-23 11:52:28,361] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [0x00002650] [2018-08-23 11:52:28,362] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [0x00002650] [2018-08-23 11:52:28,364] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:20015 )
  INFO root [0x00002650] [2018-08-23 11:52:28,364] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.106:20015, SOMAXCONN=128.
  INFO root [0x00002650] [2018-08-23 11:52:28,365] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:50699 )
  INFO root [0x00002650] [2018-08-23 11:52:28,366] - NetworkInterface::initialize(INTERNAL): address 192.168.0.106:50699, SOMAXCONN=128.
  INFO root [0x00002650] [2018-08-23 11:52:28,366] - server-configs:
  INFO root [0x00002650] [2018-08-23 11:52:28,366] - 	gameUpdateHertz : 10
  INFO root [0x00002650] [2018-08-23 11:52:28,366] - 	entryScriptFile : kbemain
  INFO root [0x00002650] [2018-08-23 11:52:28,366] - 	internalAddr : 192.168.0.106:50699
  INFO root [0x00002650] [2018-08-23 11:52:28,366] - 	externalAddr : 192.168.0.106:20015
  INFO root [0x00002650] [2018-08-23 11:52:28,366] - 	componentID : 7001
  WARN root [0x00002650] [2018-08-23 11:52:28,871] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20334, errorno=10048
  INFO root [0x00002650] [2018-08-23 11:52:28,875] - ---- baseapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: F9DFFB319FBADF35943ADF4D42C4718C. Config: Debug X86. Built: 15:53:31 Apr 29 2018. AppID: 7001. UID: 185. PID: 9092 ----
  INFO root [0x00002650] [2018-08-23 11:52:28,875] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [0x00002650] [2018-08-23 11:52:28,875] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00002650] [2018-08-23 11:52:28,876] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x00002650] [2018-08-23 11:52:28,999] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00002650] [2018-08-23 11:52:29,000] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x00002650] [2018-08-23 11:52:29,000] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x00002650] [2018-08-23 11:52:29,003] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x00002650] [2018-08-23 11:52:29,003] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x00002650] [2018-08-23 11:52:29,003] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x00002650] [2018-08-23 11:52:29,004] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x00002650] [2018-08-23 11:52:29,031] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x00002650] [2018-08-23 11:52:29,059] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x00002650] [2018-08-23 11:52:29,060] - Script::install(): KBExtra is successfully!
 DEBUG root [0x00002650] [2018-08-23 11:52:29,079] - loaded entity-script:Account(1).
 DEBUG root [0x00002650] [2018-08-23 11:52:29,080] - loaded entity-script:CheckName(2).
 DEBUG root [0x00002650] [2018-08-23 11:52:29,086] - loaded entity-script:Halls(3).
 DEBUG root [0x00002650] [2018-08-23 11:52:29,087] - loaded entity-script:Room(4).
  INFO root [0x00002650] [2018-08-23 11:52:29,087] - Baseapp::initializeEnd: started resmgr tick(60s)!
  INFO root [0x00002650] [2018-08-23 11:52:29,087] - TelnetServer server is running on port 40000
  INFO root [0x00002650] [2018-08-23 11:52:29,366] - ---- baseapp is running ----
 DEBUG root [0x00002650] [2018-08-23 11:52:29,366] - Components::process(): Request for the process of identity...
  WARN root [0x00002650] [2018-08-23 11:52:35,475] - EntityApp::checkTickPeriod: tick took 6109% (6.11 seconds)!
  INFO root [0x00002650] [2018-08-23 11:52:36,562] - Components::findComponents: find logger(1)...
  INFO root [0x00002650] [2018-08-23 11:52:36,588] - Components::findComponents: found logger, addr:192.168.0.106:50695
  INFO root [0x00002650] [2018-08-23 11:52:36,588] - Components::addComponent: reset orderLog, uid=185!
  INFO root [0x00002650] [2018-08-23 11:52:36,589] - Components::addComponent[logger], uid=185, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00002650] [2018-08-23 11:52:36,591] - Components::findComponents: find dbmgr(2)...
  INFO root [0x00002650] [2018-08-23 11:52:36,693] - Components::findComponents: found dbmgr, addr:192.168.0.106:50694
  INFO root [0x00002650] [2018-08-23 11:52:36,694] - Components::addComponent: reset orderLog, uid=185!
  INFO root [0x00002650] [2018-08-23 11:52:36,694] - Components::addComponent[dbmgr], uid=185, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00002650] [2018-08-23 11:52:36,695] - Components::findComponents: found dbmgr, addr:192.168.0.106:50694
  WARN root [0x00002650] [2018-08-23 11:52:37,696] - Forwarding logs to logger[192.168.0.106:50695/0/0/0]...
 ERROR root [0x00002650] [2018-08-23 11:58:23,501] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x00002650] [2018-08-23 11:58:23,505] - The following logs sent to logger failed:
  WARN root [0x00002650] [2018-08-23 11:58:23,505] - ==> [2018-08-23 11:58:23 497] TCPPacketReceiver::processPendingEvents(192.168.0.106:50695): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00002650] [2018-08-23 11:58:23,505] - ==> [2018-08-23 11:58:23 501] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x00002650] [2018-08-23 11:58:23,550] - TCPPacketReceiver::processPendingEvents(192.168.0.106:50694): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00002650] [2018-08-23 11:58:23,554] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x00002650] [2018-08-23 11:58:23,557] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [0x00002650] [2018-08-23 11:58:23,559] - onBaseAppShutDown: state=0
  INFO root [0x00002650] [2018-08-23 11:58:23,559] - Shutdowner::onShutdown: shutting down
S_INFO root [0x00002650] [2018-08-23 11:58:23,559] - onBaseAppShutDown: state=1
  INFO root [0x00002650] [2018-08-23 11:58:23,559] - Shutdowner::onShutdownEnd: shutting down
S_INFO root [0x00002650] [2018-08-23 11:58:23,559] - onBaseAppShutDown: state=2
 ERROR root [0x00002650] [2018-08-23 11:58:23,567] - Account::onCellWriteToDBCompleted(2): not found dbmgr!
 ERROR root [0x00002650] [2018-08-23 11:58:23,568] - Entity::onDestroy: not found dbmgr!
 ERROR root [0x00002650] [2018-08-23 11:58:23,568] - Account::onCellWriteToDBCompleted(4): not found dbmgr!
 ERROR root [0x00002650] [2018-08-23 11:58:23,569] - Entity::onDestroy: not found dbmgr!
 DEBUG root [0x00002650] [2018-08-23 11:58:23,569] - Account::~Account(): 2
 DEBUG root [0x00002650] [2018-08-23 11:58:23,569] - Account::~Account(): 4
 DEBUG root [0x00002650] [2018-08-23 11:58:23,570] - Room::~Room(): 3
 DEBUG root [0x00002650] [2018-08-23 11:58:23,570] - Halls::~Halls(): 1
 DEBUG root [0x00002650] [2018-08-23 11:58:23,571] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00002650] [2018-08-23 11:58:23,571] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x00002650] [2018-08-23 11:58:23,571] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x00002650] [2018-08-23 11:58:23,571] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x00002650] [2018-08-23 11:58:23,571] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x00002650] [2018-08-23 11:58:23,571] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x00002650] [2018-08-23 11:58:23,571] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x00002650] [2018-08-23 11:58:23,572] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x00002650] [2018-08-23 11:58:23,581] - Script::uninstall(): is successfully!
 DEBUG root [0x00002650] [2018-08-23 11:58:23,582] - ThreadPool::destroy(): starting size 2.
  INFO root [0x00002dec] [2018-08-23 11:58:24,686] - 
  INFO root [0x00002dec] [2018-08-23 11:58:24,686] - -----------------------------------------------------------------------------------------


  INFO root [0x00002dec] [2018-08-23 11:58:24,687] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [0x00002dec] [2018-08-23 11:58:24,687] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [0x00002dec] [2018-08-23 11:58:24,687] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [0x00002dec] [2018-08-23 11:58:24,691] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:20015 )
  INFO root [0x00002dec] [2018-08-23 11:58:24,691] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.106:20015, SOMAXCONN=128.
  INFO root [0x00002dec] [2018-08-23 11:58:24,692] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:50828 )
  INFO root [0x00002dec] [2018-08-23 11:58:24,692] - NetworkInterface::initialize(INTERNAL): address 192.168.0.106:50828, SOMAXCONN=128.
  INFO root [0x00002dec] [2018-08-23 11:58:24,693] - server-configs:
  INFO root [0x00002dec] [2018-08-23 11:58:24,693] - 	gameUpdateHertz : 10
  INFO root [0x00002dec] [2018-08-23 11:58:24,693] - 	entryScriptFile : kbemain
  INFO root [0x00002dec] [2018-08-23 11:58:24,693] - 	internalAddr : 192.168.0.106:50828
  INFO root [0x00002dec] [2018-08-23 11:58:24,693] - 	externalAddr : 192.168.0.106:20015
  INFO root [0x00002dec] [2018-08-23 11:58:24,693] - 	componentID : 7001
  INFO root [0x00002dec] [2018-08-23 11:58:26,385] - ---- baseapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: F9DFFB319FBADF35943ADF4D42C4718C. Config: Debug X86. Built: 15:53:31 Apr 29 2018. AppID: 7001. UID: 1348. PID: 10108 ----
  INFO root [0x00002dec] [2018-08-23 11:58:26,386] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [0x00002dec] [2018-08-23 11:58:26,386] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00002dec] [2018-08-23 11:58:26,387] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x00002dec] [2018-08-23 11:58:26,510] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00002dec] [2018-08-23 11:58:26,510] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x00002dec] [2018-08-23 11:58:26,511] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x00002dec] [2018-08-23 11:58:26,515] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x00002dec] [2018-08-23 11:58:26,516] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x00002dec] [2018-08-23 11:58:26,516] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x00002dec] [2018-08-23 11:58:26,517] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x00002dec] [2018-08-23 11:58:26,550] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x00002dec] [2018-08-23 11:58:26,583] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x00002dec] [2018-08-23 11:58:26,584] - Script::install(): KBExtra is successfully!
 DEBUG root [0x00002dec] [2018-08-23 11:58:26,611] - loaded entity-script:Account(1).
 DEBUG root [0x00002dec] [2018-08-23 11:58:26,612] - loaded entity-script:CheckName(2).
 DEBUG root [0x00002dec] [2018-08-23 11:58:26,617] - loaded entity-script:Halls(3).
 DEBUG root [0x00002dec] [2018-08-23 11:58:26,618] - loaded entity-script:Room(4).
  INFO root [0x00002dec] [2018-08-23 11:58:26,618] - Baseapp::initializeEnd: started resmgr tick(60s)!
  INFO root [0x00002dec] [2018-08-23 11:58:26,619] - TelnetServer server is running on port 40000
  INFO root [0x00002dec] [2018-08-23 11:58:26,908] - ---- baseapp is running ----
 DEBUG root [0x00002dec] [2018-08-23 11:58:26,908] - Components::process(): Request for the process of identity...
  WARN root [0x00002dec] [2018-08-23 11:58:32,960] - EntityApp::checkTickPeriod: tick took 6051% (6.05 seconds)!
  INFO root [0x00002dec] [2018-08-23 11:58:33,990] - Components::findComponents: find logger(1)...
  INFO root [0x00002dec] [2018-08-23 11:58:34,096] - Components::findComponents: found logger, addr:192.168.0.106:50826
  INFO root [0x00002dec] [2018-08-23 11:58:34,097] - Components::addComponent: reset orderLog, uid=1348!
  INFO root [0x00002dec] [2018-08-23 11:58:34,098] - Components::addComponent[logger], uid=1348, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00002dec] [2018-08-23 11:58:34,100] - Components::findComponents: find dbmgr(2)...
  INFO root [0x00002dec] [2018-08-23 11:58:34,207] - Components::findComponents: found dbmgr, addr:192.168.0.106:50831
  INFO root [0x00002dec] [2018-08-23 11:58:34,208] - Components::addComponent: reset orderLog, uid=1348!
  INFO root [0x00002dec] [2018-08-23 11:58:34,209] - Components::addComponent[dbmgr], uid=1348, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00002dec] [2018-08-23 11:58:34,209] - Components::findComponents: found dbmgr, addr:192.168.0.106:50831
  WARN root [0x00002dec] [2018-08-23 11:58:35,210] - Forwarding logs to logger[192.168.0.106:50826/0/0/0]...
 ERROR root [0x00002dec] [2018-08-23 12:04:45,715] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x00002dec] [2018-08-23 12:04:45,720] - The following logs sent to logger failed:
  WARN root [0x00002dec] [2018-08-23 12:04:45,720] - ==> [2018-08-23 12:04:45 711] TCPPacketReceiver::processPendingEvents(192.168.0.106:50826): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00002dec] [2018-08-23 12:04:45,720] - ==> [2018-08-23 12:04:45 715] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x00002dec] [2018-08-23 12:04:45,769] - TCPPacketReceiver::processPendingEvents(192.168.0.106:50831): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00002dec] [2018-08-23 12:04:45,770] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x00002dec] [2018-08-23 12:04:45,777] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [0x00002dec] [2018-08-23 12:04:45,778] - onBaseAppShutDown: state=0
  INFO root [0x00002dec] [2018-08-23 12:04:45,778] - Shutdowner::onShutdown: shutting down
S_INFO root [0x00002dec] [2018-08-23 12:04:45,778] - onBaseAppShutDown: state=1
  INFO root [0x00002dec] [2018-08-23 12:04:45,778] - Shutdowner::onShutdownEnd: shutting down
S_INFO root [0x00002dec] [2018-08-23 12:04:45,778] - onBaseAppShutDown: state=2
 ERROR root [0x00002dec] [2018-08-23 12:04:45,786] - Account::onCellWriteToDBCompleted(2002): not found dbmgr!
 ERROR root [0x00002dec] [2018-08-23 12:04:45,787] - Entity::onDestroy: not found dbmgr!
 ERROR root [0x00002dec] [2018-08-23 12:04:45,788] - Account::onCellWriteToDBCompleted(2004): not found dbmgr!
 ERROR root [0x00002dec] [2018-08-23 12:04:45,788] - Entity::onDestroy: not found dbmgr!
 DEBUG root [0x00002dec] [2018-08-23 12:04:45,788] - Account::~Account(): 2002
 DEBUG root [0x00002dec] [2018-08-23 12:04:45,789] - Account::~Account(): 2004
 DEBUG root [0x00002dec] [2018-08-23 12:04:45,789] - Room::~Room(): 2003
 DEBUG root [0x00002dec] [2018-08-23 12:04:45,789] - Halls::~Halls(): 2001
 DEBUG root [0x00002dec] [2018-08-23 12:04:45,790] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00002dec] [2018-08-23 12:04:45,790] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x00002dec] [2018-08-23 12:04:45,790] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x00002dec] [2018-08-23 12:04:45,790] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x00002dec] [2018-08-23 12:04:45,790] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x00002dec] [2018-08-23 12:04:45,790] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x00002dec] [2018-08-23 12:04:45,791] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x00002dec] [2018-08-23 12:04:45,791] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x00002dec] [2018-08-23 12:04:45,801] - Script::uninstall(): is successfully!
 DEBUG root [0x00002dec] [2018-08-23 12:04:45,801] - ThreadPool::destroy(): starting size 2.
  INFO root [0x00003238] [2018-08-23 12:04:46,878] - 
  INFO root [0x00003238] [2018-08-23 12:04:46,888] - -----------------------------------------------------------------------------------------


  INFO root [0x00003238] [2018-08-23 12:04:46,889] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [0x00003238] [2018-08-23 12:04:46,889] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [0x00003238] [2018-08-23 12:04:46,889] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [0x00003238] [2018-08-23 12:04:46,894] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:20015 )
  INFO root [0x00003238] [2018-08-23 12:04:46,894] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.106:20015, SOMAXCONN=128.
  INFO root [0x00003238] [2018-08-23 12:04:46,896] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:50933 )
  INFO root [0x00003238] [2018-08-23 12:04:46,896] - NetworkInterface::initialize(INTERNAL): address 192.168.0.106:50933, SOMAXCONN=128.
  INFO root [0x00003238] [2018-08-23 12:04:46,896] - server-configs:
  INFO root [0x00003238] [2018-08-23 12:04:46,896] - 	gameUpdateHertz : 10
  INFO root [0x00003238] [2018-08-23 12:04:46,896] - 	entryScriptFile : kbemain
  INFO root [0x00003238] [2018-08-23 12:04:46,896] - 	internalAddr : 192.168.0.106:50933
  INFO root [0x00003238] [2018-08-23 12:04:46,896] - 	externalAddr : 192.168.0.106:20015
  INFO root [0x00003238] [2018-08-23 12:04:46,896] - 	componentID : 7001
  INFO root [0x00003238] [2018-08-23 12:04:48,581] - ---- baseapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: F9DFFB319FBADF35943ADF4D42C4718C. Config: Debug X86. Built: 15:53:31 Apr 29 2018. AppID: 7001. UID: 2595. PID: 12684 ----
  INFO root [0x00003238] [2018-08-23 12:04:48,582] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [0x00003238] [2018-08-23 12:04:48,582] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00003238] [2018-08-23 12:04:48,582] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x00003238] [2018-08-23 12:04:48,710] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00003238] [2018-08-23 12:04:48,710] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x00003238] [2018-08-23 12:04:48,710] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x00003238] [2018-08-23 12:04:48,714] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x00003238] [2018-08-23 12:04:48,714] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x00003238] [2018-08-23 12:04:48,714] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x00003238] [2018-08-23 12:04:48,715] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x00003238] [2018-08-23 12:04:48,751] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x00003238] [2018-08-23 12:04:48,794] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x00003238] [2018-08-23 12:04:48,795] - Script::install(): KBExtra is successfully!
 DEBUG root [0x00003238] [2018-08-23 12:04:48,827] - loaded entity-script:Account(1).
 DEBUG root [0x00003238] [2018-08-23 12:04:48,828] - loaded entity-script:CheckName(2).
 DEBUG root [0x00003238] [2018-08-23 12:04:48,834] - loaded entity-script:Halls(3).
 DEBUG root [0x00003238] [2018-08-23 12:04:48,835] - loaded entity-script:Room(4).
  INFO root [0x00003238] [2018-08-23 12:04:48,835] - Baseapp::initializeEnd: started resmgr tick(60s)!
  INFO root [0x00003238] [2018-08-23 12:04:48,835] - TelnetServer server is running on port 40000
  INFO root [0x00003238] [2018-08-23 12:04:49,161] - ---- baseapp is running ----
 DEBUG root [0x00003238] [2018-08-23 12:04:49,162] - Components::process(): Request for the process of identity...
  WARN root [0x00003238] [2018-08-23 12:04:55,238] - EntityApp::checkTickPeriod: tick took 6076% (6.08 seconds)!
  INFO root [0x00003238] [2018-08-23 12:04:56,292] - Components::findComponents: find logger(1)...
  INFO root [0x00003238] [2018-08-23 12:04:56,376] - Components::findComponents: found logger, addr:192.168.0.106:50936
  INFO root [0x00003238] [2018-08-23 12:04:56,377] - Components::addComponent: reset orderLog, uid=2595!
  INFO root [0x00003238] [2018-08-23 12:04:56,377] - Components::addComponent[logger], uid=2595, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00003238] [2018-08-23 12:04:56,379] - Components::findComponents: find dbmgr(2)...
  INFO root [0x00003238] [2018-08-23 12:04:56,481] - Components::findComponents: found dbmgr, addr:192.168.0.106:50931
  INFO root [0x00003238] [2018-08-23 12:04:56,482] - Components::addComponent: reset orderLog, uid=2595!
  INFO root [0x00003238] [2018-08-23 12:04:56,482] - Components::addComponent[dbmgr], uid=2595, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00003238] [2018-08-23 12:04:56,483] - Components::findComponents: found dbmgr, addr:192.168.0.106:50931
  WARN root [0x00003238] [2018-08-23 12:04:57,483] - Forwarding logs to logger[192.168.0.106:50936/0/0/0]...
 ERROR root [0x00003238] [2018-08-23 15:18:30,560] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x00003238] [2018-08-23 15:18:30,577] - The following logs sent to logger failed:
  WARN root [0x00003238] [2018-08-23 15:18:30,578] - ==> [2018-08-23 15:18:30 557] TCPPacketReceiver::processPendingEvents(192.168.0.106:50936): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00003238] [2018-08-23 15:18:30,578] - ==> [2018-08-23 15:18:30 560] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x00003238] [2018-08-23 15:18:30,629] - TCPPacketReceiver::processPendingEvents(192.168.0.106:50931): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00003238] [2018-08-23 15:18:30,632] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x00003238] [2018-08-23 15:18:30,647] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [0x00003238] [2018-08-23 15:18:30,650] - onBaseAppShutDown: state=0
  INFO root [0x00003238] [2018-08-23 15:18:30,650] - Shutdowner::onShutdown: shutting down
S_INFO root [0x00003238] [2018-08-23 15:18:30,650] - onBaseAppShutDown: state=1
  INFO root [0x00003238] [2018-08-23 15:18:30,651] - Shutdowner::onShutdownEnd: shutting down
S_INFO root [0x00003238] [2018-08-23 15:18:30,651] - onBaseAppShutDown: state=2
 ERROR root [0x00003238] [2018-08-23 15:18:30,659] - Account::onCellWriteToDBCompleted(2002): not found dbmgr!
 ERROR root [0x00003238] [2018-08-23 15:18:30,659] - Entity::onDestroy: not found dbmgr!
 ERROR root [0x00003238] [2018-08-23 15:18:30,660] - Account::onCellWriteToDBCompleted(2004): not found dbmgr!
 ERROR root [0x00003238] [2018-08-23 15:18:30,660] - Entity::onDestroy: not found dbmgr!
 DEBUG root [0x00003238] [2018-08-23 15:18:30,661] - Account::~Account(): 2002
 DEBUG root [0x00003238] [2018-08-23 15:18:30,661] - Account::~Account(): 2004
 DEBUG root [0x00003238] [2018-08-23 15:18:30,661] - Room::~Room(): 2003
 DEBUG root [0x00003238] [2018-08-23 15:18:30,661] - Halls::~Halls(): 2001
 DEBUG root [0x00003238] [2018-08-23 15:18:30,662] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00003238] [2018-08-23 15:18:30,662] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x00003238] [2018-08-23 15:18:30,662] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x00003238] [2018-08-23 15:18:30,662] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x00003238] [2018-08-23 15:18:30,663] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x00003238] [2018-08-23 15:18:30,663] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x00003238] [2018-08-23 15:18:30,663] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x00003238] [2018-08-23 15:18:30,663] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x00003238] [2018-08-23 15:18:30,673] - Script::uninstall(): is successfully!
 DEBUG root [0x00003238] [2018-08-23 15:18:30,673] - ThreadPool::destroy(): starting size 2.
  INFO root [0x00003f1c] [2018-08-23 15:18:31,909] - 
  INFO root [0x00003f1c] [2018-08-23 15:18:31,910] - -----------------------------------------------------------------------------------------


  INFO root [0x00003f1c] [2018-08-23 15:18:31,910] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [0x00003f1c] [2018-08-23 15:18:31,910] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [0x00003f1c] [2018-08-23 15:18:31,910] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [0x00003f1c] [2018-08-23 15:18:31,915] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:20015 )
  INFO root [0x00003f1c] [2018-08-23 15:18:31,915] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.106:20015, SOMAXCONN=128.
  INFO root [0x00003f1c] [2018-08-23 15:18:31,917] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:55504 )
  INFO root [0x00003f1c] [2018-08-23 15:18:31,917] - NetworkInterface::initialize(INTERNAL): address 192.168.0.106:55504, SOMAXCONN=128.
  INFO root [0x00003f1c] [2018-08-23 15:18:31,917] - server-configs:
  INFO root [0x00003f1c] [2018-08-23 15:18:31,917] - 	gameUpdateHertz : 10
  INFO root [0x00003f1c] [2018-08-23 15:18:31,917] - 	entryScriptFile : kbemain
  INFO root [0x00003f1c] [2018-08-23 15:18:31,917] - 	internalAddr : 192.168.0.106:55504
  INFO root [0x00003f1c] [2018-08-23 15:18:31,917] - 	externalAddr : 192.168.0.106:20015
  INFO root [0x00003f1c] [2018-08-23 15:18:31,917] - 	componentID : 7001
  INFO root [0x00003f1c] [2018-08-23 15:18:33,642] - ---- baseapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: F9DFFB319FBADF35943ADF4D42C4718C. Config: Debug X86. Built: 15:53:31 Apr 29 2018. AppID: 7001. UID: 7790. PID: 16504 ----
  INFO root [0x00003f1c] [2018-08-23 15:18:33,642] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [0x00003f1c] [2018-08-23 15:18:33,648] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00003f1c] [2018-08-23 15:18:33,648] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x00003f1c] [2018-08-23 15:18:33,771] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00003f1c] [2018-08-23 15:18:33,772] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x00003f1c] [2018-08-23 15:18:33,772] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x00003f1c] [2018-08-23 15:18:33,776] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x00003f1c] [2018-08-23 15:18:33,776] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x00003f1c] [2018-08-23 15:18:33,777] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x00003f1c] [2018-08-23 15:18:33,777] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x00003f1c] [2018-08-23 15:18:33,804] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x00003f1c] [2018-08-23 15:18:33,832] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x00003f1c] [2018-08-23 15:18:33,832] - Script::install(): KBExtra is successfully!
 DEBUG root [0x00003f1c] [2018-08-23 15:18:33,851] - loaded entity-script:Account(1).
 DEBUG root [0x00003f1c] [2018-08-23 15:18:33,853] - loaded entity-script:CheckName(2).
 DEBUG root [0x00003f1c] [2018-08-23 15:18:33,858] - loaded entity-script:Halls(3).
 DEBUG root [0x00003f1c] [2018-08-23 15:18:33,859] - loaded entity-script:Room(4).
  INFO root [0x00003f1c] [2018-08-23 15:18:33,859] - Baseapp::initializeEnd: started resmgr tick(60s)!
  INFO root [0x00003f1c] [2018-08-23 15:18:33,859] - TelnetServer server is running on port 40000
  INFO root [0x00003f1c] [2018-08-23 15:18:34,222] - ---- baseapp is running ----
 DEBUG root [0x00003f1c] [2018-08-23 15:18:34,223] - Components::process(): Request for the process of identity...
  WARN root [0x00003f1c] [2018-08-23 15:18:40,319] - EntityApp::checkTickPeriod: tick took 6095% (6.09 seconds)!
  INFO root [0x00003f1c] [2018-08-23 15:18:41,414] - Components::findComponents: find logger(1)...
  INFO root [0x00003f1c] [2018-08-23 15:18:41,461] - Components::findComponents: found logger, addr:192.168.0.106:55503
  INFO root [0x00003f1c] [2018-08-23 15:18:41,462] - Components::addComponent: reset orderLog, uid=7790!
  INFO root [0x00003f1c] [2018-08-23 15:18:41,463] - Components::addComponent[logger], uid=7790, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00003f1c] [2018-08-23 15:18:41,465] - Components::findComponents: find dbmgr(2)...
  INFO root [0x00003f1c] [2018-08-23 15:18:41,564] - Components::findComponents: found dbmgr, addr:192.168.0.106:55505
  INFO root [0x00003f1c] [2018-08-23 15:18:41,564] - Components::addComponent: reset orderLog, uid=7790!
  INFO root [0x00003f1c] [2018-08-23 15:18:41,565] - Components::addComponent[dbmgr], uid=7790, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00003f1c] [2018-08-23 15:18:41,565] - Components::findComponents: found dbmgr, addr:192.168.0.106:55505
  WARN root [0x00003f1c] [2018-08-23 15:18:42,565] - Forwarding logs to logger[192.168.0.106:55503/0/0/0]...
 ERROR root [0x00003f1c] [2018-08-23 16:12:55,986] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x00003f1c] [2018-08-23 16:12:55,993] - The following logs sent to logger failed:
  WARN root [0x00003f1c] [2018-08-23 16:12:55,994] - ==> [2018-08-23 16:12:55 975] TCPPacketReceiver::processPendingEvents(192.168.0.106:55503): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00003f1c] [2018-08-23 16:12:55,994] - ==> [2018-08-23 16:12:55 987] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x00003f1c] [2018-08-23 16:12:56,042] - TCPPacketReceiver::processPendingEvents(192.168.0.106:55505): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00003f1c] [2018-08-23 16:12:56,046] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x00003f1c] [2018-08-23 16:12:56,061] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [0x00003f1c] [2018-08-23 16:12:56,064] - onBaseAppShutDown: state=0
  INFO root [0x00003f1c] [2018-08-23 16:12:56,064] - Shutdowner::onShutdown: shutting down
S_INFO root [0x00003f1c] [2018-08-23 16:12:56,064] - onBaseAppShutDown: state=1
  INFO root [0x00003f1c] [2018-08-23 16:12:56,064] - Shutdowner::onShutdownEnd: shutting down
S_INFO root [0x00003f1c] [2018-08-23 16:12:56,064] - onBaseAppShutDown: state=2
 ERROR root [0x00003f1c] [2018-08-23 16:12:56,072] - Account::onCellWriteToDBCompleted(2002): not found dbmgr!
 ERROR root [0x00003f1c] [2018-08-23 16:12:56,078] - Entity::onDestroy: not found dbmgr!
 DEBUG root [0x00003f1c] [2018-08-23 16:12:56,079] - Account::~Account(): 2002
 DEBUG root [0x00003f1c] [2018-08-23 16:12:56,079] - Room::~Room(): 2003
 DEBUG root [0x00003f1c] [2018-08-23 16:12:56,079] - Halls::~Halls(): 2001
 DEBUG root [0x00003f1c] [2018-08-23 16:12:56,080] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00003f1c] [2018-08-23 16:12:56,080] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x00003f1c] [2018-08-23 16:12:56,080] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x00003f1c] [2018-08-23 16:12:56,080] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x00003f1c] [2018-08-23 16:12:56,080] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x00003f1c] [2018-08-23 16:12:56,080] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x00003f1c] [2018-08-23 16:12:56,081] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x00003f1c] [2018-08-23 16:12:56,081] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x00003f1c] [2018-08-23 16:12:56,090] - Script::uninstall(): is successfully!
 DEBUG root [0x00003f1c] [2018-08-23 16:12:56,090] - ThreadPool::destroy(): starting size 2.
  INFO root [0x00002a30] [2018-08-23 16:12:57,349] - 
  INFO root [0x00002a30] [2018-08-23 16:12:57,350] - -----------------------------------------------------------------------------------------


  INFO root [0x00002a30] [2018-08-23 16:12:57,350] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [0x00002a30] [2018-08-23 16:12:57,351] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [0x00002a30] [2018-08-23 16:12:57,351] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [0x00002a30] [2018-08-23 16:12:57,354] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:20015 )
  INFO root [0x00002a30] [2018-08-23 16:12:57,354] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.106:20015, SOMAXCONN=128.
  INFO root [0x00002a30] [2018-08-23 16:12:57,355] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:56178 )
  INFO root [0x00002a30] [2018-08-23 16:12:57,355] - NetworkInterface::initialize(INTERNAL): address 192.168.0.106:56178, SOMAXCONN=128.
  INFO root [0x00002a30] [2018-08-23 16:12:57,356] - server-configs:
  INFO root [0x00002a30] [2018-08-23 16:12:57,356] - 	gameUpdateHertz : 10
  INFO root [0x00002a30] [2018-08-23 16:12:57,356] - 	entryScriptFile : kbemain
  INFO root [0x00002a30] [2018-08-23 16:12:57,356] - 	internalAddr : 192.168.0.106:56178
  INFO root [0x00002a30] [2018-08-23 16:12:57,356] - 	externalAddr : 192.168.0.106:20015
  INFO root [0x00002a30] [2018-08-23 16:12:57,356] - 	componentID : 7001
  WARN root [0x00002a30] [2018-08-23 16:12:57,861] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20266, errorno=10048
  INFO root [0x00002a30] [2018-08-23 16:12:57,867] - ---- baseapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: F9DFFB319FBADF35943ADF4D42C4718C. Config: Debug X86. Built: 15:53:31 Apr 29 2018. AppID: 7001. UID: 18452. PID: 16476 ----
  INFO root [0x00002a30] [2018-08-23 16:12:57,867] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [0x00002a30] [2018-08-23 16:12:57,868] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00002a30] [2018-08-23 16:12:57,868] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x00002a30] [2018-08-23 16:12:57,999] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00002a30] [2018-08-23 16:12:57,999] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x00002a30] [2018-08-23 16:12:58,000] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x00002a30] [2018-08-23 16:12:58,004] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x00002a30] [2018-08-23 16:12:58,005] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x00002a30] [2018-08-23 16:12:58,005] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x00002a30] [2018-08-23 16:12:58,006] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x00002a30] [2018-08-23 16:12:58,038] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x00002a30] [2018-08-23 16:12:58,065] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x00002a30] [2018-08-23 16:12:58,065] - Script::install(): KBExtra is successfully!
 DEBUG root [0x00002a30] [2018-08-23 16:12:58,090] - loaded entity-script:Account(1).
 DEBUG root [0x00002a30] [2018-08-23 16:12:58,091] - loaded entity-script:CheckName(2).
 DEBUG root [0x00002a30] [2018-08-23 16:12:58,096] - loaded entity-script:Halls(3).
 DEBUG root [0x00002a30] [2018-08-23 16:12:58,097] - loaded entity-script:Room(4).
  INFO root [0x00002a30] [2018-08-23 16:12:58,097] - Baseapp::initializeEnd: started resmgr tick(60s)!
  INFO root [0x00002a30] [2018-08-23 16:12:58,097] - TelnetServer server is running on port 40000
  INFO root [0x00002a30] [2018-08-23 16:12:58,395] - ---- baseapp is running ----
 DEBUG root [0x00002a30] [2018-08-23 16:12:58,395] - Components::process(): Request for the process of identity...
  WARN root [0x00002a30] [2018-08-23 16:13:04,458] - EntityApp::checkTickPeriod: tick took 6063% (6.06 seconds)!
  INFO root [0x00002a30] [2018-08-23 16:13:05,495] - Components::findComponents: find logger(1)...
  INFO root [0x00002a30] [2018-08-23 16:13:05,559] - Components::findComponents: found logger, addr:192.168.0.106:56181
  INFO root [0x00002a30] [2018-08-23 16:13:05,560] - Components::addComponent: reset orderLog, uid=18452!
  INFO root [0x00002a30] [2018-08-23 16:13:05,560] - Components::addComponent[logger], uid=18452, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00002a30] [2018-08-23 16:13:05,562] - Components::findComponents: find dbmgr(2)...
  INFO root [0x00002a30] [2018-08-23 16:13:05,665] - Components::findComponents: found dbmgr, addr:192.168.0.106:56182
  INFO root [0x00002a30] [2018-08-23 16:13:05,665] - Components::addComponent: reset orderLog, uid=18452!
  INFO root [0x00002a30] [2018-08-23 16:13:05,666] - Components::addComponent[dbmgr], uid=18452, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00002a30] [2018-08-23 16:13:05,666] - Components::findComponents: found dbmgr, addr:192.168.0.106:56182
  WARN root [0x00002a30] [2018-08-23 16:13:06,667] - EntityApp::checkTickPeriod: tick took 1272% (1.27 seconds)!
  WARN root [0x00002a30] [2018-08-23 16:13:06,668] - Forwarding logs to logger[192.168.0.106:56181/0/0/0]...
 ERROR root [0x00002a30] [2018-08-23 16:14:07,282] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x00002a30] [2018-08-23 16:14:07,297] - The following logs sent to logger failed:
  WARN root [0x00002a30] [2018-08-23 16:14:07,297] - ==> [2018-08-23 16:14:07 278] TCPPacketReceiver::processPendingEvents(192.168.0.106:56181): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00002a30] [2018-08-23 16:14:07,297] - ==> [2018-08-23 16:14:07 282] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x00002a30] [2018-08-23 16:14:07,352] - TCPPacketReceiver::processPendingEvents(192.168.0.106:56182): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00002a30] [2018-08-23 16:14:07,356] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x00002a30] [2018-08-23 16:14:07,373] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [0x00002a30] [2018-08-23 16:14:07,374] - onBaseAppShutDown: state=0
  INFO root [0x00002a30] [2018-08-23 16:14:07,374] - Shutdowner::onShutdown: shutting down
S_INFO root [0x00002a30] [2018-08-23 16:14:07,374] - onBaseAppShutDown: state=1
  INFO root [0x00002a30] [2018-08-23 16:14:07,375] - Shutdowner::onShutdownEnd: shutting down
S_INFO root [0x00002a30] [2018-08-23 16:14:07,375] - onBaseAppShutDown: state=2
 ERROR root [0x00002a30] [2018-08-23 16:14:07,383] - Account::onCellWriteToDBCompleted(2002): not found dbmgr!
 ERROR root [0x00002a30] [2018-08-23 16:14:07,385] - Entity::onDestroy: not found dbmgr!
 DEBUG root [0x00002a30] [2018-08-23 16:14:07,386] - Account::~Account(): 2002
 DEBUG root [0x00002a30] [2018-08-23 16:14:07,386] - Room::~Room(): 2003
 DEBUG root [0x00002a30] [2018-08-23 16:14:07,386] - Halls::~Halls(): 2001
 DEBUG root [0x00002a30] [2018-08-23 16:14:07,387] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00002a30] [2018-08-23 16:14:07,387] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x00002a30] [2018-08-23 16:14:07,388] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x00002a30] [2018-08-23 16:14:07,388] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x00002a30] [2018-08-23 16:14:07,388] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x00002a30] [2018-08-23 16:14:07,388] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x00002a30] [2018-08-23 16:14:07,388] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x00002a30] [2018-08-23 16:14:07,388] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x00002a30] [2018-08-23 16:14:07,397] - Script::uninstall(): is successfully!
 DEBUG root [0x00002a30] [2018-08-23 16:14:07,398] - ThreadPool::destroy(): starting size 2.
  INFO root [0x00003b48] [2018-08-23 16:14:08,652] - 
  INFO root [0x00003b48] [2018-08-23 16:14:08,652] - -----------------------------------------------------------------------------------------


  INFO root [0x00003b48] [2018-08-23 16:14:08,653] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [0x00003b48] [2018-08-23 16:14:08,653] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [0x00003b48] [2018-08-23 16:14:08,653] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [0x00003b48] [2018-08-23 16:14:08,658] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:20015 )
  INFO root [0x00003b48] [2018-08-23 16:14:08,658] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.106:20015, SOMAXCONN=128.
  INFO root [0x00003b48] [2018-08-23 16:14:08,660] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:56223 )
  INFO root [0x00003b48] [2018-08-23 16:14:08,660] - NetworkInterface::initialize(INTERNAL): address 192.168.0.106:56223, SOMAXCONN=128.
  INFO root [0x00003b48] [2018-08-23 16:14:08,660] - server-configs:
  INFO root [0x00003b48] [2018-08-23 16:14:08,660] - 	gameUpdateHertz : 10
  INFO root [0x00003b48] [2018-08-23 16:14:08,660] - 	entryScriptFile : kbemain
  INFO root [0x00003b48] [2018-08-23 16:14:08,661] - 	internalAddr : 192.168.0.106:56223
  INFO root [0x00003b48] [2018-08-23 16:14:08,661] - 	externalAddr : 192.168.0.106:20015
  INFO root [0x00003b48] [2018-08-23 16:14:08,661] - 	componentID : 7001
  INFO root [0x00003b48] [2018-08-23 16:14:10,381] - ---- baseapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: F9DFFB319FBADF35943ADF4D42C4718C. Config: Debug X86. Built: 15:53:31 Apr 29 2018. AppID: 7001. UID: 18687. PID: 15376 ----
  INFO root [0x00003b48] [2018-08-23 16:14:10,382] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [0x00003b48] [2018-08-23 16:14:10,382] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00003b48] [2018-08-23 16:14:10,382] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x00003b48] [2018-08-23 16:14:10,505] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00003b48] [2018-08-23 16:14:10,505] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x00003b48] [2018-08-23 16:14:10,506] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x00003b48] [2018-08-23 16:14:10,509] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x00003b48] [2018-08-23 16:14:10,510] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x00003b48] [2018-08-23 16:14:10,510] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x00003b48] [2018-08-23 16:14:10,511] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x00003b48] [2018-08-23 16:14:10,540] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x00003b48] [2018-08-23 16:14:10,572] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x00003b48] [2018-08-23 16:14:10,573] - Script::install(): KBExtra is successfully!
 DEBUG root [0x00003b48] [2018-08-23 16:14:10,594] - loaded entity-script:Account(1).
 DEBUG root [0x00003b48] [2018-08-23 16:14:10,595] - loaded entity-script:CheckName(2).
 DEBUG root [0x00003b48] [2018-08-23 16:14:10,600] - loaded entity-script:Halls(3).
 DEBUG root [0x00003b48] [2018-08-23 16:14:10,601] - loaded entity-script:Room(4).
  INFO root [0x00003b48] [2018-08-23 16:14:10,602] - Baseapp::initializeEnd: started resmgr tick(60s)!
  INFO root [0x00003b48] [2018-08-23 16:14:10,602] - TelnetServer server is running on port 40000
  INFO root [0x00003b48] [2018-08-23 16:14:10,917] - ---- baseapp is running ----
 DEBUG root [0x00003b48] [2018-08-23 16:14:10,918] - Components::process(): Request for the process of identity...
  WARN root [0x00003b48] [2018-08-23 16:14:16,983] - EntityApp::checkTickPeriod: tick took 6065% (6.07 seconds)!
  INFO root [0x00003b48] [2018-08-23 16:14:18,019] - Components::findComponents: find logger(1)...
  INFO root [0x00003b48] [2018-08-23 16:14:18,120] - Components::findComponents: found logger, addr:192.168.0.106:56221
  INFO root [0x00003b48] [2018-08-23 16:14:18,120] - Components::addComponent: reset orderLog, uid=18687!
  INFO root [0x00003b48] [2018-08-23 16:14:18,121] - Components::addComponent[logger], uid=18687, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00003b48] [2018-08-23 16:14:18,121] - Components::findComponents: find dbmgr(2)...
  INFO root [0x00003b48] [2018-08-23 16:14:18,225] - Components::findComponents: found dbmgr, addr:192.168.0.106:56219
  INFO root [0x00003b48] [2018-08-23 16:14:18,226] - Components::addComponent: reset orderLog, uid=18687!
  INFO root [0x00003b48] [2018-08-23 16:14:18,227] - Components::addComponent[dbmgr], uid=18687, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00003b48] [2018-08-23 16:14:18,228] - Components::findComponents: found dbmgr, addr:192.168.0.106:56219
  WARN root [0x00003b48] [2018-08-23 16:14:19,228] - EntityApp::checkTickPeriod: tick took 1309% (1.31 seconds)!
  WARN root [0x00003b48] [2018-08-23 16:14:19,230] - Forwarding logs to logger[192.168.0.106:56221/0/0/0]...
 ERROR root [0x00003b48] [2018-08-23 16:18:16,576] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x00003b48] [2018-08-23 16:18:16,595] - The following logs sent to logger failed:
  WARN root [0x00003b48] [2018-08-23 16:18:16,596] - ==> [2018-08-23 16:18:16 573] TCPPacketReceiver::processPendingEvents(192.168.0.106:56221): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00003b48] [2018-08-23 16:18:16,596] - ==> [2018-08-23 16:18:16 577] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x00003b48] [2018-08-23 16:18:16,647] - TCPPacketReceiver::processPendingEvents(192.168.0.106:56219): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00003b48] [2018-08-23 16:18:16,651] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x00003b48] [2018-08-23 16:18:16,666] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [0x00003b48] [2018-08-23 16:18:16,667] - onBaseAppShutDown: state=0
  INFO root [0x00003b48] [2018-08-23 16:18:16,667] - Shutdowner::onShutdown: shutting down
S_INFO root [0x00003b48] [2018-08-23 16:18:16,667] - onBaseAppShutDown: state=1
  INFO root [0x00003b48] [2018-08-23 16:18:16,667] - Shutdowner::onShutdownEnd: shutting down
S_INFO root [0x00003b48] [2018-08-23 16:18:16,668] - onBaseAppShutDown: state=2
 ERROR root [0x00003b48] [2018-08-23 16:18:16,675] - Account::onCellWriteToDBCompleted(2002): not found dbmgr!
 ERROR root [0x00003b48] [2018-08-23 16:18:16,676] - Entity::onDestroy: not found dbmgr!
 ERROR root [0x00003b48] [2018-08-23 16:18:16,677] - Account::onCellWriteToDBCompleted(2004): not found dbmgr!
 ERROR root [0x00003b48] [2018-08-23 16:18:16,677] - Entity::onDestroy: not found dbmgr!
 DEBUG root [0x00003b48] [2018-08-23 16:18:16,678] - Account::~Account(): 2002
 DEBUG root [0x00003b48] [2018-08-23 16:18:16,678] - Account::~Account(): 2004
 DEBUG root [0x00003b48] [2018-08-23 16:18:16,678] - Room::~Room(): 2003
 DEBUG root [0x00003b48] [2018-08-23 16:18:16,678] - Halls::~Halls(): 2001
 DEBUG root [0x00003b48] [2018-08-23 16:18:16,679] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00003b48] [2018-08-23 16:18:16,679] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x00003b48] [2018-08-23 16:18:16,679] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x00003b48] [2018-08-23 16:18:16,679] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x00003b48] [2018-08-23 16:18:16,679] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x00003b48] [2018-08-23 16:18:16,679] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x00003b48] [2018-08-23 16:18:16,680] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x00003b48] [2018-08-23 16:18:16,680] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x00003b48] [2018-08-23 16:18:16,691] - Script::uninstall(): is successfully!
 DEBUG root [0x00003b48] [2018-08-23 16:18:16,691] - ThreadPool::destroy(): starting size 2.
  INFO root [0x00003fd4] [2018-08-23 16:18:17,915] - 
  INFO root [0x00003fd4] [2018-08-23 16:18:17,918] - -----------------------------------------------------------------------------------------


  INFO root [0x00003fd4] [2018-08-23 16:18:17,919] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [0x00003fd4] [2018-08-23 16:18:17,919] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [0x00003fd4] [2018-08-23 16:18:17,919] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [0x00003fd4] [2018-08-23 16:18:17,931] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:20015 )
  INFO root [0x00003fd4] [2018-08-23 16:18:17,931] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.106:20015, SOMAXCONN=128.
  INFO root [0x00003fd4] [2018-08-23 16:18:17,934] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:56298 )
  INFO root [0x00003fd4] [2018-08-23 16:18:17,934] - NetworkInterface::initialize(INTERNAL): address 192.168.0.106:56298, SOMAXCONN=128.
  INFO root [0x00003fd4] [2018-08-23 16:18:17,934] - server-configs:
  INFO root [0x00003fd4] [2018-08-23 16:18:17,934] - 	gameUpdateHertz : 10
  INFO root [0x00003fd4] [2018-08-23 16:18:17,934] - 	entryScriptFile : kbemain
  INFO root [0x00003fd4] [2018-08-23 16:18:17,934] - 	internalAddr : 192.168.0.106:56298
  INFO root [0x00003fd4] [2018-08-23 16:18:17,934] - 	externalAddr : 192.168.0.106:20015
  INFO root [0x00003fd4] [2018-08-23 16:18:17,935] - 	componentID : 7001
  INFO root [0x00003fd4] [2018-08-23 16:18:19,648] - ---- baseapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: F9DFFB319FBADF35943ADF4D42C4718C. Config: Debug X86. Built: 15:53:31 Apr 29 2018. AppID: 7001. UID: 19500. PID: 12588 ----
  INFO root [0x00003fd4] [2018-08-23 16:18:19,648] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [0x00003fd4] [2018-08-23 16:18:19,649] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00003fd4] [2018-08-23 16:18:19,649] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x00003fd4] [2018-08-23 16:18:19,772] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00003fd4] [2018-08-23 16:18:19,772] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x00003fd4] [2018-08-23 16:18:19,772] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x00003fd4] [2018-08-23 16:18:19,775] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x00003fd4] [2018-08-23 16:18:19,776] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x00003fd4] [2018-08-23 16:18:19,776] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x00003fd4] [2018-08-23 16:18:19,776] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x00003fd4] [2018-08-23 16:18:19,811] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x00003fd4] [2018-08-23 16:18:19,848] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x00003fd4] [2018-08-23 16:18:19,848] - Script::install(): KBExtra is successfully!
 DEBUG root [0x00003fd4] [2018-08-23 16:18:19,870] - loaded entity-script:Account(1).
 DEBUG root [0x00003fd4] [2018-08-23 16:18:19,871] - loaded entity-script:CheckName(2).
 DEBUG root [0x00003fd4] [2018-08-23 16:18:19,878] - loaded entity-script:Halls(3).
 DEBUG root [0x00003fd4] [2018-08-23 16:18:19,879] - loaded entity-script:Room(4).
  INFO root [0x00003fd4] [2018-08-23 16:18:19,879] - Baseapp::initializeEnd: started resmgr tick(60s)!
  INFO root [0x00003fd4] [2018-08-23 16:18:19,879] - TelnetServer server is running on port 40000
  INFO root [0x00003fd4] [2018-08-23 16:18:20,203] - ---- baseapp is running ----
 DEBUG root [0x00003fd4] [2018-08-23 16:18:20,204] - Components::process(): Request for the process of identity...
  WARN root [0x00003fd4] [2018-08-23 16:18:26,276] - EntityApp::checkTickPeriod: tick took 6071% (6.07 seconds)!
  INFO root [0x00003fd4] [2018-08-23 16:18:27,305] - Components::findComponents: find logger(1)...
  INFO root [0x00003fd4] [2018-08-23 16:18:27,366] - Components::findComponents: found logger, addr:192.168.0.106:56297
  INFO root [0x00003fd4] [2018-08-23 16:18:27,366] - Components::addComponent: reset orderLog, uid=19500!
  INFO root [0x00003fd4] [2018-08-23 16:18:27,366] - Components::addComponent[logger], uid=19500, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00003fd4] [2018-08-23 16:18:27,367] - Components::findComponents: find dbmgr(2)...
  INFO root [0x00003fd4] [2018-08-23 16:18:27,470] - Components::findComponents: found dbmgr, addr:192.168.0.106:56300
  INFO root [0x00003fd4] [2018-08-23 16:18:27,470] - Components::addComponent: reset orderLog, uid=19500!
  INFO root [0x00003fd4] [2018-08-23 16:18:27,470] - Components::addComponent[dbmgr], uid=19500, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00003fd4] [2018-08-23 16:18:27,470] - Components::findComponents: found dbmgr, addr:192.168.0.106:56300
  WARN root [0x00003fd4] [2018-08-23 16:18:28,470] - EntityApp::checkTickPeriod: tick took 1265% (1.26 seconds)!
  WARN root [0x00003fd4] [2018-08-23 16:18:28,472] - Forwarding logs to logger[192.168.0.106:56297/0/0/0]...
 ERROR root [0x00003fd4] [2018-08-23 16:21:56,310] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x00003fd4] [2018-08-23 16:21:56,327] - The following logs sent to logger failed:
  WARN root [0x00003fd4] [2018-08-23 16:21:56,327] - ==> [2018-08-23 16:21:56 306] TCPPacketReceiver::processPendingEvents(192.168.0.106:56297): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00003fd4] [2018-08-23 16:21:56,327] - ==> [2018-08-23 16:21:56 310] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x00003fd4] [2018-08-23 16:21:56,381] - TCPPacketReceiver::processPendingEvents(192.168.0.106:56300): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00003fd4] [2018-08-23 16:21:56,384] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x00003fd4] [2018-08-23 16:21:56,401] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [0x00003fd4] [2018-08-23 16:21:56,403] - onBaseAppShutDown: state=0
  INFO root [0x00003fd4] [2018-08-23 16:21:56,403] - Shutdowner::onShutdown: shutting down
S_INFO root [0x00003fd4] [2018-08-23 16:21:56,403] - onBaseAppShutDown: state=1
  INFO root [0x00003fd4] [2018-08-23 16:21:56,404] - Shutdowner::onShutdownEnd: shutting down
S_INFO root [0x00003fd4] [2018-08-23 16:21:56,404] - onBaseAppShutDown: state=2
 ERROR root [0x00003fd4] [2018-08-23 16:21:56,412] - Account::onCellWriteToDBCompleted(2002): not found dbmgr!
 ERROR root [0x00003fd4] [2018-08-23 16:21:56,412] - Entity::onDestroy: not found dbmgr!
 ERROR root [0x00003fd4] [2018-08-23 16:21:56,413] - Account::onCellWriteToDBCompleted(2004): not found dbmgr!
 ERROR root [0x00003fd4] [2018-08-23 16:21:56,413] - Entity::onDestroy: not found dbmgr!
 DEBUG root [0x00003fd4] [2018-08-23 16:21:56,414] - Account::~Account(): 2002
 DEBUG root [0x00003fd4] [2018-08-23 16:21:56,414] - Account::~Account(): 2004
 DEBUG root [0x00003fd4] [2018-08-23 16:21:56,414] - Room::~Room(): 2003
 DEBUG root [0x00003fd4] [2018-08-23 16:21:56,414] - Halls::~Halls(): 2001
 DEBUG root [0x00003fd4] [2018-08-23 16:21:56,415] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00003fd4] [2018-08-23 16:21:56,415] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x00003fd4] [2018-08-23 16:21:56,415] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x00003fd4] [2018-08-23 16:21:56,415] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x00003fd4] [2018-08-23 16:21:56,415] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x00003fd4] [2018-08-23 16:21:56,415] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x00003fd4] [2018-08-23 16:21:56,415] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x00003fd4] [2018-08-23 16:21:56,416] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x00003fd4] [2018-08-23 16:21:56,426] - Script::uninstall(): is successfully!
 DEBUG root [0x00003fd4] [2018-08-23 16:21:56,426] - ThreadPool::destroy(): starting size 2.
  INFO root [0x000046bc] [2018-08-23 16:21:57,683] - 
  INFO root [0x000046bc] [2018-08-23 16:21:57,684] - -----------------------------------------------------------------------------------------


  INFO root [0x000046bc] [2018-08-23 16:21:57,685] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [0x000046bc] [2018-08-23 16:21:57,685] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [0x000046bc] [2018-08-23 16:21:57,686] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [0x000046bc] [2018-08-23 16:21:57,691] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:20015 )
  INFO root [0x000046bc] [2018-08-23 16:21:57,691] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.106:20015, SOMAXCONN=128.
  INFO root [0x000046bc] [2018-08-23 16:21:57,693] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:56360 )
  INFO root [0x000046bc] [2018-08-23 16:21:57,693] - NetworkInterface::initialize(INTERNAL): address 192.168.0.106:56360, SOMAXCONN=128.
  INFO root [0x000046bc] [2018-08-23 16:21:57,694] - server-configs:
  INFO root [0x000046bc] [2018-08-23 16:21:57,694] - 	gameUpdateHertz : 10
  INFO root [0x000046bc] [2018-08-23 16:21:57,694] - 	entryScriptFile : kbemain
  INFO root [0x000046bc] [2018-08-23 16:21:57,694] - 	internalAddr : 192.168.0.106:56360
  INFO root [0x000046bc] [2018-08-23 16:21:57,694] - 	externalAddr : 192.168.0.106:20015
  INFO root [0x000046bc] [2018-08-23 16:21:57,694] - 	componentID : 7001
  INFO root [0x000046bc] [2018-08-23 16:21:59,420] - ---- baseapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: F9DFFB319FBADF35943ADF4D42C4718C. Config: Debug X86. Built: 15:53:31 Apr 29 2018. AppID: 7001. UID: 20218. PID: 18104 ----
  INFO root [0x000046bc] [2018-08-23 16:21:59,421] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [0x000046bc] [2018-08-23 16:21:59,421] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x000046bc] [2018-08-23 16:21:59,422] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x000046bc] [2018-08-23 16:21:59,553] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x000046bc] [2018-08-23 16:21:59,554] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x000046bc] [2018-08-23 16:21:59,554] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x000046bc] [2018-08-23 16:21:59,557] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x000046bc] [2018-08-23 16:21:59,557] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x000046bc] [2018-08-23 16:21:59,557] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x000046bc] [2018-08-23 16:21:59,558] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x000046bc] [2018-08-23 16:21:59,585] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x000046bc] [2018-08-23 16:21:59,617] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x000046bc] [2018-08-23 16:21:59,618] - Script::install(): KBExtra is successfully!
 DEBUG root [0x000046bc] [2018-08-23 16:21:59,638] - loaded entity-script:Account(1).
 DEBUG root [0x000046bc] [2018-08-23 16:21:59,639] - loaded entity-script:CheckName(2).
 DEBUG root [0x000046bc] [2018-08-23 16:21:59,646] - loaded entity-script:Halls(3).
 DEBUG root [0x000046bc] [2018-08-23 16:21:59,647] - loaded entity-script:Room(4).
  INFO root [0x000046bc] [2018-08-23 16:21:59,647] - Baseapp::initializeEnd: started resmgr tick(60s)!
  INFO root [0x000046bc] [2018-08-23 16:21:59,647] - TelnetServer server is running on port 40000
  INFO root [0x000046bc] [2018-08-23 16:21:59,965] - ---- baseapp is running ----
 DEBUG root [0x000046bc] [2018-08-23 16:21:59,965] - Components::process(): Request for the process of identity...
  WARN root [0x000046bc] [2018-08-23 16:22:00,275] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20094, errorno=10048
  WARN root [0x000046bc] [2018-08-23 16:22:06,415] - EntityApp::checkTickPeriod: tick took 6450% (6.45 seconds)!
  INFO root [0x000046bc] [2018-08-23 16:22:07,465] - Components::findComponents: find logger(1)...
  INFO root [0x000046bc] [2018-08-23 16:22:07,538] - Components::findComponents: found logger, addr:192.168.0.106:56357
  INFO root [0x000046bc] [2018-08-23 16:22:07,538] - Components::addComponent: reset orderLog, uid=20218!
  INFO root [0x000046bc] [2018-08-23 16:22:07,538] - Components::addComponent[logger], uid=20218, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x000046bc] [2018-08-23 16:22:07,540] - Components::findComponents: find dbmgr(2)...
  INFO root [0x000046bc] [2018-08-23 16:22:07,640] - Components::findComponents: found dbmgr, addr:192.168.0.106:56363
  INFO root [0x000046bc] [2018-08-23 16:22:07,641] - Components::addComponent: reset orderLog, uid=20218!
  INFO root [0x000046bc] [2018-08-23 16:22:07,641] - Components::addComponent[dbmgr], uid=20218, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x000046bc] [2018-08-23 16:22:07,641] - Components::findComponents: found dbmgr, addr:192.168.0.106:56363
  WARN root [0x000046bc] [2018-08-23 16:22:08,641] - EntityApp::checkTickPeriod: tick took 1276% (1.28 seconds)!
  WARN root [0x000046bc] [2018-08-23 16:22:08,641] - Forwarding logs to logger[192.168.0.106:56357/0/0/0]...
 ERROR root [0x000046bc] [2018-08-23 16:37:35,283] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x000046bc] [2018-08-23 16:37:35,295] - The following logs sent to logger failed:
  WARN root [0x000046bc] [2018-08-23 16:37:35,296] - ==> [2018-08-23 16:37:35 272] TCPPacketReceiver::processPendingEvents(192.168.0.106:56357): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x000046bc] [2018-08-23 16:37:35,296] - ==> [2018-08-23 16:37:35 283] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x000046bc] [2018-08-23 16:37:35,349] - TCPPacketReceiver::processPendingEvents(192.168.0.106:56363): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x000046bc] [2018-08-23 16:37:35,353] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x000046bc] [2018-08-23 16:37:35,368] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [0x000046bc] [2018-08-23 16:37:35,368] - onBaseAppShutDown: state=0
  INFO root [0x000046bc] [2018-08-23 16:37:35,368] - Shutdowner::onShutdown: shutting down
S_INFO root [0x000046bc] [2018-08-23 16:37:35,368] - onBaseAppShutDown: state=1
  INFO root [0x000046bc] [2018-08-23 16:37:35,368] - Shutdowner::onShutdownEnd: shutting down
S_INFO root [0x000046bc] [2018-08-23 16:37:35,368] - onBaseAppShutDown: state=2
 ERROR root [0x000046bc] [2018-08-23 16:37:35,377] - Account::onCellWriteToDBCompleted(2002): not found dbmgr!
 ERROR root [0x000046bc] [2018-08-23 16:37:35,378] - Entity::onDestroy: not found dbmgr!
 ERROR root [0x000046bc] [2018-08-23 16:37:35,378] - Account::onCellWriteToDBCompleted(2004): not found dbmgr!
 ERROR root [0x000046bc] [2018-08-23 16:37:35,379] - Entity::onDestroy: not found dbmgr!
 DEBUG root [0x000046bc] [2018-08-23 16:37:35,379] - Account::~Account(): 2002
 DEBUG root [0x000046bc] [2018-08-23 16:37:35,379] - Account::~Account(): 2004
 DEBUG root [0x000046bc] [2018-08-23 16:37:35,380] - Room::~Room(): 2003
 DEBUG root [0x000046bc] [2018-08-23 16:37:35,380] - Halls::~Halls(): 2001
 DEBUG root [0x000046bc] [2018-08-23 16:37:35,381] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x000046bc] [2018-08-23 16:37:35,381] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x000046bc] [2018-08-23 16:37:35,381] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x000046bc] [2018-08-23 16:37:35,381] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x000046bc] [2018-08-23 16:37:35,381] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x000046bc] [2018-08-23 16:37:35,381] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x000046bc] [2018-08-23 16:37:35,381] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x000046bc] [2018-08-23 16:37:35,381] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x000046bc] [2018-08-23 16:37:35,391] - Script::uninstall(): is successfully!
 DEBUG root [0x000046bc] [2018-08-23 16:37:35,392] - ThreadPool::destroy(): starting size 2.
  INFO root [0x000035e4] [2018-08-23 16:37:36,709] - 
  INFO root [0x000035e4] [2018-08-23 16:37:36,711] - -----------------------------------------------------------------------------------------


  INFO root [0x000035e4] [2018-08-23 16:37:36,712] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [0x000035e4] [2018-08-23 16:37:36,712] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [0x000035e4] [2018-08-23 16:37:36,713] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [0x000035e4] [2018-08-23 16:37:36,715] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:20015 )
  INFO root [0x000035e4] [2018-08-23 16:37:36,716] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.106:20015, SOMAXCONN=128.
  INFO root [0x000035e4] [2018-08-23 16:37:36,717] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:60631 )
  INFO root [0x000035e4] [2018-08-23 16:37:36,717] - NetworkInterface::initialize(INTERNAL): address 192.168.0.106:60631, SOMAXCONN=128.
  INFO root [0x000035e4] [2018-08-23 16:37:36,717] - server-configs:
  INFO root [0x000035e4] [2018-08-23 16:37:36,717] - 	gameUpdateHertz : 10
  INFO root [0x000035e4] [2018-08-23 16:37:36,717] - 	entryScriptFile : kbemain
  INFO root [0x000035e4] [2018-08-23 16:37:36,718] - 	internalAddr : 192.168.0.106:60631
  INFO root [0x000035e4] [2018-08-23 16:37:36,718] - 	externalAddr : 192.168.0.106:20015
  INFO root [0x000035e4] [2018-08-23 16:37:36,718] - 	componentID : 7001
  INFO root [0x000035e4] [2018-08-23 16:37:38,414] - ---- baseapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: F9DFFB319FBADF35943ADF4D42C4718C. Config: Debug X86. Built: 15:53:31 Apr 29 2018. AppID: 7001. UID: 23285. PID: 17188 ----
  INFO root [0x000035e4] [2018-08-23 16:37:38,414] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [0x000035e4] [2018-08-23 16:37:38,415] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x000035e4] [2018-08-23 16:37:38,415] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x000035e4] [2018-08-23 16:37:38,543] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x000035e4] [2018-08-23 16:37:38,544] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x000035e4] [2018-08-23 16:37:38,544] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x000035e4] [2018-08-23 16:37:38,547] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x000035e4] [2018-08-23 16:37:38,547] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x000035e4] [2018-08-23 16:37:38,548] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x000035e4] [2018-08-23 16:37:38,548] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x000035e4] [2018-08-23 16:37:38,579] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x000035e4] [2018-08-23 16:37:38,614] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x000035e4] [2018-08-23 16:37:38,615] - Script::install(): KBExtra is successfully!
 DEBUG root [0x000035e4] [2018-08-23 16:37:38,640] - loaded entity-script:Account(1).
 DEBUG root [0x000035e4] [2018-08-23 16:37:38,641] - loaded entity-script:CheckName(2).
 DEBUG root [0x000035e4] [2018-08-23 16:37:38,648] - loaded entity-script:Halls(3).
 DEBUG root [0x000035e4] [2018-08-23 16:37:38,649] - loaded entity-script:Room(4).
  INFO root [0x000035e4] [2018-08-23 16:37:38,649] - Baseapp::initializeEnd: started resmgr tick(60s)!
  INFO root [0x000035e4] [2018-08-23 16:37:38,650] - TelnetServer server is running on port 40000
  INFO root [0x000035e4] [2018-08-23 16:37:38,949] - ---- baseapp is running ----
 DEBUG root [0x000035e4] [2018-08-23 16:37:38,949] - Components::process(): Request for the process of identity...
  WARN root [0x000035e4] [2018-08-23 16:37:45,005] - EntityApp::checkTickPeriod: tick took 6056% (6.06 seconds)!
  INFO root [0x000035e4] [2018-08-23 16:37:46,014] - Components::findComponents: find logger(1)...
  INFO root [0x000035e4] [2018-08-23 16:37:46,047] - Components::findComponents: found logger, addr:192.168.0.106:60629
  INFO root [0x000035e4] [2018-08-23 16:37:46,047] - Components::addComponent: reset orderLog, uid=23285!
  INFO root [0x000035e4] [2018-08-23 16:37:46,047] - Components::addComponent[logger], uid=23285, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x000035e4] [2018-08-23 16:37:46,048] - Components::findComponents: find dbmgr(2)...
  INFO root [0x000035e4] [2018-08-23 16:37:46,149] - Components::findComponents: found dbmgr, addr:192.168.0.106:60626
  INFO root [0x000035e4] [2018-08-23 16:37:46,149] - Components::addComponent: reset orderLog, uid=23285!
  INFO root [0x000035e4] [2018-08-23 16:37:46,149] - Components::addComponent[dbmgr], uid=23285, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x000035e4] [2018-08-23 16:37:46,149] - Components::findComponents: found dbmgr, addr:192.168.0.106:60626
  WARN root [0x000035e4] [2018-08-23 16:37:47,149] - Forwarding logs to logger[192.168.0.106:60629/0/0/0]...
 ERROR root [0x000035e4] [2018-08-23 17:33:50,829] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x000035e4] [2018-08-23 17:33:50,854] - The following logs sent to logger failed:
  WARN root [0x000035e4] [2018-08-23 17:33:50,854] - ==> [2018-08-23 17:33:50 825] TCPPacketReceiver::processPendingEvents(192.168.0.106:60629): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x000035e4] [2018-08-23 17:33:50,854] - ==> [2018-08-23 17:33:50 829] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x000035e4] [2018-08-23 17:33:50,906] - TCPPacketReceiver::processPendingEvents(192.168.0.106:60626): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x000035e4] [2018-08-23 17:33:50,909] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x000035e4] [2018-08-23 17:33:50,933] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [0x000035e4] [2018-08-23 17:33:50,933] - onBaseAppShutDown: state=0
  INFO root [0x000035e4] [2018-08-23 17:33:50,934] - Shutdowner::onShutdown: shutting down
S_INFO root [0x000035e4] [2018-08-23 17:33:50,934] - onBaseAppShutDown: state=1
  INFO root [0x000035e4] [2018-08-23 17:33:50,934] - Shutdowner::onShutdownEnd: shutting down
S_INFO root [0x000035e4] [2018-08-23 17:33:50,934] - onBaseAppShutDown: state=2
 ERROR root [0x000035e4] [2018-08-23 17:33:50,942] - Account::onCellWriteToDBCompleted(2002): not found dbmgr!
 ERROR root [0x000035e4] [2018-08-23 17:33:50,944] - Entity::onDestroy: not found dbmgr!
 ERROR root [0x000035e4] [2018-08-23 17:33:50,945] - Account::onCellWriteToDBCompleted(2004): not found dbmgr!
 ERROR root [0x000035e4] [2018-08-23 17:33:50,947] - Entity::onDestroy: not found dbmgr!
 DEBUG root [0x000035e4] [2018-08-23 17:33:50,947] - Account::~Account(): 2002
 DEBUG root [0x000035e4] [2018-08-23 17:33:50,947] - Account::~Account(): 2004
 DEBUG root [0x000035e4] [2018-08-23 17:33:50,947] - Room::~Room(): 2003
 DEBUG root [0x000035e4] [2018-08-23 17:33:50,948] - Halls::~Halls(): 2001
 DEBUG root [0x000035e4] [2018-08-23 17:33:50,948] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x000035e4] [2018-08-23 17:33:50,949] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x000035e4] [2018-08-23 17:33:50,949] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x000035e4] [2018-08-23 17:33:50,949] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x000035e4] [2018-08-23 17:33:50,949] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x000035e4] [2018-08-23 17:33:50,949] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x000035e4] [2018-08-23 17:33:50,949] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x000035e4] [2018-08-23 17:33:50,949] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x000035e4] [2018-08-23 17:33:50,959] - Script::uninstall(): is successfully!
 DEBUG root [0x000035e4] [2018-08-23 17:33:50,960] - ThreadPool::destroy(): starting size 2.
  INFO root [0x000029f4] [2018-08-23 17:33:52,261] - 
  INFO root [0x000029f4] [2018-08-23 17:33:52,262] - -----------------------------------------------------------------------------------------


  INFO root [0x000029f4] [2018-08-23 17:33:52,262] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [0x000029f4] [2018-08-23 17:33:52,263] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [0x000029f4] [2018-08-23 17:33:52,263] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [0x000029f4] [2018-08-23 17:33:52,270] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:20015 )
  INFO root [0x000029f4] [2018-08-23 17:33:52,270] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.106:20015, SOMAXCONN=128.
  INFO root [0x000029f4] [2018-08-23 17:33:52,271] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:63993 )
  INFO root [0x000029f4] [2018-08-23 17:33:52,272] - NetworkInterface::initialize(INTERNAL): address 192.168.0.106:63993, SOMAXCONN=128.
  INFO root [0x000029f4] [2018-08-23 17:33:52,272] - server-configs:
  INFO root [0x000029f4] [2018-08-23 17:33:52,272] - 	gameUpdateHertz : 10
  INFO root [0x000029f4] [2018-08-23 17:33:52,272] - 	entryScriptFile : kbemain
  INFO root [0x000029f4] [2018-08-23 17:33:52,272] - 	internalAddr : 192.168.0.106:63993
  INFO root [0x000029f4] [2018-08-23 17:33:52,272] - 	externalAddr : 192.168.0.106:20015
  INFO root [0x000029f4] [2018-08-23 17:33:52,272] - 	componentID : 7001
  INFO root [0x000029f4] [2018-08-23 17:33:54,010] - ---- baseapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: F9DFFB319FBADF35943ADF4D42C4718C. Config: Debug X86. Built: 15:53:31 Apr 29 2018. AppID: 7001. UID: 1538. PID: 14228 ----
  INFO root [0x000029f4] [2018-08-23 17:33:54,011] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [0x000029f4] [2018-08-23 17:33:54,011] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x000029f4] [2018-08-23 17:33:54,011] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x000029f4] [2018-08-23 17:33:54,142] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x000029f4] [2018-08-23 17:33:54,142] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x000029f4] [2018-08-23 17:33:54,143] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x000029f4] [2018-08-23 17:33:54,146] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x000029f4] [2018-08-23 17:33:54,147] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x000029f4] [2018-08-23 17:33:54,147] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x000029f4] [2018-08-23 17:33:54,148] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x000029f4] [2018-08-23 17:33:54,184] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x000029f4] [2018-08-23 17:33:54,222] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x000029f4] [2018-08-23 17:33:54,222] - Script::install(): KBExtra is successfully!
 DEBUG root [0x000029f4] [2018-08-23 17:33:54,248] - loaded entity-script:Account(1).
 DEBUG root [0x000029f4] [2018-08-23 17:33:54,250] - loaded entity-script:CheckName(2).
 DEBUG root [0x000029f4] [2018-08-23 17:33:54,257] - loaded entity-script:Halls(3).
 DEBUG root [0x000029f4] [2018-08-23 17:33:54,259] - loaded entity-script:Room(4).
  INFO root [0x000029f4] [2018-08-23 17:33:54,259] - Baseapp::initializeEnd: started resmgr tick(60s)!
  INFO root [0x000029f4] [2018-08-23 17:33:54,259] - TelnetServer server is running on port 40000
  INFO root [0x000029f4] [2018-08-23 17:33:54,569] - ---- baseapp is running ----
 DEBUG root [0x000029f4] [2018-08-23 17:33:54,569] - Components::process(): Request for the process of identity...
  WARN root [0x000029f4] [2018-08-23 17:34:00,697] - EntityApp::checkTickPeriod: tick took 6128% (6.13 seconds)!
  INFO root [0x000029f4] [2018-08-23 17:34:01,767] - Components::findComponents: find logger(1)...
  INFO root [0x000029f4] [2018-08-23 17:34:01,819] - Components::findComponents: found logger, addr:192.168.0.106:63991
  INFO root [0x000029f4] [2018-08-23 17:34:01,819] - Components::addComponent: reset orderLog, uid=1538!
  INFO root [0x000029f4] [2018-08-23 17:34:01,820] - Components::addComponent[logger], uid=1538, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x000029f4] [2018-08-23 17:34:01,823] - Components::findComponents: find dbmgr(2)...
  INFO root [0x000029f4] [2018-08-23 17:34:01,921] - Components::findComponents: found dbmgr, addr:192.168.0.106:63990
  INFO root [0x000029f4] [2018-08-23 17:34:01,921] - Components::addComponent: reset orderLog, uid=1538!
  INFO root [0x000029f4] [2018-08-23 17:34:01,921] - Components::addComponent[dbmgr], uid=1538, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x000029f4] [2018-08-23 17:34:01,921] - Components::findComponents: found dbmgr, addr:192.168.0.106:63990
  WARN root [0x000029f4] [2018-08-23 17:34:02,922] - Forwarding logs to logger[192.168.0.106:63991/0/0/0]...
 ERROR root [0x000029f4] [2018-08-23 17:43:09,349] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x000029f4] [2018-08-23 17:43:09,371] - The following logs sent to logger failed:
  WARN root [0x000029f4] [2018-08-23 17:43:09,371] - ==> [2018-08-23 17:43:09 344] TCPPacketReceiver::processPendingEvents(192.168.0.106:63991): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x000029f4] [2018-08-23 17:43:09,371] - ==> [2018-08-23 17:43:09 350] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x000029f4] [2018-08-23 17:43:09,430] - TCPPacketReceiver::processPendingEvents(192.168.0.106:63990): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x000029f4] [2018-08-23 17:43:09,434] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x000029f4] [2018-08-23 17:43:09,456] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [0x000029f4] [2018-08-23 17:43:09,468] - onBaseAppShutDown: state=0
  INFO root [0x000029f4] [2018-08-23 17:43:09,469] - Shutdowner::onShutdown: shutting down
S_INFO root [0x000029f4] [2018-08-23 17:43:09,469] - onBaseAppShutDown: state=1
  INFO root [0x000029f4] [2018-08-23 17:43:09,469] - Shutdowner::onShutdownEnd: shutting down
S_INFO root [0x000029f4] [2018-08-23 17:43:09,469] - onBaseAppShutDown: state=2
 ERROR root [0x000029f4] [2018-08-23 17:43:09,477] - Account::onCellWriteToDBCompleted(2002): not found dbmgr!
 ERROR root [0x000029f4] [2018-08-23 17:43:09,482] - Entity::onDestroy: not found dbmgr!
 ERROR root [0x000029f4] [2018-08-23 17:43:09,483] - Account::onCellWriteToDBCompleted(2004): not found dbmgr!
 ERROR root [0x000029f4] [2018-08-23 17:43:09,484] - Entity::onDestroy: not found dbmgr!
 DEBUG root [0x000029f4] [2018-08-23 17:43:09,485] - Account::~Account(): 2002
 DEBUG root [0x000029f4] [2018-08-23 17:43:09,485] - Account::~Account(): 2004
 DEBUG root [0x000029f4] [2018-08-23 17:43:09,485] - Room::~Room(): 2003
 DEBUG root [0x000029f4] [2018-08-23 17:43:09,485] - Halls::~Halls(): 2001
 DEBUG root [0x000029f4] [2018-08-23 17:43:09,486] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x000029f4] [2018-08-23 17:43:09,486] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x000029f4] [2018-08-23 17:43:09,487] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x000029f4] [2018-08-23 17:43:09,487] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x000029f4] [2018-08-23 17:43:09,487] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x000029f4] [2018-08-23 17:43:09,487] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x000029f4] [2018-08-23 17:43:09,487] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x000029f4] [2018-08-23 17:43:09,487] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x000029f4] [2018-08-23 17:43:09,496] - Script::uninstall(): is successfully!
 DEBUG root [0x000029f4] [2018-08-23 17:43:09,496] - ThreadPool::destroy(): starting size 2.
  INFO root [0x000038e4] [2018-08-23 17:43:10,791] - 
  INFO root [0x000038e4] [2018-08-23 17:43:10,796] - -----------------------------------------------------------------------------------------


  INFO root [0x000038e4] [2018-08-23 17:43:10,797] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [0x000038e4] [2018-08-23 17:43:10,797] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [0x000038e4] [2018-08-23 17:43:10,797] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [0x000038e4] [2018-08-23 17:43:10,801] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:20015 )
  INFO root [0x000038e4] [2018-08-23 17:43:10,801] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.106:20015, SOMAXCONN=128.
  INFO root [0x000038e4] [2018-08-23 17:43:10,803] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:64118 )
  INFO root [0x000038e4] [2018-08-23 17:43:10,803] - NetworkInterface::initialize(INTERNAL): address 192.168.0.106:64118, SOMAXCONN=128.
  INFO root [0x000038e4] [2018-08-23 17:43:10,803] - server-configs:
  INFO root [0x000038e4] [2018-08-23 17:43:10,803] - 	gameUpdateHertz : 10
  INFO root [0x000038e4] [2018-08-23 17:43:10,803] - 	entryScriptFile : kbemain
  INFO root [0x000038e4] [2018-08-23 17:43:10,803] - 	internalAddr : 192.168.0.106:64118
  INFO root [0x000038e4] [2018-08-23 17:43:10,803] - 	externalAddr : 192.168.0.106:20015
  INFO root [0x000038e4] [2018-08-23 17:43:10,803] - 	componentID : 7001
  INFO root [0x000038e4] [2018-08-23 17:43:12,503] - ---- baseapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: F9DFFB319FBADF35943ADF4D42C4718C. Config: Debug X86. Built: 15:53:31 Apr 29 2018. AppID: 7001. UID: 3364. PID: 18660 ----
  INFO root [0x000038e4] [2018-08-23 17:43:12,504] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [0x000038e4] [2018-08-23 17:43:12,504] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x000038e4] [2018-08-23 17:43:12,504] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x000038e4] [2018-08-23 17:43:12,628] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x000038e4] [2018-08-23 17:43:12,628] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x000038e4] [2018-08-23 17:43:12,628] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x000038e4] [2018-08-23 17:43:12,631] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x000038e4] [2018-08-23 17:43:12,631] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x000038e4] [2018-08-23 17:43:12,631] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x000038e4] [2018-08-23 17:43:12,632] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x000038e4] [2018-08-23 17:43:12,660] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x000038e4] [2018-08-23 17:43:12,690] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x000038e4] [2018-08-23 17:43:12,691] - Script::install(): KBExtra is successfully!
 DEBUG root [0x000038e4] [2018-08-23 17:43:12,716] - loaded entity-script:Account(1).
 DEBUG root [0x000038e4] [2018-08-23 17:43:12,718] - loaded entity-script:CheckName(2).
 DEBUG root [0x000038e4] [2018-08-23 17:43:12,723] - loaded entity-script:Halls(3).
 DEBUG root [0x000038e4] [2018-08-23 17:43:12,725] - loaded entity-script:Room(4).
  INFO root [0x000038e4] [2018-08-23 17:43:12,725] - Baseapp::initializeEnd: started resmgr tick(60s)!
  INFO root [0x000038e4] [2018-08-23 17:43:12,726] - TelnetServer server is running on port 40000
  INFO root [0x000038e4] [2018-08-23 17:43:13,079] - ---- baseapp is running ----
 DEBUG root [0x000038e4] [2018-08-23 17:43:13,080] - Components::process(): Request for the process of identity...
  WARN root [0x000038e4] [2018-08-23 17:43:13,390] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20382, errorno=10048
  WARN root [0x000038e4] [2018-08-23 17:43:19,556] - EntityApp::checkTickPeriod: tick took 6477% (6.48 seconds)!
  INFO root [0x000038e4] [2018-08-23 17:43:20,599] - Components::findComponents: find logger(1)...
  INFO root [0x000038e4] [2018-08-23 17:43:20,675] - Components::findComponents: found logger, addr:192.168.0.106:64124
  INFO root [0x000038e4] [2018-08-23 17:43:20,676] - Components::addComponent: reset orderLog, uid=3364!
  INFO root [0x000038e4] [2018-08-23 17:43:20,677] - Components::addComponent[logger], uid=3364, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x000038e4] [2018-08-23 17:43:20,678] - Components::findComponents: find dbmgr(2)...
  INFO root [0x000038e4] [2018-08-23 17:43:20,782] - Components::findComponents: found dbmgr, addr:192.168.0.106:64123
  INFO root [0x000038e4] [2018-08-23 17:43:20,783] - Components::addComponent: reset orderLog, uid=3364!
  INFO root [0x000038e4] [2018-08-23 17:43:20,784] - Components::addComponent[dbmgr], uid=3364, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x000038e4] [2018-08-23 17:43:20,784] - Components::findComponents: found dbmgr, addr:192.168.0.106:64123
  WARN root [0x000038e4] [2018-08-23 17:43:21,784] - Forwarding logs to logger[192.168.0.106:64124/0/0/0]...
 ERROR root [0x000038e4] [2018-08-23 17:45:28,114] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x000038e4] [2018-08-23 17:45:28,136] - The following logs sent to logger failed:
  WARN root [0x000038e4] [2018-08-23 17:45:28,136] - ==> [2018-08-23 17:45:28 110] TCPPacketReceiver::processPendingEvents(192.168.0.106:64124): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x000038e4] [2018-08-23 17:45:28,136] - ==> [2018-08-23 17:45:28 115] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x000038e4] [2018-08-23 17:45:28,195] - TCPPacketReceiver::processPendingEvents(192.168.0.106:64123): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x000038e4] [2018-08-23 17:45:28,199] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x000038e4] [2018-08-23 17:45:28,219] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [0x000038e4] [2018-08-23 17:45:28,221] - onBaseAppShutDown: state=0
  INFO root [0x000038e4] [2018-08-23 17:45:28,221] - Shutdowner::onShutdown: shutting down
S_INFO root [0x000038e4] [2018-08-23 17:45:28,221] - onBaseAppShutDown: state=1
  INFO root [0x000038e4] [2018-08-23 17:45:28,221] - Shutdowner::onShutdownEnd: shutting down
S_INFO root [0x000038e4] [2018-08-23 17:45:28,221] - onBaseAppShutDown: state=2
 ERROR root [0x000038e4] [2018-08-23 17:45:28,229] - Account::onCellWriteToDBCompleted(2002): not found dbmgr!
 ERROR root [0x000038e4] [2018-08-23 17:45:28,230] - Entity::onDestroy: not found dbmgr!
 ERROR root [0x000038e4] [2018-08-23 17:45:28,230] - Account::onCellWriteToDBCompleted(2004): not found dbmgr!
 ERROR root [0x000038e4] [2018-08-23 17:45:28,231] - Entity::onDestroy: not found dbmgr!
 DEBUG root [0x000038e4] [2018-08-23 17:45:28,231] - Account::~Account(): 2002
 DEBUG root [0x000038e4] [2018-08-23 17:45:28,231] - Account::~Account(): 2004
 DEBUG root [0x000038e4] [2018-08-23 17:45:28,232] - Room::~Room(): 2003
 DEBUG root [0x000038e4] [2018-08-23 17:45:28,232] - Halls::~Halls(): 2001
 DEBUG root [0x000038e4] [2018-08-23 17:45:28,233] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x000038e4] [2018-08-23 17:45:28,233] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x000038e4] [2018-08-23 17:45:28,233] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x000038e4] [2018-08-23 17:45:28,233] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x000038e4] [2018-08-23 17:45:28,233] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x000038e4] [2018-08-23 17:45:28,233] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x000038e4] [2018-08-23 17:45:28,233] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x000038e4] [2018-08-23 17:45:28,233] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x000038e4] [2018-08-23 17:45:28,244] - Script::uninstall(): is successfully!
 DEBUG root [0x000038e4] [2018-08-23 17:45:28,244] - ThreadPool::destroy(): starting size 2.
  INFO root [0x00003fb8] [2018-08-23 17:45:29,599] - 
  INFO root [0x00003fb8] [2018-08-23 17:45:29,599] - -----------------------------------------------------------------------------------------


  INFO root [0x00003fb8] [2018-08-23 17:45:29,600] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [0x00003fb8] [2018-08-23 17:45:29,600] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [0x00003fb8] [2018-08-23 17:45:29,600] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [0x00003fb8] [2018-08-23 17:45:29,603] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:20015 )
  INFO root [0x00003fb8] [2018-08-23 17:45:29,603] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.106:20015, SOMAXCONN=128.
  INFO root [0x00003fb8] [2018-08-23 17:45:29,604] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:64194 )
  INFO root [0x00003fb8] [2018-08-23 17:45:29,604] - NetworkInterface::initialize(INTERNAL): address 192.168.0.106:64194, SOMAXCONN=128.
  INFO root [0x00003fb8] [2018-08-23 17:45:29,604] - server-configs:
  INFO root [0x00003fb8] [2018-08-23 17:45:29,604] - 	gameUpdateHertz : 10
  INFO root [0x00003fb8] [2018-08-23 17:45:29,604] - 	entryScriptFile : kbemain
  INFO root [0x00003fb8] [2018-08-23 17:45:29,604] - 	internalAddr : 192.168.0.106:64194
  INFO root [0x00003fb8] [2018-08-23 17:45:29,605] - 	externalAddr : 192.168.0.106:20015
  INFO root [0x00003fb8] [2018-08-23 17:45:29,605] - 	componentID : 7001
  INFO root [0x00003fb8] [2018-08-23 17:45:29,990] - Components::findLogger: found logger, addr:192.168.0.106:64189
  INFO root [0x00003fb8] [2018-08-23 17:45:29,990] - Components::addComponent: reset orderLog, uid=3814!
  INFO root [0x00003fb8] [2018-08-23 17:45:29,990] - Components::addComponent[logger], uid=3814, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00003fb8] [2018-08-23 17:45:29,996] - ---- baseapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: F9DFFB319FBADF35943ADF4D42C4718C. Config: Debug X86. Built: 15:53:31 Apr 29 2018. AppID: 7001. UID: 3814. PID: 14352 ----
  INFO root [0x00003fb8] [2018-08-23 17:45:29,996] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [0x00003fb8] [2018-08-23 17:45:29,996] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00003fb8] [2018-08-23 17:45:29,996] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x00003fb8] [2018-08-23 17:45:30,124] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00003fb8] [2018-08-23 17:45:30,125] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x00003fb8] [2018-08-23 17:45:30,125] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x00003fb8] [2018-08-23 17:45:30,128] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x00003fb8] [2018-08-23 17:45:30,128] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x00003fb8] [2018-08-23 17:45:30,128] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x00003fb8] [2018-08-23 17:45:30,129] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x00003fb8] [2018-08-23 17:45:30,159] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x00003fb8] [2018-08-23 17:45:30,189] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x00003fb8] [2018-08-23 17:45:30,190] - Script::install(): KBExtra is successfully!
 DEBUG root [0x00003fb8] [2018-08-23 17:45:30,212] - loaded entity-script:Account(1).
 DEBUG root [0x00003fb8] [2018-08-23 17:45:30,213] - loaded entity-script:CheckName(2).
 DEBUG root [0x00003fb8] [2018-08-23 17:45:30,219] - loaded entity-script:Halls(3).
 DEBUG root [0x00003fb8] [2018-08-23 17:45:30,220] - loaded entity-script:Room(4).
  INFO root [0x00003fb8] [2018-08-23 17:45:30,220] - Baseapp::initializeEnd: started resmgr tick(60s)!
  INFO root [0x00003fb8] [2018-08-23 17:45:30,220] - TelnetServer server is running on port 40000
  INFO root [0x00003fb8] [2018-08-23 17:45:30,497] - ---- baseapp is running ----
 DEBUG root [0x00003fb8] [2018-08-23 17:45:30,497] - Components::process(): Request for the process of identity...
  WARN root [0x00003fb8] [2018-08-23 17:45:36,588] - Forwarding logs to logger[192.168.0.106:64189/0/0/0]...
