  INFO root [0x00001ad4] [2018-08-26 11:37:50,850] - 
  INFO root [0x00001ad4] [2018-08-26 11:37:50,891] - -----------------------------------------------------------------------------------------


  INFO root [0x00001ad4] [2018-08-26 11:37:51,875] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [0x00001ad4] [2018-08-26 11:37:51,875] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [0x00001ad4] [2018-08-26 11:37:51,875] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [0x00001ad4] [2018-08-26 11:37:52,395] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:20015 )
  INFO root [0x00001ad4] [2018-08-26 11:37:52,524] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.106:20015, SOMAXCONN=128.
  INFO root [0x00001ad4] [2018-08-26 11:37:52,529] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:50344 )
  INFO root [0x00001ad4] [2018-08-26 11:37:52,530] - NetworkInterface::initialize(INTERNAL): address 192.168.0.106:50344, SOMAXCONN=128.
  INFO root [0x00001ad4] [2018-08-26 11:37:52,530] - server-configs:
  INFO root [0x00001ad4] [2018-08-26 11:37:52,531] - 	gameUpdateHertz : 10
  INFO root [0x00001ad4] [2018-08-26 11:37:52,531] - 	entryScriptFile : kbemain
  INFO root [0x00001ad4] [2018-08-26 11:37:52,531] - 	internalAddr : 192.168.0.106:50344
  INFO root [0x00001ad4] [2018-08-26 11:37:52,532] - 	externalAddr : 192.168.0.106:20015
  INFO root [0x00001ad4] [2018-08-26 11:37:52,532] - 	componentID : 7001
  INFO root [0x00001ad4] [2018-08-26 11:37:53,576] - Components::findLogger: found logger, addr:192.168.0.106:50288
  INFO root [0x00001ad4] [2018-08-26 11:37:53,576] - Components::addComponent: reset orderLog, uid=24354!
  INFO root [0x00001ad4] [2018-08-26 11:37:53,576] - Components::addComponent[logger], uid=24354, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00001ad4] [2018-08-26 11:37:53,774] - ---- baseapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: F9DFFB319FBADF35943ADF4D42C4718C. Config: Debug X86. Built: 15:53:31 Apr 29 2018. AppID: 7001. UID: 24354. PID: 5912 ----
  INFO root [0x00001ad4] [2018-08-26 11:37:53,774] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [0x00001ad4] [2018-08-26 11:37:53,859] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00001ad4] [2018-08-26 11:37:53,921] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x00001ad4] [2018-08-26 11:37:57,838] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00001ad4] [2018-08-26 11:37:57,871] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x00001ad4] [2018-08-26 11:37:57,961] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x00001ad4] [2018-08-26 11:37:58,521] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x00001ad4] [2018-08-26 11:37:58,609] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x00001ad4] [2018-08-26 11:37:58,667] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x00001ad4] [2018-08-26 11:37:58,708] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x00001ad4] [2018-08-26 11:37:59,280] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x00001ad4] [2018-08-26 11:38:00,328] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x00001ad4] [2018-08-26 11:38:00,329] - Script::install(): KBExtra is successfully!
 DEBUG root [0x00001ad4] [2018-08-26 11:38:02,538] - loaded entity-script:Account(1).
 DEBUG root [0x00001ad4] [2018-08-26 11:38:02,541] - loaded entity-script:CheckName(2).
 DEBUG root [0x00001ad4] [2018-08-26 11:38:02,613] - loaded entity-script:Halls(3).
 DEBUG root [0x00001ad4] [2018-08-26 11:38:02,641] - loaded entity-script:Room(4).
  INFO root [0x00001ad4] [2018-08-26 11:38:02,642] - Baseapp::initializeEnd: started resmgr tick(60s)!
  INFO root [0x00001ad4] [2018-08-26 11:38:02,776] - TelnetServer server is running on port 40000
  INFO root [0x00001ad4] [2018-08-26 11:38:03,277] - ---- baseapp is running ----
 DEBUG root [0x00001ad4] [2018-08-26 11:38:03,312] - Components::process(): Request for the process of identity...
  WARN root [0x00001ad4] [2018-08-26 11:38:10,225] - Forwarding logs to logger[192.168.0.106:50288/0/0/0]...
 ERROR root [0x00001ad4] [2018-08-26 12:19:36,006] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x00001ad4] [2018-08-26 12:19:36,010] - The following logs sent to logger failed:
  WARN root [0x00001ad4] [2018-08-26 12:19:36,010] - ==> [2018-08-26 12:19:36 004] TCPPacketReceiver::processPendingEvents(192.168.0.106:50288): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00001ad4] [2018-08-26 12:19:36,011] - ==> [2018-08-26 12:19:36 006] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x00001ad4] [2018-08-26 12:19:36,059] - TCPPacketReceiver::processPendingEvents(192.168.0.106:50291): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00001ad4] [2018-08-26 12:19:36,061] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x00001ad4] [2018-08-26 12:19:36,084] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [0x00001ad4] [2018-08-26 12:19:36,084] - onBaseAppShutDown: state=0
  INFO root [0x00001ad4] [2018-08-26 12:19:36,085] - Shutdowner::onShutdown: shutting down
S_INFO root [0x00001ad4] [2018-08-26 12:19:36,085] - onBaseAppShutDown: state=1
  INFO root [0x00001ad4] [2018-08-26 12:19:36,085] - Shutdowner::onShutdownEnd: shutting down
S_INFO root [0x00001ad4] [2018-08-26 12:19:36,085] - onBaseAppShutDown: state=2
 ERROR root [0x00001ad4] [2018-08-26 12:19:36,176] - Account::onCellWriteToDBCompleted(2002): not found dbmgr!
 ERROR root [0x00001ad4] [2018-08-26 12:19:36,176] - Entity::onDestroy: not found dbmgr!
 ERROR root [0x00001ad4] [2018-08-26 12:19:36,177] - Account::onCellWriteToDBCompleted(2004): not found dbmgr!
 ERROR root [0x00001ad4] [2018-08-26 12:19:36,177] - Entity::onDestroy: not found dbmgr!
 DEBUG root [0x00001ad4] [2018-08-26 12:19:36,178] - Account::~Account(): 2002
 DEBUG root [0x00001ad4] [2018-08-26 12:19:36,178] - Account::~Account(): 2004
 DEBUG root [0x00001ad4] [2018-08-26 12:19:36,178] - Room::~Room(): 2003
 DEBUG root [0x00001ad4] [2018-08-26 12:19:36,178] - Halls::~Halls(): 2001
 DEBUG root [0x00001ad4] [2018-08-26 12:19:36,199] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00001ad4] [2018-08-26 12:19:36,200] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x00001ad4] [2018-08-26 12:19:36,200] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x00001ad4] [2018-08-26 12:19:36,200] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x00001ad4] [2018-08-26 12:19:36,200] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x00001ad4] [2018-08-26 12:19:36,200] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x00001ad4] [2018-08-26 12:19:36,200] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x00001ad4] [2018-08-26 12:19:36,200] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x00001b8c] [2018-08-26 12:19:37,188] - 
  INFO root [0x00001b8c] [2018-08-26 12:19:37,189] - -----------------------------------------------------------------------------------------


  INFO root [0x00001b8c] [2018-08-26 12:19:37,189] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [0x00001b8c] [2018-08-26 12:19:37,189] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [0x00001b8c] [2018-08-26 12:19:37,190] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [0x00001b8c] [2018-08-26 12:19:37,208] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:20015 )
  INFO root [0x00001b8c] [2018-08-26 12:19:37,208] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.106:20015, SOMAXCONN=128.
  INFO root [0x00001b8c] [2018-08-26 12:19:37,215] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:57435 )
  INFO root [0x00001b8c] [2018-08-26 12:19:37,215] - NetworkInterface::initialize(INTERNAL): address 192.168.0.106:57435, SOMAXCONN=128.
  INFO root [0x00001b8c] [2018-08-26 12:19:37,215] - server-configs:
  INFO root [0x00001b8c] [2018-08-26 12:19:37,215] - 	gameUpdateHertz : 10
  INFO root [0x00001b8c] [2018-08-26 12:19:37,215] - 	entryScriptFile : kbemain
  INFO root [0x00001b8c] [2018-08-26 12:19:37,215] - 	internalAddr : 192.168.0.106:57435
  INFO root [0x00001b8c] [2018-08-26 12:19:37,216] - 	externalAddr : 192.168.0.106:20015
  INFO root [0x00001b8c] [2018-08-26 12:19:37,216] - 	componentID : 7001
  INFO root [0x00001b8c] [2018-08-26 12:19:38,928] - ---- baseapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: F9DFFB319FBADF35943ADF4D42C4718C. Config: Debug X86. Built: 15:53:31 Apr 29 2018. AppID: 7001. UID: 32740. PID: 12228 ----
  INFO root [0x00001b8c] [2018-08-26 12:19:38,929] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [0x00001b8c] [2018-08-26 12:19:38,929] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00001b8c] [2018-08-26 12:19:38,929] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x00001b8c] [2018-08-26 12:19:39,062] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00001b8c] [2018-08-26 12:19:39,063] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x00001b8c] [2018-08-26 12:19:39,063] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x00001b8c] [2018-08-26 12:19:39,066] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x00001b8c] [2018-08-26 12:19:39,066] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x00001b8c] [2018-08-26 12:19:39,066] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x00001b8c] [2018-08-26 12:19:39,067] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x00001b8c] [2018-08-26 12:19:39,097] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x00001b8c] [2018-08-26 12:19:39,134] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x00001b8c] [2018-08-26 12:19:39,134] - Script::install(): KBExtra is successfully!
 DEBUG root [0x00001b8c] [2018-08-26 12:19:39,158] - loaded entity-script:Account(1).
 DEBUG root [0x00001b8c] [2018-08-26 12:19:39,159] - loaded entity-script:CheckName(2).
 DEBUG root [0x00001b8c] [2018-08-26 12:19:39,165] - loaded entity-script:Halls(3).
 DEBUG root [0x00001b8c] [2018-08-26 12:19:39,166] - loaded entity-script:Room(4).
  INFO root [0x00001b8c] [2018-08-26 12:19:39,166] - Baseapp::initializeEnd: started resmgr tick(60s)!
  INFO root [0x00001b8c] [2018-08-26 12:19:39,166] - TelnetServer server is running on port 40000
  INFO root [0x00001b8c] [2018-08-26 12:19:39,521] - ---- baseapp is running ----
 DEBUG root [0x00001b8c] [2018-08-26 12:19:39,521] - Components::process(): Request for the process of identity...
  WARN root [0x00001b8c] [2018-08-26 12:19:45,599] - EntityApp::checkTickPeriod: tick took 6078% (6.08 seconds)!
  INFO root [0x00001b8c] [2018-08-26 12:19:46,692] - Components::findComponents: find logger(1)...
  INFO root [0x00001b8c] [2018-08-26 12:19:46,759] - Components::findComponents: found logger, addr:192.168.0.106:57436
  INFO root [0x00001b8c] [2018-08-26 12:19:46,759] - Components::addComponent: reset orderLog, uid=32740!
  INFO root [0x00001b8c] [2018-08-26 12:19:46,759] - Components::addComponent[logger], uid=32740, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00001b8c] [2018-08-26 12:19:46,760] - Components::findComponents: find dbmgr(2)...
  INFO root [0x00001b8c] [2018-08-26 12:19:46,862] - Components::findComponents: found dbmgr, addr:192.168.0.106:57437
  INFO root [0x00001b8c] [2018-08-26 12:19:46,862] - Components::addComponent: reset orderLog, uid=32740!
  INFO root [0x00001b8c] [2018-08-26 12:19:46,862] - Components::addComponent[dbmgr], uid=32740, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00001b8c] [2018-08-26 12:19:46,863] - Components::findComponents: found dbmgr, addr:192.168.0.106:57437
  WARN root [0x00001b8c] [2018-08-26 12:19:47,863] - Forwarding logs to logger[192.168.0.106:57436/0/0/0]...
 ERROR root [0x00001b8c] [2018-08-26 16:02:21,403] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x00001b8c] [2018-08-26 16:02:21,415] - The following logs sent to logger failed:
  WARN root [0x00001b8c] [2018-08-26 16:02:21,415] - ==> [2018-08-26 16:02:21 401] TCPPacketReceiver::processPendingEvents(192.168.0.106:57436): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00001b8c] [2018-08-26 16:02:21,415] - ==> [2018-08-26 16:02:21 403] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x00001b8c] [2018-08-26 16:02:21,466] - TCPPacketReceiver::processPendingEvents(192.168.0.106:57437): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00001b8c] [2018-08-26 16:02:21,471] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x00001b8c] [2018-08-26 16:02:21,476] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [0x00001b8c] [2018-08-26 16:02:21,481] - onBaseAppShutDown: state=0
  INFO root [0x00001b8c] [2018-08-26 16:02:21,482] - Shutdowner::onShutdown: shutting down
S_INFO root [0x00001b8c] [2018-08-26 16:02:21,482] - onBaseAppShutDown: state=1
  INFO root [0x00001b8c] [2018-08-26 16:02:21,482] - Shutdowner::onShutdownEnd: shutting down
S_INFO root [0x00001b8c] [2018-08-26 16:02:21,482] - onBaseAppShutDown: state=2
 ERROR root [0x00001b8c] [2018-08-26 16:02:21,490] - Account::onCellWriteToDBCompleted(2002): not found dbmgr!
 ERROR root [0x00001b8c] [2018-08-26 16:02:21,492] - Entity::onDestroy: not found dbmgr!
 ERROR root [0x00001b8c] [2018-08-26 16:02:21,493] - Account::onCellWriteToDBCompleted(2004): not found dbmgr!
 ERROR root [0x00001b8c] [2018-08-26 16:02:21,494] - Entity::onDestroy: not found dbmgr!
 DEBUG root [0x00001b8c] [2018-08-26 16:02:21,495] - Account::~Account(): 2002
 DEBUG root [0x00001b8c] [2018-08-26 16:02:21,495] - Account::~Account(): 2004
 DEBUG root [0x00001b8c] [2018-08-26 16:02:21,495] - Room::~Room(): 2003
 DEBUG root [0x00001b8c] [2018-08-26 16:02:21,496] - Halls::~Halls(): 2001
 DEBUG root [0x00001b8c] [2018-08-26 16:02:21,496] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00001b8c] [2018-08-26 16:02:21,497] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x00001b8c] [2018-08-26 16:02:21,497] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x00001b8c] [2018-08-26 16:02:21,497] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x00001b8c] [2018-08-26 16:02:21,497] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x00001b8c] [2018-08-26 16:02:21,497] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x00001b8c] [2018-08-26 16:02:21,497] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x00001b8c] [2018-08-26 16:02:21,497] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x00001b8c] [2018-08-26 16:02:21,507] - Script::uninstall(): is successfully!
 DEBUG root [0x00001b8c] [2018-08-26 16:02:21,507] - ThreadPool::destroy(): starting size 2.
  INFO root [0x00001318] [2018-08-26 16:02:22,689] - 
  INFO root [0x00001318] [2018-08-26 16:02:22,689] - -----------------------------------------------------------------------------------------


  INFO root [0x00001318] [2018-08-26 16:02:22,690] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [0x00001318] [2018-08-26 16:02:22,690] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [0x00001318] [2018-08-26 16:02:22,690] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [0x00001318] [2018-08-26 16:02:22,698] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:20015 )
  INFO root [0x00001318] [2018-08-26 16:02:22,698] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.106:20015, SOMAXCONN=128.
  INFO root [0x00001318] [2018-08-26 16:02:22,699] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:58925 )
  INFO root [0x00001318] [2018-08-26 16:02:22,700] - NetworkInterface::initialize(INTERNAL): address 192.168.0.106:58925, SOMAXCONN=128.
  INFO root [0x00001318] [2018-08-26 16:02:22,700] - server-configs:
  INFO root [0x00001318] [2018-08-26 16:02:22,700] - 	gameUpdateHertz : 10
  INFO root [0x00001318] [2018-08-26 16:02:22,700] - 	entryScriptFile : kbemain
  INFO root [0x00001318] [2018-08-26 16:02:22,700] - 	internalAddr : 192.168.0.106:58925
  INFO root [0x00001318] [2018-08-26 16:02:22,700] - 	externalAddr : 192.168.0.106:20015
  INFO root [0x00001318] [2018-08-26 16:02:22,700] - 	componentID : 7001
  INFO root [0x00001318] [2018-08-26 16:02:23,139] - Components::findLogger: found logger, addr:192.168.0.106:58921
  INFO root [0x00001318] [2018-08-26 16:02:23,140] - Components::addComponent: reset orderLog, uid=10851!
  INFO root [0x00001318] [2018-08-26 16:02:23,140] - Components::addComponent[logger], uid=10851, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00001318] [2018-08-26 16:02:23,145] - ---- baseapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: F9DFFB319FBADF35943ADF4D42C4718C. Config: Debug X86. Built: 15:53:31 Apr 29 2018. AppID: 7001. UID: 10851. PID: 13628 ----
  INFO root [0x00001318] [2018-08-26 16:02:23,145] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [0x00001318] [2018-08-26 16:02:23,146] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00001318] [2018-08-26 16:02:23,146] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x00001318] [2018-08-26 16:02:23,273] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00001318] [2018-08-26 16:02:23,274] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x00001318] [2018-08-26 16:02:23,274] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x00001318] [2018-08-26 16:02:23,278] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x00001318] [2018-08-26 16:02:23,279] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x00001318] [2018-08-26 16:02:23,279] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x00001318] [2018-08-26 16:02:23,280] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x00001318] [2018-08-26 16:02:23,312] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x00001318] [2018-08-26 16:02:23,344] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x00001318] [2018-08-26 16:02:23,344] - Script::install(): KBExtra is successfully!
 DEBUG root [0x00001318] [2018-08-26 16:02:23,368] - loaded entity-script:Account(1).
 DEBUG root [0x00001318] [2018-08-26 16:02:23,369] - loaded entity-script:CheckName(2).
 DEBUG root [0x00001318] [2018-08-26 16:02:23,375] - loaded entity-script:Halls(3).
 DEBUG root [0x00001318] [2018-08-26 16:02:23,377] - loaded entity-script:Room(4).
  INFO root [0x00001318] [2018-08-26 16:02:23,377] - Baseapp::initializeEnd: started resmgr tick(60s)!
  INFO root [0x00001318] [2018-08-26 16:02:23,377] - TelnetServer server is running on port 40000
  INFO root [0x00001318] [2018-08-26 16:02:23,696] - ---- baseapp is running ----
 DEBUG root [0x00001318] [2018-08-26 16:02:23,697] - Components::process(): Request for the process of identity...
  WARN root [0x00001318] [2018-08-26 16:02:29,756] - Forwarding logs to logger[192.168.0.106:58921/0/0/0]...
 ERROR root [0x00001318] [2018-08-26 16:16:27,144] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x00001318] [2018-08-26 16:16:27,153] - The following logs sent to logger failed:
  WARN root [0x00001318] [2018-08-26 16:16:27,154] - ==> [2018-08-26 16:16:27 141] TCPPacketReceiver::processPendingEvents(192.168.0.106:58921): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00001318] [2018-08-26 16:16:27,154] - ==> [2018-08-26 16:16:27 144] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x00001318] [2018-08-26 16:16:27,204] - TCPPacketReceiver::processPendingEvents(192.168.0.106:58928): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00001318] [2018-08-26 16:16:27,207] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x00001318] [2018-08-26 16:16:27,218] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [0x00001318] [2018-08-26 16:16:27,219] - onBaseAppShutDown: state=0
  INFO root [0x00001318] [2018-08-26 16:16:27,219] - Shutdowner::onShutdown: shutting down
S_INFO root [0x00001318] [2018-08-26 16:16:27,219] - onBaseAppShutDown: state=1
  INFO root [0x00001318] [2018-08-26 16:16:27,219] - Shutdowner::onShutdownEnd: shutting down
S_INFO root [0x00001318] [2018-08-26 16:16:27,219] - onBaseAppShutDown: state=2
 ERROR root [0x00001318] [2018-08-26 16:16:27,227] - Account::onCellWriteToDBCompleted(2): not found dbmgr!
 ERROR root [0x00001318] [2018-08-26 16:16:27,228] - Entity::onDestroy: not found dbmgr!
 ERROR root [0x00001318] [2018-08-26 16:16:27,228] - Account::onCellWriteToDBCompleted(4): not found dbmgr!
 ERROR root [0x00001318] [2018-08-26 16:16:27,229] - Entity::onDestroy: not found dbmgr!
 DEBUG root [0x00001318] [2018-08-26 16:16:27,229] - Account::~Account(): 2
 DEBUG root [0x00001318] [2018-08-26 16:16:27,229] - Account::~Account(): 4
 DEBUG root [0x00001318] [2018-08-26 16:16:27,230] - Room::~Room(): 3
 DEBUG root [0x00001318] [2018-08-26 16:16:27,230] - Halls::~Halls(): 1
 DEBUG root [0x00001318] [2018-08-26 16:16:27,231] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00001318] [2018-08-26 16:16:27,231] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x00001318] [2018-08-26 16:16:27,231] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x00001318] [2018-08-26 16:16:27,231] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x00001318] [2018-08-26 16:16:27,231] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x00001318] [2018-08-26 16:16:27,231] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x00001318] [2018-08-26 16:16:27,232] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x00001318] [2018-08-26 16:16:27,232] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x00001318] [2018-08-26 16:16:27,241] - Script::uninstall(): is successfully!
 DEBUG root [0x00001318] [2018-08-26 16:16:27,241] - ThreadPool::destroy(): starting size 2.
  INFO root [0x00002900] [2018-08-26 16:16:28,420] - 
  INFO root [0x00002900] [2018-08-26 16:16:28,420] - -----------------------------------------------------------------------------------------


  INFO root [0x00002900] [2018-08-26 16:16:28,421] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [0x00002900] [2018-08-26 16:16:28,421] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [0x00002900] [2018-08-26 16:16:28,421] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [0x00002900] [2018-08-26 16:16:28,427] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:20015 )
  INFO root [0x00002900] [2018-08-26 16:16:28,428] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.106:20015, SOMAXCONN=128.
  INFO root [0x00002900] [2018-08-26 16:16:28,429] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:59073 )
  INFO root [0x00002900] [2018-08-26 16:16:28,429] - NetworkInterface::initialize(INTERNAL): address 192.168.0.106:59073, SOMAXCONN=128.
  INFO root [0x00002900] [2018-08-26 16:16:28,429] - server-configs:
  INFO root [0x00002900] [2018-08-26 16:16:28,429] - 	gameUpdateHertz : 10
  INFO root [0x00002900] [2018-08-26 16:16:28,429] - 	entryScriptFile : kbemain
  INFO root [0x00002900] [2018-08-26 16:16:28,429] - 	internalAddr : 192.168.0.106:59073
  INFO root [0x00002900] [2018-08-26 16:16:28,429] - 	externalAddr : 192.168.0.106:20015
  INFO root [0x00002900] [2018-08-26 16:16:28,430] - 	componentID : 7001
  INFO root [0x00002900] [2018-08-26 16:16:30,130] - ---- baseapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: F9DFFB319FBADF35943ADF4D42C4718C. Config: Debug X86. Built: 15:53:31 Apr 29 2018. AppID: 7001. UID: 13614. PID: 12044 ----
  INFO root [0x00002900] [2018-08-26 16:16:30,131] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [0x00002900] [2018-08-26 16:16:30,131] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00002900] [2018-08-26 16:16:30,131] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x00002900] [2018-08-26 16:16:30,255] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00002900] [2018-08-26 16:16:30,256] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x00002900] [2018-08-26 16:16:30,256] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x00002900] [2018-08-26 16:16:30,259] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x00002900] [2018-08-26 16:16:30,259] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x00002900] [2018-08-26 16:16:30,259] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x00002900] [2018-08-26 16:16:30,260] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x00002900] [2018-08-26 16:16:30,288] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x00002900] [2018-08-26 16:16:30,321] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x00002900] [2018-08-26 16:16:30,321] - Script::install(): KBExtra is successfully!
 DEBUG root [0x00002900] [2018-08-26 16:16:30,346] - loaded entity-script:Account(1).
 DEBUG root [0x00002900] [2018-08-26 16:16:30,347] - loaded entity-script:CheckName(2).
 DEBUG root [0x00002900] [2018-08-26 16:16:30,352] - loaded entity-script:Halls(3).
 DEBUG root [0x00002900] [2018-08-26 16:16:30,353] - loaded entity-script:Room(4).
  INFO root [0x00002900] [2018-08-26 16:16:30,353] - Baseapp::initializeEnd: started resmgr tick(60s)!
  INFO root [0x00002900] [2018-08-26 16:16:30,354] - TelnetServer server is running on port 40000
  INFO root [0x00002900] [2018-08-26 16:16:30,658] - ---- baseapp is running ----
 DEBUG root [0x00002900] [2018-08-26 16:16:30,658] - Components::process(): Request for the process of identity...
  WARN root [0x00002900] [2018-08-26 16:16:36,761] - EntityApp::checkTickPeriod: tick took 6103% (6.10 seconds)!
  INFO root [0x00002900] [2018-08-26 16:16:37,824] - Components::findComponents: find logger(1)...
  INFO root [0x00002900] [2018-08-26 16:16:37,885] - Components::findComponents: found logger, addr:192.168.0.106:59075
  INFO root [0x00002900] [2018-08-26 16:16:37,886] - Components::addComponent: reset orderLog, uid=13614!
  INFO root [0x00002900] [2018-08-26 16:16:37,886] - Components::addComponent[logger], uid=13614, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00002900] [2018-08-26 16:16:37,887] - Components::findComponents: find dbmgr(2)...
  INFO root [0x00002900] [2018-08-26 16:16:37,991] - Components::findComponents: found dbmgr, addr:192.168.0.106:59067
  INFO root [0x00002900] [2018-08-26 16:16:37,992] - Components::addComponent: reset orderLog, uid=13614!
  INFO root [0x00002900] [2018-08-26 16:16:37,992] - Components::addComponent[dbmgr], uid=13614, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00002900] [2018-08-26 16:16:37,993] - Components::findComponents: found dbmgr, addr:192.168.0.106:59067
  WARN root [0x00002900] [2018-08-26 16:16:38,993] - Forwarding logs to logger[192.168.0.106:59075/0/0/0]...
 ERROR root [0x00002900] [2018-08-26 16:34:00,947] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x00002900] [2018-08-26 16:34:00,955] - The following logs sent to logger failed:
  WARN root [0x00002900] [2018-08-26 16:34:00,955] - ==> [2018-08-26 16:34:00 941] TCPPacketReceiver::processPendingEvents(192.168.0.106:59075): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00002900] [2018-08-26 16:34:00,955] - ==> [2018-08-26 16:34:00 948] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x00002900] [2018-08-26 16:34:01,006] - TCPPacketReceiver::processPendingEvents(192.168.0.106:59067): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00002900] [2018-08-26 16:34:01,012] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x00002900] [2018-08-26 16:34:01,023] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [0x00002900] [2018-08-26 16:34:01,025] - onBaseAppShutDown: state=0
  INFO root [0x00002900] [2018-08-26 16:34:01,025] - Shutdowner::onShutdown: shutting down
S_INFO root [0x00002900] [2018-08-26 16:34:01,025] - onBaseAppShutDown: state=1
  INFO root [0x00002900] [2018-08-26 16:34:01,025] - Shutdowner::onShutdownEnd: shutting down
S_INFO root [0x00002900] [2018-08-26 16:34:01,025] - onBaseAppShutDown: state=2
 ERROR root [0x00002900] [2018-08-26 16:34:01,033] - Account::onCellWriteToDBCompleted(2002): not found dbmgr!
 ERROR root [0x00002900] [2018-08-26 16:34:01,038] - Entity::onDestroy: not found dbmgr!
 ERROR root [0x00002900] [2018-08-26 16:34:01,039] - Account::onCellWriteToDBCompleted(2004): not found dbmgr!
 ERROR root [0x00002900] [2018-08-26 16:34:01,039] - Entity::onDestroy: not found dbmgr!
 ERROR root [0x00002900] [2018-08-26 16:34:01,040] - Account::onCellWriteToDBCompleted(2005): not found dbmgr!
 ERROR root [0x00002900] [2018-08-26 16:34:01,040] - Entity::onDestroy: not found dbmgr!
 ERROR root [0x00002900] [2018-08-26 16:34:01,040] - Account::onCellWriteToDBCompleted(2007): not found dbmgr!
 ERROR root [0x00002900] [2018-08-26 16:34:01,041] - Entity::onDestroy: not found dbmgr!
 DEBUG root [0x00002900] [2018-08-26 16:34:01,041] - Account::~Account(): 2005
 DEBUG root [0x00002900] [2018-08-26 16:34:01,042] - Account::~Account(): 2007
 DEBUG root [0x00002900] [2018-08-26 16:34:01,042] - Room::~Room(): 2006
 DEBUG root [0x00002900] [2018-08-26 16:34:01,042] - Account::~Account(): 2002
 DEBUG root [0x00002900] [2018-08-26 16:34:01,042] - Account::~Account(): 2004
 DEBUG root [0x00002900] [2018-08-26 16:34:01,043] - Room::~Room(): 2003
 DEBUG root [0x00002900] [2018-08-26 16:34:01,043] - Halls::~Halls(): 2001
 DEBUG root [0x00002900] [2018-08-26 16:34:01,044] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00002900] [2018-08-26 16:34:01,044] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x00002900] [2018-08-26 16:34:01,044] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x00002900] [2018-08-26 16:34:01,044] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x00002900] [2018-08-26 16:34:01,044] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x00002900] [2018-08-26 16:34:01,044] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x00002900] [2018-08-26 16:34:01,044] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x00002900] [2018-08-26 16:34:01,044] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x00002900] [2018-08-26 16:34:01,055] - Script::uninstall(): is successfully!
 DEBUG root [0x00002900] [2018-08-26 16:34:01,055] - ThreadPool::destroy(): starting size 2.
  INFO root [0x00001604] [2018-08-26 16:34:02,286] - 
  INFO root [0x00001604] [2018-08-26 16:34:02,287] - -----------------------------------------------------------------------------------------


  INFO root [0x00001604] [2018-08-26 16:34:02,287] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [0x00001604] [2018-08-26 16:34:02,288] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [0x00001604] [2018-08-26 16:34:02,288] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [0x00001604] [2018-08-26 16:34:02,292] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:20015 )
  INFO root [0x00001604] [2018-08-26 16:34:02,293] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.106:20015, SOMAXCONN=128.
  INFO root [0x00001604] [2018-08-26 16:34:02,294] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:59239 )
  INFO root [0x00001604] [2018-08-26 16:34:02,294] - NetworkInterface::initialize(INTERNAL): address 192.168.0.106:59239, SOMAXCONN=128.
  INFO root [0x00001604] [2018-08-26 16:34:02,294] - server-configs:
  INFO root [0x00001604] [2018-08-26 16:34:02,294] - 	gameUpdateHertz : 10
  INFO root [0x00001604] [2018-08-26 16:34:02,294] - 	entryScriptFile : kbemain
  INFO root [0x00001604] [2018-08-26 16:34:02,294] - 	internalAddr : 192.168.0.106:59239
  INFO root [0x00001604] [2018-08-26 16:34:02,295] - 	externalAddr : 192.168.0.106:20015
  INFO root [0x00001604] [2018-08-26 16:34:02,295] - 	componentID : 7001
  WARN root [0x00001604] [2018-08-26 16:34:02,819] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20432, errorno=10048
  INFO root [0x00001604] [2018-08-26 16:34:02,824] - ---- baseapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: F9DFFB319FBADF35943ADF4D42C4718C. Config: Debug X86. Built: 15:53:31 Apr 29 2018. AppID: 7001. UID: 17053. PID: 11620 ----
  INFO root [0x00001604] [2018-08-26 16:34:02,825] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [0x00001604] [2018-08-26 16:34:02,825] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00001604] [2018-08-26 16:34:02,825] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x00001604] [2018-08-26 16:34:02,951] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00001604] [2018-08-26 16:34:02,952] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x00001604] [2018-08-26 16:34:02,952] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x00001604] [2018-08-26 16:34:02,955] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x00001604] [2018-08-26 16:34:02,955] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x00001604] [2018-08-26 16:34:02,956] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x00001604] [2018-08-26 16:34:02,956] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x00001604] [2018-08-26 16:34:02,990] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x00001604] [2018-08-26 16:34:03,023] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x00001604] [2018-08-26 16:34:03,023] - Script::install(): KBExtra is successfully!
 DEBUG root [0x00001604] [2018-08-26 16:34:03,048] - loaded entity-script:Account(1).
 DEBUG root [0x00001604] [2018-08-26 16:34:03,050] - loaded entity-script:CheckName(2).
 DEBUG root [0x00001604] [2018-08-26 16:34:03,056] - loaded entity-script:Halls(3).
 DEBUG root [0x00001604] [2018-08-26 16:34:03,057] - loaded entity-script:Room(4).
  INFO root [0x00001604] [2018-08-26 16:34:03,057] - Baseapp::initializeEnd: started resmgr tick(60s)!
  INFO root [0x00001604] [2018-08-26 16:34:03,058] - TelnetServer server is running on port 40000
  INFO root [0x00001604] [2018-08-26 16:34:03,343] - ---- baseapp is running ----
 DEBUG root [0x00001604] [2018-08-26 16:34:03,343] - Components::process(): Request for the process of identity...
  WARN root [0x00001604] [2018-08-26 16:34:09,400] - EntityApp::checkTickPeriod: tick took 6057% (6.06 seconds)!
  INFO root [0x00001604] [2018-08-26 16:34:10,443] - Components::findComponents: find logger(1)...
  INFO root [0x00001604] [2018-08-26 16:34:10,496] - Components::findComponents: found logger, addr:192.168.0.106:59240
  INFO root [0x00001604] [2018-08-26 16:34:10,497] - Components::addComponent: reset orderLog, uid=17053!
  INFO root [0x00001604] [2018-08-26 16:34:10,497] - Components::addComponent[logger], uid=17053, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00001604] [2018-08-26 16:34:10,499] - Components::findComponents: find dbmgr(2)...
  INFO root [0x00001604] [2018-08-26 16:34:10,600] - Components::findComponents: found dbmgr, addr:192.168.0.106:59236
  INFO root [0x00001604] [2018-08-26 16:34:10,600] - Components::addComponent: reset orderLog, uid=17053!
  INFO root [0x00001604] [2018-08-26 16:34:10,600] - Components::addComponent[dbmgr], uid=17053, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00001604] [2018-08-26 16:34:10,600] - Components::findComponents: found dbmgr, addr:192.168.0.106:59236
  WARN root [0x00001604] [2018-08-26 16:34:11,600] - EntityApp::checkTickPeriod: tick took 1257% (1.26 seconds)!
  WARN root [0x00001604] [2018-08-26 16:34:11,600] - Forwarding logs to logger[192.168.0.106:59240/0/0/0]...
 ERROR root [0x00001604] [2018-08-26 16:34:19,265] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x00001604] [2018-08-26 16:34:19,276] - The following logs sent to logger failed:
  WARN root [0x00001604] [2018-08-26 16:34:19,277] - ==> [2018-08-26 16:34:19 262] TCPPacketReceiver::processPendingEvents(192.168.0.106:59240): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00001604] [2018-08-26 16:34:19,277] - ==> [2018-08-26 16:34:19 265] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x00001604] [2018-08-26 16:34:19,332] - TCPPacketReceiver::processPendingEvents(192.168.0.106:59236): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00001604] [2018-08-26 16:34:19,337] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x00001604] [2018-08-26 16:34:19,344] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [0x00001604] [2018-08-26 16:34:19,346] - onBaseAppShutDown: state=0
  INFO root [0x00001604] [2018-08-26 16:34:19,347] - Shutdowner::onShutdown: shutting down
S_INFO root [0x00001604] [2018-08-26 16:34:19,347] - onBaseAppShutDown: state=1
  INFO root [0x00001604] [2018-08-26 16:34:19,347] - Shutdowner::onShutdownEnd: shutting down
S_INFO root [0x00001604] [2018-08-26 16:34:19,347] - onBaseAppShutDown: state=2
 DEBUG root [0x00001604] [2018-08-26 16:34:19,355] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00001604] [2018-08-26 16:34:19,355] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x00001604] [2018-08-26 16:34:19,355] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x00001604] [2018-08-26 16:34:19,356] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x00001604] [2018-08-26 16:34:19,356] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x00001604] [2018-08-26 16:34:19,356] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x00001604] [2018-08-26 16:34:19,356] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x00001604] [2018-08-26 16:34:19,356] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x00001604] [2018-08-26 16:34:19,366] - Script::uninstall(): is successfully!
 DEBUG root [0x00001604] [2018-08-26 16:34:19,366] - ThreadPool::destroy(): starting size 2.
  INFO root [0x00003718] [2018-08-26 16:34:20,611] - 
  INFO root [0x00003718] [2018-08-26 16:34:20,612] - -----------------------------------------------------------------------------------------


  INFO root [0x00003718] [2018-08-26 16:34:20,613] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [0x00003718] [2018-08-26 16:34:20,613] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [0x00003718] [2018-08-26 16:34:20,613] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [0x00003718] [2018-08-26 16:34:20,619] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:20015 )
  INFO root [0x00003718] [2018-08-26 16:34:20,619] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.106:20015, SOMAXCONN=128.
  INFO root [0x00003718] [2018-08-26 16:34:20,620] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:59289 )
  INFO root [0x00003718] [2018-08-26 16:34:20,621] - NetworkInterface::initialize(INTERNAL): address 192.168.0.106:59289, SOMAXCONN=128.
  INFO root [0x00003718] [2018-08-26 16:34:20,621] - server-configs:
  INFO root [0x00003718] [2018-08-26 16:34:20,621] - 	gameUpdateHertz : 10
  INFO root [0x00003718] [2018-08-26 16:34:20,621] - 	entryScriptFile : kbemain
  INFO root [0x00003718] [2018-08-26 16:34:20,621] - 	internalAddr : 192.168.0.106:59289
  INFO root [0x00003718] [2018-08-26 16:34:20,622] - 	externalAddr : 192.168.0.106:20015
  INFO root [0x00003718] [2018-08-26 16:34:20,622] - 	componentID : 7001
  INFO root [0x00003718] [2018-08-26 16:34:22,331] - ---- baseapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: F9DFFB319FBADF35943ADF4D42C4718C. Config: Debug X86. Built: 15:53:31 Apr 29 2018. AppID: 7001. UID: 17115. PID: 9208 ----
  INFO root [0x00003718] [2018-08-26 16:34:22,332] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [0x00003718] [2018-08-26 16:34:22,332] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00003718] [2018-08-26 16:34:22,332] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x00003718] [2018-08-26 16:34:22,468] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00003718] [2018-08-26 16:34:22,469] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x00003718] [2018-08-26 16:34:22,470] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x00003718] [2018-08-26 16:34:22,472] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x00003718] [2018-08-26 16:34:22,473] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x00003718] [2018-08-26 16:34:22,473] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x00003718] [2018-08-26 16:34:22,473] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x00003718] [2018-08-26 16:34:22,506] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x00003718] [2018-08-26 16:34:22,540] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x00003718] [2018-08-26 16:34:22,541] - Script::install(): KBExtra is successfully!
 DEBUG root [0x00003718] [2018-08-26 16:34:22,563] - loaded entity-script:Account(1).
 DEBUG root [0x00003718] [2018-08-26 16:34:22,564] - loaded entity-script:CheckName(2).
 DEBUG root [0x00003718] [2018-08-26 16:34:22,570] - loaded entity-script:Halls(3).
 DEBUG root [0x00003718] [2018-08-26 16:34:22,571] - loaded entity-script:Room(4).
  INFO root [0x00003718] [2018-08-26 16:34:22,571] - Baseapp::initializeEnd: started resmgr tick(60s)!
  INFO root [0x00003718] [2018-08-26 16:34:22,572] - TelnetServer server is running on port 40000
  INFO root [0x00003718] [2018-08-26 16:34:22,880] - ---- baseapp is running ----
 DEBUG root [0x00003718] [2018-08-26 16:34:22,881] - Components::process(): Request for the process of identity...
  WARN root [0x00003718] [2018-08-26 16:34:28,973] - EntityApp::checkTickPeriod: tick took 6092% (6.09 seconds)!
  INFO root [0x00003718] [2018-08-26 16:34:29,981] - Components::findComponents: find logger(1)...
  INFO root [0x00003718] [2018-08-26 16:34:30,013] - Components::findComponents: found logger, addr:192.168.0.106:59284
  INFO root [0x00003718] [2018-08-26 16:34:30,013] - Components::addComponent: reset orderLog, uid=17115!
  INFO root [0x00003718] [2018-08-26 16:34:30,013] - Components::addComponent[logger], uid=17115, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00003718] [2018-08-26 16:34:30,014] - Components::findComponents: find dbmgr(2)...
  INFO root [0x00003718] [2018-08-26 16:34:30,114] - Components::findComponents: found dbmgr, addr:192.168.0.106:59283
  INFO root [0x00003718] [2018-08-26 16:34:30,115] - Components::addComponent: reset orderLog, uid=17115!
  INFO root [0x00003718] [2018-08-26 16:34:30,115] - Components::addComponent[dbmgr], uid=17115, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00003718] [2018-08-26 16:34:30,115] - Components::findComponents: found dbmgr, addr:192.168.0.106:59283
  WARN root [0x00003718] [2018-08-26 16:34:31,115] - EntityApp::checkTickPeriod: tick took 1233% (1.23 seconds)!
  WARN root [0x00003718] [2018-08-26 16:34:31,116] - Forwarding logs to logger[192.168.0.106:59284/0/0/0]...
 ERROR root [0x00003718] [2018-08-26 21:56:13,428] - Components::removeComponentByChannel: cellapp : 8001, Abnormal exit! errorno=10054
