  INFO root [0x00001160] [2018-10-30 00:39:37,193] - 
  INFO root [0x00001160] [2018-10-30 00:39:37,329] - -----------------------------------------------------------------------------------------


  INFO root [0x00001160] [2018-10-30 00:39:39,357] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [0x00001160] [2018-10-30 00:39:39,359] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [0x00001160] [2018-10-30 00:39:39,359] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [0x00001160] [2018-10-30 00:39:40,177] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.107 ( 192.168.0.107:20015 )
  INFO root [0x00001160] [2018-10-30 00:39:40,214] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.107:20015, SOMAXCONN=128.
  INFO root [0x00001160] [2018-10-30 00:39:40,220] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.107 ( 192.168.0.107:49593 )
  INFO root [0x00001160] [2018-10-30 00:39:40,220] - NetworkInterface::initialize(INTERNAL): address 192.168.0.107:49593, SOMAXCONN=128.
  INFO root [0x00001160] [2018-10-30 00:39:40,221] - server-configs:
  INFO root [0x00001160] [2018-10-30 00:39:40,221] - 	gameUpdateHertz : 10
  INFO root [0x00001160] [2018-10-30 00:39:40,221] - 	entryScriptFile : kbemain
  INFO root [0x00001160] [2018-10-30 00:39:40,222] - 	internalAddr : 192.168.0.107:49593
  INFO root [0x00001160] [2018-10-30 00:39:40,222] - 	externalAddr : 192.168.0.107:20015
  INFO root [0x00001160] [2018-10-30 00:39:40,223] - 	externalCustomAddr : 192.168.0.107
  INFO root [0x00001160] [2018-10-30 00:39:40,223] - 	componentID : 7001
  INFO root [0x00001160] [2018-10-30 00:39:42,092] - Components::findLogger: found logger, addr:192.168.0.107:49370
  INFO root [0x00001160] [2018-10-30 00:39:42,093] - Components::addComponent: reset orderLog, uid=15852!
  INFO root [0x00001160] [2018-10-30 00:39:42,094] - Components::addComponent[logger], uid=15852, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00001160] [2018-10-30 00:39:42,398] - ---- baseapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: F9DFFB319FBADF35943ADF4D42C4718C. Config: Debug X86. Built: 15:53:31 Apr 29 2018. AppID: 7001. UID: 15852. PID: 3008 ----
  INFO root [0x00001160] [2018-10-30 00:39:42,399] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [0x00001160] [2018-10-30 00:39:42,533] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00001160] [2018-10-30 00:39:42,612] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x00001160] [2018-10-30 00:39:48,970] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00001160] [2018-10-30 00:39:49,078] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x00001160] [2018-10-30 00:39:49,251] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x00001160] [2018-10-30 00:39:50,638] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x00001160] [2018-10-30 00:39:50,825] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x00001160] [2018-10-30 00:39:51,008] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x00001160] [2018-10-30 00:39:51,124] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x00001160] [2018-10-30 00:39:51,921] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x00001160] [2018-10-30 00:39:54,669] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x00001160] [2018-10-30 00:39:54,670] - Script::install(): KBExtra is successfully!
 DEBUG root [0x00001160] [2018-10-30 00:39:57,764] - loaded entity-script:Account(1).
 DEBUG root [0x00001160] [2018-10-30 00:39:57,832] - loaded entity-script:CheckName(2).
 DEBUG root [0x00001160] [2018-10-30 00:39:58,046] - loaded entity-script:Halls(3).
 DEBUG root [0x00001160] [2018-10-30 00:39:58,091] - loaded entity-script:Room(4).
  INFO root [0x00001160] [2018-10-30 00:39:58,091] - Baseapp::initializeEnd: started resmgr tick(60s)!
  INFO root [0x00001160] [2018-10-30 00:39:58,341] - TelnetServer server is running on port 40000
  INFO root [0x00001160] [2018-10-30 00:39:59,047] - ---- baseapp is running ----
 DEBUG root [0x00001160] [2018-10-30 00:39:59,077] - Components::process(): Request for the process of identity...
  WARN root [0x00001160] [2018-10-30 00:40:05,632] - Forwarding logs to logger[192.168.0.107:49370/0/0/0]...
 ERROR root [0x00001160] [2018-10-30 00:41:00,577] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x00001160] [2018-10-30 00:41:00,579] - The following logs sent to logger failed:
  WARN root [0x00001160] [2018-10-30 00:41:00,579] - ==> [2018-10-30 00:41:00 577] TCPPacketReceiver::processPendingEvents(192.168.0.107:49370): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00001160] [2018-10-30 00:41:00,579] - ==> [2018-10-30 00:41:00 578] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x00001b80] [2018-10-30 00:41:01,665] - 
  INFO root [0x00001b80] [2018-10-30 00:41:01,665] - -----------------------------------------------------------------------------------------


  INFO root [0x00001b80] [2018-10-30 00:41:01,666] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [0x00001b80] [2018-10-30 00:41:01,666] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [0x00001b80] [2018-10-30 00:41:01,667] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [0x00001b80] [2018-10-30 00:41:01,669] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.107 ( 192.168.0.107:20015 )
  INFO root [0x00001b80] [2018-10-30 00:41:01,669] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.107:20015, SOMAXCONN=128.
  INFO root [0x00001b80] [2018-10-30 00:41:01,670] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.107 ( 192.168.0.107:49615 )
  INFO root [0x00001b80] [2018-10-30 00:41:01,670] - NetworkInterface::initialize(INTERNAL): address 192.168.0.107:49615, SOMAXCONN=128.
  INFO root [0x00001b80] [2018-10-30 00:41:01,671] - server-configs:
  INFO root [0x00001b80] [2018-10-30 00:41:01,671] - 	gameUpdateHertz : 10
  INFO root [0x00001b80] [2018-10-30 00:41:01,671] - 	entryScriptFile : kbemain
  INFO root [0x00001b80] [2018-10-30 00:41:01,671] - 	internalAddr : 192.168.0.107:49615
  INFO root [0x00001b80] [2018-10-30 00:41:01,671] - 	externalAddr : 192.168.0.107:20015
  INFO root [0x00001b80] [2018-10-30 00:41:01,671] - 	externalCustomAddr : 192.168.0.107
  INFO root [0x00001b80] [2018-10-30 00:41:01,671] - 	componentID : 7001
  WARN root [0x00001b80] [2018-10-30 00:41:02,163] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20316, errorno=10048
  INFO root [0x00001b80] [2018-10-30 00:41:02,167] - ---- baseapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: F9DFFB319FBADF35943ADF4D42C4718C. Config: Debug X86. Built: 15:53:31 Apr 29 2018. AppID: 7001. UID: 16348. PID: 5332 ----
  INFO root [0x00001b80] [2018-10-30 00:41:02,167] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [0x00001b80] [2018-10-30 00:41:02,167] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00001b80] [2018-10-30 00:41:02,167] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x00001b80] [2018-10-30 00:41:02,297] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00001b80] [2018-10-30 00:41:02,298] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x00001b80] [2018-10-30 00:41:02,298] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x00001b80] [2018-10-30 00:41:02,301] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x00001b80] [2018-10-30 00:41:02,301] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x00001b80] [2018-10-30 00:41:02,301] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x00001b80] [2018-10-30 00:41:02,302] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x00001b80] [2018-10-30 00:41:02,331] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x00001b80] [2018-10-30 00:41:02,358] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x00001b80] [2018-10-30 00:41:02,358] - Script::install(): KBExtra is successfully!
 DEBUG root [0x00001b80] [2018-10-30 00:41:02,379] - loaded entity-script:Account(1).
 DEBUG root [0x00001b80] [2018-10-30 00:41:02,380] - loaded entity-script:CheckName(2).
 DEBUG root [0x00001b80] [2018-10-30 00:41:02,385] - loaded entity-script:Halls(3).
 DEBUG root [0x00001b80] [2018-10-30 00:41:02,386] - loaded entity-script:Room(4).
  INFO root [0x00001b80] [2018-10-30 00:41:02,386] - Baseapp::initializeEnd: started resmgr tick(60s)!
  INFO root [0x00001b80] [2018-10-30 00:41:02,386] - TelnetServer server is running on port 40000
  INFO root [0x00001b80] [2018-10-30 00:41:02,659] - ---- baseapp is running ----
 DEBUG root [0x00001b80] [2018-10-30 00:41:02,659] - Components::process(): Request for the process of identity...
  WARN root [0x00001b80] [2018-10-30 00:41:08,715] - EntityApp::checkTickPeriod: tick took 6056% (6.06 seconds)!
  INFO root [0x00001b80] [2018-10-30 00:41:09,759] - Components::findComponents: find logger(1)...
  INFO root [0x00001b80] [2018-10-30 00:41:09,827] - Components::findComponents: found logger, addr:192.168.0.107:49610
  INFO root [0x00001b80] [2018-10-30 00:41:09,828] - Components::addComponent: reset orderLog, uid=16348!
  INFO root [0x00001b80] [2018-10-30 00:41:09,828] - Components::addComponent[logger], uid=16348, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00001b80] [2018-10-30 00:41:09,830] - Components::findComponents: find dbmgr(2)...
  WARN root [0x00001b80] [2018-10-30 00:41:10,931] - EntityApp::checkTickPeriod: tick took 1272% (1.27 seconds)!
  WARN root [0x00001b80] [2018-10-30 00:41:10,932] - Forwarding logs to logger[192.168.0.107:49610/0/0/0]...
 ERROR root [0x00001b80] [2018-10-30 00:42:58,307] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x00001b80] [2018-10-30 00:42:58,310] - The following logs sent to logger failed:
  WARN root [0x00001b80] [2018-10-30 00:42:58,311] - ==> [2018-10-30 00:42:58 306] TCPPacketReceiver::processPendingEvents(192.168.0.107:49610): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00001b80] [2018-10-30 00:42:58,311] - ==> [2018-10-30 00:42:58 308] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x00001a3c] [2018-10-30 00:43:12,399] - 
  INFO root [0x00001a3c] [2018-10-30 00:43:12,400] - -----------------------------------------------------------------------------------------


  INFO root [0x00001a3c] [2018-10-30 00:43:12,401] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [0x00001a3c] [2018-10-30 00:43:12,401] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [0x00001a3c] [2018-10-30 00:43:12,401] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [0x00001a3c] [2018-10-30 00:43:12,404] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.107 ( 192.168.0.107:20015 )
  INFO root [0x00001a3c] [2018-10-30 00:43:12,404] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.107:20015, SOMAXCONN=128.
  INFO root [0x00001a3c] [2018-10-30 00:43:12,406] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.107 ( 192.168.0.107:49656 )
  INFO root [0x00001a3c] [2018-10-30 00:43:12,406] - NetworkInterface::initialize(INTERNAL): address 192.168.0.107:49656, SOMAXCONN=128.
  INFO root [0x00001a3c] [2018-10-30 00:43:12,406] - server-configs:
  INFO root [0x00001a3c] [2018-10-30 00:43:12,406] - 	gameUpdateHertz : 10
  INFO root [0x00001a3c] [2018-10-30 00:43:12,406] - 	entryScriptFile : kbemain
  INFO root [0x00001a3c] [2018-10-30 00:43:12,406] - 	internalAddr : 192.168.0.107:49656
  INFO root [0x00001a3c] [2018-10-30 00:43:12,406] - 	externalAddr : 192.168.0.107:20015
  INFO root [0x00001a3c] [2018-10-30 00:43:12,406] - 	externalCustomAddr : 192.168.0.107
  INFO root [0x00001a3c] [2018-10-30 00:43:12,407] - 	componentID : 7001
  INFO root [0x00001a3c] [2018-10-30 00:43:12,763] - Components::findLogger: found logger, addr:192.168.0.107:49653
  INFO root [0x00001a3c] [2018-10-30 00:43:12,763] - Components::addComponent: reset orderLog, uid=16776!
  INFO root [0x00001a3c] [2018-10-30 00:43:12,763] - Components::addComponent[logger], uid=16776, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00001a3c] [2018-10-30 00:43:12,768] - ---- baseapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: F9DFFB319FBADF35943ADF4D42C4718C. Config: Debug X86. Built: 15:53:31 Apr 29 2018. AppID: 7001. UID: 16776. PID: 6564 ----
  INFO root [0x00001a3c] [2018-10-30 00:43:12,768] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [0x00001a3c] [2018-10-30 00:43:12,769] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00001a3c] [2018-10-30 00:43:12,769] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x00001a3c] [2018-10-30 00:43:12,903] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00001a3c] [2018-10-30 00:43:12,903] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x00001a3c] [2018-10-30 00:43:12,904] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x00001a3c] [2018-10-30 00:43:12,907] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x00001a3c] [2018-10-30 00:43:12,907] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x00001a3c] [2018-10-30 00:43:12,907] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x00001a3c] [2018-10-30 00:43:12,907] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x00001a3c] [2018-10-30 00:43:12,939] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x00001a3c] [2018-10-30 00:43:12,967] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x00001a3c] [2018-10-30 00:43:12,967] - Script::install(): KBExtra is successfully!
 DEBUG root [0x00001a3c] [2018-10-30 00:43:13,005] - loaded entity-script:Account(1).
 DEBUG root [0x00001a3c] [2018-10-30 00:43:13,007] - loaded entity-script:CheckName(2).
 DEBUG root [0x00001a3c] [2018-10-30 00:43:13,015] - loaded entity-script:Halls(3).
 DEBUG root [0x00001a3c] [2018-10-30 00:43:13,017] - loaded entity-script:Room(4).
  INFO root [0x00001a3c] [2018-10-30 00:43:13,017] - Baseapp::initializeEnd: started resmgr tick(60s)!
  INFO root [0x00001a3c] [2018-10-30 00:43:13,018] - TelnetServer server is running on port 40000
  INFO root [0x00001a3c] [2018-10-30 00:43:13,421] - ---- baseapp is running ----
 DEBUG root [0x00001a3c] [2018-10-30 00:43:13,421] - Components::process(): Request for the process of identity...
  WARN root [0x00001a3c] [2018-10-30 00:43:13,731] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20988, errorno=10048
  WARN root [0x00001a3c] [2018-10-30 00:43:19,788] - Forwarding logs to logger[192.168.0.107:49653/0/0/0]...
 ERROR root [0x00001a3c] [2018-10-30 00:48:33,380] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x00001a3c] [2018-10-30 00:48:33,385] - The following logs sent to logger failed:
  WARN root [0x00001a3c] [2018-10-30 00:48:33,386] - ==> [2018-10-30 00:48:33 379] TCPPacketReceiver::processPendingEvents(192.168.0.107:49653): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00001a3c] [2018-10-30 00:48:33,386] - ==> [2018-10-30 00:48:33 381] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x00001a3c] [2018-10-30 00:48:33,427] - TCPPacketReceiver::processPendingEvents(192.168.0.107:49658): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00001a3c] [2018-10-30 00:48:33,427] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x00001a3c] [2018-10-30 00:48:33,471] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [0x00001a3c] [2018-10-30 00:48:33,471] - onBaseAppShutDown: state=0
  INFO root [0x00001a3c] [2018-10-30 00:48:33,471] - Shutdowner::onShutdown: shutting down
S_INFO root [0x00001a3c] [2018-10-30 00:48:33,471] - onBaseAppShutDown: state=1
  INFO root [0x00001a3c] [2018-10-30 00:48:33,471] - Shutdowner::onShutdownEnd: shutting down
S_INFO root [0x00001a3c] [2018-10-30 00:48:33,471] - onBaseAppShutDown: state=2
 DEBUG root [0x00001a3c] [2018-10-30 00:48:33,566] - Halls::~Halls(): 1
  INFO root [0x00001f0c] [2018-10-30 00:48:34,537] - 
  INFO root [0x00001f0c] [2018-10-30 00:48:34,537] - -----------------------------------------------------------------------------------------


  INFO root [0x00001f0c] [2018-10-30 00:48:34,538] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [0x00001f0c] [2018-10-30 00:48:34,538] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [0x00001f0c] [2018-10-30 00:48:34,538] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [0x00001f0c] [2018-10-30 00:48:34,541] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.107 ( 192.168.0.107:20015 )
  INFO root [0x00001f0c] [2018-10-30 00:48:34,541] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.107:20015, SOMAXCONN=128.
  INFO root [0x00001f0c] [2018-10-30 00:48:34,542] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.107 ( 192.168.0.107:49757 )
  INFO root [0x00001f0c] [2018-10-30 00:48:34,542] - NetworkInterface::initialize(INTERNAL): address 192.168.0.107:49757, SOMAXCONN=128.
  INFO root [0x00001f0c] [2018-10-30 00:48:34,543] - server-configs:
  INFO root [0x00001f0c] [2018-10-30 00:48:34,543] - 	gameUpdateHertz : 10
  INFO root [0x00001f0c] [2018-10-30 00:48:34,543] - 	entryScriptFile : kbemain
  INFO root [0x00001f0c] [2018-10-30 00:48:34,543] - 	internalAddr : 192.168.0.107:49757
  INFO root [0x00001f0c] [2018-10-30 00:48:34,543] - 	externalAddr : 192.168.0.107:20015
  INFO root [0x00001f0c] [2018-10-30 00:48:34,543] - 	externalCustomAddr : 171.88.53.16
  INFO root [0x00001f0c] [2018-10-30 00:48:34,543] - 	componentID : 7001
  INFO root [0x00001f0c] [2018-10-30 00:48:36,223] - ---- baseapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: F9DFFB319FBADF35943ADF4D42C4718C. Config: Debug X86. Built: 15:53:31 Apr 29 2018. AppID: 7001. UID: 17827. PID: 6636 ----
  INFO root [0x00001f0c] [2018-10-30 00:48:36,224] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [0x00001f0c] [2018-10-30 00:48:36,224] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00001f0c] [2018-10-30 00:48:36,224] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x00001f0c] [2018-10-30 00:48:36,347] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00001f0c] [2018-10-30 00:48:36,347] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x00001f0c] [2018-10-30 00:48:36,347] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x00001f0c] [2018-10-30 00:48:36,350] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x00001f0c] [2018-10-30 00:48:36,350] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x00001f0c] [2018-10-30 00:48:36,351] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x00001f0c] [2018-10-30 00:48:36,351] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x00001f0c] [2018-10-30 00:48:36,377] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x00001f0c] [2018-10-30 00:48:36,404] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x00001f0c] [2018-10-30 00:48:36,404] - Script::install(): KBExtra is successfully!
 DEBUG root [0x00001f0c] [2018-10-30 00:48:36,425] - loaded entity-script:Account(1).
 DEBUG root [0x00001f0c] [2018-10-30 00:48:36,426] - loaded entity-script:CheckName(2).
 DEBUG root [0x00001f0c] [2018-10-30 00:48:36,431] - loaded entity-script:Halls(3).
 DEBUG root [0x00001f0c] [2018-10-30 00:48:36,432] - loaded entity-script:Room(4).
  INFO root [0x00001f0c] [2018-10-30 00:48:36,432] - Baseapp::initializeEnd: started resmgr tick(60s)!
  INFO root [0x00001f0c] [2018-10-30 00:48:36,432] - TelnetServer server is running on port 40000
  INFO root [0x00001f0c] [2018-10-30 00:48:36,700] - ---- baseapp is running ----
 DEBUG root [0x00001f0c] [2018-10-30 00:48:36,700] - Components::process(): Request for the process of identity...
  WARN root [0x00001f0c] [2018-10-30 00:48:42,803] - EntityApp::checkTickPeriod: tick took 6103% (6.10 seconds)!
  INFO root [0x00001f0c] [2018-10-30 00:48:43,839] - Components::findComponents: find logger(1)...
  WARN root [0x00001f0c] [2018-10-30 00:48:44,149] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20624, errorno=10048
  WARN root [0x00001f0c] [2018-10-30 00:48:44,150] - EntityApp::checkTickPeriod: tick took 349% (0.35 seconds)!
  INFO root [0x00001f0c] [2018-10-30 00:48:45,200] - Components::findComponents: find logger(2)...
  INFO root [0x00001f0c] [2018-10-30 00:48:45,254] - Components::findComponents: found logger, addr:192.168.0.107:49755
  INFO root [0x00001f0c] [2018-10-30 00:48:45,254] - Components::addComponent: reset orderLog, uid=17827!
  INFO root [0x00001f0c] [2018-10-30 00:48:45,255] - Components::addComponent[logger], uid=17827, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00001f0c] [2018-10-30 00:48:45,257] - Components::findComponents: find dbmgr(3)...
  INFO root [0x00001f0c] [2018-10-30 00:48:45,359] - Components::findComponents: found dbmgr, addr:192.168.0.107:49758
  INFO root [0x00001f0c] [2018-10-30 00:48:45,359] - Components::addComponent: reset orderLog, uid=17827!
  INFO root [0x00001f0c] [2018-10-30 00:48:45,360] - Components::addComponent[dbmgr], uid=17827, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00001f0c] [2018-10-30 00:48:45,361] - Components::findComponents: found dbmgr, addr:192.168.0.107:49758
  WARN root [0x00001f0c] [2018-10-30 00:48:46,361] - EntityApp::checkTickPeriod: tick took 1261% (1.26 seconds)!
  WARN root [0x00001f0c] [2018-10-30 00:48:46,363] - Forwarding logs to logger[192.168.0.107:49755/0/0/0]...
 ERROR root [0x00001f0c] [2018-10-30 00:56:16,983] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x00001f0c] [2018-10-30 00:56:16,989] - The following logs sent to logger failed:
  WARN root [0x00001f0c] [2018-10-30 00:56:16,989] - ==> [2018-10-30 00:56:16 982] TCPPacketReceiver::processPendingEvents(192.168.0.107:49755): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00001f0c] [2018-10-30 00:56:16,989] - ==> [2018-10-30 00:56:16 983] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x00001f0c] [2018-10-30 00:56:17,028] - TCPPacketReceiver::processPendingEvents(192.168.0.107:49758): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00001f0c] [2018-10-30 00:56:17,029] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x00001f0c] [2018-10-30 00:56:17,032] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [0x00001f0c] [2018-10-30 00:56:17,034] - onBaseAppShutDown: state=0
  INFO root [0x00001f0c] [2018-10-30 00:56:17,034] - Shutdowner::onShutdown: shutting down
S_INFO root [0x00001f0c] [2018-10-30 00:56:17,034] - onBaseAppShutDown: state=1
  INFO root [0x00001f0c] [2018-10-30 00:56:17,034] - Shutdowner::onShutdownEnd: shutting down
S_INFO root [0x00001f0c] [2018-10-30 00:56:17,035] - onBaseAppShutDown: state=2
 DEBUG root [0x00001f0c] [2018-10-30 00:56:17,042] - Halls::~Halls(): 2001
 DEBUG root [0x00001f0c] [2018-10-30 00:56:17,043] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00001f0c] [2018-10-30 00:56:17,043] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x00001f0c] [2018-10-30 00:56:17,043] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x00001f0c] [2018-10-30 00:56:17,043] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x00001f0c] [2018-10-30 00:56:17,044] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x00001f0c] [2018-10-30 00:56:17,044] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x00001f0c] [2018-10-30 00:56:17,044] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x00001f0c] [2018-10-30 00:56:17,044] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x00001f0c] [2018-10-30 00:56:17,063] - Script::uninstall(): is successfully!
 DEBUG root [0x00001f0c] [2018-10-30 00:56:17,063] - ThreadPool::destroy(): starting size 2.
  INFO root [0x00001ff0] [2018-10-30 00:56:18,100] - 
  INFO root [0x00001ff0] [2018-10-30 00:56:18,100] - -----------------------------------------------------------------------------------------


  INFO root [0x00001ff0] [2018-10-30 00:56:18,101] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [0x00001ff0] [2018-10-30 00:56:18,102] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [0x00001ff0] [2018-10-30 00:56:18,102] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [0x00001ff0] [2018-10-30 00:56:18,104] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.107 ( 192.168.0.107:20015 )
  INFO root [0x00001ff0] [2018-10-30 00:56:18,104] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.107:20015, SOMAXCONN=128.
  INFO root [0x00001ff0] [2018-10-30 00:56:18,105] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.107 ( 192.168.0.107:49827 )
  INFO root [0x00001ff0] [2018-10-30 00:56:18,105] - NetworkInterface::initialize(INTERNAL): address 192.168.0.107:49827, SOMAXCONN=128.
  INFO root [0x00001ff0] [2018-10-30 00:56:18,105] - server-configs:
  INFO root [0x00001ff0] [2018-10-30 00:56:18,105] - 	gameUpdateHertz : 10
  INFO root [0x00001ff0] [2018-10-30 00:56:18,105] - 	entryScriptFile : kbemain
  INFO root [0x00001ff0] [2018-10-30 00:56:18,106] - 	internalAddr : 192.168.0.107:49827
  INFO root [0x00001ff0] [2018-10-30 00:56:18,106] - 	externalAddr : 192.168.0.107:20015
  INFO root [0x00001ff0] [2018-10-30 00:56:18,106] - 	externalCustomAddr : 192.168.0.107
  INFO root [0x00001ff0] [2018-10-30 00:56:18,106] - 	componentID : 7001
  INFO root [0x00001ff0] [2018-10-30 00:56:19,793] - ---- baseapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: F9DFFB319FBADF35943ADF4D42C4718C. Config: Debug X86. Built: 15:53:31 Apr 29 2018. AppID: 7001. UID: 19339. PID: 8188 ----
  INFO root [0x00001ff0] [2018-10-30 00:56:19,794] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [0x00001ff0] [2018-10-30 00:56:19,794] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00001ff0] [2018-10-30 00:56:19,794] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x00001ff0] [2018-10-30 00:56:19,918] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00001ff0] [2018-10-30 00:56:19,918] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x00001ff0] [2018-10-30 00:56:19,919] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x00001ff0] [2018-10-30 00:56:19,922] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x00001ff0] [2018-10-30 00:56:19,922] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x00001ff0] [2018-10-30 00:56:19,922] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x00001ff0] [2018-10-30 00:56:19,923] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x00001ff0] [2018-10-30 00:56:19,949] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x00001ff0] [2018-10-30 00:56:19,977] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x00001ff0] [2018-10-30 00:56:19,977] - Script::install(): KBExtra is successfully!
 DEBUG root [0x00001ff0] [2018-10-30 00:56:19,999] - loaded entity-script:Account(1).
 DEBUG root [0x00001ff0] [2018-10-30 00:56:20,000] - loaded entity-script:CheckName(2).
 DEBUG root [0x00001ff0] [2018-10-30 00:56:20,005] - loaded entity-script:Halls(3).
 DEBUG root [0x00001ff0] [2018-10-30 00:56:20,006] - loaded entity-script:Room(4).
  INFO root [0x00001ff0] [2018-10-30 00:56:20,007] - Baseapp::initializeEnd: started resmgr tick(60s)!
  INFO root [0x00001ff0] [2018-10-30 00:56:20,007] - TelnetServer server is running on port 40000
  INFO root [0x00001ff0] [2018-10-30 00:56:20,285] - ---- baseapp is running ----
 DEBUG root [0x00001ff0] [2018-10-30 00:56:20,285] - Components::process(): Request for the process of identity...
  WARN root [0x00001ff0] [2018-10-30 00:56:26,418] - EntityApp::checkTickPeriod: tick took 6132% (6.13 seconds)!
  INFO root [0x00001ff0] [2018-10-30 00:56:27,486] - Components::findComponents: find logger(1)...
  INFO root [0x00001ff0] [2018-10-30 00:56:27,494] - Components::findComponents: found logger, addr:192.168.0.107:49824
  INFO root [0x00001ff0] [2018-10-30 00:56:27,494] - Components::addComponent: reset orderLog, uid=19339!
  INFO root [0x00001ff0] [2018-10-30 00:56:27,495] - Components::addComponent[logger], uid=19339, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00001ff0] [2018-10-30 00:56:27,497] - Components::findComponents: find dbmgr(2)...
  INFO root [0x00001ff0] [2018-10-30 00:56:27,598] - Components::findComponents: found dbmgr, addr:192.168.0.107:49822
  INFO root [0x00001ff0] [2018-10-30 00:56:27,599] - Components::addComponent: reset orderLog, uid=19339!
  INFO root [0x00001ff0] [2018-10-30 00:56:27,600] - Components::addComponent[dbmgr], uid=19339, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00001ff0] [2018-10-30 00:56:27,600] - Components::findComponents: found dbmgr, addr:192.168.0.107:49822
  WARN root [0x00001ff0] [2018-10-30 00:56:28,600] - EntityApp::checkTickPeriod: tick took 1214% (1.21 seconds)!
  WARN root [0x00001ff0] [2018-10-30 00:56:28,602] - Forwarding logs to logger[192.168.0.107:49824/0/0/0]...
 ERROR root [0x00001ff0] [2018-10-30 01:01:04,072] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x00001ff0] [2018-10-30 01:01:04,079] - The following logs sent to logger failed:
  WARN root [0x00001ff0] [2018-10-30 01:01:04,079] - ==> [2018-10-30 01:01:04 071] TCPPacketReceiver::processPendingEvents(192.168.0.107:49824): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00001ff0] [2018-10-30 01:01:04,079] - ==> [2018-10-30 01:01:04 073] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x00001ff0] [2018-10-30 01:01:04,120] - TCPPacketReceiver::processPendingEvents(192.168.0.107:49822): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00001ff0] [2018-10-30 01:01:04,121] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x00001ff0] [2018-10-30 01:01:04,124] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [0x00001ff0] [2018-10-30 01:01:04,126] - onBaseAppShutDown: state=0
  INFO root [0x00001ff0] [2018-10-30 01:01:04,126] - Shutdowner::onShutdown: shutting down
S_INFO root [0x00001ff0] [2018-10-30 01:01:04,126] - onBaseAppShutDown: state=1
  INFO root [0x00001ff0] [2018-10-30 01:01:04,126] - Shutdowner::onShutdownEnd: shutting down
S_INFO root [0x00001ff0] [2018-10-30 01:01:04,126] - onBaseAppShutDown: state=2
 DEBUG root [0x00001ff0] [2018-10-30 01:01:04,134] - Halls::~Halls(): 2001
 DEBUG root [0x00001ff0] [2018-10-30 01:01:04,135] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00001ff0] [2018-10-30 01:01:04,135] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x00001ff0] [2018-10-30 01:01:04,135] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x00001ff0] [2018-10-30 01:01:04,135] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x00001ff0] [2018-10-30 01:01:04,135] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x00001ff0] [2018-10-30 01:01:04,135] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x00001ff0] [2018-10-30 01:01:04,135] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x00001ff0] [2018-10-30 01:01:04,135] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x00001ff0] [2018-10-30 01:01:04,144] - Script::uninstall(): is successfully!
 DEBUG root [0x00001ff0] [2018-10-30 01:01:04,144] - ThreadPool::destroy(): starting size 2.
  INFO root [0x00001ff0] [2018-10-30 01:01:05,245] - 
  INFO root [0x00001ff0] [2018-10-30 01:01:05,245] - -----------------------------------------------------------------------------------------


  INFO root [0x00001ff0] [2018-10-30 01:01:05,246] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [0x00001ff0] [2018-10-30 01:01:05,246] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [0x00001ff0] [2018-10-30 01:01:05,246] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [0x00001ff0] [2018-10-30 01:01:05,248] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.107 ( 192.168.0.107:20015 )
  INFO root [0x00001ff0] [2018-10-30 01:01:05,248] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.107:20015, SOMAXCONN=128.
  INFO root [0x00001ff0] [2018-10-30 01:01:05,249] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.107 ( 192.168.0.107:50278 )
  INFO root [0x00001ff0] [2018-10-30 01:01:05,249] - NetworkInterface::initialize(INTERNAL): address 192.168.0.107:50278, SOMAXCONN=128.
  INFO root [0x00001ff0] [2018-10-30 01:01:05,249] - server-configs:
  INFO root [0x00001ff0] [2018-10-30 01:01:05,249] - 	gameUpdateHertz : 10
  INFO root [0x00001ff0] [2018-10-30 01:01:05,249] - 	entryScriptFile : kbemain
  INFO root [0x00001ff0] [2018-10-30 01:01:05,249] - 	internalAddr : 192.168.0.107:50278
  INFO root [0x00001ff0] [2018-10-30 01:01:05,250] - 	externalAddr : 192.168.0.107:20015
  INFO root [0x00001ff0] [2018-10-30 01:01:05,250] - 	externalCustomAddr : 192.168.0.107
  INFO root [0x00001ff0] [2018-10-30 01:01:05,250] - 	componentID : 7001
  INFO root [0x00001ff0] [2018-10-30 01:01:06,939] - ---- baseapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: F9DFFB319FBADF35943ADF4D42C4718C. Config: Debug X86. Built: 15:53:31 Apr 29 2018. AppID: 7001. UID: 20276. PID: 5580 ----
  INFO root [0x00001ff0] [2018-10-30 01:01:06,940] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [0x00001ff0] [2018-10-30 01:01:06,940] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00001ff0] [2018-10-30 01:01:06,940] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x00001ff0] [2018-10-30 01:01:07,063] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00001ff0] [2018-10-30 01:01:07,063] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x00001ff0] [2018-10-30 01:01:07,063] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x00001ff0] [2018-10-30 01:01:07,067] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x00001ff0] [2018-10-30 01:01:07,067] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x00001ff0] [2018-10-30 01:01:07,067] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x00001ff0] [2018-10-30 01:01:07,068] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x00001ff0] [2018-10-30 01:01:07,095] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x00001ff0] [2018-10-30 01:01:07,122] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x00001ff0] [2018-10-30 01:01:07,122] - Script::install(): KBExtra is successfully!
 DEBUG root [0x00001ff0] [2018-10-30 01:01:07,142] - loaded entity-script:Account(1).
 DEBUG root [0x00001ff0] [2018-10-30 01:01:07,143] - loaded entity-script:CheckName(2).
 DEBUG root [0x00001ff0] [2018-10-30 01:01:07,150] - loaded entity-script:Halls(3).
 DEBUG root [0x00001ff0] [2018-10-30 01:01:07,151] - loaded entity-script:Room(4).
  INFO root [0x00001ff0] [2018-10-30 01:01:07,152] - Baseapp::initializeEnd: started resmgr tick(60s)!
  INFO root [0x00001ff0] [2018-10-30 01:01:07,152] - TelnetServer server is running on port 40000
  INFO root [0x00001ff0] [2018-10-30 01:01:07,492] - ---- baseapp is running ----
 DEBUG root [0x00001ff0] [2018-10-30 01:01:07,493] - Components::process(): Request for the process of identity...
  WARN root [0x00001ff0] [2018-10-30 01:01:13,605] - EntityApp::checkTickPeriod: tick took 6113% (6.11 seconds)!
  INFO root [0x00001ff0] [2018-10-30 01:01:14,646] - Components::findComponents: find logger(1)...
  INFO root [0x00001ff0] [2018-10-30 01:01:14,656] - Components::findComponents: found logger, addr:192.168.0.107:50276
  INFO root [0x00001ff0] [2018-10-30 01:01:14,656] - Components::addComponent: reset orderLog, uid=20276!
  INFO root [0x00001ff0] [2018-10-30 01:01:14,657] - Components::addComponent[logger], uid=20276, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00001ff0] [2018-10-30 01:01:14,658] - Components::findComponents: find dbmgr(2)...
  INFO root [0x00001ff0] [2018-10-30 01:01:14,760] - Components::findComponents: found dbmgr, addr:192.168.0.107:50277
  INFO root [0x00001ff0] [2018-10-30 01:01:14,761] - Components::addComponent: reset orderLog, uid=20276!
  INFO root [0x00001ff0] [2018-10-30 01:01:14,761] - Components::addComponent[dbmgr], uid=20276, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00001ff0] [2018-10-30 01:01:14,762] - Components::findComponents: found dbmgr, addr:192.168.0.107:50277
  WARN root [0x00001ff0] [2018-10-30 01:01:15,762] - Forwarding logs to logger[192.168.0.107:50276/0/0/0]...
 ERROR root [0x00001ff0] [2018-10-30 01:04:06,314] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x00001ff0] [2018-10-30 01:04:06,319] - The following logs sent to logger failed:
  WARN root [0x00001ff0] [2018-10-30 01:04:06,320] - ==> [2018-10-30 01:04:06 313] TCPPacketReceiver::processPendingEvents(192.168.0.107:50276): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00001ff0] [2018-10-30 01:04:06,320] - ==> [2018-10-30 01:04:06 315] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x00001ff0] [2018-10-30 01:04:06,361] - TCPPacketReceiver::processPendingEvents(192.168.0.107:50277): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00001ff0] [2018-10-30 01:04:06,361] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x00001ff0] [2018-10-30 01:04:06,365] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [0x00001ff0] [2018-10-30 01:04:06,366] - onBaseAppShutDown: state=0
  INFO root [0x00001ff0] [2018-10-30 01:04:06,366] - Shutdowner::onShutdown: shutting down
S_INFO root [0x00001ff0] [2018-10-30 01:04:06,366] - onBaseAppShutDown: state=1
  INFO root [0x00001ff0] [2018-10-30 01:04:06,367] - Shutdowner::onShutdownEnd: shutting down
S_INFO root [0x00001ff0] [2018-10-30 01:04:06,367] - onBaseAppShutDown: state=2
 DEBUG root [0x00001ff0] [2018-10-30 01:04:06,375] - Halls::~Halls(): 2001
 DEBUG root [0x00001ff0] [2018-10-30 01:04:06,376] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00001ff0] [2018-10-30 01:04:06,376] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x00001ff0] [2018-10-30 01:04:06,376] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x00001ff0] [2018-10-30 01:04:06,376] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x00001ff0] [2018-10-30 01:04:06,376] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x00001ff0] [2018-10-30 01:04:06,376] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x00001ff0] [2018-10-30 01:04:06,376] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x00001ff0] [2018-10-30 01:04:06,376] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x00001ff0] [2018-10-30 01:04:06,386] - Script::uninstall(): is successfully!
 DEBUG root [0x00001ff0] [2018-10-30 01:04:06,386] - ThreadPool::destroy(): starting size 2.
  INFO root [0x00002278] [2018-10-30 01:04:07,435] - 
  INFO root [0x00002278] [2018-10-30 01:04:07,435] - -----------------------------------------------------------------------------------------


  INFO root [0x00002278] [2018-10-30 01:04:07,435] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [0x00002278] [2018-10-30 01:04:07,435] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [0x00002278] [2018-10-30 01:04:07,436] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [0x00002278] [2018-10-30 01:04:07,446] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.107 ( 192.168.0.107:20015 )
  INFO root [0x00002278] [2018-10-30 01:04:07,447] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.107:20015, SOMAXCONN=128.
  INFO root [0x00002278] [2018-10-30 01:04:07,451] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.107 ( 192.168.0.107:50329 )
  INFO root [0x00002278] [2018-10-30 01:04:07,451] - NetworkInterface::initialize(INTERNAL): address 192.168.0.107:50329, SOMAXCONN=128.
  INFO root [0x00002278] [2018-10-30 01:04:07,451] - server-configs:
  INFO root [0x00002278] [2018-10-30 01:04:07,451] - 	gameUpdateHertz : 10
  INFO root [0x00002278] [2018-10-30 01:04:07,451] - 	entryScriptFile : kbemain
  INFO root [0x00002278] [2018-10-30 01:04:07,451] - 	internalAddr : 192.168.0.107:50329
  INFO root [0x00002278] [2018-10-30 01:04:07,452] - 	externalAddr : 192.168.0.107:20015
  INFO root [0x00002278] [2018-10-30 01:04:07,452] - 	externalCustomAddr : 192.168.0.107
  INFO root [0x00002278] [2018-10-30 01:04:07,452] - 	componentID : 7001
  INFO root [0x00002278] [2018-10-30 01:04:09,143] - ---- baseapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: F9DFFB319FBADF35943ADF4D42C4718C. Config: Debug X86. Built: 15:53:31 Apr 29 2018. AppID: 7001. UID: 20874. PID: 9876 ----
  INFO root [0x00002278] [2018-10-30 01:04:09,144] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [0x00002278] [2018-10-30 01:04:09,145] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00002278] [2018-10-30 01:04:09,145] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x00002278] [2018-10-30 01:04:09,269] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00002278] [2018-10-30 01:04:09,269] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x00002278] [2018-10-30 01:04:09,270] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x00002278] [2018-10-30 01:04:09,273] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x00002278] [2018-10-30 01:04:09,273] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x00002278] [2018-10-30 01:04:09,273] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x00002278] [2018-10-30 01:04:09,274] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x00002278] [2018-10-30 01:04:09,301] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x00002278] [2018-10-30 01:04:09,329] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x00002278] [2018-10-30 01:04:09,329] - Script::install(): KBExtra is successfully!
 DEBUG root [0x00002278] [2018-10-30 01:04:09,350] - loaded entity-script:Account(1).
 DEBUG root [0x00002278] [2018-10-30 01:04:09,351] - loaded entity-script:CheckName(2).
 DEBUG root [0x00002278] [2018-10-30 01:04:09,356] - loaded entity-script:Halls(3).
 DEBUG root [0x00002278] [2018-10-30 01:04:09,357] - loaded entity-script:Room(4).
  INFO root [0x00002278] [2018-10-30 01:04:09,357] - Baseapp::initializeEnd: started resmgr tick(60s)!
  INFO root [0x00002278] [2018-10-30 01:04:09,358] - TelnetServer server is running on port 40000
  INFO root [0x00002278] [2018-10-30 01:04:09,636] - ---- baseapp is running ----
 DEBUG root [0x00002278] [2018-10-30 01:04:09,637] - Components::process(): Request for the process of identity...
  WARN root [0x00002278] [2018-10-30 01:04:15,723] - EntityApp::checkTickPeriod: tick took 6086% (6.09 seconds)!
  INFO root [0x00002278] [2018-10-30 01:04:16,837] - Components::findComponents: find logger(1)...
  INFO root [0x00002278] [2018-10-30 01:04:16,859] - Components::findComponents: found logger, addr:192.168.0.107:50327
  INFO root [0x00002278] [2018-10-30 01:04:16,859] - Components::addComponent: reset orderLog, uid=20874!
  INFO root [0x00002278] [2018-10-30 01:04:16,860] - Components::addComponent[logger], uid=20874, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00002278] [2018-10-30 01:04:16,862] - Components::findComponents: find dbmgr(2)...
  INFO root [0x00002278] [2018-10-30 01:04:16,964] - Components::findComponents: found dbmgr, addr:192.168.0.107:50331
  INFO root [0x00002278] [2018-10-30 01:04:16,964] - Components::addComponent: reset orderLog, uid=20874!
  INFO root [0x00002278] [2018-10-30 01:04:16,965] - Components::addComponent[dbmgr], uid=20874, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00002278] [2018-10-30 01:04:16,966] - Components::findComponents: found dbmgr, addr:192.168.0.107:50331
  WARN root [0x00002278] [2018-10-30 01:04:17,966] - Forwarding logs to logger[192.168.0.107:50327/0/0/0]...
 ERROR root [0x00002278] [2018-10-30 01:06:59,831] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x00002278] [2018-10-30 01:06:59,838] - The following logs sent to logger failed:
  WARN root [0x00002278] [2018-10-30 01:06:59,838] - ==> [2018-10-30 01:06:59 830] TCPPacketReceiver::processPendingEvents(192.168.0.107:50327): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00002278] [2018-10-30 01:06:59,838] - ==> [2018-10-30 01:06:59 831] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x00002278] [2018-10-30 01:06:59,878] - TCPPacketReceiver::processPendingEvents(192.168.0.107:50331): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00002278] [2018-10-30 01:06:59,879] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x00002278] [2018-10-30 01:06:59,882] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [0x00002278] [2018-10-30 01:06:59,885] - onBaseAppShutDown: state=0
  INFO root [0x00002278] [2018-10-30 01:06:59,885] - Shutdowner::onShutdown: shutting down
S_INFO root [0x00002278] [2018-10-30 01:06:59,885] - onBaseAppShutDown: state=1
  INFO root [0x00002278] [2018-10-30 01:06:59,885] - Shutdowner::onShutdownEnd: shutting down
S_INFO root [0x00002278] [2018-10-30 01:06:59,885] - onBaseAppShutDown: state=2
 DEBUG root [0x00002278] [2018-10-30 01:06:59,893] - Halls::~Halls(): 2001
 DEBUG root [0x00002278] [2018-10-30 01:06:59,894] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00002278] [2018-10-30 01:06:59,894] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x00002278] [2018-10-30 01:06:59,894] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x00002278] [2018-10-30 01:06:59,894] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x00002278] [2018-10-30 01:06:59,894] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x00002278] [2018-10-30 01:06:59,894] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x00002278] [2018-10-30 01:06:59,895] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x00002278] [2018-10-30 01:06:59,895] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x00002278] [2018-10-30 01:06:59,904] - Script::uninstall(): is successfully!
 DEBUG root [0x00002278] [2018-10-30 01:06:59,904] - ThreadPool::destroy(): starting size 2.
  INFO root [0x00002140] [2018-10-30 01:07:00,953] - 
  INFO root [0x00002140] [2018-10-30 01:07:00,953] - -----------------------------------------------------------------------------------------


  INFO root [0x00002140] [2018-10-30 01:07:00,954] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [0x00002140] [2018-10-30 01:07:00,954] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [0x00002140] [2018-10-30 01:07:00,954] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [0x00002140] [2018-10-30 01:07:00,957] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.107 ( 192.168.0.107:20015 )
  INFO root [0x00002140] [2018-10-30 01:07:00,957] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.107:20015, SOMAXCONN=128.
  INFO root [0x00002140] [2018-10-30 01:07:00,959] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.107 ( 192.168.0.107:50408 )
  INFO root [0x00002140] [2018-10-30 01:07:00,960] - NetworkInterface::initialize(INTERNAL): address 192.168.0.107:50408, SOMAXCONN=128.
  INFO root [0x00002140] [2018-10-30 01:07:00,960] - server-configs:
  INFO root [0x00002140] [2018-10-30 01:07:00,960] - 	gameUpdateHertz : 10
  INFO root [0x00002140] [2018-10-30 01:07:00,960] - 	entryScriptFile : kbemain
  INFO root [0x00002140] [2018-10-30 01:07:00,960] - 	internalAddr : 192.168.0.107:50408
  INFO root [0x00002140] [2018-10-30 01:07:00,960] - 	externalAddr : 192.168.0.107:20015
  INFO root [0x00002140] [2018-10-30 01:07:00,960] - 	externalCustomAddr : 192.168.0.107
  INFO root [0x00002140] [2018-10-30 01:07:00,961] - 	componentID : 7001
  INFO root [0x00002140] [2018-10-30 01:07:02,630] - ---- baseapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: F9DFFB319FBADF35943ADF4D42C4718C. Config: Debug X86. Built: 15:53:31 Apr 29 2018. AppID: 7001. UID: 21439. PID: 7116 ----
  INFO root [0x00002140] [2018-10-30 01:07:02,631] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [0x00002140] [2018-10-30 01:07:02,631] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00002140] [2018-10-30 01:07:02,632] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x00002140] [2018-10-30 01:07:02,755] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00002140] [2018-10-30 01:07:02,756] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x00002140] [2018-10-30 01:07:02,756] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x00002140] [2018-10-30 01:07:02,759] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x00002140] [2018-10-30 01:07:02,759] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x00002140] [2018-10-30 01:07:02,759] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x00002140] [2018-10-30 01:07:02,760] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x00002140] [2018-10-30 01:07:02,788] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x00002140] [2018-10-30 01:07:02,827] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x00002140] [2018-10-30 01:07:02,827] - Script::install(): KBExtra is successfully!
 DEBUG root [0x00002140] [2018-10-30 01:07:02,857] - loaded entity-script:Account(1).
 DEBUG root [0x00002140] [2018-10-30 01:07:02,858] - loaded entity-script:CheckName(2).
 DEBUG root [0x00002140] [2018-10-30 01:07:02,864] - loaded entity-script:Halls(3).
 DEBUG root [0x00002140] [2018-10-30 01:07:02,865] - loaded entity-script:Room(4).
  INFO root [0x00002140] [2018-10-30 01:07:02,865] - Baseapp::initializeEnd: started resmgr tick(60s)!
  INFO root [0x00002140] [2018-10-30 01:07:02,866] - TelnetServer server is running on port 40000
  INFO root [0x00002140] [2018-10-30 01:07:03,156] - ---- baseapp is running ----
 DEBUG root [0x00002140] [2018-10-30 01:07:03,156] - Components::process(): Request for the process of identity...
  WARN root [0x00002140] [2018-10-30 01:07:09,243] - EntityApp::checkTickPeriod: tick took 6086% (6.09 seconds)!
  INFO root [0x00002140] [2018-10-30 01:07:10,355] - Components::findComponents: find logger(1)...
  INFO root [0x00002140] [2018-10-30 01:07:10,372] - Components::findComponents: found logger, addr:192.168.0.107:50405
  INFO root [0x00002140] [2018-10-30 01:07:10,373] - Components::addComponent: reset orderLog, uid=21439!
  INFO root [0x00002140] [2018-10-30 01:07:10,374] - Components::addComponent[logger], uid=21439, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00002140] [2018-10-30 01:07:10,376] - Components::findComponents: find dbmgr(2)...
  INFO root [0x00002140] [2018-10-30 01:07:10,477] - Components::findComponents: found dbmgr, addr:192.168.0.107:50403
  INFO root [0x00002140] [2018-10-30 01:07:10,478] - Components::addComponent: reset orderLog, uid=21439!
  INFO root [0x00002140] [2018-10-30 01:07:10,478] - Components::addComponent[dbmgr], uid=21439, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00002140] [2018-10-30 01:07:10,479] - Components::findComponents: found dbmgr, addr:192.168.0.107:50403
  WARN root [0x00002140] [2018-10-30 01:07:11,479] - Forwarding logs to logger[192.168.0.107:50405/0/0/0]...
 ERROR root [0x00002140] [2018-10-30 01:07:38,144] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x00002140] [2018-10-30 01:07:38,150] - The following logs sent to logger failed:
  WARN root [0x00002140] [2018-10-30 01:07:38,151] - ==> [2018-10-30 01:07:38 143] TCPPacketReceiver::processPendingEvents(192.168.0.107:50405): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00002140] [2018-10-30 01:07:38,151] - ==> [2018-10-30 01:07:38 144] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x00002140] [2018-10-30 01:07:38,193] - TCPPacketReceiver::processPendingEvents(192.168.0.107:50403): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00002140] [2018-10-30 01:07:38,194] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x00002140] [2018-10-30 01:07:38,197] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [0x00002140] [2018-10-30 01:07:38,199] - onBaseAppShutDown: state=0
  INFO root [0x00002140] [2018-10-30 01:07:38,199] - Shutdowner::onShutdown: shutting down
S_INFO root [0x00002140] [2018-10-30 01:07:38,200] - onBaseAppShutDown: state=1
  INFO root [0x00002140] [2018-10-30 01:07:38,200] - Shutdowner::onShutdownEnd: shutting down
S_INFO root [0x00002140] [2018-10-30 01:07:38,200] - onBaseAppShutDown: state=2
 DEBUG root [0x00002140] [2018-10-30 01:07:38,208] - Halls::~Halls(): 2001
 DEBUG root [0x00002140] [2018-10-30 01:07:38,209] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00002140] [2018-10-30 01:07:38,209] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x00002140] [2018-10-30 01:07:38,209] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x00002140] [2018-10-30 01:07:38,209] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x00002140] [2018-10-30 01:07:38,209] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x00002140] [2018-10-30 01:07:38,209] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x00002140] [2018-10-30 01:07:38,209] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x00002140] [2018-10-30 01:07:38,209] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x00002140] [2018-10-30 01:07:38,219] - Script::uninstall(): is successfully!
 DEBUG root [0x00002140] [2018-10-30 01:07:38,219] - ThreadPool::destroy(): starting size 2.
  INFO root [0x00002738] [2018-10-30 01:07:39,269] - 
  INFO root [0x00002738] [2018-10-30 01:07:39,269] - -----------------------------------------------------------------------------------------


  INFO root [0x00002738] [2018-10-30 01:07:39,270] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [0x00002738] [2018-10-30 01:07:39,270] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [0x00002738] [2018-10-30 01:07:39,270] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [0x00002738] [2018-10-30 01:07:39,284] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.107 ( 192.168.0.107:20015 )
  INFO root [0x00002738] [2018-10-30 01:07:39,284] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.107:20015, SOMAXCONN=128.
  INFO root [0x00002738] [2018-10-30 01:07:39,285] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.107 ( 192.168.0.107:50446 )
  INFO root [0x00002738] [2018-10-30 01:07:39,285] - NetworkInterface::initialize(INTERNAL): address 192.168.0.107:50446, SOMAXCONN=128.
  INFO root [0x00002738] [2018-10-30 01:07:39,285] - server-configs:
  INFO root [0x00002738] [2018-10-30 01:07:39,285] - 	gameUpdateHertz : 10
  INFO root [0x00002738] [2018-10-30 01:07:39,286] - 	entryScriptFile : kbemain
  INFO root [0x00002738] [2018-10-30 01:07:39,286] - 	internalAddr : 192.168.0.107:50446
  INFO root [0x00002738] [2018-10-30 01:07:39,286] - 	externalAddr : 192.168.0.107:20015
  INFO root [0x00002738] [2018-10-30 01:07:39,286] - 	externalCustomAddr : 192.168.0.107
  INFO root [0x00002738] [2018-10-30 01:07:39,286] - 	componentID : 7001
  INFO root [0x00002738] [2018-10-30 01:07:40,968] - ---- baseapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: F9DFFB319FBADF35943ADF4D42C4718C. Config: Debug X86. Built: 15:53:31 Apr 29 2018. AppID: 7001. UID: 21566. PID: 7048 ----
  INFO root [0x00002738] [2018-10-30 01:07:40,969] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [0x00002738] [2018-10-30 01:07:40,969] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00002738] [2018-10-30 01:07:40,969] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x00002738] [2018-10-30 01:07:41,100] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00002738] [2018-10-30 01:07:41,100] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x00002738] [2018-10-30 01:07:41,101] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x00002738] [2018-10-30 01:07:41,104] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x00002738] [2018-10-30 01:07:41,104] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x00002738] [2018-10-30 01:07:41,104] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x00002738] [2018-10-30 01:07:41,105] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x00002738] [2018-10-30 01:07:41,136] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x00002738] [2018-10-30 01:07:41,176] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x00002738] [2018-10-30 01:07:41,177] - Script::install(): KBExtra is successfully!
 DEBUG root [0x00002738] [2018-10-30 01:07:41,203] - loaded entity-script:Account(1).
 DEBUG root [0x00002738] [2018-10-30 01:07:41,204] - loaded entity-script:CheckName(2).
 DEBUG root [0x00002738] [2018-10-30 01:07:41,211] - loaded entity-script:Halls(3).
 DEBUG root [0x00002738] [2018-10-30 01:07:41,213] - loaded entity-script:Room(4).
  INFO root [0x00002738] [2018-10-30 01:07:41,214] - Baseapp::initializeEnd: started resmgr tick(60s)!
  INFO root [0x00002738] [2018-10-30 01:07:41,214] - TelnetServer server is running on port 40000
  INFO root [0x00002738] [2018-10-30 01:07:41,514] - ---- baseapp is running ----
 DEBUG root [0x00002738] [2018-10-30 01:07:41,515] - Components::process(): Request for the process of identity...
  WARN root [0x00002738] [2018-10-30 01:07:47,617] - EntityApp::checkTickPeriod: tick took 6102% (6.10 seconds)!
  INFO root [0x00002738] [2018-10-30 01:07:48,679] - Components::findComponents: find logger(1)...
  INFO root [0x00002738] [2018-10-30 01:07:48,761] - Components::findComponents: found logger, addr:192.168.0.107:50444
  INFO root [0x00002738] [2018-10-30 01:07:48,762] - Components::addComponent: reset orderLog, uid=21566!
  INFO root [0x00002738] [2018-10-30 01:07:48,763] - Components::addComponent[logger], uid=21566, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00002738] [2018-10-30 01:07:48,765] - Components::findComponents: find dbmgr(2)...
  INFO root [0x00002738] [2018-10-30 01:07:48,866] - Components::findComponents: found dbmgr, addr:192.168.0.107:50441
  INFO root [0x00002738] [2018-10-30 01:07:48,867] - Components::addComponent: reset orderLog, uid=21566!
  INFO root [0x00002738] [2018-10-30 01:07:48,867] - Components::addComponent[dbmgr], uid=21566, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00002738] [2018-10-30 01:07:48,868] - Components::findComponents: found dbmgr, addr:192.168.0.107:50441
  WARN root [0x00002738] [2018-10-30 01:07:49,868] - Forwarding logs to logger[192.168.0.107:50444/0/0/0]...
 ERROR root [0x00002738] [2018-10-30 01:07:50,062] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x00002738] [2018-10-30 01:07:50,068] - The following logs sent to logger failed:
  WARN root [0x00002738] [2018-10-30 01:07:50,068] - ==> [2018-10-30 01:07:50 061] TCPPacketReceiver::processPendingEvents(192.168.0.107:50444): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00002738] [2018-10-30 01:07:50,068] - ==> [2018-10-30 01:07:50 062] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x0000155c] [2018-10-30 01:08:12,841] - 
  INFO root [0x0000155c] [2018-10-30 01:08:12,843] - -----------------------------------------------------------------------------------------


  INFO root [0x0000155c] [2018-10-30 01:08:12,843] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [0x0000155c] [2018-10-30 01:08:12,843] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [0x0000155c] [2018-10-30 01:08:12,843] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [0x0000155c] [2018-10-30 01:08:12,849] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.107 ( 192.168.0.107:20015 )
  INFO root [0x0000155c] [2018-10-30 01:08:12,849] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.107:20015, SOMAXCONN=128.
  INFO root [0x0000155c] [2018-10-30 01:08:12,850] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.107 ( 192.168.0.107:50466 )
  INFO root [0x0000155c] [2018-10-30 01:08:12,850] - NetworkInterface::initialize(INTERNAL): address 192.168.0.107:50466, SOMAXCONN=128.
  INFO root [0x0000155c] [2018-10-30 01:08:12,850] - server-configs:
  INFO root [0x0000155c] [2018-10-30 01:08:12,850] - 	gameUpdateHertz : 10
  INFO root [0x0000155c] [2018-10-30 01:08:12,851] - 	entryScriptFile : kbemain
  INFO root [0x0000155c] [2018-10-30 01:08:12,851] - 	internalAddr : 192.168.0.107:50466
  INFO root [0x0000155c] [2018-10-30 01:08:12,851] - 	externalAddr : 192.168.0.107:20015
  INFO root [0x0000155c] [2018-10-30 01:08:12,851] - 	externalCustomAddr : 192.168.0.107
  INFO root [0x0000155c] [2018-10-30 01:08:12,851] - 	componentID : 7001
  INFO root [0x0000155c] [2018-10-30 01:08:14,524] - ---- baseapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: F9DFFB319FBADF35943ADF4D42C4718C. Config: Debug X86. Built: 15:53:31 Apr 29 2018. AppID: 7001. UID: 21674. PID: 8556 ----
  INFO root [0x0000155c] [2018-10-30 01:08:14,525] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [0x0000155c] [2018-10-30 01:08:14,525] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x0000155c] [2018-10-30 01:08:14,525] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x0000155c] [2018-10-30 01:08:14,647] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x0000155c] [2018-10-30 01:08:14,648] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x0000155c] [2018-10-30 01:08:14,648] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x0000155c] [2018-10-30 01:08:14,651] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x0000155c] [2018-10-30 01:08:14,651] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x0000155c] [2018-10-30 01:08:14,651] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x0000155c] [2018-10-30 01:08:14,652] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x0000155c] [2018-10-30 01:08:14,678] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x0000155c] [2018-10-30 01:08:14,705] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x0000155c] [2018-10-30 01:08:14,705] - Script::install(): KBExtra is successfully!
 DEBUG root [0x0000155c] [2018-10-30 01:08:14,726] - loaded entity-script:Account(1).
 DEBUG root [0x0000155c] [2018-10-30 01:08:14,727] - loaded entity-script:CheckName(2).
 DEBUG root [0x0000155c] [2018-10-30 01:08:14,732] - loaded entity-script:Halls(3).
 DEBUG root [0x0000155c] [2018-10-30 01:08:14,733] - loaded entity-script:Room(4).
  INFO root [0x0000155c] [2018-10-30 01:08:14,733] - Baseapp::initializeEnd: started resmgr tick(60s)!
  INFO root [0x0000155c] [2018-10-30 01:08:14,733] - TelnetServer server is running on port 40000
  INFO root [0x0000155c] [2018-10-30 01:08:15,007] - ---- baseapp is running ----
 DEBUG root [0x0000155c] [2018-10-30 01:08:15,008] - Components::process(): Request for the process of identity...
  WARN root [0x0000155c] [2018-10-30 01:08:21,081] - EntityApp::checkTickPeriod: tick took 6073% (6.07 seconds)!
  INFO root [0x000027b4] [2018-10-30 01:16:40,648] - 
  INFO root [0x000027b4] [2018-10-30 01:16:40,648] - -----------------------------------------------------------------------------------------


  INFO root [0x000027b4] [2018-10-30 01:16:40,649] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [0x000027b4] [2018-10-30 01:16:40,649] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [0x000027b4] [2018-10-30 01:16:40,649] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [0x000027b4] [2018-10-30 01:16:40,664] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.107 ( 192.168.0.107:20015 )
  INFO root [0x000027b4] [2018-10-30 01:16:40,664] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.107:20015, SOMAXCONN=128.
  INFO root [0x000027b4] [2018-10-30 01:16:40,668] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.107 ( 192.168.0.107:52660 )
  INFO root [0x000027b4] [2018-10-30 01:16:40,669] - NetworkInterface::initialize(INTERNAL): address 192.168.0.107:52660, SOMAXCONN=128.
  INFO root [0x000027b4] [2018-10-30 01:16:40,669] - server-configs:
  INFO root [0x000027b4] [2018-10-30 01:16:40,669] - 	gameUpdateHertz : 10
  INFO root [0x000027b4] [2018-10-30 01:16:40,669] - 	entryScriptFile : kbemain
  INFO root [0x000027b4] [2018-10-30 01:16:40,669] - 	internalAddr : 192.168.0.107:52660
  INFO root [0x000027b4] [2018-10-30 01:16:40,669] - 	externalAddr : 192.168.0.107:20015
  INFO root [0x000027b4] [2018-10-30 01:16:40,669] - 	externalCustomAddr : 192.168.0.107
  INFO root [0x000027b4] [2018-10-30 01:16:40,669] - 	componentID : 7001
  INFO root [0x000027b4] [2018-10-30 01:16:42,361] - ---- baseapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: F9DFFB319FBADF35943ADF4D42C4718C. Config: Debug X86. Built: 15:53:31 Apr 29 2018. AppID: 7001. UID: 23333. PID: 9816 ----
  INFO root [0x000027b4] [2018-10-30 01:16:42,362] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [0x000027b4] [2018-10-30 01:16:42,362] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x000027b4] [2018-10-30 01:16:42,362] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x000027b4] [2018-10-30 01:16:42,485] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x000027b4] [2018-10-30 01:16:42,486] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x000027b4] [2018-10-30 01:16:42,486] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x000027b4] [2018-10-30 01:16:42,489] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x000027b4] [2018-10-30 01:16:42,489] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x000027b4] [2018-10-30 01:16:42,490] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x000027b4] [2018-10-30 01:16:42,490] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x000027b4] [2018-10-30 01:16:42,518] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x000027b4] [2018-10-30 01:16:42,545] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x000027b4] [2018-10-30 01:16:42,545] - Script::install(): KBExtra is successfully!
 DEBUG root [0x000027b4] [2018-10-30 01:16:42,567] - loaded entity-script:Account(1).
 DEBUG root [0x000027b4] [2018-10-30 01:16:42,568] - loaded entity-script:CheckName(2).
 DEBUG root [0x000027b4] [2018-10-30 01:16:42,573] - loaded entity-script:Halls(3).
 DEBUG root [0x000027b4] [2018-10-30 01:16:42,575] - loaded entity-script:Room(4).
  INFO root [0x000027b4] [2018-10-30 01:16:42,575] - Baseapp::initializeEnd: started resmgr tick(60s)!
  INFO root [0x000027b4] [2018-10-30 01:16:42,575] - TelnetServer server is running on port 40000
  INFO root [0x000027b4] [2018-10-30 01:16:42,852] - ---- baseapp is running ----
 DEBUG root [0x000027b4] [2018-10-30 01:16:42,853] - Components::process(): Request for the process of identity...
  WARN root [0x000027b4] [2018-10-30 01:16:48,936] - EntityApp::checkTickPeriod: tick took 6082% (6.08 seconds)!
  INFO root [0x000027b4] [2018-10-30 01:16:50,051] - Components::findComponents: find logger(1)...
  INFO root [0x000027b4] [2018-10-30 01:16:50,085] - Components::findComponents: found logger, addr:192.168.0.107:52658
  INFO root [0x000027b4] [2018-10-30 01:16:50,085] - Components::addComponent: reset orderLog, uid=23333!
  INFO root [0x000027b4] [2018-10-30 01:16:50,085] - Components::addComponent[logger], uid=23333, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x000027b4] [2018-10-30 01:16:50,086] - Components::findComponents: find dbmgr(2)...
  INFO root [0x000027b4] [2018-10-30 01:16:50,189] - Components::findComponents: found dbmgr, addr:192.168.0.107:52656
  INFO root [0x000027b4] [2018-10-30 01:16:50,190] - Components::addComponent: reset orderLog, uid=23333!
  INFO root [0x000027b4] [2018-10-30 01:16:50,190] - Components::addComponent[dbmgr], uid=23333, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x000027b4] [2018-10-30 01:16:50,191] - Components::findComponents: found dbmgr, addr:192.168.0.107:52656
  WARN root [0x000027b4] [2018-10-30 01:16:51,191] - Forwarding logs to logger[192.168.0.107:52658/0/0/0]...
 ERROR root [0x000027b4] [2018-10-30 01:17:55,034] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x000027b4] [2018-10-30 01:17:55,041] - The following logs sent to logger failed:
  WARN root [0x000027b4] [2018-10-30 01:17:55,041] - ==> [2018-10-30 01:17:55 034] TCPPacketReceiver::processPendingEvents(192.168.0.107:52658): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x000027b4] [2018-10-30 01:17:55,042] - ==> [2018-10-30 01:17:55 035] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x000027b4] [2018-10-30 01:17:55,084] - TCPPacketReceiver::processPendingEvents(192.168.0.107:52656): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x000027b4] [2018-10-30 01:17:55,085] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x000027b4] [2018-10-30 01:17:55,090] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [0x000027b4] [2018-10-30 01:17:55,091] - onBaseAppShutDown: state=0
  INFO root [0x000027b4] [2018-10-30 01:17:55,091] - Shutdowner::onShutdown: shutting down
S_INFO root [0x000027b4] [2018-10-30 01:17:55,091] - onBaseAppShutDown: state=1
  INFO root [0x000027b4] [2018-10-30 01:17:55,091] - Shutdowner::onShutdownEnd: shutting down
S_INFO root [0x000027b4] [2018-10-30 01:17:55,091] - onBaseAppShutDown: state=2
 DEBUG root [0x000027b4] [2018-10-30 01:17:55,099] - Halls::~Halls(): 2001
 DEBUG root [0x000027b4] [2018-10-30 01:17:55,100] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x000027b4] [2018-10-30 01:17:55,100] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x000027b4] [2018-10-30 01:17:55,100] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x000027b4] [2018-10-30 01:17:55,100] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x000027b4] [2018-10-30 01:17:55,101] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x000027b4] [2018-10-30 01:17:55,101] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x000027b4] [2018-10-30 01:17:55,101] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x000027b4] [2018-10-30 01:17:55,101] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x000027b4] [2018-10-30 01:17:55,111] - Script::uninstall(): is successfully!
 DEBUG root [0x000027b4] [2018-10-30 01:17:55,111] - ThreadPool::destroy(): starting size 2.
  INFO root [0x00001264] [2018-10-30 01:17:56,195] - 
  INFO root [0x00001264] [2018-10-30 01:17:56,197] - -----------------------------------------------------------------------------------------


  INFO root [0x00001264] [2018-10-30 01:17:56,197] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [0x00001264] [2018-10-30 01:17:56,198] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [0x00001264] [2018-10-30 01:17:56,198] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [0x00001264] [2018-10-30 01:17:56,202] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.107 ( 192.168.0.107:20015 )
  INFO root [0x00001264] [2018-10-30 01:17:56,203] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.107:20015, SOMAXCONN=128.
  INFO root [0x00001264] [2018-10-30 01:17:56,205] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.107 ( 192.168.0.107:52708 )
  INFO root [0x00001264] [2018-10-30 01:17:56,206] - NetworkInterface::initialize(INTERNAL): address 192.168.0.107:52708, SOMAXCONN=128.
  INFO root [0x00001264] [2018-10-30 01:17:56,206] - server-configs:
  INFO root [0x00001264] [2018-10-30 01:17:56,206] - 	gameUpdateHertz : 10
  INFO root [0x00001264] [2018-10-30 01:17:56,206] - 	entryScriptFile : kbemain
  INFO root [0x00001264] [2018-10-30 01:17:56,206] - 	internalAddr : 192.168.0.107:52708
  INFO root [0x00001264] [2018-10-30 01:17:56,206] - 	externalAddr : 192.168.0.107:20015
  INFO root [0x00001264] [2018-10-30 01:17:56,206] - 	externalCustomAddr : 192.168.0.107
  INFO root [0x00001264] [2018-10-30 01:17:56,206] - 	componentID : 7001
  INFO root [0x00001264] [2018-10-30 01:17:57,889] - ---- baseapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: F9DFFB319FBADF35943ADF4D42C4718C. Config: Debug X86. Built: 15:53:31 Apr 29 2018. AppID: 7001. UID: 23578. PID: 9700 ----
  INFO root [0x00001264] [2018-10-30 01:17:57,890] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [0x00001264] [2018-10-30 01:17:57,890] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00001264] [2018-10-30 01:17:57,891] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x00001264] [2018-10-30 01:17:58,014] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00001264] [2018-10-30 01:17:58,015] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x00001264] [2018-10-30 01:17:58,015] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x00001264] [2018-10-30 01:17:58,018] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x00001264] [2018-10-30 01:17:58,019] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x00001264] [2018-10-30 01:17:58,019] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x00001264] [2018-10-30 01:17:58,019] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x00001264] [2018-10-30 01:17:58,049] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x00001264] [2018-10-30 01:17:58,076] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x00001264] [2018-10-30 01:17:58,077] - Script::install(): KBExtra is successfully!
 DEBUG root [0x00001264] [2018-10-30 01:17:58,098] - loaded entity-script:Account(1).
 DEBUG root [0x00001264] [2018-10-30 01:17:58,099] - loaded entity-script:CheckName(2).
 DEBUG root [0x00001264] [2018-10-30 01:17:58,104] - loaded entity-script:Halls(3).
 DEBUG root [0x00001264] [2018-10-30 01:17:58,105] - loaded entity-script:Room(4).
  INFO root [0x00001264] [2018-10-30 01:17:58,106] - Baseapp::initializeEnd: started resmgr tick(60s)!
  INFO root [0x00001264] [2018-10-30 01:17:58,106] - TelnetServer server is running on port 40000
  INFO root [0x00001264] [2018-10-30 01:17:58,445] - ---- baseapp is running ----
 DEBUG root [0x00001264] [2018-10-30 01:17:58,445] - Components::process(): Request for the process of identity...
  WARN root [0x00001264] [2018-10-30 01:17:58,755] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20029, errorno=10048
  WARN root [0x00001264] [2018-10-30 01:18:04,830] - EntityApp::checkTickPeriod: tick took 6385% (6.39 seconds)!
  INFO root [0x00001264] [2018-10-30 01:18:05,899] - Components::findComponents: find logger(1)...
  INFO root [0x00001264] [2018-10-30 01:18:05,945] - Components::findComponents: found logger, addr:192.168.0.107:52704
  INFO root [0x00001264] [2018-10-30 01:18:05,945] - Components::addComponent: reset orderLog, uid=23578!
  INFO root [0x00001264] [2018-10-30 01:18:05,946] - Components::addComponent[logger], uid=23578, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00001264] [2018-10-30 01:18:05,948] - Components::findComponents: find dbmgr(2)...
  INFO root [0x00001264] [2018-10-30 01:18:06,047] - Components::findComponents: found dbmgr, addr:192.168.0.107:52705
  INFO root [0x00001264] [2018-10-30 01:18:06,048] - Components::addComponent: reset orderLog, uid=23578!
  INFO root [0x00001264] [2018-10-30 01:18:06,048] - Components::addComponent[dbmgr], uid=23578, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00001264] [2018-10-30 01:18:06,048] - Components::findComponents: found dbmgr, addr:192.168.0.107:52705
  WARN root [0x00001264] [2018-10-30 01:18:07,048] - Forwarding logs to logger[192.168.0.107:52704/0/0/0]...
 ERROR root [0x00001264] [2018-10-30 01:18:27,731] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x00001264] [2018-10-30 01:18:27,737] - The following logs sent to logger failed:
  WARN root [0x00001264] [2018-10-30 01:18:27,737] - ==> [2018-10-30 01:18:27 729] TCPPacketReceiver::processPendingEvents(192.168.0.107:52704): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00001264] [2018-10-30 01:18:27,737] - ==> [2018-10-30 01:18:27 732] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x00001264] [2018-10-30 01:18:27,778] - TCPPacketReceiver::processPendingEvents(192.168.0.107:52705): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00001264] [2018-10-30 01:18:27,779] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x00001264] [2018-10-30 01:18:27,783] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [0x00001264] [2018-10-30 01:18:27,786] - onBaseAppShutDown: state=0
  INFO root [0x00001264] [2018-10-30 01:18:27,786] - Shutdowner::onShutdown: shutting down
S_INFO root [0x00001264] [2018-10-30 01:18:27,786] - onBaseAppShutDown: state=1
  INFO root [0x00001264] [2018-10-30 01:18:27,786] - Shutdowner::onShutdownEnd: shutting down
S_INFO root [0x00001264] [2018-10-30 01:18:27,787] - onBaseAppShutDown: state=2
 DEBUG root [0x00001264] [2018-10-30 01:18:27,794] - Halls::~Halls(): 2001
 DEBUG root [0x00001264] [2018-10-30 01:18:27,795] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00001264] [2018-10-30 01:18:27,795] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x00001264] [2018-10-30 01:18:27,795] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x00001264] [2018-10-30 01:18:27,795] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x00001264] [2018-10-30 01:18:27,796] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x00001264] [2018-10-30 01:18:27,796] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x00001264] [2018-10-30 01:18:27,796] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x00001264] [2018-10-30 01:18:27,796] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x00001264] [2018-10-30 01:18:27,806] - Script::uninstall(): is successfully!
 DEBUG root [0x00001264] [2018-10-30 01:18:27,806] - ThreadPool::destroy(): starting size 2.
  INFO root [0x0000186c] [2018-10-30 01:18:28,878] - 
  INFO root [0x0000186c] [2018-10-30 01:18:28,878] - -----------------------------------------------------------------------------------------


  INFO root [0x0000186c] [2018-10-30 01:18:28,879] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [0x0000186c] [2018-10-30 01:18:28,879] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [0x0000186c] [2018-10-30 01:18:28,879] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [0x0000186c] [2018-10-30 01:18:28,884] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.107 ( 192.168.0.107:20015 )
  INFO root [0x0000186c] [2018-10-30 01:18:28,884] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.107:20015, SOMAXCONN=128.
  INFO root [0x0000186c] [2018-10-30 01:18:28,885] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.107 ( 192.168.0.107:52749 )
  INFO root [0x0000186c] [2018-10-30 01:18:28,885] - NetworkInterface::initialize(INTERNAL): address 192.168.0.107:52749, SOMAXCONN=128.
  INFO root [0x0000186c] [2018-10-30 01:18:28,885] - server-configs:
  INFO root [0x0000186c] [2018-10-30 01:18:28,885] - 	gameUpdateHertz : 10
  INFO root [0x0000186c] [2018-10-30 01:18:28,885] - 	entryScriptFile : kbemain
  INFO root [0x0000186c] [2018-10-30 01:18:28,885] - 	internalAddr : 192.168.0.107:52749
  INFO root [0x0000186c] [2018-10-30 01:18:28,886] - 	externalAddr : 192.168.0.107:20015
  INFO root [0x0000186c] [2018-10-30 01:18:28,886] - 	componentID : 7001
  INFO root [0x0000186c] [2018-10-30 01:18:30,579] - ---- baseapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: F9DFFB319FBADF35943ADF4D42C4718C. Config: Debug X86. Built: 15:53:31 Apr 29 2018. AppID: 7001. UID: 23686. PID: 10500 ----
  INFO root [0x0000186c] [2018-10-30 01:18:30,579] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [0x0000186c] [2018-10-30 01:18:30,579] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x0000186c] [2018-10-30 01:18:30,580] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x0000186c] [2018-10-30 01:18:30,703] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x0000186c] [2018-10-30 01:18:30,704] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x0000186c] [2018-10-30 01:18:30,704] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x0000186c] [2018-10-30 01:18:30,707] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x0000186c] [2018-10-30 01:18:30,707] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x0000186c] [2018-10-30 01:18:30,707] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x0000186c] [2018-10-30 01:18:30,708] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x0000186c] [2018-10-30 01:18:30,734] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x0000186c] [2018-10-30 01:18:30,761] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x0000186c] [2018-10-30 01:18:30,761] - Script::install(): KBExtra is successfully!
 DEBUG root [0x0000186c] [2018-10-30 01:18:30,781] - loaded entity-script:Account(1).
 DEBUG root [0x0000186c] [2018-10-30 01:18:30,782] - loaded entity-script:CheckName(2).
 DEBUG root [0x0000186c] [2018-10-30 01:18:30,787] - loaded entity-script:Halls(3).
 DEBUG root [0x0000186c] [2018-10-30 01:18:30,788] - loaded entity-script:Room(4).
  INFO root [0x0000186c] [2018-10-30 01:18:30,788] - Baseapp::initializeEnd: started resmgr tick(60s)!
  INFO root [0x0000186c] [2018-10-30 01:18:30,788] - TelnetServer server is running on port 40000
  INFO root [0x0000186c] [2018-10-30 01:18:31,064] - ---- baseapp is running ----
 DEBUG root [0x0000186c] [2018-10-30 01:18:31,064] - Components::process(): Request for the process of identity...
  WARN root [0x0000186c] [2018-10-30 01:18:37,161] - EntityApp::checkTickPeriod: tick took 6097% (6.10 seconds)!
  INFO root [0x0000186c] [2018-10-30 01:18:38,264] - Components::findComponents: find logger(1)...
  INFO root [0x0000186c] [2018-10-30 01:18:38,337] - Components::findComponents: found logger, addr:192.168.0.107:52743
  INFO root [0x0000186c] [2018-10-30 01:18:38,337] - Components::addComponent: reset orderLog, uid=23686!
  INFO root [0x0000186c] [2018-10-30 01:18:38,338] - Components::addComponent[logger], uid=23686, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x0000186c] [2018-10-30 01:18:38,338] - Components::findComponents: find dbmgr(2)...
  INFO root [0x0000186c] [2018-10-30 01:18:38,442] - Components::findComponents: found dbmgr, addr:192.168.0.107:52745
  INFO root [0x0000186c] [2018-10-30 01:18:38,443] - Components::addComponent: reset orderLog, uid=23686!
  INFO root [0x0000186c] [2018-10-30 01:18:38,443] - Components::addComponent[dbmgr], uid=23686, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x0000186c] [2018-10-30 01:18:38,444] - Components::findComponents: found dbmgr, addr:192.168.0.107:52745
  WARN root [0x0000186c] [2018-10-30 01:18:39,444] - EntityApp::checkTickPeriod: tick took 1280% (1.28 seconds)!
  WARN root [0x0000186c] [2018-10-30 01:18:39,446] - Forwarding logs to logger[192.168.0.107:52743/0/0/0]...
 ERROR root [0x0000186c] [2018-10-30 01:18:56,438] - Components::removeComponentByChannel: cellapp : 8001, Abnormal exit! errorno=10054
