  INFO root [0x000027b8] [2018-10-23 00:00:00,429] - Components::findComponents: find logger(1)...
  INFO root [0x000027b8] [2018-10-23 00:00:00,478] - Components::findComponents: found logger, addr:192.168.0.107:57710
  INFO root [0x000027b8] [2018-10-23 00:00:00,479] - Components::addComponent: reset orderLog, uid=32104!
  INFO root [0x000027b8] [2018-10-23 00:00:00,480] - Components::addComponent[logger], uid=32104, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x000027b8] [2018-10-23 00:00:00,482] - Components::findComponents: find dbmgr(2)...
  INFO root [0x000027b8] [2018-10-23 00:00:00,585] - Components::findComponents: found dbmgr, addr:192.168.0.107:57703
  INFO root [0x000027b8] [2018-10-23 00:00:00,585] - Components::addComponent: reset orderLog, uid=32104!
  INFO root [0x000027b8] [2018-10-23 00:00:00,586] - Components::addComponent[dbmgr], uid=32104, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x000027b8] [2018-10-23 00:00:00,586] - Components::findComponents: found dbmgr, addr:192.168.0.107:57703
  WARN root [0x000027b8] [2018-10-23 00:00:01,586] - Forwarding logs to logger[192.168.0.107:57710/0/0/0]...
 ERROR root [0x000027b8] [2018-10-23 00:07:16,846] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x000027b8] [2018-10-23 00:07:16,850] - The following logs sent to logger failed:
  WARN root [0x000027b8] [2018-10-23 00:07:16,851] - ==> [2018-10-23 00:07:16 845] TCPPacketReceiver::processPendingEvents(192.168.0.107:57710): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x000027b8] [2018-10-23 00:07:16,851] - ==> [2018-10-23 00:07:16 846] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x000027b8] [2018-10-23 00:07:16,897] - TCPPacketReceiver::processPendingEvents(192.168.0.107:57703): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x000027b8] [2018-10-23 00:07:16,898] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x000027b8] [2018-10-23 00:07:16,900] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [0x000027b8] [2018-10-23 00:07:16,901] - Shutdowner::onShutdown: shutting down
  INFO root [0x000027b8] [2018-10-23 00:07:16,901] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [0x000027b8] [2018-10-23 00:07:16,902] - EntityRef::destroyObjPool(): size 0.
 DEBUG root [0x000027b8] [2018-10-23 00:07:16,902] - Witness::destroyObjPool(): size 0.
 DEBUG root [0x000027b8] [2018-10-23 00:07:16,911] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x000027b8] [2018-10-23 00:07:16,912] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x000027b8] [2018-10-23 00:07:16,912] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x000027b8] [2018-10-23 00:07:16,912] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x000027b8] [2018-10-23 00:07:16,912] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x000027b8] [2018-10-23 00:07:16,912] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x000027b8] [2018-10-23 00:07:16,912] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x000027b8] [2018-10-23 00:07:16,912] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x000027b8] [2018-10-23 00:07:16,921] - Script::uninstall(): is successfully!
 DEBUG root [0x000027b8] [2018-10-23 00:07:16,921] - ThreadPool::destroy(): starting size 2.
  INFO root [0x00002318] [2018-10-23 00:07:18,055] - 
  INFO root [0x00002318] [2018-10-23 00:07:18,055] - -----------------------------------------------------------------------------------------


  INFO root [0x00002318] [2018-10-23 00:07:18,056] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [0x00002318] [2018-10-23 00:07:18,056] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [0x00002318] [2018-10-23 00:07:18,056] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [0x00002318] [2018-10-23 00:07:18,061] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.107 ( 192.168.0.107:57836 )
  INFO root [0x00002318] [2018-10-23 00:07:18,062] - NetworkInterface::initialize(INTERNAL): address 192.168.0.107:57836, SOMAXCONN=5.
  INFO root [0x00002318] [2018-10-23 00:07:18,062] - server-configs:
  INFO root [0x00002318] [2018-10-23 00:07:18,062] - 	gameUpdateHertz : 10
  INFO root [0x00002318] [2018-10-23 00:07:18,062] - 	defaultViewRadius : 80
  INFO root [0x00002318] [2018-10-23 00:07:18,062] - 	defaultViewHysteresisArea : 5
  INFO root [0x00002318] [2018-10-23 00:07:18,062] - 	entryScriptFile : kbemain
  INFO root [0x00002318] [2018-10-23 00:07:18,062] - 	internalAddr : 192.168.0.107:57836
  INFO root [0x00002318] [2018-10-23 00:07:18,062] - 	componentID : 8001
  INFO root [0x00002318] [2018-10-23 00:07:19,576] - ---- cellapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 85A70C5E64F896E0F1A60BF405B4EB07. Config: Debug X86. Built: 15:53:53 Apr 29 2018. AppID: 8001. UID: 796. PID: 6416 ----
  INFO root [0x00002318] [2018-10-23 00:07:19,577] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [0x00002318] [2018-10-23 00:07:19,578] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00002318] [2018-10-23 00:07:19,579] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x00002318] [2018-10-23 00:07:19,712] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00002318] [2018-10-23 00:07:19,712] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x00002318] [2018-10-23 00:07:19,713] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x00002318] [2018-10-23 00:07:19,716] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x00002318] [2018-10-23 00:07:19,716] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x00002318] [2018-10-23 00:07:19,716] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x00002318] [2018-10-23 00:07:19,717] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x00002318] [2018-10-23 00:07:19,746] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x00002318] [2018-10-23 00:07:19,776] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x00002318] [2018-10-23 00:07:19,777] - Script::install(): KBExtra is successfully!
 DEBUG root [0x00002318] [2018-10-23 00:07:19,799] - loaded entity-script:Account(1).
 DEBUG root [0x00002318] [2018-10-23 00:07:19,807] - loaded entity-script:Room(4).
  INFO root [0x00002318] [2018-10-23 00:07:19,807] - TelnetServer server is running on port 50000
  INFO root [0x00002318] [2018-10-23 00:07:20,117] - ---- cellapp is running ----
 DEBUG root [0x00002318] [2018-10-23 00:07:20,117] - Components::process(): Request for the process of identity...
  WARN root [0x00002318] [2018-10-23 00:07:26,200] - EntityApp::checkTickPeriod: tick took 6082% (6.08 seconds)!
  INFO root [0x00002318] [2018-10-23 00:07:27,218] - Components::findComponents: find logger(1)...
  INFO root [0x00002318] [2018-10-23 00:07:27,269] - Components::findComponents: found logger, addr:192.168.0.107:57834
  INFO root [0x00002318] [2018-10-23 00:07:27,269] - Components::addComponent: reset orderLog, uid=796!
  INFO root [0x00002318] [2018-10-23 00:07:27,270] - Components::addComponent[logger], uid=796, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00002318] [2018-10-23 00:07:27,270] - Components::findComponents: find dbmgr(2)...
  INFO root [0x00002318] [2018-10-23 00:07:27,370] - Components::findComponents: found dbmgr, addr:192.168.0.107:57830
  INFO root [0x00002318] [2018-10-23 00:07:27,370] - Components::addComponent: reset orderLog, uid=796!
  INFO root [0x00002318] [2018-10-23 00:07:27,370] - Components::addComponent[dbmgr], uid=796, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00002318] [2018-10-23 00:07:27,371] - Components::findComponents: found dbmgr, addr:192.168.0.107:57830
  WARN root [0x00002318] [2018-10-23 00:07:28,371] - EntityApp::checkTickPeriod: tick took 1253% (1.25 seconds)!
  WARN root [0x00002318] [2018-10-23 00:07:28,372] - Forwarding logs to logger[192.168.0.107:57834/0/0/0]...
 ERROR root [0x00002318] [2018-10-23 00:10:19,741] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x00002318] [2018-10-23 00:10:19,742] - The following logs sent to logger failed:
  WARN root [0x00002318] [2018-10-23 00:10:19,742] - ==> [2018-10-23 00:10:19 740] TCPPacketReceiver::processPendingEvents(192.168.0.107:57834): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00002318] [2018-10-23 00:10:19,743] - ==> [2018-10-23 00:10:19 741] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x00002318] [2018-10-23 00:10:19,792] - TCPPacketReceiver::processPendingEvents(192.168.0.107:57830): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00002318] [2018-10-23 00:10:19,792] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x00002318] [2018-10-23 00:10:19,798] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [0x00002318] [2018-10-23 00:10:19,798] - Shutdowner::onShutdown: shutting down
  INFO root [0x00002318] [2018-10-23 00:10:19,798] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [0x00002318] [2018-10-23 00:10:19,798] - EntityRef::destroyObjPool(): size 0.
 DEBUG root [0x00002318] [2018-10-23 00:10:19,799] - Witness::destroyObjPool(): size 0.
 DEBUG root [0x00002318] [2018-10-23 00:10:19,808] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00002318] [2018-10-23 00:10:19,808] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x00002318] [2018-10-23 00:10:19,808] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x00002318] [2018-10-23 00:10:19,808] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x00002318] [2018-10-23 00:10:19,808] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x00002318] [2018-10-23 00:10:19,808] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x00002318] [2018-10-23 00:10:19,808] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x00002318] [2018-10-23 00:10:19,808] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x00002318] [2018-10-23 00:10:19,817] - Script::uninstall(): is successfully!
 DEBUG root [0x00002318] [2018-10-23 00:10:19,818] - ThreadPool::destroy(): starting size 2.
  INFO root [0x000023a8] [2018-10-23 00:10:20,961] - 
  INFO root [0x000023a8] [2018-10-23 00:10:20,962] - -----------------------------------------------------------------------------------------


  INFO root [0x000023a8] [2018-10-23 00:10:20,962] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [0x000023a8] [2018-10-23 00:10:20,962] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [0x000023a8] [2018-10-23 00:10:20,963] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [0x000023a8] [2018-10-23 00:10:20,970] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.107 ( 192.168.0.107:57912 )
  INFO root [0x000023a8] [2018-10-23 00:10:20,970] - NetworkInterface::initialize(INTERNAL): address 192.168.0.107:57912, SOMAXCONN=5.
  INFO root [0x000023a8] [2018-10-23 00:10:20,970] - server-configs:
  INFO root [0x000023a8] [2018-10-23 00:10:20,970] - 	gameUpdateHertz : 10
  INFO root [0x000023a8] [2018-10-23 00:10:20,971] - 	defaultViewRadius : 80
  INFO root [0x000023a8] [2018-10-23 00:10:20,971] - 	defaultViewHysteresisArea : 5
  INFO root [0x000023a8] [2018-10-23 00:10:20,971] - 	entryScriptFile : kbemain
  INFO root [0x000023a8] [2018-10-23 00:10:20,971] - 	internalAddr : 192.168.0.107:57912
  INFO root [0x000023a8] [2018-10-23 00:10:20,971] - 	componentID : 8001
  INFO root [0x000023a8] [2018-10-23 00:10:22,481] - ---- cellapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 85A70C5E64F896E0F1A60BF405B4EB07. Config: Debug X86. Built: 15:53:53 Apr 29 2018. AppID: 8001. UID: 1394. PID: 5560 ----
  INFO root [0x000023a8] [2018-10-23 00:10:22,483] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [0x000023a8] [2018-10-23 00:10:22,483] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x000023a8] [2018-10-23 00:10:22,484] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x000023a8] [2018-10-23 00:10:22,624] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x000023a8] [2018-10-23 00:10:22,624] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x000023a8] [2018-10-23 00:10:22,625] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x000023a8] [2018-10-23 00:10:22,628] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x000023a8] [2018-10-23 00:10:22,628] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x000023a8] [2018-10-23 00:10:22,628] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x000023a8] [2018-10-23 00:10:22,628] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x000023a8] [2018-10-23 00:10:22,659] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x000023a8] [2018-10-23 00:10:22,690] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x000023a8] [2018-10-23 00:10:22,690] - Script::install(): KBExtra is successfully!
 DEBUG root [0x000023a8] [2018-10-23 00:10:22,712] - loaded entity-script:Account(1).
 DEBUG root [0x000023a8] [2018-10-23 00:10:22,720] - loaded entity-script:Room(4).
  INFO root [0x000023a8] [2018-10-23 00:10:22,720] - TelnetServer server is running on port 50000
  INFO root [0x000023a8] [2018-10-23 00:10:23,112] - ---- cellapp is running ----
 DEBUG root [0x000023a8] [2018-10-23 00:10:23,113] - Components::process(): Request for the process of identity...
  WARN root [0x000023a8] [2018-10-23 00:10:29,203] - EntityApp::checkTickPeriod: tick took 6090% (6.09 seconds)!
  INFO root [0x000023a8] [2018-10-23 00:10:30,266] - Components::findComponents: find logger(1)...
  INFO root [0x000023a8] [2018-10-23 00:10:30,360] - Components::findComponents: found logger, addr:192.168.0.107:57906
  INFO root [0x000023a8] [2018-10-23 00:10:30,360] - Components::addComponent: reset orderLog, uid=1394!
  INFO root [0x000023a8] [2018-10-23 00:10:30,361] - Components::addComponent[logger], uid=1394, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x000023a8] [2018-10-23 00:10:30,362] - Components::findComponents: find dbmgr(2)...
  INFO root [0x000023a8] [2018-10-23 00:10:30,465] - Components::findComponents: found dbmgr, addr:192.168.0.107:57904
  INFO root [0x000023a8] [2018-10-23 00:10:30,465] - Components::addComponent: reset orderLog, uid=1394!
  INFO root [0x000023a8] [2018-10-23 00:10:30,465] - Components::addComponent[dbmgr], uid=1394, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x000023a8] [2018-10-23 00:10:30,466] - Components::findComponents: found dbmgr, addr:192.168.0.107:57904
  WARN root [0x000023a8] [2018-10-23 00:10:31,466] - Forwarding logs to logger[192.168.0.107:57906/0/0/0]...
