  INFO root [0x00001cdc] [2018-10-29 23:19:24,595] - 
  INFO root [0x00001cdc] [2018-10-29 23:19:24,676] - -----------------------------------------------------------------------------------------


  INFO root [0x00001cdc] [2018-10-29 23:19:26,503] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [0x00001cdc] [2018-10-29 23:19:26,505] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [0x00001cdc] [2018-10-29 23:19:26,506] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [0x00001cdc] [2018-10-29 23:19:27,538] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.107 ( 192.168.0.107:62855 )
  INFO root [0x00001cdc] [2018-10-29 23:19:27,677] - NetworkInterface::initialize(INTERNAL): address 192.168.0.107:62855, SOMAXCONN=5.
  INFO root [0x00001cdc] [2018-10-29 23:19:27,677] - server-configs:
  INFO root [0x00001cdc] [2018-10-29 23:19:27,677] - 	gameUpdateHertz : 10
  INFO root [0x00001cdc] [2018-10-29 23:19:27,777] - 	defaultViewRadius : 80
  INFO root [0x00001cdc] [2018-10-29 23:19:27,778] - 	defaultViewHysteresisArea : 5
  INFO root [0x00001cdc] [2018-10-29 23:19:27,778] - 	entryScriptFile : kbemain
  INFO root [0x00001cdc] [2018-10-29 23:19:27,778] - 	internalAddr : 192.168.0.107:62855
  INFO root [0x00001cdc] [2018-10-29 23:19:27,779] - 	componentID : 8001
  INFO root [0x00001cdc] [2018-10-29 23:19:28,716] - Components::findLogger: found logger, addr:192.168.0.107:62849
  INFO root [0x00001cdc] [2018-10-29 23:19:28,717] - Components::addComponent: reset orderLog, uid=285!
  INFO root [0x00001cdc] [2018-10-29 23:19:28,840] - Components::addComponent[logger], uid=285, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00001cdc] [2018-10-29 23:19:29,283] - ---- cellapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 85A70C5E64F896E0F1A60BF405B4EB07. Config: Debug X86. Built: 15:53:53 Apr 29 2018. AppID: 8001. UID: 285. PID: 7404 ----
  INFO root [0x00001cdc] [2018-10-29 23:19:29,284] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [0x00001cdc] [2018-10-29 23:19:29,319] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00001cdc] [2018-10-29 23:19:29,336] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x00001cdc] [2018-10-29 23:19:35,953] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00001cdc] [2018-10-29 23:19:36,068] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x00001cdc] [2018-10-29 23:19:36,256] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x00001cdc] [2018-10-29 23:19:37,060] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x00001cdc] [2018-10-29 23:19:37,133] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x00001cdc] [2018-10-29 23:19:37,197] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x00001cdc] [2018-10-29 23:19:37,246] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x00001cdc] [2018-10-29 23:19:37,931] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x00001cdc] [2018-10-29 23:19:39,410] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x00001cdc] [2018-10-29 23:19:39,411] - Script::install(): KBExtra is successfully!
 DEBUG root [0x00001cdc] [2018-10-29 23:19:40,954] - loaded entity-script:Account(1).
 DEBUG root [0x00001cdc] [2018-10-29 23:19:41,163] - loaded entity-script:Room(4).
  INFO root [0x00001cdc] [2018-10-29 23:19:41,200] - TelnetServer server is running on port 50000
  INFO root [0x00001cdc] [2018-10-29 23:19:41,685] - ---- cellapp is running ----
 DEBUG root [0x00001cdc] [2018-10-29 23:19:41,686] - Components::process(): Request for the process of identity...
  WARN root [0x00001cdc] [2018-10-29 23:19:47,890] - Forwarding logs to logger[192.168.0.107:62849/0/0/0]...
 ERROR root [0x00001cdc] [2018-10-29 23:36:02,163] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x00001cdc] [2018-10-29 23:36:02,169] - The following logs sent to logger failed:
  WARN root [0x00001cdc] [2018-10-29 23:36:02,169] - ==> [2018-10-29 23:36:02 163] TCPPacketReceiver::processPendingEvents(192.168.0.107:62849): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00001cdc] [2018-10-29 23:36:02,169] - ==> [2018-10-29 23:36:02 164] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x00001cdc] [2018-10-29 23:36:02,209] - TCPPacketReceiver::processPendingEvents(192.168.0.107:62851): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00001cdc] [2018-10-29 23:36:02,210] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x00001cdc] [2018-10-29 23:36:02,219] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [0x00001cdc] [2018-10-29 23:36:02,219] - Shutdowner::onShutdown: shutting down
  INFO root [0x00001cdc] [2018-10-29 23:36:02,219] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [0x00001cdc] [2018-10-29 23:36:02,337] - EntityRef::destroyObjPool(): size 0.
 DEBUG root [0x00001cdc] [2018-10-29 23:36:02,337] - Witness::destroyObjPool(): size 0.
 DEBUG root [0x00001cdc] [2018-10-29 23:36:02,393] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00001cdc] [2018-10-29 23:36:02,393] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x00001cdc] [2018-10-29 23:36:02,393] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x00001cdc] [2018-10-29 23:36:02,393] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x00001cdc] [2018-10-29 23:36:02,393] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x00001cdc] [2018-10-29 23:36:02,393] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x00001cdc] [2018-10-29 23:36:02,393] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x00001cdc] [2018-10-29 23:36:02,393] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x00000e70] [2018-10-29 23:36:03,306] - 
  INFO root [0x00000e70] [2018-10-29 23:36:03,306] - -----------------------------------------------------------------------------------------


  INFO root [0x00000e70] [2018-10-29 23:36:03,306] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [0x00000e70] [2018-10-29 23:36:03,307] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [0x00000e70] [2018-10-29 23:36:03,307] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [0x00000e70] [2018-10-29 23:36:03,309] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.107 ( 192.168.0.107:63162 )
  INFO root [0x00000e70] [2018-10-29 23:36:03,309] - NetworkInterface::initialize(INTERNAL): address 192.168.0.107:63162, SOMAXCONN=5.
  INFO root [0x00000e70] [2018-10-29 23:36:03,309] - server-configs:
  INFO root [0x00000e70] [2018-10-29 23:36:03,309] - 	gameUpdateHertz : 10
  INFO root [0x00000e70] [2018-10-29 23:36:03,309] - 	defaultViewRadius : 80
  INFO root [0x00000e70] [2018-10-29 23:36:03,310] - 	defaultViewHysteresisArea : 5
  INFO root [0x00000e70] [2018-10-29 23:36:03,310] - 	entryScriptFile : kbemain
  INFO root [0x00000e70] [2018-10-29 23:36:03,310] - 	internalAddr : 192.168.0.107:63162
  INFO root [0x00000e70] [2018-10-29 23:36:03,310] - 	componentID : 8001
  INFO root [0x00000e70] [2018-10-29 23:36:04,823] - ---- cellapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 85A70C5E64F896E0F1A60BF405B4EB07. Config: Debug X86. Built: 15:53:53 Apr 29 2018. AppID: 8001. UID: 3619. PID: 3448 ----
  INFO root [0x00000e70] [2018-10-29 23:36:04,824] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [0x00000e70] [2018-10-29 23:36:04,824] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00000e70] [2018-10-29 23:36:04,825] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x00000e70] [2018-10-29 23:36:04,975] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00000e70] [2018-10-29 23:36:04,975] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x00000e70] [2018-10-29 23:36:04,975] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x00000e70] [2018-10-29 23:36:04,978] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x00000e70] [2018-10-29 23:36:04,979] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x00000e70] [2018-10-29 23:36:04,979] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x00000e70] [2018-10-29 23:36:04,979] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x00000e70] [2018-10-29 23:36:05,006] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x00000e70] [2018-10-29 23:36:05,033] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x00000e70] [2018-10-29 23:36:05,034] - Script::install(): KBExtra is successfully!
 DEBUG root [0x00000e70] [2018-10-29 23:36:05,054] - loaded entity-script:Account(1).
 DEBUG root [0x00000e70] [2018-10-29 23:36:05,061] - loaded entity-script:Room(4).
  INFO root [0x00000e70] [2018-10-29 23:36:05,062] - TelnetServer server is running on port 50000
  INFO root [0x00000e70] [2018-10-29 23:36:05,365] - ---- cellapp is running ----
 DEBUG root [0x00000e70] [2018-10-29 23:36:05,365] - Components::process(): Request for the process of identity...
  WARN root [0x00000e70] [2018-10-29 23:36:11,442] - EntityApp::checkTickPeriod: tick took 6077% (6.08 seconds)!
  INFO root [0x00000e70] [2018-10-29 23:36:12,465] - Components::findComponents: find logger(1)...
  INFO root [0x00000e70] [2018-10-29 23:36:12,528] - Components::findComponents: found logger, addr:192.168.0.107:63160
  INFO root [0x00000e70] [2018-10-29 23:36:12,529] - Components::addComponent: reset orderLog, uid=3619!
  INFO root [0x00000e70] [2018-10-29 23:36:12,529] - Components::addComponent[logger], uid=3619, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00000e70] [2018-10-29 23:36:12,531] - Components::findComponents: find dbmgr(2)...
  INFO root [0x00000e70] [2018-10-29 23:36:12,633] - Components::findComponents: found dbmgr, addr:192.168.0.107:63155
  INFO root [0x00000e70] [2018-10-29 23:36:12,633] - Components::addComponent: reset orderLog, uid=3619!
  INFO root [0x00000e70] [2018-10-29 23:36:12,634] - Components::addComponent[dbmgr], uid=3619, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00000e70] [2018-10-29 23:36:12,634] - Components::findComponents: found dbmgr, addr:192.168.0.107:63155
  WARN root [0x00000e70] [2018-10-29 23:36:13,634] - EntityApp::checkTickPeriod: tick took 1269% (1.27 seconds)!
  WARN root [0x00000e70] [2018-10-29 23:36:13,636] - Forwarding logs to logger[192.168.0.107:63160/0/0/0]...
 ERROR root [0x00000e70] [2018-10-29 23:38:15,628] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x00000e70] [2018-10-29 23:38:15,632] - The following logs sent to logger failed:
  WARN root [0x00000e70] [2018-10-29 23:38:15,633] - ==> [2018-10-29 23:38:15 628] TCPPacketReceiver::processPendingEvents(192.168.0.107:63160): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00000e70] [2018-10-29 23:38:15,633] - ==> [2018-10-29 23:38:15 629] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x00000e70] [2018-10-29 23:38:15,674] - TCPPacketReceiver::processPendingEvents(192.168.0.107:63155): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00000e70] [2018-10-29 23:38:15,675] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x00000e70] [2018-10-29 23:38:15,677] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [0x00000e70] [2018-10-29 23:38:15,679] - Shutdowner::onShutdown: shutting down
  INFO root [0x00000e70] [2018-10-29 23:38:15,679] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [0x00000e70] [2018-10-29 23:38:15,680] - EntityRef::destroyObjPool(): size 0.
 DEBUG root [0x00000e70] [2018-10-29 23:38:15,680] - Witness::destroyObjPool(): size 0.
 DEBUG root [0x00000e70] [2018-10-29 23:38:15,688] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00000e70] [2018-10-29 23:38:15,688] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x00000e70] [2018-10-29 23:38:15,688] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x00000e70] [2018-10-29 23:38:15,689] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x00000e70] [2018-10-29 23:38:15,689] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x00000e70] [2018-10-29 23:38:15,689] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x00000e70] [2018-10-29 23:38:15,689] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x00000e70] [2018-10-29 23:38:15,689] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x00000e70] [2018-10-29 23:38:15,698] - Script::uninstall(): is successfully!
 DEBUG root [0x00000e70] [2018-10-29 23:38:15,698] - ThreadPool::destroy(): starting size 2.
  INFO root [0x00001820] [2018-10-29 23:38:16,775] - 
  INFO root [0x00001820] [2018-10-29 23:38:16,776] - -----------------------------------------------------------------------------------------


  INFO root [0x00001820] [2018-10-29 23:38:16,777] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [0x00001820] [2018-10-29 23:38:16,777] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [0x00001820] [2018-10-29 23:38:16,777] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [0x00001820] [2018-10-29 23:38:16,785] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.107 ( 192.168.0.107:63212 )
  INFO root [0x00001820] [2018-10-29 23:38:16,786] - NetworkInterface::initialize(INTERNAL): address 192.168.0.107:63212, SOMAXCONN=5.
  INFO root [0x00001820] [2018-10-29 23:38:16,786] - server-configs:
  INFO root [0x00001820] [2018-10-29 23:38:16,786] - 	gameUpdateHertz : 10
  INFO root [0x00001820] [2018-10-29 23:38:16,786] - 	defaultViewRadius : 80
  INFO root [0x00001820] [2018-10-29 23:38:16,786] - 	defaultViewHysteresisArea : 5
  INFO root [0x00001820] [2018-10-29 23:38:16,786] - 	entryScriptFile : kbemain
  INFO root [0x00001820] [2018-10-29 23:38:16,786] - 	internalAddr : 192.168.0.107:63212
  INFO root [0x00001820] [2018-10-29 23:38:16,787] - 	componentID : 8001
  WARN root [0x00001820] [2018-10-29 23:38:17,097] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20278, errorno=10048
  INFO root [0x00001820] [2018-10-29 23:38:17,101] - ---- cellapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 85A70C5E64F896E0F1A60BF405B4EB07. Config: Debug X86. Built: 15:53:53 Apr 29 2018. AppID: 8001. UID: 4053. PID: 5188 ----
  INFO root [0x00001820] [2018-10-29 23:38:17,101] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [0x00001820] [2018-10-29 23:38:17,101] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00001820] [2018-10-29 23:38:17,101] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x00001820] [2018-10-29 23:38:17,227] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00001820] [2018-10-29 23:38:17,227] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x00001820] [2018-10-29 23:38:17,228] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x00001820] [2018-10-29 23:38:17,231] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x00001820] [2018-10-29 23:38:17,231] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x00001820] [2018-10-29 23:38:17,231] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x00001820] [2018-10-29 23:38:17,231] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x00001820] [2018-10-29 23:38:17,258] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x00001820] [2018-10-29 23:38:17,286] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x00001820] [2018-10-29 23:38:17,286] - Script::install(): KBExtra is successfully!
 DEBUG root [0x00001820] [2018-10-29 23:38:17,306] - loaded entity-script:Account(1).
 DEBUG root [0x00001820] [2018-10-29 23:38:17,314] - loaded entity-script:Room(4).
  INFO root [0x00001820] [2018-10-29 23:38:17,314] - TelnetServer server is running on port 50000
  INFO root [0x00001820] [2018-10-29 23:38:17,605] - ---- cellapp is running ----
 DEBUG root [0x00001820] [2018-10-29 23:38:17,605] - Components::process(): Request for the process of identity...
  WARN root [0x00001820] [2018-10-29 23:38:23,671] - EntityApp::checkTickPeriod: tick took 6066% (6.07 seconds)!
  INFO root [0x00001820] [2018-10-29 23:38:24,706] - Components::findComponents: find logger(1)...
  INFO root [0x00001820] [2018-10-29 23:38:24,721] - Components::findComponents: found logger, addr:192.168.0.107:63206
  INFO root [0x00001820] [2018-10-29 23:38:24,722] - Components::addComponent: reset orderLog, uid=4053!
  INFO root [0x00001820] [2018-10-29 23:38:24,722] - Components::addComponent[logger], uid=4053, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00001820] [2018-10-29 23:38:24,724] - Components::findComponents: find dbmgr(2)...
  INFO root [0x00001820] [2018-10-29 23:38:24,823] - Components::findComponents: found dbmgr, addr:192.168.0.107:63210
  INFO root [0x00001820] [2018-10-29 23:38:24,823] - Components::addComponent: reset orderLog, uid=4053!
  INFO root [0x00001820] [2018-10-29 23:38:24,823] - Components::addComponent[dbmgr], uid=4053, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00001820] [2018-10-29 23:38:24,823] - Components::findComponents: found dbmgr, addr:192.168.0.107:63210
  WARN root [0x00001820] [2018-10-29 23:38:25,823] - EntityApp::checkTickPeriod: tick took 1217% (1.22 seconds)!
  WARN root [0x00001820] [2018-10-29 23:38:25,824] - Forwarding logs to logger[192.168.0.107:63206/0/0/0]...
 ERROR root [0x00001820] [2018-10-29 23:42:16,739] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x00001820] [2018-10-29 23:42:16,745] - The following logs sent to logger failed:
  WARN root [0x00001820] [2018-10-29 23:42:16,746] - ==> [2018-10-29 23:42:16 737] TCPPacketReceiver::processPendingEvents(192.168.0.107:63206): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00001820] [2018-10-29 23:42:16,746] - ==> [2018-10-29 23:42:16 739] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x00001820] [2018-10-29 23:42:16,786] - TCPPacketReceiver::processPendingEvents(192.168.0.107:63210): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00001820] [2018-10-29 23:42:16,789] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x00001820] [2018-10-29 23:42:16,791] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [0x00001820] [2018-10-29 23:42:16,791] - Shutdowner::onShutdown: shutting down
  INFO root [0x00001820] [2018-10-29 23:42:16,791] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [0x00001820] [2018-10-29 23:42:16,792] - EntityRef::destroyObjPool(): size 0.
 DEBUG root [0x00001820] [2018-10-29 23:42:16,792] - Witness::destroyObjPool(): size 0.
 DEBUG root [0x00001820] [2018-10-29 23:42:16,801] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00001820] [2018-10-29 23:42:16,801] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x00001820] [2018-10-29 23:42:16,801] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x00001820] [2018-10-29 23:42:16,801] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x00001820] [2018-10-29 23:42:16,801] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x00001820] [2018-10-29 23:42:16,801] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x00001820] [2018-10-29 23:42:16,801] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x00001820] [2018-10-29 23:42:16,801] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x00001820] [2018-10-29 23:42:16,810] - Script::uninstall(): is successfully!
 DEBUG root [0x00001820] [2018-10-29 23:42:16,810] - ThreadPool::destroy(): starting size 2.
  INFO root [0x00000868] [2018-10-29 23:42:17,859] - 
  INFO root [0x00000868] [2018-10-29 23:42:17,859] - -----------------------------------------------------------------------------------------


  INFO root [0x00000868] [2018-10-29 23:42:17,860] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [0x00000868] [2018-10-29 23:42:17,860] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [0x00000868] [2018-10-29 23:42:17,860] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [0x00000868] [2018-10-29 23:42:17,863] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.107 ( 192.168.0.107:63310 )
  INFO root [0x00000868] [2018-10-29 23:42:17,863] - NetworkInterface::initialize(INTERNAL): address 192.168.0.107:63310, SOMAXCONN=5.
  INFO root [0x00000868] [2018-10-29 23:42:17,863] - server-configs:
  INFO root [0x00000868] [2018-10-29 23:42:17,864] - 	gameUpdateHertz : 10
  INFO root [0x00000868] [2018-10-29 23:42:17,864] - 	defaultViewRadius : 80
  INFO root [0x00000868] [2018-10-29 23:42:17,864] - 	defaultViewHysteresisArea : 5
  INFO root [0x00000868] [2018-10-29 23:42:17,864] - 	entryScriptFile : kbemain
  INFO root [0x00000868] [2018-10-29 23:42:17,864] - 	internalAddr : 192.168.0.107:63310
  INFO root [0x00000868] [2018-10-29 23:42:17,864] - 	componentID : 8001
  INFO root [0x00000868] [2018-10-29 23:42:19,379] - ---- cellapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 85A70C5E64F896E0F1A60BF405B4EB07. Config: Debug X86. Built: 15:53:53 Apr 29 2018. AppID: 8001. UID: 4840. PID: 5364 ----
  INFO root [0x00000868] [2018-10-29 23:42:19,381] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [0x00000868] [2018-10-29 23:42:19,381] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00000868] [2018-10-29 23:42:19,382] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x00000868] [2018-10-29 23:42:19,548] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00000868] [2018-10-29 23:42:19,549] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x00000868] [2018-10-29 23:42:19,549] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x00000868] [2018-10-29 23:42:19,552] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x00000868] [2018-10-29 23:42:19,552] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x00000868] [2018-10-29 23:42:19,552] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x00000868] [2018-10-29 23:42:19,553] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x00000868] [2018-10-29 23:42:19,580] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x00000868] [2018-10-29 23:42:19,607] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x00000868] [2018-10-29 23:42:19,607] - Script::install(): KBExtra is successfully!
 DEBUG root [0x00000868] [2018-10-29 23:42:19,627] - loaded entity-script:Account(1).
 DEBUG root [0x00000868] [2018-10-29 23:42:19,635] - loaded entity-script:Room(4).
  INFO root [0x00000868] [2018-10-29 23:42:19,635] - TelnetServer server is running on port 50000
  INFO root [0x00000868] [2018-10-29 23:42:19,918] - ---- cellapp is running ----
 DEBUG root [0x00000868] [2018-10-29 23:42:19,919] - Components::process(): Request for the process of identity...
  INFO root [0x00001864] [2018-10-29 23:42:25,164] - 
  INFO root [0x00001864] [2018-10-29 23:42:25,164] - -----------------------------------------------------------------------------------------


  INFO root [0x00001864] [2018-10-29 23:42:25,165] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [0x00001864] [2018-10-29 23:42:25,165] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [0x00001864] [2018-10-29 23:42:25,165] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [0x00001864] [2018-10-29 23:42:25,170] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.107 ( 192.168.0.107:63323 )
  INFO root [0x00001864] [2018-10-29 23:42:25,170] - NetworkInterface::initialize(INTERNAL): address 192.168.0.107:63323, SOMAXCONN=5.
  INFO root [0x00001864] [2018-10-29 23:42:25,171] - server-configs:
  INFO root [0x00001864] [2018-10-29 23:42:25,171] - 	gameUpdateHertz : 10
  INFO root [0x00001864] [2018-10-29 23:42:25,171] - 	defaultViewRadius : 80
  INFO root [0x00001864] [2018-10-29 23:42:25,171] - 	defaultViewHysteresisArea : 5
  INFO root [0x00001864] [2018-10-29 23:42:25,171] - 	entryScriptFile : kbemain
  INFO root [0x00001864] [2018-10-29 23:42:25,171] - 	internalAddr : 192.168.0.107:63323
  INFO root [0x00001864] [2018-10-29 23:42:25,171] - 	componentID : 8001
  WARN root [0x00001864] [2018-10-29 23:42:25,482] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20195, errorno=10048
  INFO root [0x00001864] [2018-10-29 23:42:25,486] - ---- cellapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 85A70C5E64F896E0F1A60BF405B4EB07. Config: Debug X86. Built: 15:53:53 Apr 29 2018. AppID: 8001. UID: 4863. PID: 6296 ----
  INFO root [0x00001864] [2018-10-29 23:42:25,486] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [0x00001864] [2018-10-29 23:42:25,486] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00001864] [2018-10-29 23:42:25,486] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x00001864] [2018-10-29 23:42:25,616] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00001864] [2018-10-29 23:42:25,616] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x00001864] [2018-10-29 23:42:25,616] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x00001864] [2018-10-29 23:42:25,619] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x00001864] [2018-10-29 23:42:25,619] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x00001864] [2018-10-29 23:42:25,620] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x00001864] [2018-10-29 23:42:25,620] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x00001864] [2018-10-29 23:42:25,648] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x00001864] [2018-10-29 23:42:25,677] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x00001864] [2018-10-29 23:42:25,677] - Script::install(): KBExtra is successfully!
 DEBUG root [0x00001864] [2018-10-29 23:42:25,697] - loaded entity-script:Account(1).
 DEBUG root [0x00001864] [2018-10-29 23:42:25,705] - loaded entity-script:Room(4).
  INFO root [0x00001864] [2018-10-29 23:42:25,706] - TelnetServer server is running on port 50000
  INFO root [0x00001864] [2018-10-29 23:42:25,987] - ---- cellapp is running ----
 DEBUG root [0x00001864] [2018-10-29 23:42:25,987] - Components::process(): Request for the process of identity...
  WARN root [0x00001864] [2018-10-29 23:42:32,031] - EntityApp::checkTickPeriod: tick took 6044% (6.04 seconds)!
  INFO root [0x00001864] [2018-10-29 23:42:33,068] - Components::findComponents: find logger(1)...
  INFO root [0x00001864] [2018-10-29 23:42:33,106] - Components::findComponents: found logger, addr:192.168.0.107:63325
  INFO root [0x00001864] [2018-10-29 23:42:33,107] - Components::addComponent: reset orderLog, uid=4863!
  INFO root [0x00001864] [2018-10-29 23:42:33,107] - Components::addComponent[logger], uid=4863, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00001864] [2018-10-29 23:42:33,110] - Components::findComponents: find dbmgr(2)...
  INFO root [0x00001864] [2018-10-29 23:42:33,210] - Components::findComponents: found dbmgr, addr:192.168.0.107:63320
  INFO root [0x00001864] [2018-10-29 23:42:33,211] - Components::addComponent: reset orderLog, uid=4863!
  INFO root [0x00001864] [2018-10-29 23:42:33,212] - Components::addComponent[dbmgr], uid=4863, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00001864] [2018-10-29 23:42:33,212] - Components::findComponents: found dbmgr, addr:192.168.0.107:63320
  WARN root [0x00001864] [2018-10-29 23:42:34,212] - Forwarding logs to logger[192.168.0.107:63325/0/0/0]...
 ERROR root [0x00001864] [2018-10-29 23:42:41,317] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x00001864] [2018-10-29 23:42:41,324] - The following logs sent to logger failed:
  WARN root [0x00001864] [2018-10-29 23:42:41,325] - ==> [2018-10-29 23:42:41 315] TCPPacketReceiver::processPendingEvents(192.168.0.107:63325): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00001864] [2018-10-29 23:42:41,325] - ==> [2018-10-29 23:42:41 317] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x00001864] [2018-10-29 23:42:41,365] - TCPPacketReceiver::processPendingEvents(192.168.0.107:63320): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00001864] [2018-10-29 23:42:41,367] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x00001864] [2018-10-29 23:42:41,372] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [0x00001864] [2018-10-29 23:42:41,374] - Shutdowner::onShutdown: shutting down
  INFO root [0x00001864] [2018-10-29 23:42:41,374] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [0x00001864] [2018-10-29 23:42:41,374] - EntityRef::destroyObjPool(): size 0.
 DEBUG root [0x00001864] [2018-10-29 23:42:41,374] - Witness::destroyObjPool(): size 0.
 DEBUG root [0x00001864] [2018-10-29 23:42:41,383] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00001864] [2018-10-29 23:42:41,383] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x00001864] [2018-10-29 23:42:41,383] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x00001864] [2018-10-29 23:42:41,383] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x00001864] [2018-10-29 23:42:41,383] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x00001864] [2018-10-29 23:42:41,383] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x00001864] [2018-10-29 23:42:41,383] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x00001864] [2018-10-29 23:42:41,383] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x00001864] [2018-10-29 23:42:41,393] - Script::uninstall(): is successfully!
 DEBUG root [0x00001864] [2018-10-29 23:42:41,393] - ThreadPool::destroy(): starting size 2.
  INFO root [0x000027a0] [2018-10-29 23:55:58,971] - 
  INFO root [0x000027a0] [2018-10-29 23:55:58,972] - -----------------------------------------------------------------------------------------


  INFO root [0x000027a0] [2018-10-29 23:55:58,972] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [0x000027a0] [2018-10-29 23:55:58,972] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [0x000027a0] [2018-10-29 23:55:58,972] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [0x000027a0] [2018-10-29 23:55:58,975] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.107 ( 192.168.0.107:59047 )
  INFO root [0x000027a0] [2018-10-29 23:55:58,975] - NetworkInterface::initialize(INTERNAL): address 192.168.0.107:59047, SOMAXCONN=5.
  INFO root [0x000027a0] [2018-10-29 23:55:58,975] - server-configs:
  INFO root [0x000027a0] [2018-10-29 23:55:58,975] - 	gameUpdateHertz : 10
  INFO root [0x000027a0] [2018-10-29 23:55:58,975] - 	defaultViewRadius : 80
  INFO root [0x000027a0] [2018-10-29 23:55:58,975] - 	defaultViewHysteresisArea : 5
  INFO root [0x000027a0] [2018-10-29 23:55:58,975] - 	entryScriptFile : kbemain
  INFO root [0x000027a0] [2018-10-29 23:55:58,975] - 	internalAddr : 192.168.0.107:59047
  INFO root [0x000027a0] [2018-10-29 23:55:58,975] - 	componentID : 8001
  WARN root [0x000027a0] [2018-10-29 23:55:59,286] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20552, errorno=10048
  INFO root [0x000027a0] [2018-10-29 23:55:59,290] - ---- cellapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 85A70C5E64F896E0F1A60BF405B4EB07. Config: Debug X86. Built: 15:53:53 Apr 29 2018. AppID: 8001. UID: 7521. PID: 10056 ----
  INFO root [0x000027a0] [2018-10-29 23:55:59,290] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [0x000027a0] [2018-10-29 23:55:59,290] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x000027a0] [2018-10-29 23:55:59,291] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x000027a0] [2018-10-29 23:55:59,417] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x000027a0] [2018-10-29 23:55:59,417] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x000027a0] [2018-10-29 23:55:59,418] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x000027a0] [2018-10-29 23:55:59,421] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x000027a0] [2018-10-29 23:55:59,421] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x000027a0] [2018-10-29 23:55:59,421] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x000027a0] [2018-10-29 23:55:59,421] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x000027a0] [2018-10-29 23:55:59,449] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x000027a0] [2018-10-29 23:55:59,477] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x000027a0] [2018-10-29 23:55:59,478] - Script::install(): KBExtra is successfully!
 DEBUG root [0x000027a0] [2018-10-29 23:55:59,499] - loaded entity-script:Account(1).
 DEBUG root [0x000027a0] [2018-10-29 23:55:59,509] - loaded entity-script:Room(4).
  INFO root [0x000027a0] [2018-10-29 23:55:59,509] - TelnetServer server is running on port 50000
  INFO root [0x000027a0] [2018-10-29 23:55:59,865] - ---- cellapp is running ----
 DEBUG root [0x000027a0] [2018-10-29 23:55:59,865] - Components::process(): Request for the process of identity...
  WARN root [0x000027a0] [2018-10-29 23:56:05,946] - EntityApp::checkTickPeriod: tick took 6080% (6.08 seconds)!
  INFO root [0x000027a0] [2018-10-29 23:56:06,967] - Components::findComponents: find logger(1)...
  INFO root [0x000027a0] [2018-10-29 23:56:07,035] - Components::findComponents: found logger, addr:192.168.0.107:59041
  INFO root [0x000027a0] [2018-10-29 23:56:07,036] - Components::addComponent: reset orderLog, uid=7521!
  INFO root [0x000027a0] [2018-10-29 23:56:07,036] - Components::addComponent[logger], uid=7521, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x000027a0] [2018-10-29 23:56:07,038] - Components::findComponents: find dbmgr(2)...
  INFO root [0x000027a0] [2018-10-29 23:56:07,139] - Components::findComponents: found dbmgr, addr:192.168.0.107:59043
  INFO root [0x000027a0] [2018-10-29 23:56:07,140] - Components::addComponent: reset orderLog, uid=7521!
  INFO root [0x000027a0] [2018-10-29 23:56:07,140] - Components::addComponent[dbmgr], uid=7521, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x000027a0] [2018-10-29 23:56:07,141] - Components::findComponents: found dbmgr, addr:192.168.0.107:59043
  WARN root [0x000027a0] [2018-10-29 23:56:08,141] - EntityApp::checkTickPeriod: tick took 1274% (1.27 seconds)!
  WARN root [0x000027a0] [2018-10-29 23:56:08,143] - Forwarding logs to logger[192.168.0.107:59041/0/0/0]...
