  INFO root [0x0000270c] [2018-08-22 15:10:01,445] - 
  INFO root [0x0000270c] [2018-08-22 15:10:01,520] - -----------------------------------------------------------------------------------------


  INFO root [0x0000270c] [2018-08-22 15:10:03,082] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [0x0000270c] [2018-08-22 15:10:03,083] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [0x0000270c] [2018-08-22 15:10:03,083] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [0x0000270c] [2018-08-22 15:10:03,484] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:60621 )
  INFO root [0x0000270c] [2018-08-22 15:10:03,514] - NetworkInterface::initialize(INTERNAL): address 192.168.0.106:60621, SOMAXCONN=5.
  INFO root [0x0000270c] [2018-08-22 15:10:03,514] - server-configs:
  INFO root [0x0000270c] [2018-08-22 15:10:03,515] - 	gameUpdateHertz : 10
  INFO root [0x0000270c] [2018-08-22 15:10:03,564] - 	defaultViewRadius : 80
  INFO root [0x0000270c] [2018-08-22 15:10:03,565] - 	defaultViewHysteresisArea : 5
  INFO root [0x0000270c] [2018-08-22 15:10:03,565] - 	entryScriptFile : kbemain
  INFO root [0x0000270c] [2018-08-22 15:10:03,566] - 	internalAddr : 192.168.0.106:60621
  INFO root [0x0000270c] [2018-08-22 15:10:03,566] - 	componentID : 8001
  INFO root [0x0000270c] [2018-08-22 15:10:03,978] - Components::findLogger: found logger, addr:192.168.0.106:60614
  INFO root [0x0000270c] [2018-08-22 15:10:03,978] - Components::addComponent: reset orderLog, uid=18805!
  INFO root [0x0000270c] [2018-08-22 15:10:04,010] - Components::addComponent[logger], uid=18805, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x0000270c] [2018-08-22 15:10:04,172] - ---- cellapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 85A70C5E64F896E0F1A60BF405B4EB07. Config: Debug X86. Built: 15:53:53 Apr 29 2018. AppID: 8001. UID: 18805. PID: 12352 ----
  INFO root [0x0000270c] [2018-08-22 15:10:04,173] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [0x0000270c] [2018-08-22 15:10:04,214] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x0000270c] [2018-08-22 15:10:04,215] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x0000270c] [2018-08-22 15:10:10,774] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x0000270c] [2018-08-22 15:10:10,823] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x0000270c] [2018-08-22 15:10:11,019] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x0000270c] [2018-08-22 15:10:12,155] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x0000270c] [2018-08-22 15:10:12,312] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x0000270c] [2018-08-22 15:10:12,368] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x0000270c] [2018-08-22 15:10:12,467] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x0000270c] [2018-08-22 15:10:13,050] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x0000270c] [2018-08-22 15:10:14,330] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x0000270c] [2018-08-22 15:10:14,331] - Script::install(): KBExtra is successfully!
 ERROR root [0x0000270c] [2018-08-22 15:10:15,607] - ScriptDefModule::addPropertyDescription: [cur_turn] is exist! componentType=5.
 ERROR root [0x0000270c] [2018-08-22 15:10:15,609] - ScriptDefModule::addPropertyDescription: [cur_turn] is exist! componentType=7.
 ERROR root [0x0000270c] [2018-08-22 15:10:15,611] - EntityDef::addPropertyDescription(Room): E:/kbengine/assets/scripts/entity_defs/Room.def.
 ERROR root [0x0000270c] [2018-08-22 15:10:15,615] - EntityDef::loadDefInfo: failed to loadAllDefDescription(), entity:Room
 ERROR root [0x0000270c] [2018-08-22 15:10:15,617] - EntityDef::initialize: failed to load entity(Room) module!
 ERROR root [0x0000270c] [2018-08-22 15:10:15,619] - app::initialize(): initialization failed!
 DEBUG root [0x0000270c] [2018-08-22 15:10:15,670] - EntityRef::destroyObjPool(): size 0.
 DEBUG root [0x0000270c] [2018-08-22 15:10:15,671] - Witness::destroyObjPool(): size 0.
 DEBUG root [0x0000270c] [2018-08-22 15:10:15,793] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x0000270c] [2018-08-22 15:10:15,793] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x0000270c] [2018-08-22 15:10:15,794] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x0000270c] [2018-08-22 15:10:15,794] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x0000270c] [2018-08-22 15:10:15,795] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x0000270c] [2018-08-22 15:10:15,795] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x0000270c] [2018-08-22 15:10:15,795] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x0000270c] [2018-08-22 15:10:15,796] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x0000270c] [2018-08-22 15:10:15,854] - Script::uninstall(): is successfully!
 DEBUG root [0x0000270c] [2018-08-22 15:10:15,855] - ThreadPool::destroy(): starting size 2.
  WARN root [0x0000270c] [2018-08-22 15:10:16,155] - ThreadPool::destroy(): waiting for thread(2)[0x4ed358,0x4ed2f0,], try=1
 DEBUG root [0x0000270c] [2018-08-22 15:10:16,556] - TPThread::~TPThread(): 0x4ed358
 DEBUG root [0x0000270c] [2018-08-22 15:10:16,556] - TPThread::~TPThread(): 0x4ed2f0
 DEBUG root [0x0000270c] [2018-08-22 15:10:16,556] - ThreadPool::destroy(): successfully!
 DEBUG root [0x0000270c] [2018-08-22 15:10:16,556] - Bundle::destroyObjPool(): size 12.
 DEBUG root [0x0000270c] [2018-08-22 15:10:16,557] - Channel::destroyObjPool(): size 15.
 DEBUG root [0x0000270c] [2018-08-22 15:10:16,557] - TCPPacket::destroyObjPool(): size 0.
 DEBUG root [0x0000270c] [2018-08-22 15:10:16,557] - UDPPacket::destroyObjPool(): size 14.
 DEBUG root [0x0000270c] [2018-08-22 15:10:16,558] - EndPoint::destroyObjPool(): size 15.
 DEBUG root [0x0000270c] [2018-08-22 15:10:16,558] - Address::destroyObjPool(): size 0.
 DEBUG root [0x0000270c] [2018-08-22 15:10:16,558] - TCPPacketReceiver::destroyObjPool(): size 0.
 DEBUG root [0x0000270c] [2018-08-22 15:10:16,558] - UDPPacketReceiver::destroyObjPool(): size 0.
  WARN root [0x0000270c] [2018-08-22 15:10:16,558] - Forwarding logs to logger[192.168.0.106:60614/0/0/0]...
  INFO root [0x0000270c] [2018-08-22 15:10:23,088] - EventDispatcher()::~EventDispatcher: Num timers = 1
  INFO root [0x0000343c] [2018-08-22 15:10:32,226] - 
  INFO root [0x0000343c] [2018-08-22 15:10:32,226] - -----------------------------------------------------------------------------------------


  INFO root [0x0000343c] [2018-08-22 15:10:32,227] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [0x0000343c] [2018-08-22 15:10:32,227] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [0x0000343c] [2018-08-22 15:10:32,227] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [0x0000343c] [2018-08-22 15:10:32,229] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:60635 )
  INFO root [0x0000343c] [2018-08-22 15:10:32,229] - NetworkInterface::initialize(INTERNAL): address 192.168.0.106:60635, SOMAXCONN=5.
  INFO root [0x0000343c] [2018-08-22 15:10:32,229] - server-configs:
  INFO root [0x0000343c] [2018-08-22 15:10:32,229] - 	gameUpdateHertz : 10
  INFO root [0x0000343c] [2018-08-22 15:10:32,230] - 	defaultViewRadius : 80
  INFO root [0x0000343c] [2018-08-22 15:10:32,230] - 	defaultViewHysteresisArea : 5
  INFO root [0x0000343c] [2018-08-22 15:10:32,230] - 	entryScriptFile : kbemain
  INFO root [0x0000343c] [2018-08-22 15:10:32,230] - 	internalAddr : 192.168.0.106:60635
  INFO root [0x0000343c] [2018-08-22 15:10:32,230] - 	componentID : 8001
  INFO root [0x0000343c] [2018-08-22 15:10:33,746] - ---- cellapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 85A70C5E64F896E0F1A60BF405B4EB07. Config: Debug X86. Built: 15:53:53 Apr 29 2018. AppID: 8001. UID: 18988. PID: 13368 ----
  INFO root [0x0000343c] [2018-08-22 15:10:33,748] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [0x0000343c] [2018-08-22 15:10:33,749] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x0000343c] [2018-08-22 15:10:33,750] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x0000343c] [2018-08-22 15:10:33,886] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x0000343c] [2018-08-22 15:10:33,886] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x0000343c] [2018-08-22 15:10:33,887] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x0000343c] [2018-08-22 15:10:33,890] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x0000343c] [2018-08-22 15:10:33,890] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x0000343c] [2018-08-22 15:10:33,890] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x0000343c] [2018-08-22 15:10:33,891] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x0000343c] [2018-08-22 15:10:33,922] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x0000343c] [2018-08-22 15:10:33,952] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x0000343c] [2018-08-22 15:10:33,952] - Script::install(): KBExtra is successfully!
 ERROR root [0x0000343c] [2018-08-22 15:10:33,968] - ScriptDefModule::addPropertyDescription: [cur_turn] is exist! componentType=5.
 ERROR root [0x0000343c] [2018-08-22 15:10:33,969] - ScriptDefModule::addPropertyDescription: [cur_turn] is exist! componentType=7.
 ERROR root [0x0000343c] [2018-08-22 15:10:33,969] - EntityDef::addPropertyDescription(Room): E:/kbengine/assets/scripts/entity_defs/Room.def.
 ERROR root [0x0000343c] [2018-08-22 15:10:33,969] - EntityDef::loadDefInfo: failed to loadAllDefDescription(), entity:Room
 ERROR root [0x0000343c] [2018-08-22 15:10:33,970] - EntityDef::initialize: failed to load entity(Room) module!
 ERROR root [0x0000343c] [2018-08-22 15:10:33,971] - app::initialize(): initialization failed!
 DEBUG root [0x0000343c] [2018-08-22 15:10:33,972] - EntityRef::destroyObjPool(): size 0.
 DEBUG root [0x0000343c] [2018-08-22 15:10:33,972] - Witness::destroyObjPool(): size 0.
 DEBUG root [0x0000343c] [2018-08-22 15:10:33,973] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x0000343c] [2018-08-22 15:10:33,973] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x0000343c] [2018-08-22 15:10:33,973] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x0000343c] [2018-08-22 15:10:33,973] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x0000343c] [2018-08-22 15:10:33,973] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x0000343c] [2018-08-22 15:10:33,973] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x0000343c] [2018-08-22 15:10:33,973] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x0000343c] [2018-08-22 15:10:33,973] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x0000343c] [2018-08-22 15:10:33,981] - Script::uninstall(): is successfully!
 DEBUG root [0x0000343c] [2018-08-22 15:10:33,981] - ThreadPool::destroy(): starting size 2.
  WARN root [0x0000343c] [2018-08-22 15:10:34,281] - ThreadPool::destroy(): waiting for thread(2)[0x1ced358,0x1ced2f0,], try=1
 DEBUG root [0x0000343c] [2018-08-22 15:10:34,681] - TPThread::~TPThread(): 0x1ced358
 DEBUG root [0x0000343c] [2018-08-22 15:10:34,681] - TPThread::~TPThread(): 0x1ced2f0
 DEBUG root [0x0000343c] [2018-08-22 15:10:34,682] - ThreadPool::destroy(): successfully!
 DEBUG root [0x0000343c] [2018-08-22 15:10:34,683] - Bundle::destroyObjPool(): size 15.
 DEBUG root [0x0000343c] [2018-08-22 15:10:34,683] - Channel::destroyObjPool(): size 0.
 DEBUG root [0x0000343c] [2018-08-22 15:10:34,684] - TCPPacket::destroyObjPool(): size 0.
 DEBUG root [0x0000343c] [2018-08-22 15:10:34,685] - UDPPacket::destroyObjPool(): size 14.
 DEBUG root [0x0000343c] [2018-08-22 15:10:34,685] - EndPoint::destroyObjPool(): size 0.
 DEBUG root [0x0000343c] [2018-08-22 15:10:34,685] - Address::destroyObjPool(): size 0.
 DEBUG root [0x0000343c] [2018-08-22 15:10:34,686] - TCPPacketReceiver::destroyObjPool(): size 0.
 DEBUG root [0x0000343c] [2018-08-22 15:10:34,686] - UDPPacketReceiver::destroyObjPool(): size 0.
  INFO root [0x0000343c] [2018-08-22 15:10:41,189] - EventDispatcher()::~EventDispatcher: Num timers = 1
  INFO root [0x00001f1c] [2018-08-22 15:12:12,648] - 
  INFO root [0x00001f1c] [2018-08-22 15:12:12,648] - -----------------------------------------------------------------------------------------


  INFO root [0x00001f1c] [2018-08-22 15:12:12,649] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [0x00001f1c] [2018-08-22 15:12:12,649] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [0x00001f1c] [2018-08-22 15:12:12,650] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [0x00001f1c] [2018-08-22 15:12:12,652] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:60651 )
  INFO root [0x00001f1c] [2018-08-22 15:12:12,652] - NetworkInterface::initialize(INTERNAL): address 192.168.0.106:60651, SOMAXCONN=5.
  INFO root [0x00001f1c] [2018-08-22 15:12:12,652] - server-configs:
  INFO root [0x00001f1c] [2018-08-22 15:12:12,652] - 	gameUpdateHertz : 10
  INFO root [0x00001f1c] [2018-08-22 15:12:12,653] - 	defaultViewRadius : 80
  INFO root [0x00001f1c] [2018-08-22 15:12:12,653] - 	defaultViewHysteresisArea : 5
  INFO root [0x00001f1c] [2018-08-22 15:12:12,653] - 	entryScriptFile : kbemain
  INFO root [0x00001f1c] [2018-08-22 15:12:12,653] - 	internalAddr : 192.168.0.106:60651
  INFO root [0x00001f1c] [2018-08-22 15:12:12,653] - 	componentID : 8001
  WARN root [0x00001f1c] [2018-08-22 15:12:12,963] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20796, errorno=10048
  INFO root [0x00001f1c] [2018-08-22 15:12:12,966] - ---- cellapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 85A70C5E64F896E0F1A60BF405B4EB07. Config: Debug X86. Built: 15:53:53 Apr 29 2018. AppID: 8001. UID: 19318. PID: 14248 ----
  INFO root [0x00001f1c] [2018-08-22 15:12:12,966] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [0x00001f1c] [2018-08-22 15:12:12,967] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00001f1c] [2018-08-22 15:12:12,967] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x00001f1c] [2018-08-22 15:12:13,094] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00001f1c] [2018-08-22 15:12:13,095] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x00001f1c] [2018-08-22 15:12:13,095] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x00001f1c] [2018-08-22 15:12:13,098] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x00001f1c] [2018-08-22 15:12:13,098] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x00001f1c] [2018-08-22 15:12:13,098] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x00001f1c] [2018-08-22 15:12:13,099] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x00001f1c] [2018-08-22 15:12:13,126] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x00001f1c] [2018-08-22 15:12:13,157] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x00001f1c] [2018-08-22 15:12:13,157] - Script::install(): KBExtra is successfully!
 ERROR root [0x00001f1c] [2018-08-22 15:12:13,211] - EntityDef::checkDefMethod: class Account does not have method[onHu], defined in Account.def!
 ERROR root [0x00001f1c] [2018-08-22 15:12:13,211] - EntityDef::initialize: EntityClass[Account] checkDefMethod is failed!
 ERROR root [0x00001f1c] [2018-08-22 15:12:13,212] - app::initialize(): initialization failed!
 DEBUG root [0x00001f1c] [2018-08-22 15:12:13,212] - EntityRef::destroyObjPool(): size 0.
 DEBUG root [0x00001f1c] [2018-08-22 15:12:13,212] - Witness::destroyObjPool(): size 0.
 DEBUG root [0x00001f1c] [2018-08-22 15:12:13,213] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00001f1c] [2018-08-22 15:12:13,213] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x00001f1c] [2018-08-22 15:12:13,213] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x00001f1c] [2018-08-22 15:12:13,213] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x00001f1c] [2018-08-22 15:12:13,214] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x00001f1c] [2018-08-22 15:12:13,214] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x00001f1c] [2018-08-22 15:12:13,214] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x00001f1c] [2018-08-22 15:12:13,214] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x00001f1c] [2018-08-22 15:12:13,222] - Script::uninstall(): is successfully!
 DEBUG root [0x00001f1c] [2018-08-22 15:12:13,222] - ThreadPool::destroy(): starting size 2.
  WARN root [0x00001f1c] [2018-08-22 15:12:13,522] - ThreadPool::destroy(): waiting for thread(2)[0x44d3c0,0x44d358,], try=1
 DEBUG root [0x00001f1c] [2018-08-22 15:12:13,922] - TPThread::~TPThread(): 0x44d3c0
 DEBUG root [0x00001f1c] [2018-08-22 15:12:13,923] - TPThread::~TPThread(): 0x44d358
 DEBUG root [0x00001f1c] [2018-08-22 15:12:13,923] - ThreadPool::destroy(): successfully!
 DEBUG root [0x00001f1c] [2018-08-22 15:12:13,924] - Bundle::destroyObjPool(): size 1.
 DEBUG root [0x00001f1c] [2018-08-22 15:12:13,925] - Channel::destroyObjPool(): size 0.
 DEBUG root [0x00001f1c] [2018-08-22 15:12:13,926] - TCPPacket::destroyObjPool(): size 0.
 DEBUG root [0x00001f1c] [2018-08-22 15:12:13,926] - UDPPacket::destroyObjPool(): size 15.
 DEBUG root [0x00001f1c] [2018-08-22 15:12:13,927] - EndPoint::destroyObjPool(): size 0.
 DEBUG root [0x00001f1c] [2018-08-22 15:12:13,927] - Address::destroyObjPool(): size 0.
 DEBUG root [0x00001f1c] [2018-08-22 15:12:13,928] - TCPPacketReceiver::destroyObjPool(): size 0.
 DEBUG root [0x00001f1c] [2018-08-22 15:12:13,928] - UDPPacketReceiver::destroyObjPool(): size 0.
  INFO root [0x00001f1c] [2018-08-22 15:12:20,428] - EventDispatcher()::~EventDispatcher: Num timers = 1
  INFO root [0x00003600] [2018-08-22 15:13:51,336] - 
  INFO root [0x00003600] [2018-08-22 15:13:51,336] - -----------------------------------------------------------------------------------------


  INFO root [0x00003600] [2018-08-22 15:13:51,337] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [0x00003600] [2018-08-22 15:13:51,337] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [0x00003600] [2018-08-22 15:13:51,337] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [0x00003600] [2018-08-22 15:13:51,340] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:60686 )
  INFO root [0x00003600] [2018-08-22 15:13:51,340] - NetworkInterface::initialize(INTERNAL): address 192.168.0.106:60686, SOMAXCONN=5.
  INFO root [0x00003600] [2018-08-22 15:13:51,340] - server-configs:
  INFO root [0x00003600] [2018-08-22 15:13:51,340] - 	gameUpdateHertz : 10
  INFO root [0x00003600] [2018-08-22 15:13:51,340] - 	defaultViewRadius : 80
  INFO root [0x00003600] [2018-08-22 15:13:51,340] - 	defaultViewHysteresisArea : 5
  INFO root [0x00003600] [2018-08-22 15:13:51,340] - 	entryScriptFile : kbemain
  INFO root [0x00003600] [2018-08-22 15:13:51,340] - 	internalAddr : 192.168.0.106:60686
  INFO root [0x00003600] [2018-08-22 15:13:51,341] - 	componentID : 8001
  WARN root [0x00003600] [2018-08-22 15:13:51,651] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20151, errorno=10048
  INFO root [0x00003600] [2018-08-22 15:13:51,654] - ---- cellapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 85A70C5E64F896E0F1A60BF405B4EB07. Config: Debug X86. Built: 15:53:53 Apr 29 2018. AppID: 8001. UID: 19638. PID: 13160 ----
  INFO root [0x00003600] [2018-08-22 15:13:51,655] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [0x00003600] [2018-08-22 15:13:51,655] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00003600] [2018-08-22 15:13:51,655] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x00003600] [2018-08-22 15:13:51,785] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00003600] [2018-08-22 15:13:51,785] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x00003600] [2018-08-22 15:13:51,786] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x00003600] [2018-08-22 15:13:51,789] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x00003600] [2018-08-22 15:13:51,790] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x00003600] [2018-08-22 15:13:51,790] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x00003600] [2018-08-22 15:13:51,790] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x00003600] [2018-08-22 15:13:51,824] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x00003600] [2018-08-22 15:13:51,855] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x00003600] [2018-08-22 15:13:51,855] - Script::install(): KBExtra is successfully!
 DEBUG root [0x00003600] [2018-08-22 15:13:51,877] - loaded entity-script:Account(1).
 DEBUG root [0x00003600] [2018-08-22 15:13:51,931] - loaded entity-script:Room(4).
  INFO root [0x00003600] [2018-08-22 15:13:51,931] - TelnetServer server is running on port 50000
  INFO root [0x00003600] [2018-08-22 15:13:52,269] - ---- cellapp is running ----
 DEBUG root [0x00003600] [2018-08-22 15:13:52,270] - Components::process(): Request for the process of identity...
  WARN root [0x00003600] [2018-08-22 15:13:58,424] - EntityApp::checkTickPeriod: tick took 6155% (6.16 seconds)!
  INFO root [0x00003600] [2018-08-22 15:13:59,470] - Components::findComponents: find logger(1)...
  INFO root [0x00003600] [2018-08-22 15:13:59,527] - Components::findComponents: found logger, addr:192.168.0.106:60684
  INFO root [0x00003600] [2018-08-22 15:13:59,528] - Components::addComponent: reset orderLog, uid=19638!
  INFO root [0x00003600] [2018-08-22 15:13:59,528] - Components::addComponent[logger], uid=19638, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00003600] [2018-08-22 15:13:59,530] - Components::findComponents: find dbmgr(2)...
  INFO root [0x00003600] [2018-08-22 15:13:59,633] - Components::findComponents: found dbmgr, addr:192.168.0.106:60685
  INFO root [0x00003600] [2018-08-22 15:13:59,633] - Components::addComponent: reset orderLog, uid=19638!
  INFO root [0x00003600] [2018-08-22 15:13:59,633] - Components::addComponent[dbmgr], uid=19638, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00003600] [2018-08-22 15:13:59,634] - Components::findComponents: found dbmgr, addr:192.168.0.106:60685
  WARN root [0x00003600] [2018-08-22 15:14:00,634] - EntityApp::checkTickPeriod: tick took 1264% (1.26 seconds)!
  WARN root [0x00003600] [2018-08-22 15:14:00,634] - Forwarding logs to logger[192.168.0.106:60684/0/0/0]...
 ERROR root [0x00003600] [2018-08-22 15:14:18,782] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x00003600] [2018-08-22 15:14:18,792] - The following logs sent to logger failed:
  WARN root [0x00003600] [2018-08-22 15:14:18,792] - ==> [2018-08-22 15:14:18 769] TCPPacketReceiver::processPendingEvents(192.168.0.106:60684): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00003600] [2018-08-22 15:14:18,792] - ==> [2018-08-22 15:14:18 782] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x00003600] [2018-08-22 15:14:18,843] - TCPPacketReceiver::processPendingEvents(192.168.0.106:60685): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00003600] [2018-08-22 15:14:18,846] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x00003600] [2018-08-22 15:14:18,859] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [0x00003600] [2018-08-22 15:14:18,863] - Shutdowner::onShutdown: shutting down
  INFO root [0x00003600] [2018-08-22 15:14:18,864] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [0x00003600] [2018-08-22 15:14:18,886] - EntityRef::destroyObjPool(): size 0.
 DEBUG root [0x00003600] [2018-08-22 15:14:18,886] - Witness::destroyObjPool(): size 0.
 DEBUG root [0x00003600] [2018-08-22 15:14:18,895] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00003600] [2018-08-22 15:14:18,895] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x00003600] [2018-08-22 15:14:18,895] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x00003600] [2018-08-22 15:14:18,895] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x00003600] [2018-08-22 15:14:18,896] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x00003600] [2018-08-22 15:14:18,896] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x00003600] [2018-08-22 15:14:18,896] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x00003600] [2018-08-22 15:14:18,896] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x00003600] [2018-08-22 15:14:18,904] - Script::uninstall(): is successfully!
 DEBUG root [0x00003600] [2018-08-22 15:14:18,904] - ThreadPool::destroy(): starting size 2.
  INFO root [0x000032a0] [2018-08-22 15:16:29,012] - 
  INFO root [0x000032a0] [2018-08-22 15:16:29,013] - -----------------------------------------------------------------------------------------


  INFO root [0x000032a0] [2018-08-22 15:16:29,014] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [0x000032a0] [2018-08-22 15:16:29,014] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [0x000032a0] [2018-08-22 15:16:29,015] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [0x000032a0] [2018-08-22 15:16:29,023] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:60765 )
  INFO root [0x000032a0] [2018-08-22 15:16:29,024] - NetworkInterface::initialize(INTERNAL): address 192.168.0.106:60765, SOMAXCONN=5.
  INFO root [0x000032a0] [2018-08-22 15:16:29,024] - server-configs:
  INFO root [0x000032a0] [2018-08-22 15:16:29,024] - 	gameUpdateHertz : 10
  INFO root [0x000032a0] [2018-08-22 15:16:29,024] - 	defaultViewRadius : 80
  INFO root [0x000032a0] [2018-08-22 15:16:29,024] - 	defaultViewHysteresisArea : 5
  INFO root [0x000032a0] [2018-08-22 15:16:29,024] - 	entryScriptFile : kbemain
  INFO root [0x000032a0] [2018-08-22 15:16:29,024] - 	internalAddr : 192.168.0.106:60765
  INFO root [0x000032a0] [2018-08-22 15:16:29,025] - 	componentID : 8001
  WARN root [0x000032a0] [2018-08-22 15:16:29,338] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20799, errorno=10048
  INFO root [0x000032a0] [2018-08-22 15:16:29,342] - ---- cellapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 85A70C5E64F896E0F1A60BF405B4EB07. Config: Debug X86. Built: 15:53:53 Apr 29 2018. AppID: 8001. UID: 20154. PID: 13980 ----
  INFO root [0x000032a0] [2018-08-22 15:16:29,342] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [0x000032a0] [2018-08-22 15:16:29,342] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x000032a0] [2018-08-22 15:16:29,343] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x000032a0] [2018-08-22 15:16:29,476] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x000032a0] [2018-08-22 15:16:29,476] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x000032a0] [2018-08-22 15:16:29,476] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x000032a0] [2018-08-22 15:16:29,479] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x000032a0] [2018-08-22 15:16:29,480] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x000032a0] [2018-08-22 15:16:29,480] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x000032a0] [2018-08-22 15:16:29,480] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x000032a0] [2018-08-22 15:16:29,511] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x000032a0] [2018-08-22 15:16:29,541] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x000032a0] [2018-08-22 15:16:29,541] - Script::install(): KBExtra is successfully!
 DEBUG root [0x000032a0] [2018-08-22 15:16:29,563] - loaded entity-script:Account(1).
 DEBUG root [0x000032a0] [2018-08-22 15:16:29,572] - loaded entity-script:Room(4).
  INFO root [0x000032a0] [2018-08-22 15:16:29,572] - TelnetServer server is running on port 50000
  INFO root [0x000032a0] [2018-08-22 15:16:29,894] - ---- cellapp is running ----
 DEBUG root [0x000032a0] [2018-08-22 15:16:29,894] - Components::process(): Request for the process of identity...
  WARN root [0x000032a0] [2018-08-22 15:16:33,242] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20767, errorno=10048
  WARN root [0x000032a0] [2018-08-22 15:16:36,287] - EntityApp::checkTickPeriod: tick took 6393% (6.39 seconds)!
  INFO root [0x000032a0] [2018-08-22 15:16:37,319] - Components::findComponents: find logger(1)...
  INFO root [0x000032a0] [2018-08-22 15:16:37,422] - Components::findComponents: found logger, addr:192.168.0.106:60761
  INFO root [0x000032a0] [2018-08-22 15:16:37,423] - Components::addComponent: reset orderLog, uid=20154!
  INFO root [0x000032a0] [2018-08-22 15:16:37,423] - Components::addComponent[logger], uid=20154, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x000032a0] [2018-08-22 15:16:37,425] - Components::findComponents: find dbmgr(2)...
  INFO root [0x000032a0] [2018-08-22 15:16:37,528] - Components::findComponents: found dbmgr, addr:192.168.0.106:60760
  INFO root [0x000032a0] [2018-08-22 15:16:37,529] - Components::addComponent: reset orderLog, uid=20154!
  INFO root [0x000032a0] [2018-08-22 15:16:37,529] - Components::addComponent[dbmgr], uid=20154, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x000032a0] [2018-08-22 15:16:37,530] - Components::findComponents: found dbmgr, addr:192.168.0.106:60760
  WARN root [0x000032a0] [2018-08-22 15:16:38,530] - Forwarding logs to logger[192.168.0.106:60761/0/0/0]...
 ERROR root [0x000032a0] [2018-08-22 15:28:43,551] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x000032a0] [2018-08-22 15:28:43,569] - The following logs sent to logger failed:
  WARN root [0x000032a0] [2018-08-22 15:28:43,569] - ==> [2018-08-22 15:28:43 547] TCPPacketReceiver::processPendingEvents(192.168.0.106:60761): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x000032a0] [2018-08-22 15:28:43,569] - ==> [2018-08-22 15:28:43 551] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x000032a0] [2018-08-22 15:28:43,623] - TCPPacketReceiver::processPendingEvents(192.168.0.106:60760): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x000032a0] [2018-08-22 15:28:43,627] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x000032a0] [2018-08-22 15:28:43,641] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [0x000032a0] [2018-08-22 15:28:43,642] - Shutdowner::onShutdown: shutting down
  INFO root [0x000032a0] [2018-08-22 15:28:43,643] - Spaces::destroySpace: 1.
  INFO root [0x000032a0] [2018-08-22 15:28:43,643] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [0x000032a0] [2018-08-22 15:28:43,665] - Account::~Account(): 2002
 DEBUG root [0x000032a0] [2018-08-22 15:28:43,665] - Account::~Account(): 2004
 DEBUG root [0x000032a0] [2018-08-22 15:28:43,666] - EntityRef::destroyObjPool(): size 16.
 DEBUG root [0x000032a0] [2018-08-22 15:28:43,666] - Witness::destroyObjPool(): size 16.
 DEBUG root [0x000032a0] [2018-08-22 15:28:43,674] - Room::~Room(): 2003
 ERROR root [0x000032a0] [2018-08-22 15:28:43,675] - PyGC::debugTracing(): EntityCall : leaked(2)
 DEBUG root [0x000032a0] [2018-08-22 15:28:43,675] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x000032a0] [2018-08-22 15:28:43,676] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x000032a0] [2018-08-22 15:28:43,676] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x000032a0] [2018-08-22 15:28:43,676] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x000032a0] [2018-08-22 15:28:43,676] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x000032a0] [2018-08-22 15:28:43,676] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x000032a0] [2018-08-22 15:28:43,676] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x000032a0] [2018-08-22 15:28:43,676] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x000032a0] [2018-08-22 15:28:43,685] - Script::uninstall(): is successfully!
 DEBUG root [0x000032a0] [2018-08-22 15:28:43,685] - ThreadPool::destroy(): starting size 2.
  INFO root [0x00003c48] [2018-08-22 15:28:44,912] - 
  INFO root [0x00003c48] [2018-08-22 15:28:44,913] - -----------------------------------------------------------------------------------------


  INFO root [0x00003c48] [2018-08-22 15:28:44,914] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [0x00003c48] [2018-08-22 15:28:44,914] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [0x00003c48] [2018-08-22 15:28:44,914] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [0x00003c48] [2018-08-22 15:28:44,921] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:60893 )
  INFO root [0x00003c48] [2018-08-22 15:28:44,921] - NetworkInterface::initialize(INTERNAL): address 192.168.0.106:60893, SOMAXCONN=5.
  INFO root [0x00003c48] [2018-08-22 15:28:44,921] - server-configs:
  INFO root [0x00003c48] [2018-08-22 15:28:44,921] - 	gameUpdateHertz : 10
  INFO root [0x00003c48] [2018-08-22 15:28:44,922] - 	defaultViewRadius : 80
  INFO root [0x00003c48] [2018-08-22 15:28:44,922] - 	defaultViewHysteresisArea : 5
  INFO root [0x00003c48] [2018-08-22 15:28:44,922] - 	entryScriptFile : kbemain
  INFO root [0x00003c48] [2018-08-22 15:28:44,922] - 	internalAddr : 192.168.0.106:60893
  INFO root [0x00003c48] [2018-08-22 15:28:44,922] - 	componentID : 8001
  INFO root [0x00003c48] [2018-08-22 15:28:46,436] - ---- cellapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 85A70C5E64F896E0F1A60BF405B4EB07. Config: Debug X86. Built: 15:53:53 Apr 29 2018. AppID: 8001. UID: 22557. PID: 16088 ----
  INFO root [0x00003c48] [2018-08-22 15:28:46,436] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [0x00003c48] [2018-08-22 15:28:46,437] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00003c48] [2018-08-22 15:28:46,437] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x00003c48] [2018-08-22 15:28:46,611] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00003c48] [2018-08-22 15:28:46,612] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x00003c48] [2018-08-22 15:28:46,612] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x00003c48] [2018-08-22 15:28:46,615] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x00003c48] [2018-08-22 15:28:46,616] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x00003c48] [2018-08-22 15:28:46,616] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x00003c48] [2018-08-22 15:28:46,616] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x00003c48] [2018-08-22 15:28:46,646] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x00003c48] [2018-08-22 15:28:46,674] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x00003c48] [2018-08-22 15:28:46,674] - Script::install(): KBExtra is successfully!
 DEBUG root [0x00003c48] [2018-08-22 15:28:46,692] - loaded entity-script:Account(1).
 DEBUG root [0x00003c48] [2018-08-22 15:28:46,717] - loaded entity-script:Room(4).
  INFO root [0x00003c48] [2018-08-22 15:28:46,718] - TelnetServer server is running on port 50000
  INFO root [0x00003c48] [2018-08-22 15:28:47,025] - ---- cellapp is running ----
 DEBUG root [0x00003c48] [2018-08-22 15:28:47,025] - Components::process(): Request for the process of identity...
  WARN root [0x00003c48] [2018-08-22 15:28:53,097] - EntityApp::checkTickPeriod: tick took 6072% (6.07 seconds)!
  INFO root [0x00003c48] [2018-08-22 15:28:54,119] - Components::findComponents: find logger(1)...
  INFO root [0x00003c48] [2018-08-22 15:28:54,140] - Components::findComponents: found logger, addr:192.168.0.106:60899
  INFO root [0x00003c48] [2018-08-22 15:28:54,141] - Components::addComponent: reset orderLog, uid=22557!
  INFO root [0x00003c48] [2018-08-22 15:28:54,141] - Components::addComponent[logger], uid=22557, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00003c48] [2018-08-22 15:28:54,141] - Components::findComponents: find dbmgr(2)...
  INFO root [0x00003c48] [2018-08-22 15:28:54,242] - Components::findComponents: found dbmgr, addr:192.168.0.106:60895
  INFO root [0x00003c48] [2018-08-22 15:28:54,243] - Components::addComponent: reset orderLog, uid=22557!
  INFO root [0x00003c48] [2018-08-22 15:28:54,243] - Components::addComponent[dbmgr], uid=22557, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00003c48] [2018-08-22 15:28:54,243] - Components::findComponents: found dbmgr, addr:192.168.0.106:60895
  WARN root [0x00003c48] [2018-08-22 15:28:55,243] - Forwarding logs to logger[192.168.0.106:60899/0/0/0]...
 ERROR root [0x00003c48] [2018-08-22 15:31:43,288] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x00003c48] [2018-08-22 15:31:43,306] - The following logs sent to logger failed:
  WARN root [0x00003c48] [2018-08-22 15:31:43,307] - ==> [2018-08-22 15:31:43 285] TCPPacketReceiver::processPendingEvents(192.168.0.106:60899): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00003c48] [2018-08-22 15:31:43,307] - ==> [2018-08-22 15:31:43 289] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x00003c48] [2018-08-22 15:31:43,361] - TCPPacketReceiver::processPendingEvents(192.168.0.106:60895): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00003c48] [2018-08-22 15:31:43,364] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x00003c48] [2018-08-22 15:31:43,379] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [0x00003c48] [2018-08-22 15:31:43,380] - Shutdowner::onShutdown: shutting down
  INFO root [0x00003c48] [2018-08-22 15:31:43,381] - Spaces::destroySpace: 1.
  INFO root [0x00003c48] [2018-08-22 15:31:43,381] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [0x00003c48] [2018-08-22 15:31:43,382] - Account::~Account(): 2
 DEBUG root [0x00003c48] [2018-08-22 15:31:43,382] - Account::~Account(): 4
 DEBUG root [0x00003c48] [2018-08-22 15:31:43,382] - EntityRef::destroyObjPool(): size 16.
 DEBUG root [0x00003c48] [2018-08-22 15:31:43,382] - Witness::destroyObjPool(): size 16.
 DEBUG root [0x00003c48] [2018-08-22 15:31:43,391] - Room::~Room(): 3
 ERROR root [0x00003c48] [2018-08-22 15:31:43,392] - PyGC::debugTracing(): EntityCall : leaked(2)
 DEBUG root [0x00003c48] [2018-08-22 15:31:43,392] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00003c48] [2018-08-22 15:31:43,392] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x00003c48] [2018-08-22 15:31:43,392] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x00003c48] [2018-08-22 15:31:43,392] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x00003c48] [2018-08-22 15:31:43,392] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x00003c48] [2018-08-22 15:31:43,393] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x00003c48] [2018-08-22 15:31:43,393] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x00003c48] [2018-08-22 15:31:43,393] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x00003c48] [2018-08-22 15:31:43,403] - Script::uninstall(): is successfully!
 DEBUG root [0x00003c48] [2018-08-22 15:31:43,404] - ThreadPool::destroy(): starting size 2.
  INFO root [0x00003e38] [2018-08-22 15:31:44,678] - 
  INFO root [0x00003e38] [2018-08-22 15:31:44,678] - -----------------------------------------------------------------------------------------


  INFO root [0x00003e38] [2018-08-22 15:31:44,679] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [0x00003e38] [2018-08-22 15:31:44,679] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [0x00003e38] [2018-08-22 15:31:44,680] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [0x00003e38] [2018-08-22 15:31:44,682] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:60956 )
  INFO root [0x00003e38] [2018-08-22 15:31:44,682] - NetworkInterface::initialize(INTERNAL): address 192.168.0.106:60956, SOMAXCONN=5.
  INFO root [0x00003e38] [2018-08-22 15:31:44,682] - server-configs:
  INFO root [0x00003e38] [2018-08-22 15:31:44,682] - 	gameUpdateHertz : 10
  INFO root [0x00003e38] [2018-08-22 15:31:44,683] - 	defaultViewRadius : 80
  INFO root [0x00003e38] [2018-08-22 15:31:44,683] - 	defaultViewHysteresisArea : 5
  INFO root [0x00003e38] [2018-08-22 15:31:44,683] - 	entryScriptFile : kbemain
  INFO root [0x00003e38] [2018-08-22 15:31:44,683] - 	internalAddr : 192.168.0.106:60956
  INFO root [0x00003e38] [2018-08-22 15:31:44,683] - 	componentID : 8001
  WARN root [0x00003e38] [2018-08-22 15:31:44,994] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20085, errorno=10048
  INFO root [0x00003e38] [2018-08-22 15:31:44,997] - ---- cellapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 85A70C5E64F896E0F1A60BF405B4EB07. Config: Debug X86. Built: 15:53:53 Apr 29 2018. AppID: 8001. UID: 23145. PID: 15256 ----
  INFO root [0x00003e38] [2018-08-22 15:31:44,998] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [0x00003e38] [2018-08-22 15:31:44,998] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00003e38] [2018-08-22 15:31:44,998] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x00003e38] [2018-08-22 15:31:45,125] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00003e38] [2018-08-22 15:31:45,125] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x00003e38] [2018-08-22 15:31:45,126] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x00003e38] [2018-08-22 15:31:45,129] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x00003e38] [2018-08-22 15:31:45,129] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x00003e38] [2018-08-22 15:31:45,129] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x00003e38] [2018-08-22 15:31:45,130] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x00003e38] [2018-08-22 15:31:45,156] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x00003e38] [2018-08-22 15:31:45,184] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x00003e38] [2018-08-22 15:31:45,184] - Script::install(): KBExtra is successfully!
 DEBUG root [0x00003e38] [2018-08-22 15:31:45,204] - loaded entity-script:Account(1).
 DEBUG root [0x00003e38] [2018-08-22 15:31:45,231] - loaded entity-script:Room(4).
  INFO root [0x00003e38] [2018-08-22 15:31:45,231] - TelnetServer server is running on port 50000
  INFO root [0x00003e38] [2018-08-22 15:31:45,525] - ---- cellapp is running ----
 DEBUG root [0x00003e38] [2018-08-22 15:31:45,525] - Components::process(): Request for the process of identity...
  WARN root [0x00003e38] [2018-08-22 15:31:51,625] - EntityApp::checkTickPeriod: tick took 6100% (6.10 seconds)!
  INFO root [0x00003e38] [2018-08-22 15:31:52,680] - Components::findComponents: find logger(1)...
  INFO root [0x00003e38] [2018-08-22 15:31:52,695] - Components::findComponents: found logger, addr:192.168.0.106:60953
  INFO root [0x00003e38] [2018-08-22 15:31:52,695] - Components::addComponent: reset orderLog, uid=23145!
  INFO root [0x00003e38] [2018-08-22 15:31:52,696] - Components::addComponent[logger], uid=23145, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00003e38] [2018-08-22 15:31:52,698] - Components::findComponents: find dbmgr(2)...
  INFO root [0x00003e38] [2018-08-22 15:31:52,801] - Components::findComponents: found dbmgr, addr:192.168.0.106:60950
  INFO root [0x00003e38] [2018-08-22 15:31:52,802] - Components::addComponent: reset orderLog, uid=23145!
  INFO root [0x00003e38] [2018-08-22 15:31:52,802] - Components::addComponent[dbmgr], uid=23145, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00003e38] [2018-08-22 15:31:52,803] - Components::findComponents: found dbmgr, addr:192.168.0.106:60950
  WARN root [0x00003e38] [2018-08-22 15:31:53,804] - Forwarding logs to logger[192.168.0.106:60953/0/0/0]...
 ERROR root [0x00003e38] [2018-08-22 15:52:19,753] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x00003e38] [2018-08-22 15:52:19,771] - The following logs sent to logger failed:
  WARN root [0x00003e38] [2018-08-22 15:52:19,772] - ==> [2018-08-22 15:52:19 750] TCPPacketReceiver::processPendingEvents(192.168.0.106:60953): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00003e38] [2018-08-22 15:52:19,772] - ==> [2018-08-22 15:52:19 754] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x00003e38] [2018-08-22 15:52:19,824] - TCPPacketReceiver::processPendingEvents(192.168.0.106:60950): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00003e38] [2018-08-22 15:52:19,828] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x00003e38] [2018-08-22 15:52:19,843] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [0x00003e38] [2018-08-22 15:52:19,849] - Shutdowner::onShutdown: shutting down
  INFO root [0x00003e38] [2018-08-22 15:52:19,850] - Spaces::destroySpace: 1.
  INFO root [0x00003e38] [2018-08-22 15:52:19,850] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [0x00003e38] [2018-08-22 15:52:19,850] - Account::~Account(): 2002
 DEBUG root [0x00003e38] [2018-08-22 15:52:19,851] - Account::~Account(): 2004
 DEBUG root [0x00003e38] [2018-08-22 15:52:19,851] - EntityRef::destroyObjPool(): size 16.
 DEBUG root [0x00003e38] [2018-08-22 15:52:19,851] - Witness::destroyObjPool(): size 16.
 DEBUG root [0x00003e38] [2018-08-22 15:52:19,859] - Room::~Room(): 2003
 ERROR root [0x00003e38] [2018-08-22 15:52:19,860] - PyGC::debugTracing(): EntityCall : leaked(2)
 DEBUG root [0x00003e38] [2018-08-22 15:52:19,860] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00003e38] [2018-08-22 15:52:19,860] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x00003e38] [2018-08-22 15:52:19,861] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x00003e38] [2018-08-22 15:52:19,861] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x00003e38] [2018-08-22 15:52:19,861] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x00003e38] [2018-08-22 15:52:19,861] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x00003e38] [2018-08-22 15:52:19,861] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x00003e38] [2018-08-22 15:52:19,861] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x00003e38] [2018-08-22 15:52:19,871] - Script::uninstall(): is successfully!
 DEBUG root [0x00003e38] [2018-08-22 15:52:19,871] - ThreadPool::destroy(): starting size 2.
  INFO root [0x00003160] [2018-08-22 15:52:21,162] - 
  INFO root [0x00003160] [2018-08-22 15:52:21,162] - -----------------------------------------------------------------------------------------


  INFO root [0x00003160] [2018-08-22 15:52:21,163] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [0x00003160] [2018-08-22 15:52:21,163] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [0x00003160] [2018-08-22 15:52:21,163] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [0x00003160] [2018-08-22 15:52:21,167] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:61155 )
  INFO root [0x00003160] [2018-08-22 15:52:21,167] - NetworkInterface::initialize(INTERNAL): address 192.168.0.106:61155, SOMAXCONN=5.
  INFO root [0x00003160] [2018-08-22 15:52:21,167] - server-configs:
  INFO root [0x00003160] [2018-08-22 15:52:21,167] - 	gameUpdateHertz : 10
  INFO root [0x00003160] [2018-08-22 15:52:21,167] - 	defaultViewRadius : 80
  INFO root [0x00003160] [2018-08-22 15:52:21,167] - 	defaultViewHysteresisArea : 5
  INFO root [0x00003160] [2018-08-22 15:52:21,167] - 	entryScriptFile : kbemain
  INFO root [0x00003160] [2018-08-22 15:52:21,167] - 	internalAddr : 192.168.0.106:61155
  INFO root [0x00003160] [2018-08-22 15:52:21,167] - 	componentID : 8001
  WARN root [0x00003160] [2018-08-22 15:52:21,478] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20673, errorno=10048
  INFO root [0x00003160] [2018-08-22 15:52:21,482] - ---- cellapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 85A70C5E64F896E0F1A60BF405B4EB07. Config: Debug X86. Built: 15:53:53 Apr 29 2018. AppID: 8001. UID: 27181. PID: 16200 ----
  INFO root [0x00003160] [2018-08-22 15:52:21,482] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [0x00003160] [2018-08-22 15:52:21,482] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00003160] [2018-08-22 15:52:21,482] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x00003160] [2018-08-22 15:52:21,608] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00003160] [2018-08-22 15:52:21,609] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x00003160] [2018-08-22 15:52:21,609] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x00003160] [2018-08-22 15:52:21,612] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x00003160] [2018-08-22 15:52:21,612] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x00003160] [2018-08-22 15:52:21,612] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x00003160] [2018-08-22 15:52:21,613] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x00003160] [2018-08-22 15:52:21,640] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x00003160] [2018-08-22 15:52:21,668] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x00003160] [2018-08-22 15:52:21,668] - Script::install(): KBExtra is successfully!
 DEBUG root [0x00003160] [2018-08-22 15:52:21,697] - loaded entity-script:Account(1).
 DEBUG root [0x00003160] [2018-08-22 15:52:21,723] - loaded entity-script:Room(4).
  INFO root [0x00003160] [2018-08-22 15:52:21,724] - TelnetServer server is running on port 50000
  INFO root [0x00003160] [2018-08-22 15:52:22,018] - ---- cellapp is running ----
 DEBUG root [0x00003160] [2018-08-22 15:52:22,019] - Components::process(): Request for the process of identity...
  WARN root [0x00003160] [2018-08-22 15:52:28,136] - EntityApp::checkTickPeriod: tick took 6117% (6.12 seconds)!
  INFO root [0x00003160] [2018-08-22 15:52:29,164] - Components::findComponents: find logger(1)...
  INFO root [0x00003160] [2018-08-22 15:52:29,243] - Components::findComponents: found logger, addr:192.168.0.106:61152
  INFO root [0x00003160] [2018-08-22 15:52:29,244] - Components::addComponent: reset orderLog, uid=27181!
  INFO root [0x00003160] [2018-08-22 15:52:29,244] - Components::addComponent[logger], uid=27181, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00003160] [2018-08-22 15:52:29,246] - Components::findComponents: find dbmgr(2)...
  INFO root [0x00003160] [2018-08-22 15:52:29,349] - Components::findComponents: found dbmgr, addr:192.168.0.106:61154
  INFO root [0x00003160] [2018-08-22 15:52:29,350] - Components::addComponent: reset orderLog, uid=27181!
  INFO root [0x00003160] [2018-08-22 15:52:29,350] - Components::addComponent[dbmgr], uid=27181, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00003160] [2018-08-22 15:52:29,350] - Components::findComponents: found dbmgr, addr:192.168.0.106:61154
  WARN root [0x00003160] [2018-08-22 15:52:30,350] - Forwarding logs to logger[192.168.0.106:61152/0/0/0]...
 ERROR root [0x00003160] [2018-08-22 15:54:05,525] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x00003160] [2018-08-22 15:54:05,544] - The following logs sent to logger failed:
  WARN root [0x00003160] [2018-08-22 15:54:05,544] - ==> [2018-08-22 15:54:05 521] TCPPacketReceiver::processPendingEvents(192.168.0.106:61152): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00003160] [2018-08-22 15:54:05,545] - ==> [2018-08-22 15:54:05 525] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x00003160] [2018-08-22 15:54:05,598] - TCPPacketReceiver::processPendingEvents(192.168.0.106:61154): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00003160] [2018-08-22 15:54:05,602] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x00003160] [2018-08-22 15:54:05,602] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [0x00003160] [2018-08-22 15:54:05,616] - Shutdowner::onShutdown: shutting down
  INFO root [0x00003160] [2018-08-22 15:54:05,617] - Spaces::destroySpace: 1.
  INFO root [0x00003160] [2018-08-22 15:54:05,618] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [0x00003160] [2018-08-22 15:54:05,618] - Account::~Account(): 2002
 DEBUG root [0x00003160] [2018-08-22 15:54:05,618] - Account::~Account(): 2004
 DEBUG root [0x00003160] [2018-08-22 15:54:05,618] - EntityRef::destroyObjPool(): size 16.
 DEBUG root [0x00003160] [2018-08-22 15:54:05,618] - Witness::destroyObjPool(): size 16.
 DEBUG root [0x00003160] [2018-08-22 15:54:05,626] - Room::~Room(): 2003
 ERROR root [0x00003160] [2018-08-22 15:54:05,627] - PyGC::debugTracing(): EntityCall : leaked(2)
 DEBUG root [0x00003160] [2018-08-22 15:54:05,628] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00003160] [2018-08-22 15:54:05,628] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x00003160] [2018-08-22 15:54:05,628] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x00003160] [2018-08-22 15:54:05,628] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x00003160] [2018-08-22 15:54:05,629] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x00003160] [2018-08-22 15:54:05,629] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x00003160] [2018-08-22 15:54:05,629] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x00003160] [2018-08-22 15:54:05,629] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x00003160] [2018-08-22 15:54:05,639] - Script::uninstall(): is successfully!
 DEBUG root [0x00003160] [2018-08-22 15:54:05,639] - ThreadPool::destroy(): starting size 2.
  INFO root [0x00003654] [2018-08-22 15:54:06,948] - 
  INFO root [0x00003654] [2018-08-22 15:54:06,950] - -----------------------------------------------------------------------------------------


  INFO root [0x00003654] [2018-08-22 15:54:06,951] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [0x00003654] [2018-08-22 15:54:06,951] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [0x00003654] [2018-08-22 15:54:06,951] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [0x00003654] [2018-08-22 15:54:06,954] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:61229 )
  INFO root [0x00003654] [2018-08-22 15:54:06,954] - NetworkInterface::initialize(INTERNAL): address 192.168.0.106:61229, SOMAXCONN=5.
  INFO root [0x00003654] [2018-08-22 15:54:06,954] - server-configs:
  INFO root [0x00003654] [2018-08-22 15:54:06,954] - 	gameUpdateHertz : 10
  INFO root [0x00003654] [2018-08-22 15:54:06,954] - 	defaultViewRadius : 80
  INFO root [0x00003654] [2018-08-22 15:54:06,954] - 	defaultViewHysteresisArea : 5
  INFO root [0x00003654] [2018-08-22 15:54:06,954] - 	entryScriptFile : kbemain
  INFO root [0x00003654] [2018-08-22 15:54:06,954] - 	internalAddr : 192.168.0.106:61229
  INFO root [0x00003654] [2018-08-22 15:54:06,955] - 	componentID : 8001
  WARN root [0x00003654] [2018-08-22 15:54:07,265] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20439, errorno=10048
  INFO root [0x00003654] [2018-08-22 15:54:07,269] - ---- cellapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 85A70C5E64F896E0F1A60BF405B4EB07. Config: Debug X86. Built: 15:53:53 Apr 29 2018. AppID: 8001. UID: 27528. PID: 15260 ----
  INFO root [0x00003654] [2018-08-22 15:54:07,269] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [0x00003654] [2018-08-22 15:54:07,269] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00003654] [2018-08-22 15:54:07,269] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x00003654] [2018-08-22 15:54:07,395] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00003654] [2018-08-22 15:54:07,396] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x00003654] [2018-08-22 15:54:07,396] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x00003654] [2018-08-22 15:54:07,399] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x00003654] [2018-08-22 15:54:07,399] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x00003654] [2018-08-22 15:54:07,399] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x00003654] [2018-08-22 15:54:07,400] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x00003654] [2018-08-22 15:54:07,427] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x00003654] [2018-08-22 15:54:07,455] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x00003654] [2018-08-22 15:54:07,455] - Script::install(): KBExtra is successfully!
 DEBUG root [0x00003654] [2018-08-22 15:54:07,474] - loaded entity-script:Account(1).
 DEBUG root [0x00003654] [2018-08-22 15:54:07,506] - loaded entity-script:Room(4).
  INFO root [0x00003654] [2018-08-22 15:54:07,506] - TelnetServer server is running on port 50000
  INFO root [0x00003654] [2018-08-22 15:54:07,808] - ---- cellapp is running ----
 DEBUG root [0x00003654] [2018-08-22 15:54:07,809] - Components::process(): Request for the process of identity...
  WARN root [0x00003654] [2018-08-22 15:54:13,888] - EntityApp::checkTickPeriod: tick took 6079% (6.08 seconds)!
  INFO root [0x00003654] [2018-08-22 15:54:14,909] - Components::findComponents: find logger(1)...
  INFO root [0x00003654] [2018-08-22 15:54:14,971] - Components::findComponents: found logger, addr:192.168.0.106:61224
  INFO root [0x00003654] [2018-08-22 15:54:14,971] - Components::addComponent: reset orderLog, uid=27528!
  INFO root [0x00003654] [2018-08-22 15:54:14,972] - Components::addComponent[logger], uid=27528, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00003654] [2018-08-22 15:54:14,974] - Components::findComponents: find dbmgr(2)...
  INFO root [0x00003654] [2018-08-22 15:54:15,074] - Components::findComponents: found dbmgr, addr:192.168.0.106:61225
  INFO root [0x00003654] [2018-08-22 15:54:15,075] - Components::addComponent: reset orderLog, uid=27528!
  INFO root [0x00003654] [2018-08-22 15:54:15,075] - Components::addComponent[dbmgr], uid=27528, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00003654] [2018-08-22 15:54:15,075] - Components::findComponents: found dbmgr, addr:192.168.0.106:61225
  WARN root [0x00003654] [2018-08-22 15:54:16,076] - EntityApp::checkTickPeriod: tick took 1267% (1.27 seconds)!
  WARN root [0x00003654] [2018-08-22 15:54:16,076] - Forwarding logs to logger[192.168.0.106:61224/0/0/0]...
 ERROR root [0x00003654] [2018-08-22 16:00:25,547] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x00003654] [2018-08-22 16:00:25,564] - The following logs sent to logger failed:
  WARN root [0x00003654] [2018-08-22 16:00:25,564] - ==> [2018-08-22 16:00:25 543] TCPPacketReceiver::processPendingEvents(192.168.0.106:61224): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00003654] [2018-08-22 16:00:25,565] - ==> [2018-08-22 16:00:25 547] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x00003654] [2018-08-22 16:00:25,619] - TCPPacketReceiver::processPendingEvents(192.168.0.106:61225): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00003654] [2018-08-22 16:00:25,623] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x00003654] [2018-08-22 16:00:25,639] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [0x00003654] [2018-08-22 16:00:25,640] - Shutdowner::onShutdown: shutting down
  INFO root [0x00003654] [2018-08-22 16:00:25,641] - Spaces::destroySpace: 1.
  INFO root [0x00003654] [2018-08-22 16:00:25,641] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [0x00003654] [2018-08-22 16:00:25,642] - Account::~Account(): 2002
 DEBUG root [0x00003654] [2018-08-22 16:00:25,642] - Account::~Account(): 2004
 DEBUG root [0x00003654] [2018-08-22 16:00:25,642] - EntityRef::destroyObjPool(): size 16.
 DEBUG root [0x00003654] [2018-08-22 16:00:25,642] - Witness::destroyObjPool(): size 16.
 DEBUG root [0x00003654] [2018-08-22 16:00:25,650] - Room::~Room(): 2003
 ERROR root [0x00003654] [2018-08-22 16:00:25,651] - PyGC::debugTracing(): EntityCall : leaked(2)
 DEBUG root [0x00003654] [2018-08-22 16:00:25,652] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00003654] [2018-08-22 16:00:25,652] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x00003654] [2018-08-22 16:00:25,652] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x00003654] [2018-08-22 16:00:25,653] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x00003654] [2018-08-22 16:00:25,653] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x00003654] [2018-08-22 16:00:25,653] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x00003654] [2018-08-22 16:00:25,653] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x00003654] [2018-08-22 16:00:25,653] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x00003654] [2018-08-22 16:00:25,663] - Script::uninstall(): is successfully!
 DEBUG root [0x00003654] [2018-08-22 16:00:25,664] - ThreadPool::destroy(): starting size 2.
  INFO root [0x00003d34] [2018-08-22 16:00:26,949] - 
  INFO root [0x00003d34] [2018-08-22 16:00:26,950] - -----------------------------------------------------------------------------------------


  INFO root [0x00003d34] [2018-08-22 16:00:26,951] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [0x00003d34] [2018-08-22 16:00:26,951] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [0x00003d34] [2018-08-22 16:00:26,951] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [0x00003d34] [2018-08-22 16:00:26,954] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:61313 )
  INFO root [0x00003d34] [2018-08-22 16:00:26,954] - NetworkInterface::initialize(INTERNAL): address 192.168.0.106:61313, SOMAXCONN=5.
  INFO root [0x00003d34] [2018-08-22 16:00:26,955] - server-configs:
  INFO root [0x00003d34] [2018-08-22 16:00:26,955] - 	gameUpdateHertz : 10
  INFO root [0x00003d34] [2018-08-22 16:00:26,955] - 	defaultViewRadius : 80
  INFO root [0x00003d34] [2018-08-22 16:00:26,955] - 	defaultViewHysteresisArea : 5
  INFO root [0x00003d34] [2018-08-22 16:00:26,955] - 	entryScriptFile : kbemain
  INFO root [0x00003d34] [2018-08-22 16:00:26,955] - 	internalAddr : 192.168.0.106:61313
  INFO root [0x00003d34] [2018-08-22 16:00:26,955] - 	componentID : 8001
  INFO root [0x00003d34] [2018-08-22 16:00:28,464] - ---- cellapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 85A70C5E64F896E0F1A60BF405B4EB07. Config: Debug X86. Built: 15:53:53 Apr 29 2018. AppID: 8001. UID: 28768. PID: 15476 ----
  INFO root [0x00003d34] [2018-08-22 16:00:28,465] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [0x00003d34] [2018-08-22 16:00:28,465] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00003d34] [2018-08-22 16:00:28,465] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x00003d34] [2018-08-22 16:00:28,615] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00003d34] [2018-08-22 16:00:28,615] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x00003d34] [2018-08-22 16:00:28,616] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x00003d34] [2018-08-22 16:00:28,619] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x00003d34] [2018-08-22 16:00:28,619] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x00003d34] [2018-08-22 16:00:28,619] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x00003d34] [2018-08-22 16:00:28,619] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x00003d34] [2018-08-22 16:00:28,647] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x00003d34] [2018-08-22 16:00:28,677] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x00003d34] [2018-08-22 16:00:28,677] - Script::install(): KBExtra is successfully!
 DEBUG root [0x00003d34] [2018-08-22 16:00:28,696] - loaded entity-script:Account(1).
 DEBUG root [0x00003d34] [2018-08-22 16:00:28,721] - loaded entity-script:Room(4).
  INFO root [0x00003d34] [2018-08-22 16:00:28,721] - TelnetServer server is running on port 50000
  INFO root [0x00003d34] [2018-08-22 16:00:29,013] - ---- cellapp is running ----
 DEBUG root [0x00003d34] [2018-08-22 16:00:29,014] - Components::process(): Request for the process of identity...
  WARN root [0x00003d34] [2018-08-22 16:00:35,082] - EntityApp::checkTickPeriod: tick took 6068% (6.07 seconds)!
  INFO root [0x00003d34] [2018-08-22 16:00:36,114] - Components::findComponents: find logger(1)...
  INFO root [0x00003d34] [2018-08-22 16:00:36,138] - Components::findComponents: found logger, addr:192.168.0.106:61308
  INFO root [0x00003d34] [2018-08-22 16:00:36,138] - Components::addComponent: reset orderLog, uid=28768!
  INFO root [0x00003d34] [2018-08-22 16:00:36,139] - Components::addComponent[logger], uid=28768, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00003d34] [2018-08-22 16:00:36,140] - Components::findComponents: find dbmgr(2)...
  INFO root [0x00003d34] [2018-08-22 16:00:36,242] - Components::findComponents: found dbmgr, addr:192.168.0.106:61311
  INFO root [0x00003d34] [2018-08-22 16:00:36,243] - Components::addComponent: reset orderLog, uid=28768!
  INFO root [0x00003d34] [2018-08-22 16:00:36,243] - Components::addComponent[dbmgr], uid=28768, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00003d34] [2018-08-22 16:00:36,244] - Components::findComponents: found dbmgr, addr:192.168.0.106:61311
  WARN root [0x00003d34] [2018-08-22 16:00:37,244] - EntityApp::checkTickPeriod: tick took 1230% (1.23 seconds)!
  WARN root [0x00003d34] [2018-08-22 16:00:37,246] - Forwarding logs to logger[192.168.0.106:61308/0/0/0]...
 ERROR root [0x00003d34] [2018-08-22 16:09:48,434] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x00003d34] [2018-08-22 16:09:48,453] - The following logs sent to logger failed:
  WARN root [0x00003d34] [2018-08-22 16:09:48,453] - ==> [2018-08-22 16:09:48 430] TCPPacketReceiver::processPendingEvents(192.168.0.106:61308): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00003d34] [2018-08-22 16:09:48,453] - ==> [2018-08-22 16:09:48 434] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x00003d34] [2018-08-22 16:09:48,508] - TCPPacketReceiver::processPendingEvents(192.168.0.106:61311): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00003d34] [2018-08-22 16:09:48,512] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x00003d34] [2018-08-22 16:09:48,530] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [0x00003d34] [2018-08-22 16:09:48,532] - Shutdowner::onShutdown: shutting down
  INFO root [0x00003d34] [2018-08-22 16:09:48,533] - Spaces::destroySpace: 1.
  INFO root [0x00003d34] [2018-08-22 16:09:48,533] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [0x00003d34] [2018-08-22 16:09:48,533] - Account::~Account(): 2
 DEBUG root [0x00003d34] [2018-08-22 16:09:48,534] - Account::~Account(): 4
 DEBUG root [0x00003d34] [2018-08-22 16:09:48,534] - EntityRef::destroyObjPool(): size 16.
 DEBUG root [0x00003d34] [2018-08-22 16:09:48,534] - Witness::destroyObjPool(): size 16.
 DEBUG root [0x00003d34] [2018-08-22 16:09:48,542] - Room::~Room(): 3
 ERROR root [0x00003d34] [2018-08-22 16:09:48,543] - PyGC::debugTracing(): EntityCall : leaked(2)
 DEBUG root [0x00003d34] [2018-08-22 16:09:48,543] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00003d34] [2018-08-22 16:09:48,543] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x00003d34] [2018-08-22 16:09:48,544] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x00003d34] [2018-08-22 16:09:48,544] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x00003d34] [2018-08-22 16:09:48,544] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x00003d34] [2018-08-22 16:09:48,544] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x00003d34] [2018-08-22 16:09:48,544] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x00003d34] [2018-08-22 16:09:48,544] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x00003d34] [2018-08-22 16:09:48,554] - Script::uninstall(): is successfully!
 DEBUG root [0x00003d34] [2018-08-22 16:09:48,555] - ThreadPool::destroy(): starting size 2.
  INFO root [0x0000307c] [2018-08-22 16:09:49,841] - 
  INFO root [0x0000307c] [2018-08-22 16:09:49,842] - -----------------------------------------------------------------------------------------


  INFO root [0x0000307c] [2018-08-22 16:09:49,843] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [0x0000307c] [2018-08-22 16:09:49,843] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [0x0000307c] [2018-08-22 16:09:49,844] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [0x0000307c] [2018-08-22 16:09:49,849] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:64636 )
  INFO root [0x0000307c] [2018-08-22 16:09:49,850] - NetworkInterface::initialize(INTERNAL): address 192.168.0.106:64636, SOMAXCONN=5.
  INFO root [0x0000307c] [2018-08-22 16:09:49,850] - server-configs:
  INFO root [0x0000307c] [2018-08-22 16:09:49,850] - 	gameUpdateHertz : 10
  INFO root [0x0000307c] [2018-08-22 16:09:49,850] - 	defaultViewRadius : 80
  INFO root [0x0000307c] [2018-08-22 16:09:49,850] - 	defaultViewHysteresisArea : 5
  INFO root [0x0000307c] [2018-08-22 16:09:49,850] - 	entryScriptFile : kbemain
  INFO root [0x0000307c] [2018-08-22 16:09:49,850] - 	internalAddr : 192.168.0.106:64636
  INFO root [0x0000307c] [2018-08-22 16:09:49,850] - 	componentID : 8001
  WARN root [0x0000307c] [2018-08-22 16:09:50,161] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20368, errorno=10048
  INFO root [0x0000307c] [2018-08-22 16:09:50,164] - ---- cellapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 85A70C5E64F896E0F1A60BF405B4EB07. Config: Debug X86. Built: 15:53:53 Apr 29 2018. AppID: 8001. UID: 30607. PID: 16644 ----
  INFO root [0x0000307c] [2018-08-22 16:09:50,165] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [0x0000307c] [2018-08-22 16:09:50,165] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x0000307c] [2018-08-22 16:09:50,165] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x0000307c] [2018-08-22 16:09:50,293] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x0000307c] [2018-08-22 16:09:50,294] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x0000307c] [2018-08-22 16:09:50,294] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x0000307c] [2018-08-22 16:09:50,297] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x0000307c] [2018-08-22 16:09:50,297] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x0000307c] [2018-08-22 16:09:50,297] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x0000307c] [2018-08-22 16:09:50,298] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x0000307c] [2018-08-22 16:09:50,329] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x0000307c] [2018-08-22 16:09:50,362] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x0000307c] [2018-08-22 16:09:50,362] - Script::install(): KBExtra is successfully!
 DEBUG root [0x0000307c] [2018-08-22 16:09:50,381] - loaded entity-script:Account(1).
 DEBUG root [0x0000307c] [2018-08-22 16:09:50,406] - loaded entity-script:Room(4).
  INFO root [0x0000307c] [2018-08-22 16:09:50,407] - TelnetServer server is running on port 50000
  INFO root [0x0000307c] [2018-08-22 16:09:50,710] - ---- cellapp is running ----
 DEBUG root [0x0000307c] [2018-08-22 16:09:50,710] - Components::process(): Request for the process of identity...
  WARN root [0x0000307c] [2018-08-22 16:09:56,806] - EntityApp::checkTickPeriod: tick took 6096% (6.10 seconds)!
  INFO root [0x0000307c] [2018-08-22 16:09:57,845] - Components::findComponents: find logger(1)...
  INFO root [0x0000307c] [2018-08-22 16:09:57,952] - Components::findComponents: found logger, addr:192.168.0.106:64639
  INFO root [0x0000307c] [2018-08-22 16:09:57,952] - Components::addComponent: reset orderLog, uid=30607!
  INFO root [0x0000307c] [2018-08-22 16:09:57,953] - Components::addComponent[logger], uid=30607, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x0000307c] [2018-08-22 16:09:57,955] - Components::findComponents: find dbmgr(2)...
  INFO root [0x0000307c] [2018-08-22 16:09:58,058] - Components::findComponents: found dbmgr, addr:192.168.0.106:64633
  INFO root [0x0000307c] [2018-08-22 16:09:58,060] - Components::addComponent: reset orderLog, uid=30607!
  INFO root [0x0000307c] [2018-08-22 16:09:58,060] - Components::addComponent[dbmgr], uid=30607, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x0000307c] [2018-08-22 16:09:58,061] - Components::findComponents: found dbmgr, addr:192.168.0.106:64633
  WARN root [0x0000307c] [2018-08-22 16:09:59,061] - Forwarding logs to logger[192.168.0.106:64639/0/0/0]...
 ERROR root [0x0000307c] [2018-08-22 16:12:16,125] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x0000307c] [2018-08-22 16:12:16,145] - The following logs sent to logger failed:
  WARN root [0x0000307c] [2018-08-22 16:12:16,146] - ==> [2018-08-22 16:12:16 121] TCPPacketReceiver::processPendingEvents(192.168.0.106:64639): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x0000307c] [2018-08-22 16:12:16,146] - ==> [2018-08-22 16:12:16 125] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x0000307c] [2018-08-22 16:12:16,198] - TCPPacketReceiver::processPendingEvents(192.168.0.106:64633): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x0000307c] [2018-08-22 16:12:16,203] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x0000307c] [2018-08-22 16:12:16,220] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [0x0000307c] [2018-08-22 16:12:16,222] - Shutdowner::onShutdown: shutting down
  INFO root [0x0000307c] [2018-08-22 16:12:16,223] - Spaces::destroySpace: 1.
  INFO root [0x0000307c] [2018-08-22 16:12:16,223] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [0x0000307c] [2018-08-22 16:12:16,223] - Account::~Account(): 2002
 DEBUG root [0x0000307c] [2018-08-22 16:12:16,223] - Account::~Account(): 2004
 DEBUG root [0x0000307c] [2018-08-22 16:12:16,224] - EntityRef::destroyObjPool(): size 16.
 DEBUG root [0x0000307c] [2018-08-22 16:12:16,224] - Witness::destroyObjPool(): size 16.
 DEBUG root [0x0000307c] [2018-08-22 16:12:16,231] - Room::~Room(): 2003
 ERROR root [0x0000307c] [2018-08-22 16:12:16,232] - PyGC::debugTracing(): EntityCall : leaked(2)
 DEBUG root [0x0000307c] [2018-08-22 16:12:16,234] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x0000307c] [2018-08-22 16:12:16,234] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x0000307c] [2018-08-22 16:12:16,234] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x0000307c] [2018-08-22 16:12:16,235] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x0000307c] [2018-08-22 16:12:16,235] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x0000307c] [2018-08-22 16:12:16,235] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x0000307c] [2018-08-22 16:12:16,235] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x0000307c] [2018-08-22 16:12:16,235] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x0000307c] [2018-08-22 16:12:16,246] - Script::uninstall(): is successfully!
 DEBUG root [0x0000307c] [2018-08-22 16:12:16,246] - ThreadPool::destroy(): starting size 2.
  INFO root [0x00001798] [2018-08-22 16:12:17,532] - 
  INFO root [0x00001798] [2018-08-22 16:12:17,534] - -----------------------------------------------------------------------------------------


  INFO root [0x00001798] [2018-08-22 16:12:17,535] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [0x00001798] [2018-08-22 16:12:17,535] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [0x00001798] [2018-08-22 16:12:17,535] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [0x00001798] [2018-08-22 16:12:17,541] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:64693 )
  INFO root [0x00001798] [2018-08-22 16:12:17,541] - NetworkInterface::initialize(INTERNAL): address 192.168.0.106:64693, SOMAXCONN=5.
  INFO root [0x00001798] [2018-08-22 16:12:17,541] - server-configs:
  INFO root [0x00001798] [2018-08-22 16:12:17,541] - 	gameUpdateHertz : 10
  INFO root [0x00001798] [2018-08-22 16:12:17,541] - 	defaultViewRadius : 80
  INFO root [0x00001798] [2018-08-22 16:12:17,542] - 	defaultViewHysteresisArea : 5
  INFO root [0x00001798] [2018-08-22 16:12:17,542] - 	entryScriptFile : kbemain
  INFO root [0x00001798] [2018-08-22 16:12:17,542] - 	internalAddr : 192.168.0.106:64693
  INFO root [0x00001798] [2018-08-22 16:12:17,542] - 	componentID : 8001
  WARN root [0x00001798] [2018-08-22 16:12:17,856] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20128, errorno=10048
  INFO root [0x00001798] [2018-08-22 16:12:17,861] - ---- cellapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 85A70C5E64F896E0F1A60BF405B4EB07. Config: Debug X86. Built: 15:53:53 Apr 29 2018. AppID: 8001. UID: 31087. PID: 16004 ----
  INFO root [0x00001798] [2018-08-22 16:12:17,861] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [0x00001798] [2018-08-22 16:12:17,861] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00001798] [2018-08-22 16:12:17,862] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x00001798] [2018-08-22 16:12:17,989] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00001798] [2018-08-22 16:12:17,990] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x00001798] [2018-08-22 16:12:17,990] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x00001798] [2018-08-22 16:12:17,993] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x00001798] [2018-08-22 16:12:17,993] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x00001798] [2018-08-22 16:12:17,994] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x00001798] [2018-08-22 16:12:17,994] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x00001798] [2018-08-22 16:12:18,021] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x00001798] [2018-08-22 16:12:18,049] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x00001798] [2018-08-22 16:12:18,049] - Script::install(): KBExtra is successfully!
 DEBUG root [0x00001798] [2018-08-22 16:12:18,068] - loaded entity-script:Account(1).
 DEBUG root [0x00001798] [2018-08-22 16:12:18,096] - loaded entity-script:Room(4).
  INFO root [0x00001798] [2018-08-22 16:12:18,096] - TelnetServer server is running on port 50000
  INFO root [0x00001798] [2018-08-22 16:12:18,391] - ---- cellapp is running ----
 DEBUG root [0x00001798] [2018-08-22 16:12:18,391] - Components::process(): Request for the process of identity...
  WARN root [0x00001798] [2018-08-22 16:12:24,461] - EntityApp::checkTickPeriod: tick took 6069% (6.07 seconds)!
  INFO root [0x00001798] [2018-08-22 16:12:25,492] - Components::findComponents: find logger(1)...
  INFO root [0x00001798] [2018-08-22 16:12:25,555] - Components::findComponents: found logger, addr:192.168.0.106:64699
  INFO root [0x00001798] [2018-08-22 16:12:25,556] - Components::addComponent: reset orderLog, uid=31087!
  INFO root [0x00001798] [2018-08-22 16:12:25,557] - Components::addComponent[logger], uid=31087, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00001798] [2018-08-22 16:12:25,559] - Components::findComponents: find dbmgr(2)...
  INFO root [0x00001798] [2018-08-22 16:12:25,658] - Components::findComponents: found dbmgr, addr:192.168.0.106:64692
  INFO root [0x00001798] [2018-08-22 16:12:25,658] - Components::addComponent: reset orderLog, uid=31087!
  INFO root [0x00001798] [2018-08-22 16:12:25,659] - Components::addComponent[dbmgr], uid=31087, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00001798] [2018-08-22 16:12:25,659] - Components::findComponents: found dbmgr, addr:192.168.0.106:64692
  WARN root [0x00001798] [2018-08-22 16:12:26,659] - EntityApp::checkTickPeriod: tick took 1267% (1.27 seconds)!
  WARN root [0x00001798] [2018-08-22 16:12:26,662] - Forwarding logs to logger[192.168.0.106:64699/0/0/0]...
 ERROR root [0x00001798] [2018-08-22 16:16:33,558] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x00001798] [2018-08-22 16:16:33,569] - The following logs sent to logger failed:
  WARN root [0x00001798] [2018-08-22 16:16:33,569] - ==> [2018-08-22 16:16:33 548] TCPPacketReceiver::processPendingEvents(192.168.0.106:64699): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00001798] [2018-08-22 16:16:33,569] - ==> [2018-08-22 16:16:33 559] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x00001798] [2018-08-22 16:16:33,624] - TCPPacketReceiver::processPendingEvents(192.168.0.106:64692): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00001798] [2018-08-22 16:16:33,638] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x00001798] [2018-08-22 16:16:33,644] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [0x00001798] [2018-08-22 16:16:33,646] - Shutdowner::onShutdown: shutting down
  INFO root [0x00001798] [2018-08-22 16:16:33,647] - Spaces::destroySpace: 1.
  INFO root [0x00001798] [2018-08-22 16:16:33,647] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [0x00001798] [2018-08-22 16:16:33,648] - Account::~Account(): 2002
 DEBUG root [0x00001798] [2018-08-22 16:16:33,648] - Account::~Account(): 2004
 DEBUG root [0x00001798] [2018-08-22 16:16:33,648] - EntityRef::destroyObjPool(): size 16.
 DEBUG root [0x00001798] [2018-08-22 16:16:33,648] - Witness::destroyObjPool(): size 16.
 DEBUG root [0x00001798] [2018-08-22 16:16:33,656] - Room::~Room(): 2003
 ERROR root [0x00001798] [2018-08-22 16:16:33,657] - PyGC::debugTracing(): EntityCall : leaked(2)
 DEBUG root [0x00001798] [2018-08-22 16:16:33,658] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00001798] [2018-08-22 16:16:33,658] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x00001798] [2018-08-22 16:16:33,658] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x00001798] [2018-08-22 16:16:33,658] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x00001798] [2018-08-22 16:16:33,658] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x00001798] [2018-08-22 16:16:33,658] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x00001798] [2018-08-22 16:16:33,658] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x00001798] [2018-08-22 16:16:33,658] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x00001798] [2018-08-22 16:16:33,668] - Script::uninstall(): is successfully!
 DEBUG root [0x00001798] [2018-08-22 16:16:33,668] - ThreadPool::destroy(): starting size 2.
  INFO root [0x00000348] [2018-08-22 16:16:34,941] - 
  INFO root [0x00000348] [2018-08-22 16:16:34,943] - -----------------------------------------------------------------------------------------


  INFO root [0x00000348] [2018-08-22 16:16:34,944] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [0x00000348] [2018-08-22 16:16:34,945] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [0x00000348] [2018-08-22 16:16:34,945] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [0x00000348] [2018-08-22 16:16:34,951] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:64783 )
  INFO root [0x00000348] [2018-08-22 16:16:34,951] - NetworkInterface::initialize(INTERNAL): address 192.168.0.106:64783, SOMAXCONN=5.
  INFO root [0x00000348] [2018-08-22 16:16:34,951] - server-configs:
  INFO root [0x00000348] [2018-08-22 16:16:34,951] - 	gameUpdateHertz : 10
  INFO root [0x00000348] [2018-08-22 16:16:34,951] - 	defaultViewRadius : 80
  INFO root [0x00000348] [2018-08-22 16:16:34,951] - 	defaultViewHysteresisArea : 5
  INFO root [0x00000348] [2018-08-22 16:16:34,951] - 	entryScriptFile : kbemain
  INFO root [0x00000348] [2018-08-22 16:16:34,951] - 	internalAddr : 192.168.0.106:64783
  INFO root [0x00000348] [2018-08-22 16:16:34,951] - 	componentID : 8001
  INFO root [0x00000348] [2018-08-22 16:16:36,466] - ---- cellapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 85A70C5E64F896E0F1A60BF405B4EB07. Config: Debug X86. Built: 15:53:53 Apr 29 2018. AppID: 8001. UID: 31930. PID: 16956 ----
  INFO root [0x00000348] [2018-08-22 16:16:36,467] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [0x00000348] [2018-08-22 16:16:36,468] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00000348] [2018-08-22 16:16:36,468] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x00000348] [2018-08-22 16:16:36,624] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00000348] [2018-08-22 16:16:36,625] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x00000348] [2018-08-22 16:16:36,625] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x00000348] [2018-08-22 16:16:36,629] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x00000348] [2018-08-22 16:16:36,629] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x00000348] [2018-08-22 16:16:36,629] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x00000348] [2018-08-22 16:16:36,629] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x00000348] [2018-08-22 16:16:36,660] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x00000348] [2018-08-22 16:16:36,690] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x00000348] [2018-08-22 16:16:36,690] - Script::install(): KBExtra is successfully!
 DEBUG root [0x00000348] [2018-08-22 16:16:36,710] - loaded entity-script:Account(1).
 DEBUG root [0x00000348] [2018-08-22 16:16:36,737] - loaded entity-script:Room(4).
  INFO root [0x00000348] [2018-08-22 16:16:36,737] - TelnetServer server is running on port 50000
  INFO root [0x00000348] [2018-08-22 16:16:37,082] - ---- cellapp is running ----
 DEBUG root [0x00000348] [2018-08-22 16:16:37,083] - Components::process(): Request for the process of identity...
  WARN root [0x00000348] [2018-08-22 16:16:43,162] - EntityApp::checkTickPeriod: tick took 6080% (6.08 seconds)!
  INFO root [0x00000348] [2018-08-22 16:16:44,248] - Components::findComponents: find logger(1)...
  INFO root [0x00000348] [2018-08-22 16:16:44,268] - Components::findComponents: found logger, addr:192.168.0.106:64786
  INFO root [0x00000348] [2018-08-22 16:16:44,268] - Components::addComponent: reset orderLog, uid=31930!
  INFO root [0x00000348] [2018-08-22 16:16:44,269] - Components::addComponent[logger], uid=31930, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00000348] [2018-08-22 16:16:44,271] - Components::findComponents: find dbmgr(2)...
  INFO root [0x00000348] [2018-08-22 16:16:44,371] - Components::findComponents: found dbmgr, addr:192.168.0.106:64779
  INFO root [0x00000348] [2018-08-22 16:16:44,372] - Components::addComponent: reset orderLog, uid=31930!
  INFO root [0x00000348] [2018-08-22 16:16:44,372] - Components::addComponent[dbmgr], uid=31930, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00000348] [2018-08-22 16:16:44,372] - Components::findComponents: found dbmgr, addr:192.168.0.106:64779
  WARN root [0x00000348] [2018-08-22 16:16:45,372] - Forwarding logs to logger[192.168.0.106:64786/0/0/0]...
 ERROR root [0x00000348] [2018-08-22 16:18:51,613] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x00000348] [2018-08-22 16:18:51,634] - The following logs sent to logger failed:
  WARN root [0x00000348] [2018-08-22 16:18:51,634] - ==> [2018-08-22 16:18:51 609] TCPPacketReceiver::processPendingEvents(192.168.0.106:64786): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00000348] [2018-08-22 16:18:51,634] - ==> [2018-08-22 16:18:51 614] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x00000348] [2018-08-22 16:18:51,694] - TCPPacketReceiver::processPendingEvents(192.168.0.106:64779): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00000348] [2018-08-22 16:18:51,709] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x00000348] [2018-08-22 16:18:51,715] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [0x00000348] [2018-08-22 16:18:51,717] - Shutdowner::onShutdown: shutting down
  INFO root [0x00000348] [2018-08-22 16:18:51,718] - Spaces::destroySpace: 1.
  INFO root [0x00000348] [2018-08-22 16:18:51,718] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [0x00000348] [2018-08-22 16:18:51,719] - Account::~Account(): 2002
 DEBUG root [0x00000348] [2018-08-22 16:18:51,719] - Account::~Account(): 2004
 DEBUG root [0x00000348] [2018-08-22 16:18:51,719] - EntityRef::destroyObjPool(): size 16.
 DEBUG root [0x00000348] [2018-08-22 16:18:51,719] - Witness::destroyObjPool(): size 16.
 DEBUG root [0x00000348] [2018-08-22 16:18:51,727] - Room::~Room(): 2003
 ERROR root [0x00000348] [2018-08-22 16:18:51,728] - PyGC::debugTracing(): EntityCall : leaked(2)
 DEBUG root [0x00000348] [2018-08-22 16:18:51,729] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00000348] [2018-08-22 16:18:51,729] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x00000348] [2018-08-22 16:18:51,729] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x00000348] [2018-08-22 16:18:51,729] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x00000348] [2018-08-22 16:18:51,729] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x00000348] [2018-08-22 16:18:51,729] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x00000348] [2018-08-22 16:18:51,729] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x00000348] [2018-08-22 16:18:51,729] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x00000348] [2018-08-22 16:18:51,740] - Script::uninstall(): is successfully!
 DEBUG root [0x00000348] [2018-08-22 16:18:51,741] - ThreadPool::destroy(): starting size 2.
  INFO root [0x00003028] [2018-08-22 16:18:53,059] - 
  INFO root [0x00003028] [2018-08-22 16:18:53,060] - -----------------------------------------------------------------------------------------


  INFO root [0x00003028] [2018-08-22 16:18:53,061] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [0x00003028] [2018-08-22 16:18:53,061] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [0x00003028] [2018-08-22 16:18:53,061] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [0x00003028] [2018-08-22 16:18:53,066] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:64861 )
  INFO root [0x00003028] [2018-08-22 16:18:53,066] - NetworkInterface::initialize(INTERNAL): address 192.168.0.106:64861, SOMAXCONN=5.
  INFO root [0x00003028] [2018-08-22 16:18:53,066] - server-configs:
  INFO root [0x00003028] [2018-08-22 16:18:53,066] - 	gameUpdateHertz : 10
  INFO root [0x00003028] [2018-08-22 16:18:53,067] - 	defaultViewRadius : 80
  INFO root [0x00003028] [2018-08-22 16:18:53,067] - 	defaultViewHysteresisArea : 5
  INFO root [0x00003028] [2018-08-22 16:18:53,067] - 	entryScriptFile : kbemain
  INFO root [0x00003028] [2018-08-22 16:18:53,067] - 	internalAddr : 192.168.0.106:64861
  INFO root [0x00003028] [2018-08-22 16:18:53,067] - 	componentID : 8001
  WARN root [0x00003028] [2018-08-22 16:18:53,378] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20795, errorno=10048
  INFO root [0x00003028] [2018-08-22 16:18:53,382] - ---- cellapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 85A70C5E64F896E0F1A60BF405B4EB07. Config: Debug X86. Built: 15:53:53 Apr 29 2018. AppID: 8001. UID: 32380. PID: 14596 ----
  INFO root [0x00003028] [2018-08-22 16:18:53,383] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [0x00003028] [2018-08-22 16:18:53,383] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00003028] [2018-08-22 16:18:53,383] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x00003028] [2018-08-22 16:18:53,513] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00003028] [2018-08-22 16:18:53,514] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x00003028] [2018-08-22 16:18:53,514] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x00003028] [2018-08-22 16:18:53,517] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x00003028] [2018-08-22 16:18:53,517] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x00003028] [2018-08-22 16:18:53,517] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x00003028] [2018-08-22 16:18:53,518] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x00003028] [2018-08-22 16:18:53,549] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x00003028] [2018-08-22 16:18:53,580] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x00003028] [2018-08-22 16:18:53,580] - Script::install(): KBExtra is successfully!
 DEBUG root [0x00003028] [2018-08-22 16:18:53,601] - loaded entity-script:Account(1).
 DEBUG root [0x00003028] [2018-08-22 16:18:53,627] - loaded entity-script:Room(4).
  INFO root [0x00003028] [2018-08-22 16:18:53,627] - TelnetServer server is running on port 50000
  INFO root [0x00003028] [2018-08-22 16:18:53,919] - ---- cellapp is running ----
 DEBUG root [0x00003028] [2018-08-22 16:18:53,920] - Components::process(): Request for the process of identity...
  WARN root [0x00003028] [2018-08-22 16:19:00,002] - EntityApp::checkTickPeriod: tick took 6082% (6.08 seconds)!
  INFO root [0x00003028] [2018-08-22 16:19:01,020] - Components::findComponents: find logger(1)...
  INFO root [0x00003028] [2018-08-22 16:19:01,059] - Components::findComponents: found logger, addr:192.168.0.106:64854
  INFO root [0x00003028] [2018-08-22 16:19:01,059] - Components::addComponent: reset orderLog, uid=32380!
  INFO root [0x00003028] [2018-08-22 16:19:01,059] - Components::addComponent[logger], uid=32380, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00003028] [2018-08-22 16:19:01,060] - Components::findComponents: find dbmgr(2)...
  INFO root [0x00003028] [2018-08-22 16:19:01,164] - Components::findComponents: found dbmgr, addr:192.168.0.106:64858
  INFO root [0x00003028] [2018-08-22 16:19:01,165] - Components::addComponent: reset orderLog, uid=32380!
  INFO root [0x00003028] [2018-08-22 16:19:01,165] - Components::addComponent[dbmgr], uid=32380, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00003028] [2018-08-22 16:19:01,166] - Components::findComponents: found dbmgr, addr:192.168.0.106:64858
  WARN root [0x00003028] [2018-08-22 16:19:02,166] - EntityApp::checkTickPeriod: tick took 1246% (1.25 seconds)!
  WARN root [0x00003028] [2018-08-22 16:19:02,168] - Forwarding logs to logger[192.168.0.106:64854/0/0/0]...
 ERROR root [0x00003028] [2018-08-22 16:32:09,252] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x00003028] [2018-08-22 16:32:09,274] - The following logs sent to logger failed:
  WARN root [0x00003028] [2018-08-22 16:32:09,274] - ==> [2018-08-22 16:32:09 246] TCPPacketReceiver::processPendingEvents(192.168.0.106:64854): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00003028] [2018-08-22 16:32:09,274] - ==> [2018-08-22 16:32:09 252] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x00003028] [2018-08-22 16:32:09,330] - TCPPacketReceiver::processPendingEvents(192.168.0.106:64858): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00003028] [2018-08-22 16:32:09,334] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x00003028] [2018-08-22 16:32:09,354] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [0x00003028] [2018-08-22 16:32:09,355] - Shutdowner::onShutdown: shutting down
  INFO root [0x00003028] [2018-08-22 16:32:09,356] - Spaces::destroySpace: 1.
  INFO root [0x00003028] [2018-08-22 16:32:09,356] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [0x00003028] [2018-08-22 16:32:09,356] - Account::~Account(): 2002
 DEBUG root [0x00003028] [2018-08-22 16:32:09,356] - Account::~Account(): 2004
 DEBUG root [0x00003028] [2018-08-22 16:32:09,356] - EntityRef::destroyObjPool(): size 16.
 DEBUG root [0x00003028] [2018-08-22 16:32:09,357] - Witness::destroyObjPool(): size 16.
 DEBUG root [0x00003028] [2018-08-22 16:32:09,365] - Room::~Room(): 2003
 ERROR root [0x00003028] [2018-08-22 16:32:09,366] - PyGC::debugTracing(): EntityCall : leaked(2)
 DEBUG root [0x00003028] [2018-08-22 16:32:09,367] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00003028] [2018-08-22 16:32:09,367] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x00003028] [2018-08-22 16:32:09,367] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x00003028] [2018-08-22 16:32:09,367] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x00003028] [2018-08-22 16:32:09,367] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x00003028] [2018-08-22 16:32:09,367] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x00003028] [2018-08-22 16:32:09,368] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x00003028] [2018-08-22 16:32:09,368] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x00003028] [2018-08-22 16:32:09,378] - Script::uninstall(): is successfully!
 DEBUG root [0x00003028] [2018-08-22 16:32:09,378] - ThreadPool::destroy(): starting size 2.
  INFO root [0x00002548] [2018-08-22 16:32:10,671] - 
  INFO root [0x00002548] [2018-08-22 16:32:10,680] - -----------------------------------------------------------------------------------------


  INFO root [0x00002548] [2018-08-22 16:32:10,680] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [0x00002548] [2018-08-22 16:32:10,680] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [0x00002548] [2018-08-22 16:32:10,681] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [0x00002548] [2018-08-22 16:32:10,688] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:64995 )
  INFO root [0x00002548] [2018-08-22 16:32:10,688] - NetworkInterface::initialize(INTERNAL): address 192.168.0.106:64995, SOMAXCONN=5.
  INFO root [0x00002548] [2018-08-22 16:32:10,688] - server-configs:
  INFO root [0x00002548] [2018-08-22 16:32:10,688] - 	gameUpdateHertz : 10
  INFO root [0x00002548] [2018-08-22 16:32:10,688] - 	defaultViewRadius : 80
  INFO root [0x00002548] [2018-08-22 16:32:10,688] - 	defaultViewHysteresisArea : 5
  INFO root [0x00002548] [2018-08-22 16:32:10,689] - 	entryScriptFile : kbemain
  INFO root [0x00002548] [2018-08-22 16:32:10,689] - 	internalAddr : 192.168.0.106:64995
  INFO root [0x00002548] [2018-08-22 16:32:10,689] - 	componentID : 8001
  INFO root [0x00002548] [2018-08-22 16:32:12,199] - ---- cellapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 85A70C5E64F896E0F1A60BF405B4EB07. Config: Debug X86. Built: 15:53:53 Apr 29 2018. AppID: 8001. UID: 2218. PID: 14876 ----
  INFO root [0x00002548] [2018-08-22 16:32:12,205] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [0x00002548] [2018-08-22 16:32:12,205] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00002548] [2018-08-22 16:32:12,205] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x00002548] [2018-08-22 16:32:12,352] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00002548] [2018-08-22 16:32:12,352] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x00002548] [2018-08-22 16:32:12,353] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x00002548] [2018-08-22 16:32:12,356] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x00002548] [2018-08-22 16:32:12,356] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x00002548] [2018-08-22 16:32:12,356] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x00002548] [2018-08-22 16:32:12,357] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x00002548] [2018-08-22 16:32:12,385] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x00002548] [2018-08-22 16:32:12,415] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x00002548] [2018-08-22 16:32:12,415] - Script::install(): KBExtra is successfully!
 DEBUG root [0x00002548] [2018-08-22 16:32:12,439] - loaded entity-script:Account(1).
 DEBUG root [0x00002548] [2018-08-22 16:32:12,461] - loaded entity-script:Room(4).
  INFO root [0x00002548] [2018-08-22 16:32:12,461] - TelnetServer server is running on port 50000
  INFO root [0x00002548] [2018-08-22 16:32:12,777] - ---- cellapp is running ----
 DEBUG root [0x00002548] [2018-08-22 16:32:12,777] - Components::process(): Request for the process of identity...
  WARN root [0x00002548] [2018-08-22 16:32:18,854] - EntityApp::checkTickPeriod: tick took 6077% (6.08 seconds)!
  INFO root [0x00002548] [2018-08-22 16:32:19,885] - Components::findComponents: find logger(1)...
  INFO root [0x00002548] [2018-08-22 16:32:19,921] - Components::findComponents: found logger, addr:192.168.0.106:64996
  INFO root [0x00002548] [2018-08-22 16:32:19,921] - Components::addComponent: reset orderLog, uid=2218!
  INFO root [0x00002548] [2018-08-22 16:32:19,921] - Components::addComponent[logger], uid=2218, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00002548] [2018-08-22 16:32:19,922] - Components::findComponents: find dbmgr(2)...
  INFO root [0x00002548] [2018-08-22 16:32:20,027] - Components::findComponents: found dbmgr, addr:192.168.0.106:64997
  INFO root [0x00002548] [2018-08-22 16:32:20,028] - Components::addComponent: reset orderLog, uid=2218!
  INFO root [0x00002548] [2018-08-22 16:32:20,028] - Components::addComponent[dbmgr], uid=2218, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00002548] [2018-08-22 16:32:20,028] - Components::findComponents: found dbmgr, addr:192.168.0.106:64997
  WARN root [0x00002548] [2018-08-22 16:32:21,028] - Forwarding logs to logger[192.168.0.106:64996/0/0/0]...
 ERROR root [0x00002548] [2018-08-22 16:34:53,327] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x00002548] [2018-08-22 16:34:53,350] - The following logs sent to logger failed:
  WARN root [0x00002548] [2018-08-22 16:34:53,350] - ==> [2018-08-22 16:34:53 322] TCPPacketReceiver::processPendingEvents(192.168.0.106:64996): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00002548] [2018-08-22 16:34:53,350] - ==> [2018-08-22 16:34:53 328] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x00002548] [2018-08-22 16:34:53,403] - TCPPacketReceiver::processPendingEvents(192.168.0.106:64997): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00002548] [2018-08-22 16:34:53,408] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x00002548] [2018-08-22 16:34:53,429] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [0x00002548] [2018-08-22 16:34:53,431] - Shutdowner::onShutdown: shutting down
  INFO root [0x00002548] [2018-08-22 16:34:53,432] - Spaces::destroySpace: 1.
  INFO root [0x00002548] [2018-08-22 16:34:53,433] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [0x00002548] [2018-08-22 16:34:53,433] - Account::~Account(): 2002
 DEBUG root [0x00002548] [2018-08-22 16:34:53,433] - Account::~Account(): 2004
 DEBUG root [0x00002548] [2018-08-22 16:34:53,433] - EntityRef::destroyObjPool(): size 16.
 DEBUG root [0x00002548] [2018-08-22 16:34:53,433] - Witness::destroyObjPool(): size 16.
 DEBUG root [0x00002548] [2018-08-22 16:34:53,442] - Room::~Room(): 2003
 ERROR root [0x00002548] [2018-08-22 16:34:53,443] - PyGC::debugTracing(): EntityCall : leaked(2)
 DEBUG root [0x00002548] [2018-08-22 16:34:53,447] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00002548] [2018-08-22 16:34:53,447] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x00002548] [2018-08-22 16:34:53,448] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x00002548] [2018-08-22 16:34:53,448] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x00002548] [2018-08-22 16:34:53,448] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x00002548] [2018-08-22 16:34:53,448] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x00002548] [2018-08-22 16:34:53,448] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x00002548] [2018-08-22 16:34:53,448] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x00002548] [2018-08-22 16:34:53,458] - Script::uninstall(): is successfully!
 DEBUG root [0x00002548] [2018-08-22 16:34:53,458] - ThreadPool::destroy(): starting size 2.
  INFO root [0x00003df8] [2018-08-22 16:34:54,773] - 
  INFO root [0x00003df8] [2018-08-22 16:34:54,774] - -----------------------------------------------------------------------------------------


  INFO root [0x00003df8] [2018-08-22 16:34:54,775] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [0x00003df8] [2018-08-22 16:34:54,775] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [0x00003df8] [2018-08-22 16:34:54,775] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [0x00003df8] [2018-08-22 16:34:54,784] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:65087 )
  INFO root [0x00003df8] [2018-08-22 16:34:54,784] - NetworkInterface::initialize(INTERNAL): address 192.168.0.106:65087, SOMAXCONN=5.
  INFO root [0x00003df8] [2018-08-22 16:34:54,784] - server-configs:
  INFO root [0x00003df8] [2018-08-22 16:34:54,784] - 	gameUpdateHertz : 10
  INFO root [0x00003df8] [2018-08-22 16:34:54,784] - 	defaultViewRadius : 80
  INFO root [0x00003df8] [2018-08-22 16:34:54,784] - 	defaultViewHysteresisArea : 5
  INFO root [0x00003df8] [2018-08-22 16:34:54,785] - 	entryScriptFile : kbemain
  INFO root [0x00003df8] [2018-08-22 16:34:54,785] - 	internalAddr : 192.168.0.106:65087
  INFO root [0x00003df8] [2018-08-22 16:34:54,785] - 	componentID : 8001
  WARN root [0x00003df8] [2018-08-22 16:34:55,096] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20623, errorno=10048
  INFO root [0x00003df8] [2018-08-22 16:34:55,103] - ---- cellapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 85A70C5E64F896E0F1A60BF405B4EB07. Config: Debug X86. Built: 15:53:53 Apr 29 2018. AppID: 8001. UID: 2754. PID: 12112 ----
  INFO root [0x00003df8] [2018-08-22 16:34:55,103] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [0x00003df8] [2018-08-22 16:34:55,103] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00003df8] [2018-08-22 16:34:55,103] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x00003df8] [2018-08-22 16:34:55,236] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00003df8] [2018-08-22 16:34:55,236] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x00003df8] [2018-08-22 16:34:55,236] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x00003df8] [2018-08-22 16:34:55,240] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x00003df8] [2018-08-22 16:34:55,240] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x00003df8] [2018-08-22 16:34:55,240] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x00003df8] [2018-08-22 16:34:55,241] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x00003df8] [2018-08-22 16:34:55,274] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x00003df8] [2018-08-22 16:34:55,306] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x00003df8] [2018-08-22 16:34:55,307] - Script::install(): KBExtra is successfully!
 DEBUG root [0x00003df8] [2018-08-22 16:34:55,326] - loaded entity-script:Account(1).
 DEBUG root [0x00003df8] [2018-08-22 16:34:55,357] - loaded entity-script:Room(4).
  INFO root [0x00003df8] [2018-08-22 16:34:55,357] - TelnetServer server is running on port 50000
  INFO root [0x00003df8] [2018-08-22 16:34:55,659] - ---- cellapp is running ----
 DEBUG root [0x00003df8] [2018-08-22 16:34:55,660] - Components::process(): Request for the process of identity...
  WARN root [0x00003df8] [2018-08-22 16:35:01,749] - EntityApp::checkTickPeriod: tick took 6089% (6.09 seconds)!
  INFO root [0x00003df8] [2018-08-22 16:35:02,779] - Components::findComponents: find logger(1)...
  INFO root [0x00003df8] [2018-08-22 16:35:02,794] - Components::findComponents: found logger, addr:192.168.0.106:65085
  INFO root [0x00003df8] [2018-08-22 16:35:02,794] - Components::addComponent: reset orderLog, uid=2754!
  INFO root [0x00003df8] [2018-08-22 16:35:02,794] - Components::addComponent[logger], uid=2754, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00003df8] [2018-08-22 16:35:02,795] - Components::findComponents: find dbmgr(2)...
  INFO root [0x00003df8] [2018-08-22 16:35:02,896] - Components::findComponents: found dbmgr, addr:192.168.0.106:65086
  INFO root [0x00003df8] [2018-08-22 16:35:02,896] - Components::addComponent: reset orderLog, uid=2754!
  INFO root [0x00003df8] [2018-08-22 16:35:02,896] - Components::addComponent[dbmgr], uid=2754, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00003df8] [2018-08-22 16:35:02,896] - Components::findComponents: found dbmgr, addr:192.168.0.106:65086
  WARN root [0x00003df8] [2018-08-22 16:35:03,896] - Forwarding logs to logger[192.168.0.106:65085/0/0/0]...
 ERROR root [0x00003df8] [2018-08-22 16:45:36,206] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x00003df8] [2018-08-22 16:45:36,217] - The following logs sent to logger failed:
  WARN root [0x00003df8] [2018-08-22 16:45:36,217] - ==> [2018-08-22 16:45:36 192] TCPPacketReceiver::processPendingEvents(192.168.0.106:65085): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00003df8] [2018-08-22 16:45:36,218] - ==> [2018-08-22 16:45:36 206] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x00003df8] [2018-08-22 16:45:36,274] - TCPPacketReceiver::processPendingEvents(192.168.0.106:65086): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00003df8] [2018-08-22 16:45:36,279] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x00003df8] [2018-08-22 16:45:36,300] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [0x00003df8] [2018-08-22 16:45:36,302] - Shutdowner::onShutdown: shutting down
  INFO root [0x00003df8] [2018-08-22 16:45:36,303] - Spaces::destroySpace: 1.
  INFO root [0x00003df8] [2018-08-22 16:45:36,303] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [0x00003df8] [2018-08-22 16:45:36,303] - Account::~Account(): 2002
 DEBUG root [0x00003df8] [2018-08-22 16:45:36,304] - Account::~Account(): 2004
 DEBUG root [0x00003df8] [2018-08-22 16:45:36,304] - EntityRef::destroyObjPool(): size 16.
 DEBUG root [0x00003df8] [2018-08-22 16:45:36,304] - Witness::destroyObjPool(): size 16.
 DEBUG root [0x00003df8] [2018-08-22 16:45:36,312] - Room::~Room(): 2003
 ERROR root [0x00003df8] [2018-08-22 16:45:36,313] - PyGC::debugTracing(): EntityCall : leaked(2)
 DEBUG root [0x00003df8] [2018-08-22 16:45:36,313] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00003df8] [2018-08-22 16:45:36,313] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x00003df8] [2018-08-22 16:45:36,313] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x00003df8] [2018-08-22 16:45:36,314] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x00003df8] [2018-08-22 16:45:36,314] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x00003df8] [2018-08-22 16:45:36,314] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x00003df8] [2018-08-22 16:45:36,314] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x00003df8] [2018-08-22 16:45:36,314] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x00003df8] [2018-08-22 16:45:36,325] - Script::uninstall(): is successfully!
 DEBUG root [0x00003df8] [2018-08-22 16:45:36,325] - ThreadPool::destroy(): starting size 2.
  INFO root [0x0000472c] [2018-08-22 16:45:37,673] - 
  INFO root [0x0000472c] [2018-08-22 16:45:37,674] - -----------------------------------------------------------------------------------------


  INFO root [0x0000472c] [2018-08-22 16:45:37,675] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [0x0000472c] [2018-08-22 16:45:37,675] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [0x0000472c] [2018-08-22 16:45:37,675] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [0x0000472c] [2018-08-22 16:45:37,682] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:65191 )
  INFO root [0x0000472c] [2018-08-22 16:45:37,682] - NetworkInterface::initialize(INTERNAL): address 192.168.0.106:65191, SOMAXCONN=5.
  INFO root [0x0000472c] [2018-08-22 16:45:37,683] - server-configs:
  INFO root [0x0000472c] [2018-08-22 16:45:37,683] - 	gameUpdateHertz : 10
  INFO root [0x0000472c] [2018-08-22 16:45:37,683] - 	defaultViewRadius : 80
  INFO root [0x0000472c] [2018-08-22 16:45:37,683] - 	defaultViewHysteresisArea : 5
  INFO root [0x0000472c] [2018-08-22 16:45:37,683] - 	entryScriptFile : kbemain
  INFO root [0x0000472c] [2018-08-22 16:45:37,683] - 	internalAddr : 192.168.0.106:65191
  INFO root [0x0000472c] [2018-08-22 16:45:37,683] - 	componentID : 8001
  INFO root [0x0000472c] [2018-08-22 16:45:39,193] - ---- cellapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 85A70C5E64F896E0F1A60BF405B4EB07. Config: Debug X86. Built: 15:53:53 Apr 29 2018. AppID: 8001. UID: 4853. PID: 18212 ----
  INFO root [0x0000472c] [2018-08-22 16:45:39,194] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [0x0000472c] [2018-08-22 16:45:39,194] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x0000472c] [2018-08-22 16:45:39,195] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x0000472c] [2018-08-22 16:45:39,341] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x0000472c] [2018-08-22 16:45:39,342] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x0000472c] [2018-08-22 16:45:39,342] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x0000472c] [2018-08-22 16:45:39,345] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x0000472c] [2018-08-22 16:45:39,346] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x0000472c] [2018-08-22 16:45:39,346] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x0000472c] [2018-08-22 16:45:39,346] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x0000472c] [2018-08-22 16:45:39,377] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x0000472c] [2018-08-22 16:45:39,409] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x0000472c] [2018-08-22 16:45:39,409] - Script::install(): KBExtra is successfully!
 DEBUG root [0x0000472c] [2018-08-22 16:45:39,430] - loaded entity-script:Account(1).
 DEBUG root [0x0000472c] [2018-08-22 16:45:39,440] - loaded entity-script:Room(4).
  INFO root [0x0000472c] [2018-08-22 16:45:39,440] - TelnetServer server is running on port 50000
  INFO root [0x0000472c] [2018-08-22 16:45:39,770] - ---- cellapp is running ----
 DEBUG root [0x0000472c] [2018-08-22 16:45:39,771] - Components::process(): Request for the process of identity...
  WARN root [0x0000472c] [2018-08-22 16:45:45,852] - EntityApp::checkTickPeriod: tick took 6081% (6.08 seconds)!
  INFO root [0x0000472c] [2018-08-22 16:45:46,871] - Components::findComponents: find logger(1)...
  INFO root [0x0000472c] [2018-08-22 16:45:46,957] - Components::findComponents: found logger, addr:192.168.0.106:65187
  INFO root [0x0000472c] [2018-08-22 16:45:46,958] - Components::addComponent: reset orderLog, uid=4853!
  INFO root [0x0000472c] [2018-08-22 16:45:46,958] - Components::addComponent[logger], uid=4853, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x0000472c] [2018-08-22 16:45:46,961] - Components::findComponents: find dbmgr(2)...
  INFO root [0x0000472c] [2018-08-22 16:45:47,061] - Components::findComponents: found dbmgr, addr:192.168.0.106:65185
  INFO root [0x0000472c] [2018-08-22 16:45:47,061] - Components::addComponent: reset orderLog, uid=4853!
  INFO root [0x0000472c] [2018-08-22 16:45:47,062] - Components::addComponent[dbmgr], uid=4853, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x0000472c] [2018-08-22 16:45:47,062] - Components::findComponents: found dbmgr, addr:192.168.0.106:65185
  WARN root [0x0000472c] [2018-08-22 16:45:48,062] - EntityApp::checkTickPeriod: tick took 1291% (1.29 seconds)!
  WARN root [0x0000472c] [2018-08-22 16:45:48,064] - Forwarding logs to logger[192.168.0.106:65187/0/0/0]...
 ERROR root [0x0000472c] [2018-08-22 21:07:47,088] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x0000472c] [2018-08-22 21:07:47,115] - The following logs sent to logger failed:
  WARN root [0x0000472c] [2018-08-22 21:07:47,116] - ==> [2018-08-22 21:07:47 080] TCPPacketReceiver::processPendingEvents(192.168.0.106:65187): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x0000472c] [2018-08-22 21:07:47,116] - ==> [2018-08-22 21:07:47 088] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x0000472c] [2018-08-22 21:07:47,168] - TCPPacketReceiver::processPendingEvents(192.168.0.106:65185): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x0000472c] [2018-08-22 21:07:47,176] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x0000472c] [2018-08-22 21:07:47,202] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [0x0000472c] [2018-08-22 21:07:47,204] - Shutdowner::onShutdown: shutting down
  INFO root [0x0000472c] [2018-08-22 21:07:47,205] - Spaces::destroySpace: 1.
  INFO root [0x0000472c] [2018-08-22 21:07:47,206] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [0x0000472c] [2018-08-22 21:07:47,206] - Account::~Account(): 2002
 DEBUG root [0x0000472c] [2018-08-22 21:07:47,206] - Account::~Account(): 2004
 DEBUG root [0x0000472c] [2018-08-22 21:07:47,206] - EntityRef::destroyObjPool(): size 16.
 DEBUG root [0x0000472c] [2018-08-22 21:07:47,206] - Witness::destroyObjPool(): size 16.
 DEBUG root [0x0000472c] [2018-08-22 21:07:47,214] - Room::~Room(): 2003
 ERROR root [0x0000472c] [2018-08-22 21:07:47,215] - PyGC::debugTracing(): EntityCall : leaked(2)
 DEBUG root [0x0000472c] [2018-08-22 21:07:47,216] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x0000472c] [2018-08-22 21:07:47,216] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x0000472c] [2018-08-22 21:07:47,216] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x0000472c] [2018-08-22 21:07:47,216] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x0000472c] [2018-08-22 21:07:47,216] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x0000472c] [2018-08-22 21:07:47,216] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x0000472c] [2018-08-22 21:07:47,216] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x0000472c] [2018-08-22 21:07:47,217] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x0000472c] [2018-08-22 21:07:47,225] - Script::uninstall(): is successfully!
 DEBUG root [0x0000472c] [2018-08-22 21:07:47,225] - ThreadPool::destroy(): starting size 2.
  INFO root [0x000045e8] [2018-08-22 21:07:48,663] - 
  INFO root [0x000045e8] [2018-08-22 21:07:48,664] - -----------------------------------------------------------------------------------------


  INFO root [0x000045e8] [2018-08-22 21:07:48,665] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [0x000045e8] [2018-08-22 21:07:48,665] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [0x000045e8] [2018-08-22 21:07:48,666] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [0x000045e8] [2018-08-22 21:07:48,670] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:61896 )
  INFO root [0x000045e8] [2018-08-22 21:07:48,670] - NetworkInterface::initialize(INTERNAL): address 192.168.0.106:61896, SOMAXCONN=5.
  INFO root [0x000045e8] [2018-08-22 21:07:48,670] - server-configs:
  INFO root [0x000045e8] [2018-08-22 21:07:48,670] - 	gameUpdateHertz : 10
  INFO root [0x000045e8] [2018-08-22 21:07:48,670] - 	defaultViewRadius : 80
  INFO root [0x000045e8] [2018-08-22 21:07:48,671] - 	defaultViewHysteresisArea : 5
  INFO root [0x000045e8] [2018-08-22 21:07:48,671] - 	entryScriptFile : kbemain
  INFO root [0x000045e8] [2018-08-22 21:07:48,671] - 	internalAddr : 192.168.0.106:61896
  INFO root [0x000045e8] [2018-08-22 21:07:48,671] - 	componentID : 8001
  WARN root [0x000045e8] [2018-08-22 21:07:48,988] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20502, errorno=10048
  INFO root [0x000045e8] [2018-08-22 21:07:48,991] - ---- cellapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 85A70C5E64F896E0F1A60BF405B4EB07. Config: Debug X86. Built: 15:53:53 Apr 29 2018. AppID: 8001. UID: 23453. PID: 18472 ----
  INFO root [0x000045e8] [2018-08-22 21:07:48,992] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [0x000045e8] [2018-08-22 21:07:48,992] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x000045e8] [2018-08-22 21:07:48,992] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x000045e8] [2018-08-22 21:07:49,119] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x000045e8] [2018-08-22 21:07:49,120] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x000045e8] [2018-08-22 21:07:49,120] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x000045e8] [2018-08-22 21:07:49,123] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x000045e8] [2018-08-22 21:07:49,123] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x000045e8] [2018-08-22 21:07:49,124] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x000045e8] [2018-08-22 21:07:49,124] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x000045e8] [2018-08-22 21:07:49,151] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x000045e8] [2018-08-22 21:07:49,179] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x000045e8] [2018-08-22 21:07:49,179] - Script::install(): KBExtra is successfully!
 DEBUG root [0x000045e8] [2018-08-22 21:07:49,197] - loaded entity-script:Account(1).
 DEBUG root [0x000045e8] [2018-08-22 21:07:49,223] - loaded entity-script:Room(4).
  INFO root [0x000045e8] [2018-08-22 21:07:49,224] - TelnetServer server is running on port 50000
  INFO root [0x000045e8] [2018-08-22 21:07:49,509] - ---- cellapp is running ----
 DEBUG root [0x000045e8] [2018-08-22 21:07:49,509] - Components::process(): Request for the process of identity...
  WARN root [0x000045e8] [2018-08-22 21:07:55,568] - EntityApp::checkTickPeriod: tick took 6058% (6.06 seconds)!
  INFO root [0x000045e8] [2018-08-22 21:07:56,611] - Components::findComponents: find logger(1)...
  INFO root [0x000045e8] [2018-08-22 21:07:56,654] - Components::findComponents: found logger, addr:192.168.0.106:61901
  INFO root [0x000045e8] [2018-08-22 21:07:56,654] - Components::addComponent: reset orderLog, uid=23453!
  INFO root [0x000045e8] [2018-08-22 21:07:56,655] - Components::addComponent[logger], uid=23453, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x000045e8] [2018-08-22 21:07:56,658] - Components::findComponents: find dbmgr(2)...
  INFO root [0x000045e8] [2018-08-22 21:07:56,760] - Components::findComponents: found dbmgr, addr:192.168.0.106:61894
  INFO root [0x000045e8] [2018-08-22 21:07:56,761] - Components::addComponent: reset orderLog, uid=23453!
  INFO root [0x000045e8] [2018-08-22 21:07:56,762] - Components::addComponent[dbmgr], uid=23453, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x000045e8] [2018-08-22 21:07:56,763] - Components::findComponents: found dbmgr, addr:192.168.0.106:61894
  WARN root [0x000045e8] [2018-08-22 21:07:57,763] - EntityApp::checkTickPeriod: tick took 1252% (1.25 seconds)!
  WARN root [0x000045e8] [2018-08-22 21:07:57,764] - Forwarding logs to logger[192.168.0.106:61901/0/0/0]...
 ERROR root [0x000045e8] [2018-08-22 21:12:20,632] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x000045e8] [2018-08-22 21:12:20,657] - The following logs sent to logger failed:
  WARN root [0x000045e8] [2018-08-22 21:12:20,657] - ==> [2018-08-22 21:12:20 624] TCPPacketReceiver::processPendingEvents(192.168.0.106:61901): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x000045e8] [2018-08-22 21:12:20,657] - ==> [2018-08-22 21:12:20 633] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x000045e8] [2018-08-22 21:12:20,725] - TCPPacketReceiver::processPendingEvents(192.168.0.106:61894): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x000045e8] [2018-08-22 21:12:20,733] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x000045e8] [2018-08-22 21:12:20,763] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [0x000045e8] [2018-08-22 21:12:20,765] - Shutdowner::onShutdown: shutting down
  INFO root [0x000045e8] [2018-08-22 21:12:20,766] - Spaces::destroySpace: 1.
  INFO root [0x000045e8] [2018-08-22 21:12:20,766] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [0x000045e8] [2018-08-22 21:12:20,767] - Account::~Account(): 2002
 DEBUG root [0x000045e8] [2018-08-22 21:12:20,767] - Account::~Account(): 2004
 DEBUG root [0x000045e8] [2018-08-22 21:12:20,767] - EntityRef::destroyObjPool(): size 16.
 DEBUG root [0x000045e8] [2018-08-22 21:12:20,767] - Witness::destroyObjPool(): size 16.
 DEBUG root [0x000045e8] [2018-08-22 21:12:20,775] - Room::~Room(): 2003
 ERROR root [0x000045e8] [2018-08-22 21:12:20,776] - PyGC::debugTracing(): EntityCall : leaked(2)
 DEBUG root [0x000045e8] [2018-08-22 21:12:20,776] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x000045e8] [2018-08-22 21:12:20,776] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x000045e8] [2018-08-22 21:12:20,777] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x000045e8] [2018-08-22 21:12:20,777] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x000045e8] [2018-08-22 21:12:20,777] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x000045e8] [2018-08-22 21:12:20,777] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x000045e8] [2018-08-22 21:12:20,777] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x000045e8] [2018-08-22 21:12:20,777] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x000045e8] [2018-08-22 21:12:20,787] - Script::uninstall(): is successfully!
 DEBUG root [0x000045e8] [2018-08-22 21:12:20,787] - ThreadPool::destroy(): starting size 2.
  WARN root [0x000045e8] [2018-08-22 21:12:21,087] - ThreadPool::destroy(): waiting for thread(2)[0x83c4d8,0x83c470,], try=1
  INFO root [0x00003280] [2018-08-22 21:12:22,213] - 
  INFO root [0x00003280] [2018-08-22 21:12:22,213] - -----------------------------------------------------------------------------------------


  INFO root [0x00003280] [2018-08-22 21:12:22,214] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [0x00003280] [2018-08-22 21:12:22,214] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [0x00003280] [2018-08-22 21:12:22,214] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [0x00003280] [2018-08-22 21:12:22,219] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:61963 )
  INFO root [0x00003280] [2018-08-22 21:12:22,219] - NetworkInterface::initialize(INTERNAL): address 192.168.0.106:61963, SOMAXCONN=5.
  INFO root [0x00003280] [2018-08-22 21:12:22,219] - server-configs:
  INFO root [0x00003280] [2018-08-22 21:12:22,219] - 	gameUpdateHertz : 10
  INFO root [0x00003280] [2018-08-22 21:12:22,219] - 	defaultViewRadius : 80
  INFO root [0x00003280] [2018-08-22 21:12:22,220] - 	defaultViewHysteresisArea : 5
  INFO root [0x00003280] [2018-08-22 21:12:22,220] - 	entryScriptFile : kbemain
  INFO root [0x00003280] [2018-08-22 21:12:22,220] - 	internalAddr : 192.168.0.106:61963
  INFO root [0x00003280] [2018-08-22 21:12:22,220] - 	componentID : 8001
  WARN root [0x00003280] [2018-08-22 21:12:22,537] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20058, errorno=10048
  INFO root [0x00003280] [2018-08-22 21:12:22,540] - ---- cellapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 85A70C5E64F896E0F1A60BF405B4EB07. Config: Debug X86. Built: 15:53:53 Apr 29 2018. AppID: 8001. UID: 24348. PID: 19128 ----
  INFO root [0x00003280] [2018-08-22 21:12:22,541] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [0x00003280] [2018-08-22 21:12:22,541] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00003280] [2018-08-22 21:12:22,541] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x00003280] [2018-08-22 21:12:22,671] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00003280] [2018-08-22 21:12:22,671] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x00003280] [2018-08-22 21:12:22,672] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x00003280] [2018-08-22 21:12:22,675] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x00003280] [2018-08-22 21:12:22,676] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x00003280] [2018-08-22 21:12:22,676] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x00003280] [2018-08-22 21:12:22,676] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x00003280] [2018-08-22 21:12:22,703] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x00003280] [2018-08-22 21:12:22,731] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x00003280] [2018-08-22 21:12:22,732] - Script::install(): KBExtra is successfully!
 DEBUG root [0x00003280] [2018-08-22 21:12:22,750] - loaded entity-script:Account(1).
 DEBUG root [0x00003280] [2018-08-22 21:12:22,776] - loaded entity-script:Room(4).
  INFO root [0x00003280] [2018-08-22 21:12:22,776] - TelnetServer server is running on port 50000
  INFO root [0x00003280] [2018-08-22 21:12:23,082] - ---- cellapp is running ----
 DEBUG root [0x00003280] [2018-08-22 21:12:23,083] - Components::process(): Request for the process of identity...
  WARN root [0x00003280] [2018-08-22 21:12:29,144] - EntityApp::checkTickPeriod: tick took 6061% (6.06 seconds)!
  INFO root [0x00003280] [2018-08-22 21:12:30,183] - Components::findComponents: find logger(1)...
  INFO root [0x00003280] [2018-08-22 21:12:30,234] - Components::findComponents: found logger, addr:192.168.0.106:61969
  INFO root [0x00003280] [2018-08-22 21:12:30,234] - Components::addComponent: reset orderLog, uid=24348!
  INFO root [0x00003280] [2018-08-22 21:12:30,234] - Components::addComponent[logger], uid=24348, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00003280] [2018-08-22 21:12:30,235] - Components::findComponents: find dbmgr(2)...
  INFO root [0x00003280] [2018-08-22 21:12:30,335] - Components::findComponents: found dbmgr, addr:192.168.0.106:61962
  INFO root [0x00003280] [2018-08-22 21:12:30,336] - Components::addComponent: reset orderLog, uid=24348!
  INFO root [0x00003280] [2018-08-22 21:12:30,336] - Components::addComponent[dbmgr], uid=24348, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00003280] [2018-08-22 21:12:30,336] - Components::findComponents: found dbmgr, addr:192.168.0.106:61962
  WARN root [0x00003280] [2018-08-22 21:12:31,337] - EntityApp::checkTickPeriod: tick took 1253% (1.25 seconds)!
  WARN root [0x00003280] [2018-08-22 21:12:31,337] - Forwarding logs to logger[192.168.0.106:61969/0/0/0]...
 ERROR root [0x00003280] [2018-08-22 21:22:06,078] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x00003280] [2018-08-22 21:22:06,111] - The following logs sent to logger failed:
  WARN root [0x00003280] [2018-08-22 21:22:06,111] - ==> [2018-08-22 21:22:06 070] TCPPacketReceiver::processPendingEvents(192.168.0.106:61969): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00003280] [2018-08-22 21:22:06,112] - ==> [2018-08-22 21:22:06 078] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x00003280] [2018-08-22 21:22:06,167] - TCPPacketReceiver::processPendingEvents(192.168.0.106:61962): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00003280] [2018-08-22 21:22:06,175] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x00003280] [2018-08-22 21:22:06,205] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [0x00003280] [2018-08-22 21:22:06,213] - Shutdowner::onShutdown: shutting down
  INFO root [0x00003280] [2018-08-22 21:22:06,214] - Spaces::destroySpace: 1.
  INFO root [0x00003280] [2018-08-22 21:22:06,214] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [0x00003280] [2018-08-22 21:22:06,214] - Account::~Account(): 2002
 DEBUG root [0x00003280] [2018-08-22 21:22:06,214] - Account::~Account(): 2004
 DEBUG root [0x00003280] [2018-08-22 21:22:06,214] - EntityRef::destroyObjPool(): size 16.
 DEBUG root [0x00003280] [2018-08-22 21:22:06,215] - Witness::destroyObjPool(): size 16.
 DEBUG root [0x00003280] [2018-08-22 21:22:06,222] - Room::~Room(): 2003
 ERROR root [0x00003280] [2018-08-22 21:22:06,223] - PyGC::debugTracing(): EntityCall : leaked(2)
 DEBUG root [0x00003280] [2018-08-22 21:22:06,227] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00003280] [2018-08-22 21:22:06,227] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x00003280] [2018-08-22 21:22:06,227] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x00003280] [2018-08-22 21:22:06,227] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x00003280] [2018-08-22 21:22:06,227] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x00003280] [2018-08-22 21:22:06,227] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x00003280] [2018-08-22 21:22:06,227] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x00003280] [2018-08-22 21:22:06,227] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x00003280] [2018-08-22 21:22:06,238] - Script::uninstall(): is successfully!
 DEBUG root [0x00003280] [2018-08-22 21:22:06,238] - ThreadPool::destroy(): starting size 2.
  INFO root [0x000049b8] [2018-08-22 21:22:07,692] - 
  INFO root [0x000049b8] [2018-08-22 21:22:07,692] - -----------------------------------------------------------------------------------------


  INFO root [0x000049b8] [2018-08-22 21:22:07,693] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [0x000049b8] [2018-08-22 21:22:07,693] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [0x000049b8] [2018-08-22 21:22:07,693] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [0x000049b8] [2018-08-22 21:22:07,698] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:62084 )
  INFO root [0x000049b8] [2018-08-22 21:22:07,698] - NetworkInterface::initialize(INTERNAL): address 192.168.0.106:62084, SOMAXCONN=5.
  INFO root [0x000049b8] [2018-08-22 21:22:07,698] - server-configs:
  INFO root [0x000049b8] [2018-08-22 21:22:07,698] - 	gameUpdateHertz : 10
  INFO root [0x000049b8] [2018-08-22 21:22:07,698] - 	defaultViewRadius : 80
  INFO root [0x000049b8] [2018-08-22 21:22:07,698] - 	defaultViewHysteresisArea : 5
  INFO root [0x000049b8] [2018-08-22 21:22:07,698] - 	entryScriptFile : kbemain
  INFO root [0x000049b8] [2018-08-22 21:22:07,699] - 	internalAddr : 192.168.0.106:62084
  INFO root [0x000049b8] [2018-08-22 21:22:07,699] - 	componentID : 8001
  WARN root [0x000049b8] [2018-08-22 21:22:08,011] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20648, errorno=10048
  INFO root [0x000049b8] [2018-08-22 21:22:08,016] - ---- cellapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 85A70C5E64F896E0F1A60BF405B4EB07. Config: Debug X86. Built: 15:53:53 Apr 29 2018. AppID: 8001. UID: 26258. PID: 14976 ----
  INFO root [0x000049b8] [2018-08-22 21:22:08,017] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [0x000049b8] [2018-08-22 21:22:08,017] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x000049b8] [2018-08-22 21:22:08,018] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x000049b8] [2018-08-22 21:22:08,149] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x000049b8] [2018-08-22 21:22:08,150] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x000049b8] [2018-08-22 21:22:08,150] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x000049b8] [2018-08-22 21:22:08,153] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x000049b8] [2018-08-22 21:22:08,154] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x000049b8] [2018-08-22 21:22:08,154] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x000049b8] [2018-08-22 21:22:08,155] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x000049b8] [2018-08-22 21:22:08,189] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x000049b8] [2018-08-22 21:22:08,226] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x000049b8] [2018-08-22 21:22:08,226] - Script::install(): KBExtra is successfully!
 DEBUG root [0x000049b8] [2018-08-22 21:22:08,257] - loaded entity-script:Account(1).
 DEBUG root [0x000049b8] [2018-08-22 21:22:08,282] - loaded entity-script:Room(4).
  INFO root [0x000049b8] [2018-08-22 21:22:08,282] - TelnetServer server is running on port 50000
  INFO root [0x000049b8] [2018-08-22 21:22:08,639] - ---- cellapp is running ----
 DEBUG root [0x000049b8] [2018-08-22 21:22:08,640] - Components::process(): Request for the process of identity...
  WARN root [0x000049b8] [2018-08-22 21:22:14,696] - EntityApp::checkTickPeriod: tick took 6056% (6.06 seconds)!
  INFO root [0x000049b8] [2018-08-22 21:22:15,740] - Components::findComponents: find logger(1)...
  INFO root [0x000049b8] [2018-08-22 21:22:15,806] - Components::findComponents: found logger, addr:192.168.0.106:62085
  INFO root [0x000049b8] [2018-08-22 21:22:15,807] - Components::addComponent: reset orderLog, uid=26258!
  INFO root [0x000049b8] [2018-08-22 21:22:15,807] - Components::addComponent[logger], uid=26258, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x000049b8] [2018-08-22 21:22:15,808] - Components::findComponents: find dbmgr(2)...
  INFO root [0x000049b8] [2018-08-22 21:22:15,910] - Components::findComponents: found dbmgr, addr:192.168.0.106:62079
  INFO root [0x000049b8] [2018-08-22 21:22:15,910] - Components::addComponent: reset orderLog, uid=26258!
  INFO root [0x000049b8] [2018-08-22 21:22:15,911] - Components::addComponent[dbmgr], uid=26258, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x000049b8] [2018-08-22 21:22:15,911] - Components::findComponents: found dbmgr, addr:192.168.0.106:62079
  WARN root [0x000049b8] [2018-08-22 21:22:16,911] - EntityApp::checkTickPeriod: tick took 1271% (1.27 seconds)!
  WARN root [0x000049b8] [2018-08-22 21:22:16,911] - Forwarding logs to logger[192.168.0.106:62085/0/0/0]...
 ERROR root [0x000049b8] [2018-08-22 21:53:10,206] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x000049b8] [2018-08-22 21:53:10,252] - The following logs sent to logger failed:
  WARN root [0x000049b8] [2018-08-22 21:53:10,253] - ==> [2018-08-22 21:53:10 197] TCPPacketReceiver::processPendingEvents(192.168.0.106:62085): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x000049b8] [2018-08-22 21:53:10,253] - ==> [2018-08-22 21:53:10 207] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x000049b8] [2018-08-22 21:53:10,309] - TCPPacketReceiver::processPendingEvents(192.168.0.106:62079): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x000049b8] [2018-08-22 21:53:10,316] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x000049b8] [2018-08-22 21:53:10,343] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [0x000049b8] [2018-08-22 21:53:10,345] - Shutdowner::onShutdown: shutting down
  INFO root [0x000049b8] [2018-08-22 21:53:10,346] - Spaces::destroySpace: 1.
  INFO root [0x000049b8] [2018-08-22 21:53:10,346] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [0x000049b8] [2018-08-22 21:53:10,347] - Account::~Account(): 2002
 DEBUG root [0x000049b8] [2018-08-22 21:53:10,347] - Account::~Account(): 2004
 DEBUG root [0x000049b8] [2018-08-22 21:53:10,347] - EntityRef::destroyObjPool(): size 16.
 DEBUG root [0x000049b8] [2018-08-22 21:53:10,348] - Witness::destroyObjPool(): size 16.
 DEBUG root [0x000049b8] [2018-08-22 21:53:10,356] - Room::~Room(): 2003
 ERROR root [0x000049b8] [2018-08-22 21:53:10,357] - PyGC::debugTracing(): EntityCall : leaked(2)
 DEBUG root [0x000049b8] [2018-08-22 21:53:10,357] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x000049b8] [2018-08-22 21:53:10,357] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x000049b8] [2018-08-22 21:53:10,357] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x000049b8] [2018-08-22 21:53:10,357] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x000049b8] [2018-08-22 21:53:10,357] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x000049b8] [2018-08-22 21:53:10,358] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x000049b8] [2018-08-22 21:53:10,358] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x000049b8] [2018-08-22 21:53:10,358] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x000049b8] [2018-08-22 21:53:10,368] - Script::uninstall(): is successfully!
 DEBUG root [0x000049b8] [2018-08-22 21:53:10,368] - ThreadPool::destroy(): starting size 2.
  WARN root [0x000049b8] [2018-08-22 21:53:10,668] - ThreadPool::destroy(): waiting for thread(2)[0x4fc4d8,0x4fc470,], try=1
  INFO root [0x00004288] [2018-08-22 21:53:11,895] - 
  INFO root [0x00004288] [2018-08-22 21:53:11,895] - -----------------------------------------------------------------------------------------


  INFO root [0x00004288] [2018-08-22 21:53:11,896] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [0x00004288] [2018-08-22 21:53:11,896] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [0x00004288] [2018-08-22 21:53:11,896] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [0x00004288] [2018-08-22 21:53:11,900] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:62367 )
  INFO root [0x00004288] [2018-08-22 21:53:11,900] - NetworkInterface::initialize(INTERNAL): address 192.168.0.106:62367, SOMAXCONN=5.
  INFO root [0x00004288] [2018-08-22 21:53:11,901] - server-configs:
  INFO root [0x00004288] [2018-08-22 21:53:11,901] - 	gameUpdateHertz : 10
  INFO root [0x00004288] [2018-08-22 21:53:11,901] - 	defaultViewRadius : 80
  INFO root [0x00004288] [2018-08-22 21:53:11,901] - 	defaultViewHysteresisArea : 5
  INFO root [0x00004288] [2018-08-22 21:53:11,901] - 	entryScriptFile : kbemain
  INFO root [0x00004288] [2018-08-22 21:53:11,901] - 	internalAddr : 192.168.0.106:62367
  INFO root [0x00004288] [2018-08-22 21:53:11,901] - 	componentID : 8001
  WARN root [0x00004288] [2018-08-22 21:53:12,213] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20300, errorno=10048
  INFO root [0x00004288] [2018-08-22 21:53:12,217] - ---- cellapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 85A70C5E64F896E0F1A60BF405B4EB07. Config: Debug X86. Built: 15:53:53 Apr 29 2018. AppID: 8001. UID: 32348. PID: 19608 ----
  INFO root [0x00004288] [2018-08-22 21:53:12,217] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [0x00004288] [2018-08-22 21:53:12,217] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00004288] [2018-08-22 21:53:12,218] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x00004288] [2018-08-22 21:53:12,353] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00004288] [2018-08-22 21:53:12,354] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x00004288] [2018-08-22 21:53:12,354] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x00004288] [2018-08-22 21:53:12,359] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x00004288] [2018-08-22 21:53:12,359] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x00004288] [2018-08-22 21:53:12,359] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x00004288] [2018-08-22 21:53:12,360] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x00004288] [2018-08-22 21:53:12,392] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x00004288] [2018-08-22 21:53:12,432] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x00004288] [2018-08-22 21:53:12,433] - Script::install(): KBExtra is successfully!
 DEBUG root [0x00004288] [2018-08-22 21:53:12,464] - loaded entity-script:Account(1).
 DEBUG root [0x00004288] [2018-08-22 21:53:12,494] - loaded entity-script:Room(4).
  INFO root [0x00004288] [2018-08-22 21:53:12,495] - TelnetServer server is running on port 50000
  INFO root [0x00004288] [2018-08-22 21:53:12,804] - ---- cellapp is running ----
 DEBUG root [0x00004288] [2018-08-22 21:53:12,804] - Components::process(): Request for the process of identity...
  WARN root [0x00004288] [2018-08-22 21:53:18,896] - EntityApp::checkTickPeriod: tick took 6092% (6.09 seconds)!
  INFO root [0x00004288] [2018-08-22 21:53:20,000] - Components::findComponents: find logger(1)...
  INFO root [0x00004288] [2018-08-22 21:53:20,072] - Components::findComponents: found logger, addr:192.168.0.106:62364
  INFO root [0x00004288] [2018-08-22 21:53:20,072] - Components::addComponent: reset orderLog, uid=32348!
  INFO root [0x00004288] [2018-08-22 21:53:20,072] - Components::addComponent[logger], uid=32348, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00004288] [2018-08-22 21:53:20,073] - Components::findComponents: find dbmgr(2)...
  INFO root [0x00004288] [2018-08-22 21:53:20,175] - Components::findComponents: found dbmgr, addr:192.168.0.106:62361
  INFO root [0x00004288] [2018-08-22 21:53:20,175] - Components::addComponent: reset orderLog, uid=32348!
  INFO root [0x00004288] [2018-08-22 21:53:20,175] - Components::addComponent[dbmgr], uid=32348, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00004288] [2018-08-22 21:53:20,176] - Components::findComponents: found dbmgr, addr:192.168.0.106:62361
  WARN root [0x00004288] [2018-08-22 21:53:21,176] - Forwarding logs to logger[192.168.0.106:62364/0/0/0]...
 ERROR root [0x00004288] [2018-08-22 22:07:54,171] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x00004288] [2018-08-22 22:07:54,203] - The following logs sent to logger failed:
  WARN root [0x00004288] [2018-08-22 22:07:54,204] - ==> [2018-08-22 22:07:54 163] TCPPacketReceiver::processPendingEvents(192.168.0.106:62364): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00004288] [2018-08-22 22:07:54,204] - ==> [2018-08-22 22:07:54 171] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x00004288] [2018-08-22 22:07:54,260] - TCPPacketReceiver::processPendingEvents(192.168.0.106:62361): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00004288] [2018-08-22 22:07:54,269] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x00004288] [2018-08-22 22:07:54,302] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [0x00004288] [2018-08-22 22:07:54,303] - Shutdowner::onShutdown: shutting down
  INFO root [0x00004288] [2018-08-22 22:07:54,305] - Spaces::destroySpace: 1.
  INFO root [0x00004288] [2018-08-22 22:07:54,305] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [0x00004288] [2018-08-22 22:07:54,305] - Account::~Account(): 2002
 DEBUG root [0x00004288] [2018-08-22 22:07:54,305] - Account::~Account(): 2004
 DEBUG root [0x00004288] [2018-08-22 22:07:54,305] - EntityRef::destroyObjPool(): size 16.
 DEBUG root [0x00004288] [2018-08-22 22:07:54,306] - Witness::destroyObjPool(): size 16.
 DEBUG root [0x00004288] [2018-08-22 22:07:54,316] - Room::~Room(): 2003
 ERROR root [0x00004288] [2018-08-22 22:07:54,317] - PyGC::debugTracing(): EntityCall : leaked(2)
 DEBUG root [0x00004288] [2018-08-22 22:07:54,317] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00004288] [2018-08-22 22:07:54,317] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x00004288] [2018-08-22 22:07:54,317] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x00004288] [2018-08-22 22:07:54,317] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x00004288] [2018-08-22 22:07:54,318] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x00004288] [2018-08-22 22:07:54,318] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x00004288] [2018-08-22 22:07:54,318] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x00004288] [2018-08-22 22:07:54,318] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x00004288] [2018-08-22 22:07:54,330] - Script::uninstall(): is successfully!
 DEBUG root [0x00004288] [2018-08-22 22:07:54,330] - ThreadPool::destroy(): starting size 2.
  WARN root [0x00004288] [2018-08-22 22:07:54,630] - ThreadPool::destroy(): waiting for thread(2)[0x43c4f0,0x43c488,], try=1
  INFO root [0x0000458c] [2018-08-22 22:07:55,855] - 
  INFO root [0x0000458c] [2018-08-22 22:07:55,859] - -----------------------------------------------------------------------------------------


  INFO root [0x0000458c] [2018-08-22 22:07:55,860] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [0x0000458c] [2018-08-22 22:07:55,860] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [0x0000458c] [2018-08-22 22:07:55,860] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [0x0000458c] [2018-08-22 22:07:55,865] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:62526 )
  INFO root [0x0000458c] [2018-08-22 22:07:55,865] - NetworkInterface::initialize(INTERNAL): address 192.168.0.106:62526, SOMAXCONN=5.
  INFO root [0x0000458c] [2018-08-22 22:07:55,865] - server-configs:
  INFO root [0x0000458c] [2018-08-22 22:07:55,865] - 	gameUpdateHertz : 10
  INFO root [0x0000458c] [2018-08-22 22:07:55,865] - 	defaultViewRadius : 80
  INFO root [0x0000458c] [2018-08-22 22:07:55,866] - 	defaultViewHysteresisArea : 5
  INFO root [0x0000458c] [2018-08-22 22:07:55,866] - 	entryScriptFile : kbemain
  INFO root [0x0000458c] [2018-08-22 22:07:55,866] - 	internalAddr : 192.168.0.106:62526
  INFO root [0x0000458c] [2018-08-22 22:07:55,866] - 	componentID : 8001
  WARN root [0x0000458c] [2018-08-22 22:07:56,180] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20371, errorno=10048
  INFO root [0x0000458c] [2018-08-22 22:07:56,187] - ---- cellapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 85A70C5E64F896E0F1A60BF405B4EB07. Config: Debug X86. Built: 15:53:53 Apr 29 2018. AppID: 8001. UID: 2464. PID: 17780 ----
  INFO root [0x0000458c] [2018-08-22 22:07:56,188] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [0x0000458c] [2018-08-22 22:07:56,188] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x0000458c] [2018-08-22 22:07:56,189] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x0000458c] [2018-08-22 22:07:56,329] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x0000458c] [2018-08-22 22:07:56,330] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x0000458c] [2018-08-22 22:07:56,330] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x0000458c] [2018-08-22 22:07:56,333] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x0000458c] [2018-08-22 22:07:56,334] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x0000458c] [2018-08-22 22:07:56,334] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x0000458c] [2018-08-22 22:07:56,334] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x0000458c] [2018-08-22 22:07:56,369] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x0000458c] [2018-08-22 22:07:56,404] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x0000458c] [2018-08-22 22:07:56,404] - Script::install(): KBExtra is successfully!
 DEBUG root [0x0000458c] [2018-08-22 22:07:56,424] - loaded entity-script:Account(1).
 DEBUG root [0x0000458c] [2018-08-22 22:07:56,450] - loaded entity-script:Room(4).
  INFO root [0x0000458c] [2018-08-22 22:07:56,450] - TelnetServer server is running on port 50000
  INFO root [0x0000458c] [2018-08-22 22:07:56,771] - ---- cellapp is running ----
 DEBUG root [0x0000458c] [2018-08-22 22:07:56,772] - Components::process(): Request for the process of identity...
  WARN root [0x0000458c] [2018-08-22 22:08:02,872] - EntityApp::checkTickPeriod: tick took 6100% (6.10 seconds)!
  INFO root [0x0000458c] [2018-08-22 22:08:03,964] - Components::findComponents: find logger(1)...
  INFO root [0x0000458c] [2018-08-22 22:08:03,981] - Components::findComponents: found logger, addr:192.168.0.106:62530
  INFO root [0x0000458c] [2018-08-22 22:08:03,981] - Components::addComponent: reset orderLog, uid=2464!
  INFO root [0x0000458c] [2018-08-22 22:08:03,982] - Components::addComponent[logger], uid=2464, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x0000458c] [2018-08-22 22:08:03,990] - Components::findComponents: find dbmgr(2)...
  INFO root [0x0000458c] [2018-08-22 22:08:04,086] - Components::findComponents: found dbmgr, addr:192.168.0.106:62523
  INFO root [0x0000458c] [2018-08-22 22:08:04,087] - Components::addComponent: reset orderLog, uid=2464!
  INFO root [0x0000458c] [2018-08-22 22:08:04,087] - Components::addComponent[dbmgr], uid=2464, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x0000458c] [2018-08-22 22:08:04,087] - Components::findComponents: found dbmgr, addr:192.168.0.106:62523
  WARN root [0x0000458c] [2018-08-22 22:08:05,088] - Forwarding logs to logger[192.168.0.106:62530/0/0/0]...
