  INFO root [0x000031e0] [2018-11-18 12:32:02,590] - 
  INFO root [0x000031e0] [2018-11-18 12:32:02,726] - -----------------------------------------------------------------------------------------


  INFO root [0x000031e0] [2018-11-18 12:32:03,705] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [0x000031e0] [2018-11-18 12:32:03,705] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [0x000031e0] [2018-11-18 12:32:03,705] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [0x000031e0] [2018-11-18 12:32:03,956] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.107 ( 192.168.0.107:58549 )
  INFO root [0x000031e0] [2018-11-18 12:32:04,003] - NetworkInterface::initialize(INTERNAL): address 192.168.0.107:58549, SOMAXCONN=5.
  INFO root [0x000031e0] [2018-11-18 12:32:04,003] - server-configs:
  INFO root [0x000031e0] [2018-11-18 12:32:04,004] - 	gameUpdateHertz : 10
  INFO root [0x000031e0] [2018-11-18 12:32:04,187] - 	defaultViewRadius : 80
  INFO root [0x000031e0] [2018-11-18 12:32:04,187] - 	defaultViewHysteresisArea : 5
  INFO root [0x000031e0] [2018-11-18 12:32:04,187] - 	entryScriptFile : kbemain
  INFO root [0x000031e0] [2018-11-18 12:32:04,188] - 	internalAddr : 192.168.0.107:58549
  INFO root [0x000031e0] [2018-11-18 12:32:04,189] - 	componentID : 8001
  INFO root [0x000031e0] [2018-11-18 12:32:04,809] - ---- cellapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 85A70C5E64F896E0F1A60BF405B4EB07. Config: Debug X86. Built: 15:53:53 Apr 29 2018. AppID: 8001. UID: 11340. PID: 12372 ----
  INFO root [0x000031e0] [2018-11-18 12:32:04,810] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [0x000031e0] [2018-11-18 12:32:04,862] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x000031e0] [2018-11-18 12:32:04,879] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x000031e0] [2018-11-18 12:32:09,013] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x000031e0] [2018-11-18 12:32:09,161] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x000031e0] [2018-11-18 12:32:09,258] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x000031e0] [2018-11-18 12:32:11,386] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x000031e0] [2018-11-18 12:32:11,751] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x000031e0] [2018-11-18 12:32:11,790] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x000031e0] [2018-11-18 12:32:11,847] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x000031e0] [2018-11-18 12:32:13,240] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x000031e0] [2018-11-18 12:32:14,236] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x000031e0] [2018-11-18 12:32:14,237] - Script::install(): KBExtra is successfully!
 DEBUG root [0x000031e0] [2018-11-18 12:32:15,647] - loaded entity-script:Account(1).
 DEBUG root [0x000031e0] [2018-11-18 12:32:15,970] - loaded entity-script:Room(4).
  INFO root [0x000031e0] [2018-11-18 12:32:16,085] - TelnetServer server is running on port 50000
  INFO root [0x000031e0] [2018-11-18 12:32:17,226] - ---- cellapp is running ----
 DEBUG root [0x000031e0] [2018-11-18 12:32:17,342] - Components::process(): Request for the process of identity...
  WARN root [0x000031e0] [2018-11-18 12:32:23,768] - EntityApp::checkTickPeriod: tick took 6542% (6.54 seconds)!
  WARN root [0x000031e0] [2018-11-18 12:32:23,871] - e:\kbengine\kbe\src\lib\network\event_dispatcher.cpp:153: Profile callSystemTimers took 0.15 seconds
  INFO root [0x000031e0] [2018-11-18 12:32:24,926] - Components::findComponents: find logger(1)...
  INFO root [0x000031e0] [2018-11-18 12:32:25,003] - Components::findComponents: found logger, addr:192.168.0.107:58544
  INFO root [0x000031e0] [2018-11-18 12:32:25,003] - Components::addComponent: reset orderLog, uid=11340!
  INFO root [0x000031e0] [2018-11-18 12:32:25,004] - Components::addComponent[logger], uid=11340, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x000031e0] [2018-11-18 12:32:25,061] - Components::findComponents: find dbmgr(2)...
  WARN root [0x000031e0] [2018-11-18 12:32:26,105] - EntityApp::checkTickPeriod: tick took 1279% (1.28 seconds)!
  WARN root [0x000031e0] [2018-11-18 12:32:26,105] - Forwarding logs to logger[192.168.0.107:58544/0/0/0]...
 ERROR root [0x000031e0] [2018-11-18 12:33:04,050] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x000031e0] [2018-11-18 12:33:04,128] - The following logs sent to logger failed:
  WARN root [0x000031e0] [2018-11-18 12:33:04,129] - ==> [2018-11-18 12:33:04 026] TCPPacketReceiver::processPendingEvents(192.168.0.107:58544): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x000031e0] [2018-11-18 12:33:04,129] - ==> [2018-11-18 12:33:04 050] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x000031e0] [2018-11-18 12:33:04,826] - Components::findComponents: find dbmgr(21)...
delay time is too long, please check the dbmgr logs!
  INFO root [0x00001c38] [2018-11-18 12:33:25,654] - 
  INFO root [0x00001c38] [2018-11-18 12:33:25,654] - -----------------------------------------------------------------------------------------


  INFO root [0x00001c38] [2018-11-18 12:33:25,654] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [0x00001c38] [2018-11-18 12:33:25,654] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [0x00001c38] [2018-11-18 12:33:25,654] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [0x00001c38] [2018-11-18 12:33:25,654] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.107 ( 192.168.0.107:58596 )
  INFO root [0x00001c38] [2018-11-18 12:33:25,654] - NetworkInterface::initialize(INTERNAL): address 192.168.0.107:58596, SOMAXCONN=5.
  INFO root [0x00001c38] [2018-11-18 12:33:25,654] - server-configs:
  INFO root [0x00001c38] [2018-11-18 12:33:25,654] - 	gameUpdateHertz : 10
  INFO root [0x00001c38] [2018-11-18 12:33:25,654] - 	defaultViewRadius : 80
  INFO root [0x00001c38] [2018-11-18 12:33:25,654] - 	defaultViewHysteresisArea : 5
  INFO root [0x00001c38] [2018-11-18 12:33:25,654] - 	entryScriptFile : kbemain
  INFO root [0x00001c38] [2018-11-18 12:33:25,654] - 	internalAddr : 192.168.0.107:58596
  INFO root [0x00001c38] [2018-11-18 12:33:25,654] - 	componentID : 8001
  INFO root [0x00001c38] [2018-11-18 12:33:27,179] - ---- cellapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 85A70C5E64F896E0F1A60BF405B4EB07. Config: Debug X86. Built: 15:53:53 Apr 29 2018. AppID: 8001. UID: 11679. PID: 7436 ----
  INFO root [0x00001c38] [2018-11-18 12:33:27,179] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [0x00001c38] [2018-11-18 12:33:27,179] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00001c38] [2018-11-18 12:33:27,179] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x00001c38] [2018-11-18 12:33:27,179] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00001c38] [2018-11-18 12:33:27,179] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x00001c38] [2018-11-18 12:33:27,179] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x00001c38] [2018-11-18 12:33:27,179] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x00001c38] [2018-11-18 12:33:27,179] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x00001c38] [2018-11-18 12:33:27,179] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x00001c38] [2018-11-18 12:33:27,179] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x00001c38] [2018-11-18 12:33:27,179] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x00001c38] [2018-11-18 12:33:27,179] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x00001c38] [2018-11-18 12:33:27,179] - Script::install(): KBExtra is successfully!
 DEBUG root [0x00001c38] [2018-11-18 12:33:27,179] - loaded entity-script:Account(1).
 DEBUG root [0x00001c38] [2018-11-18 12:33:27,179] - loaded entity-script:Room(4).
  INFO root [0x00001c38] [2018-11-18 12:33:27,179] - TelnetServer server is running on port 50000
  INFO root [0x00001c38] [2018-11-18 12:33:27,179] - ---- cellapp is running ----
 DEBUG root [0x00001c38] [2018-11-18 12:33:27,179] - Components::process(): Request for the process of identity...
  WARN root [0x00001c38] [2018-11-18 12:33:33,868] - EntityApp::checkTickPeriod: tick took 6093% (6.09 seconds)!
  INFO root [0x00001c38] [2018-11-18 12:33:34,959] - Components::findComponents: find logger(1)...
  INFO root [0x00001c38] [2018-11-18 12:33:35,035] - Components::findComponents: found logger, addr:192.168.0.107:58590
  INFO root [0x00001c38] [2018-11-18 12:33:35,035] - Components::addComponent: reset orderLog, uid=11679!
  INFO root [0x00001c38] [2018-11-18 12:33:35,035] - Components::addComponent[logger], uid=11679, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00001c38] [2018-11-18 12:33:35,035] - Components::findComponents: find dbmgr(2)...
  INFO root [0x00001c38] [2018-11-18 12:33:35,035] - Components::findComponents: found dbmgr, addr:192.168.0.107:58591
  INFO root [0x00001c38] [2018-11-18 12:33:35,035] - Components::addComponent: reset orderLog, uid=11679!
  INFO root [0x00001c38] [2018-11-18 12:33:35,035] - Components::addComponent[dbmgr], uid=11679, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00001c38] [2018-11-18 12:33:35,035] - Components::findComponents: found dbmgr, addr:192.168.0.107:58591
  WARN root [0x00001c38] [2018-11-18 12:33:36,142] - Forwarding logs to logger[192.168.0.107:58590/0/0/0]...
 ERROR root [0x00001c38] [2018-11-18 23:14:28,035] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x00001c38] [2018-11-18 23:14:28,035] - The following logs sent to logger failed:
  WARN root [0x00001c38] [2018-11-18 23:14:28,035] - ==> [2018-11-18 23:14:27 976] TCPPacketReceiver::processPendingEvents(192.168.0.107:58590): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00001c38] [2018-11-18 23:14:28,035] - ==> [2018-11-18 23:14:28 035] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x00001c38] [2018-11-18 23:14:28,035] - EntityApp::checkTickPeriod: tick took 237% (0.24 seconds)!
  WARN root [0x00001c38] [2018-11-18 23:14:28,035] - TCPPacketReceiver::processPendingEvents(192.168.0.107:58591): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00001c38] [2018-11-18 23:14:28,035] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x00001c38] [2018-11-18 23:14:28,035] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [0x00001c38] [2018-11-18 23:14:28,035] - Shutdowner::onShutdown: shutting down
  INFO root [0x00001c38] [2018-11-18 23:14:28,035] - Spaces::destroySpace: 2.
  INFO root [0x00001c38] [2018-11-18 23:14:28,035] - Spaces::destroySpace: 1.
  INFO root [0x00001c38] [2018-11-18 23:14:28,035] - Spaces::destroySpace: 3.
  INFO root [0x00001c38] [2018-11-18 23:14:28,035] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [0x00001c38] [2018-11-18 23:14:28,035] - Account::~Account(): 10
 DEBUG root [0x00001c38] [2018-11-18 23:14:28,035] - Account::~Account(): 7
 DEBUG root [0x00001c38] [2018-11-18 23:14:28,035] - Account::~Account(): 5
 DEBUG root [0x00001c38] [2018-11-18 23:14:28,035] - Account::~Account(): 2
 DEBUG root [0x00001c38] [2018-11-18 23:14:28,035] - EntityRef::destroyObjPool(): size 16.
 DEBUG root [0x00001c38] [2018-11-18 23:14:28,035] - Witness::destroyObjPool(): size 16.
 DEBUG root [0x00001c38] [2018-11-18 23:14:28,035] - Room::~Room(): 3
 DEBUG root [0x00001c38] [2018-11-18 23:14:28,035] - Room::~Room(): 9
 DEBUG root [0x00001c38] [2018-11-18 23:14:28,035] - Room::~Room(): 4
 ERROR root [0x00001c38] [2018-11-18 23:14:28,035] - PyGC::debugTracing(): EntityCall : leaked(44)
 DEBUG root [0x00001c38] [2018-11-18 23:14:28,035] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00001c38] [2018-11-18 23:14:28,035] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x00001c38] [2018-11-18 23:14:28,035] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x00001c38] [2018-11-18 23:14:28,035] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x00001c38] [2018-11-18 23:14:28,035] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x00001c38] [2018-11-18 23:14:28,035] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x00001c38] [2018-11-18 23:14:28,035] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x00001c38] [2018-11-18 23:14:28,035] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x00001c38] [2018-11-18 23:14:28,035] - Script::uninstall(): is successfully!
 DEBUG root [0x00001c38] [2018-11-18 23:14:28,035] - ThreadPool::destroy(): starting size 2.
  WARN root [0x00001c38] [2018-11-18 23:14:29,038] - ThreadPool::destroy(): waiting for thread(2)[0x62b5c0,0x62b558,], try=1
  INFO root [0x00001dd0] [2018-11-18 23:14:31,726] - 
  INFO root [0x00001dd0] [2018-11-18 23:14:31,727] - -----------------------------------------------------------------------------------------


  INFO root [0x00001dd0] [2018-11-18 23:14:31,728] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [0x00001dd0] [2018-11-18 23:14:31,728] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [0x00001dd0] [2018-11-18 23:14:31,728] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [0x00001dd0] [2018-11-18 23:14:31,734] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.107 ( 192.168.0.107:49850 )
  INFO root [0x00001dd0] [2018-11-18 23:14:31,734] - NetworkInterface::initialize(INTERNAL): address 192.168.0.107:49850, SOMAXCONN=5.
  INFO root [0x00001dd0] [2018-11-18 23:14:31,734] - server-configs:
  INFO root [0x00001dd0] [2018-11-18 23:14:31,735] - 	gameUpdateHertz : 10
  INFO root [0x00001dd0] [2018-11-18 23:14:31,735] - 	defaultViewRadius : 80
  INFO root [0x00001dd0] [2018-11-18 23:14:31,735] - 	defaultViewHysteresisArea : 5
  INFO root [0x00001dd0] [2018-11-18 23:14:31,735] - 	entryScriptFile : kbemain
  INFO root [0x00001dd0] [2018-11-18 23:14:31,735] - 	internalAddr : 192.168.0.107:49850
  INFO root [0x00001dd0] [2018-11-18 23:14:31,735] - 	componentID : 8001
  INFO root [0x00001dd0] [2018-11-18 23:14:33,245] - ---- cellapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 85A70C5E64F896E0F1A60BF405B4EB07. Config: Debug X86. Built: 15:53:53 Apr 29 2018. AppID: 8001. UID: 6215. PID: 9140 ----
  INFO root [0x00001dd0] [2018-11-18 23:14:33,246] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [0x00001dd0] [2018-11-18 23:14:33,247] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00001dd0] [2018-11-18 23:14:33,248] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x00001dd0] [2018-11-18 23:14:33,382] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00001dd0] [2018-11-18 23:14:33,382] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x00001dd0] [2018-11-18 23:14:33,382] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x00001dd0] [2018-11-18 23:14:33,386] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x00001dd0] [2018-11-18 23:14:33,386] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x00001dd0] [2018-11-18 23:14:33,387] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x00001dd0] [2018-11-18 23:14:33,387] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x00001dd0] [2018-11-18 23:14:33,428] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x00001dd0] [2018-11-18 23:14:33,462] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x00001dd0] [2018-11-18 23:14:33,462] - Script::install(): KBExtra is successfully!
 DEBUG root [0x00001dd0] [2018-11-18 23:14:33,488] - loaded entity-script:Account(1).
 DEBUG root [0x00001dd0] [2018-11-18 23:14:33,496] - loaded entity-script:Room(4).
  INFO root [0x00001dd0] [2018-11-18 23:14:33,496] - TelnetServer server is running on port 50000
  INFO root [0x00001dd0] [2018-11-18 23:14:33,848] - ---- cellapp is running ----
 DEBUG root [0x00001dd0] [2018-11-18 23:14:33,849] - Components::process(): Request for the process of identity...
  WARN root [0x00001dd0] [2018-11-18 23:14:39,953] - EntityApp::checkTickPeriod: tick took 6103% (6.10 seconds)!
  INFO root [0x00001dd0] [2018-11-18 23:14:41,031] - Components::findComponents: find logger(1)...
  INFO root [0x00001dd0] [2018-11-18 23:14:41,062] - Components::findComponents: found logger, addr:192.168.0.107:49846
  INFO root [0x00001dd0] [2018-11-18 23:14:41,062] - Components::addComponent: reset orderLog, uid=6215!
  INFO root [0x00001dd0] [2018-11-18 23:14:41,063] - Components::addComponent[logger], uid=6215, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00001dd0] [2018-11-18 23:14:41,107] - Components::findComponents: find dbmgr(2)...
  INFO root [0x00001dd0] [2018-11-18 23:14:41,166] - Components::findComponents: found dbmgr, addr:192.168.0.107:49843
  INFO root [0x00001dd0] [2018-11-18 23:14:41,166] - Components::addComponent: reset orderLog, uid=6215!
  INFO root [0x00001dd0] [2018-11-18 23:14:41,166] - Components::addComponent[dbmgr], uid=6215, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00001dd0] [2018-11-18 23:14:41,167] - Components::findComponents: found dbmgr, addr:192.168.0.107:49843
  WARN root [0x00001dd0] [2018-11-18 23:14:42,167] - Forwarding logs to logger[192.168.0.107:49846/0/0/0]...
