  INFO root [0x00000a40] [2018-11-03 13:43:54,051] - 
  INFO root [0x00000a40] [2018-11-03 13:43:54,103] - -----------------------------------------------------------------------------------------


  INFO root [0x00000a40] [2018-11-03 13:43:55,606] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [0x00000a40] [2018-11-03 13:43:55,607] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [0x00000a40] [2018-11-03 13:43:55,607] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [0x00000a40] [2018-11-03 13:43:56,341] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.107 ( 192.168.0.107:54382 )
  INFO root [0x00000a40] [2018-11-03 13:43:56,354] - NetworkInterface::initialize(INTERNAL): address 192.168.0.107:54382, SOMAXCONN=5.
  INFO root [0x00000a40] [2018-11-03 13:43:56,355] - server-configs:
  INFO root [0x00000a40] [2018-11-03 13:43:56,355] - 	gameUpdateHertz : 10
  INFO root [0x00000a40] [2018-11-03 13:43:56,463] - 	defaultViewRadius : 80
  INFO root [0x00000a40] [2018-11-03 13:43:56,464] - 	defaultViewHysteresisArea : 5
  INFO root [0x00000a40] [2018-11-03 13:43:56,464] - 	entryScriptFile : kbemain
  INFO root [0x00000a40] [2018-11-03 13:43:56,464] - 	internalAddr : 192.168.0.107:54382
  INFO root [0x00000a40] [2018-11-03 13:43:56,464] - 	componentID : 8001
  INFO root [0x00000a40] [2018-11-03 13:43:56,985] - Components::findLogger: found logger, addr:192.168.0.107:54377
  INFO root [0x00000a40] [2018-11-03 13:43:56,985] - Components::addComponent: reset orderLog, uid=20302!
  INFO root [0x00000a40] [2018-11-03 13:43:56,986] - Components::addComponent[logger], uid=20302, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00000a40] [2018-11-03 13:43:57,207] - ---- cellapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 85A70C5E64F896E0F1A60BF405B4EB07. Config: Debug X86. Built: 15:53:53 Apr 29 2018. AppID: 8001. UID: 20302. PID: 2612 ----
  INFO root [0x00000a40] [2018-11-03 13:43:57,207] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [0x00000a40] [2018-11-03 13:43:57,247] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00000a40] [2018-11-03 13:43:57,264] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x00000a40] [2018-11-03 13:44:02,015] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00000a40] [2018-11-03 13:44:02,155] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x00000a40] [2018-11-03 13:44:02,244] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x00000a40] [2018-11-03 13:44:03,446] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x00000a40] [2018-11-03 13:44:03,811] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x00000a40] [2018-11-03 13:44:03,858] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x00000a40] [2018-11-03 13:44:03,974] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x00000a40] [2018-11-03 13:44:04,918] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x00000a40] [2018-11-03 13:44:07,072] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x00000a40] [2018-11-03 13:44:07,072] - Script::install(): KBExtra is successfully!
 DEBUG root [0x00000a40] [2018-11-03 13:44:08,191] - loaded entity-script:Account(1).
 DEBUG root [0x00000a40] [2018-11-03 13:44:08,774] - loaded entity-script:Room(4).
  INFO root [0x00000a40] [2018-11-03 13:44:08,862] - TelnetServer server is running on port 50000
  INFO root [0x00000a40] [2018-11-03 13:44:09,821] - ---- cellapp is running ----
 DEBUG root [0x00000a40] [2018-11-03 13:44:09,823] - Components::process(): Request for the process of identity...
  WARN root [0x00000a40] [2018-11-03 13:44:13,290] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20695, errorno=10048
  WARN root [0x00000a40] [2018-11-03 13:44:16,360] - Forwarding logs to logger[192.168.0.107:54377/0/0/0]...
 ERROR root [0x00000a40] [2018-11-03 13:46:20,345] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x00000a40] [2018-11-03 13:46:20,371] - The following logs sent to logger failed:
  WARN root [0x00000a40] [2018-11-03 13:46:20,372] - ==> [2018-11-03 13:46:20 340] TCPPacketReceiver::processPendingEvents(192.168.0.107:54377): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00000a40] [2018-11-03 13:46:20,372] - ==> [2018-11-03 13:46:20 346] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x00000a40] [2018-11-03 13:46:20,417] - TCPPacketReceiver::processPendingEvents(192.168.0.107:54381): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00000a40] [2018-11-03 13:46:20,422] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x00000a40] [2018-11-03 13:46:20,501] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [0x00000a40] [2018-11-03 13:46:20,502] - Shutdowner::onShutdown: shutting down
  INFO root [0x00000a40] [2018-11-03 13:46:20,502] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [0x00000a40] [2018-11-03 13:46:20,594] - EntityRef::destroyObjPool(): size 0.
 DEBUG root [0x00000a40] [2018-11-03 13:46:20,594] - Witness::destroyObjPool(): size 0.
  INFO root [0x00000a00] [2018-11-03 13:46:21,869] - 
  INFO root [0x00000a00] [2018-11-03 13:46:21,870] - -----------------------------------------------------------------------------------------


  INFO root [0x00000a00] [2018-11-03 13:46:21,871] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [0x00000a00] [2018-11-03 13:46:21,871] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [0x00000a00] [2018-11-03 13:46:21,871] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [0x00000a00] [2018-11-03 13:46:21,879] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.107 ( 192.168.0.107:54446 )
  INFO root [0x00000a00] [2018-11-03 13:46:21,879] - NetworkInterface::initialize(INTERNAL): address 192.168.0.107:54446, SOMAXCONN=5.
  INFO root [0x00000a00] [2018-11-03 13:46:21,879] - server-configs:
  INFO root [0x00000a00] [2018-11-03 13:46:21,879] - 	gameUpdateHertz : 10
  INFO root [0x00000a00] [2018-11-03 13:46:21,880] - 	defaultViewRadius : 80
  INFO root [0x00000a00] [2018-11-03 13:46:21,880] - 	defaultViewHysteresisArea : 5
  INFO root [0x00000a00] [2018-11-03 13:46:21,880] - 	entryScriptFile : kbemain
  INFO root [0x00000a00] [2018-11-03 13:46:21,880] - 	internalAddr : 192.168.0.107:54446
  INFO root [0x00000a00] [2018-11-03 13:46:21,880] - 	componentID : 8001
  INFO root [0x00000a00] [2018-11-03 13:46:23,398] - ---- cellapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 85A70C5E64F896E0F1A60BF405B4EB07. Config: Debug X86. Built: 15:53:53 Apr 29 2018. AppID: 8001. UID: 20854. PID: 4360 ----
  INFO root [0x00000a00] [2018-11-03 13:46:23,399] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [0x00000a00] [2018-11-03 13:46:23,399] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00000a00] [2018-11-03 13:46:23,400] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x00000a00] [2018-11-03 13:46:23,555] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00000a00] [2018-11-03 13:46:23,556] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x00000a00] [2018-11-03 13:46:23,556] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x00000a00] [2018-11-03 13:46:23,559] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x00000a00] [2018-11-03 13:46:23,559] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x00000a00] [2018-11-03 13:46:23,559] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x00000a00] [2018-11-03 13:46:23,560] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x00000a00] [2018-11-03 13:46:23,587] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x00000a00] [2018-11-03 13:46:23,617] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x00000a00] [2018-11-03 13:46:23,617] - Script::install(): KBExtra is successfully!
 DEBUG root [0x00000a00] [2018-11-03 13:46:23,637] - loaded entity-script:Account(1).
 DEBUG root [0x00000a00] [2018-11-03 13:46:23,646] - loaded entity-script:Room(4).
  INFO root [0x00000a00] [2018-11-03 13:46:23,646] - TelnetServer server is running on port 50000
  INFO root [0x00000a00] [2018-11-03 13:46:23,984] - ---- cellapp is running ----
 DEBUG root [0x00000a00] [2018-11-03 13:46:23,985] - Components::process(): Request for the process of identity...
  WARN root [0x00000a00] [2018-11-03 13:46:30,119] - EntityApp::checkTickPeriod: tick took 6133% (6.13 seconds)!
  INFO root [0x00000a00] [2018-11-03 13:46:31,177] - Components::findComponents: find logger(1)...
  WARN root [0x00000a00] [2018-11-03 13:46:31,488] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20249, errorno=10048
  WARN root [0x00000a00] [2018-11-03 13:46:31,489] - EntityApp::checkTickPeriod: tick took 403% (0.40 seconds)!
  INFO root [0x00000a00] [2018-11-03 13:46:32,577] - Components::findComponents: find logger(2)...
  INFO root [0x00000a00] [2018-11-03 13:46:32,681] - Components::findComponents: found logger, addr:192.168.0.107:54451
  INFO root [0x00000a00] [2018-11-03 13:46:32,681] - Components::addComponent: reset orderLog, uid=20854!
  INFO root [0x00000a00] [2018-11-03 13:46:32,682] - Components::addComponent[logger], uid=20854, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00000a00] [2018-11-03 13:46:32,684] - Components::findComponents: find dbmgr(3)...
  INFO root [0x00000a00] [2018-11-03 13:46:32,785] - Components::findComponents: found dbmgr, addr:192.168.0.107:54448
  INFO root [0x00000a00] [2018-11-03 13:46:32,785] - Components::addComponent: reset orderLog, uid=20854!
  INFO root [0x00000a00] [2018-11-03 13:46:32,785] - Components::addComponent[dbmgr], uid=20854, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00000a00] [2018-11-03 13:46:32,786] - Components::findComponents: found dbmgr, addr:192.168.0.107:54448
  WARN root [0x00000a00] [2018-11-03 13:46:33,786] - Forwarding logs to logger[192.168.0.107:54451/0/0/0]...
 ERROR root [0x00000a00] [2018-11-03 14:09:52,773] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x00000a00] [2018-11-03 14:09:52,797] - The following logs sent to logger failed:
  WARN root [0x00000a00] [2018-11-03 14:09:52,798] - ==> [2018-11-03 14:09:52 769] TCPPacketReceiver::processPendingEvents(192.168.0.107:54451): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00000a00] [2018-11-03 14:09:52,798] - ==> [2018-11-03 14:09:52 773] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x00000a00] [2018-11-03 14:09:52,854] - TCPPacketReceiver::processPendingEvents(192.168.0.107:54448): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00000a00] [2018-11-03 14:09:52,865] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x00000a00] [2018-11-03 14:09:52,872] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [0x00000a00] [2018-11-03 14:09:52,874] - Shutdowner::onShutdown: shutting down
  INFO root [0x00000a00] [2018-11-03 14:09:52,874] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [0x00000a00] [2018-11-03 14:09:52,874] - EntityRef::destroyObjPool(): size 0.
 DEBUG root [0x00000a00] [2018-11-03 14:09:52,874] - Witness::destroyObjPool(): size 0.
 DEBUG root [0x00000a00] [2018-11-03 14:09:52,928] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00000a00] [2018-11-03 14:09:52,928] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x00000a00] [2018-11-03 14:09:52,928] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x00000a00] [2018-11-03 14:09:52,928] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x00000a00] [2018-11-03 14:09:52,928] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x00000a00] [2018-11-03 14:09:52,929] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x00000a00] [2018-11-03 14:09:52,929] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x00000a00] [2018-11-03 14:09:52,929] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x00000a00] [2018-11-03 14:09:52,943] - Script::uninstall(): is successfully!
 DEBUG root [0x00000a00] [2018-11-03 14:09:52,943] - ThreadPool::destroy(): starting size 2.
  INFO root [0x0000050c] [2018-11-03 14:09:54,189] - 
  INFO root [0x0000050c] [2018-11-03 14:09:54,190] - -----------------------------------------------------------------------------------------


  INFO root [0x0000050c] [2018-11-03 14:09:54,191] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [0x0000050c] [2018-11-03 14:09:54,191] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [0x0000050c] [2018-11-03 14:09:54,191] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [0x0000050c] [2018-11-03 14:09:54,195] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.107 ( 192.168.0.107:54988 )
  INFO root [0x0000050c] [2018-11-03 14:09:54,195] - NetworkInterface::initialize(INTERNAL): address 192.168.0.107:54988, SOMAXCONN=5.
  INFO root [0x0000050c] [2018-11-03 14:09:54,195] - server-configs:
  INFO root [0x0000050c] [2018-11-03 14:09:54,195] - 	gameUpdateHertz : 10
  INFO root [0x0000050c] [2018-11-03 14:09:54,195] - 	defaultViewRadius : 80
  INFO root [0x0000050c] [2018-11-03 14:09:54,195] - 	defaultViewHysteresisArea : 5
  INFO root [0x0000050c] [2018-11-03 14:09:54,195] - 	entryScriptFile : kbemain
  INFO root [0x0000050c] [2018-11-03 14:09:54,196] - 	internalAddr : 192.168.0.107:54988
  INFO root [0x0000050c] [2018-11-03 14:09:54,196] - 	componentID : 8001
  WARN root [0x0000050c] [2018-11-03 14:09:54,506] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20422, errorno=10048
  INFO root [0x0000050c] [2018-11-03 14:09:54,513] - ---- cellapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 85A70C5E64F896E0F1A60BF405B4EB07. Config: Debug X86. Built: 15:53:53 Apr 29 2018. AppID: 8001. UID: 25465. PID: 2692 ----
  INFO root [0x0000050c] [2018-11-03 14:09:54,513] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [0x0000050c] [2018-11-03 14:09:54,513] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x0000050c] [2018-11-03 14:09:54,513] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x0000050c] [2018-11-03 14:09:54,643] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x0000050c] [2018-11-03 14:09:54,643] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x0000050c] [2018-11-03 14:09:54,644] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x0000050c] [2018-11-03 14:09:54,646] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x0000050c] [2018-11-03 14:09:54,647] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x0000050c] [2018-11-03 14:09:54,647] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x0000050c] [2018-11-03 14:09:54,647] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x0000050c] [2018-11-03 14:09:54,676] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x0000050c] [2018-11-03 14:09:54,707] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x0000050c] [2018-11-03 14:09:54,707] - Script::install(): KBExtra is successfully!
 DEBUG root [0x0000050c] [2018-11-03 14:09:54,728] - loaded entity-script:Account(1).
 DEBUG root [0x0000050c] [2018-11-03 14:09:54,737] - loaded entity-script:Room(4).
  INFO root [0x0000050c] [2018-11-03 14:09:54,737] - TelnetServer server is running on port 50000
  INFO root [0x0000050c] [2018-11-03 14:09:55,030] - ---- cellapp is running ----
 DEBUG root [0x0000050c] [2018-11-03 14:09:55,031] - Components::process(): Request for the process of identity...
  WARN root [0x0000050c] [2018-11-03 14:10:01,111] - EntityApp::checkTickPeriod: tick took 6081% (6.08 seconds)!
  INFO root [0x0000050c] [2018-11-03 14:10:02,192] - Components::findComponents: find logger(1)...
  INFO root [0x0000050c] [2018-11-03 14:10:02,292] - Components::findComponents: found logger, addr:192.168.0.107:54987
  INFO root [0x0000050c] [2018-11-03 14:10:02,293] - Components::addComponent: reset orderLog, uid=25465!
  INFO root [0x0000050c] [2018-11-03 14:10:02,293] - Components::addComponent[logger], uid=25465, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x0000050c] [2018-11-03 14:10:02,296] - Components::findComponents: find dbmgr(2)...
  INFO root [0x0000050c] [2018-11-03 14:10:02,397] - Components::findComponents: found dbmgr, addr:192.168.0.107:54986
  INFO root [0x0000050c] [2018-11-03 14:10:02,398] - Components::addComponent: reset orderLog, uid=25465!
  INFO root [0x0000050c] [2018-11-03 14:10:02,399] - Components::addComponent[dbmgr], uid=25465, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x0000050c] [2018-11-03 14:10:02,399] - Components::findComponents: found dbmgr, addr:192.168.0.107:54986
  WARN root [0x0000050c] [2018-11-03 14:10:03,400] - Forwarding logs to logger[192.168.0.107:54987/0/0/0]...
 ERROR root [0x0000050c] [2018-11-03 14:11:38,031] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x0000050c] [2018-11-03 14:11:38,042] - The following logs sent to logger failed:
  WARN root [0x0000050c] [2018-11-03 14:11:38,043] - ==> [2018-11-03 14:11:38 026] TCPPacketReceiver::processPendingEvents(192.168.0.107:54987): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x0000050c] [2018-11-03 14:11:38,043] - ==> [2018-11-03 14:11:38 032] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x0000050c] [2018-11-03 14:11:38,103] - TCPPacketReceiver::processPendingEvents(192.168.0.107:54986): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x0000050c] [2018-11-03 14:11:38,107] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x0000050c] [2018-11-03 14:11:38,130] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [0x0000050c] [2018-11-03 14:11:38,130] - Shutdowner::onShutdown: shutting down
  INFO root [0x0000050c] [2018-11-03 14:11:38,130] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [0x0000050c] [2018-11-03 14:11:38,131] - EntityRef::destroyObjPool(): size 0.
 DEBUG root [0x0000050c] [2018-11-03 14:11:38,131] - Witness::destroyObjPool(): size 0.
 DEBUG root [0x0000050c] [2018-11-03 14:11:38,139] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x0000050c] [2018-11-03 14:11:38,140] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x0000050c] [2018-11-03 14:11:38,140] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x0000050c] [2018-11-03 14:11:38,140] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x0000050c] [2018-11-03 14:11:38,140] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x0000050c] [2018-11-03 14:11:38,140] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x0000050c] [2018-11-03 14:11:38,140] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x0000050c] [2018-11-03 14:11:38,140] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x0000050c] [2018-11-03 14:11:38,151] - Script::uninstall(): is successfully!
 DEBUG root [0x0000050c] [2018-11-03 14:11:38,151] - ThreadPool::destroy(): starting size 2.
  INFO root [0x00002a48] [2018-11-03 14:11:39,457] - 
  INFO root [0x00002a48] [2018-11-03 14:11:39,458] - -----------------------------------------------------------------------------------------


  INFO root [0x00002a48] [2018-11-03 14:11:39,459] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [0x00002a48] [2018-11-03 14:11:39,460] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [0x00002a48] [2018-11-03 14:11:39,460] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [0x00002a48] [2018-11-03 14:11:39,465] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.107 ( 192.168.0.107:55052 )
  INFO root [0x00002a48] [2018-11-03 14:11:39,465] - NetworkInterface::initialize(INTERNAL): address 192.168.0.107:55052, SOMAXCONN=5.
  INFO root [0x00002a48] [2018-11-03 14:11:39,465] - server-configs:
  INFO root [0x00002a48] [2018-11-03 14:11:39,465] - 	gameUpdateHertz : 10
  INFO root [0x00002a48] [2018-11-03 14:11:39,465] - 	defaultViewRadius : 80
  INFO root [0x00002a48] [2018-11-03 14:11:39,465] - 	defaultViewHysteresisArea : 5
  INFO root [0x00002a48] [2018-11-03 14:11:39,466] - 	entryScriptFile : kbemain
  INFO root [0x00002a48] [2018-11-03 14:11:39,466] - 	internalAddr : 192.168.0.107:55052
  INFO root [0x00002a48] [2018-11-03 14:11:39,466] - 	componentID : 8001
  INFO root [0x00002a48] [2018-11-03 14:11:40,980] - ---- cellapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 85A70C5E64F896E0F1A60BF405B4EB07. Config: Debug X86. Built: 15:53:53 Apr 29 2018. AppID: 8001. UID: 25808. PID: 5112 ----
  INFO root [0x00002a48] [2018-11-03 14:11:40,981] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [0x00002a48] [2018-11-03 14:11:40,982] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00002a48] [2018-11-03 14:11:40,983] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x00002a48] [2018-11-03 14:11:41,129] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00002a48] [2018-11-03 14:11:41,129] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x00002a48] [2018-11-03 14:11:41,130] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x00002a48] [2018-11-03 14:11:41,132] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x00002a48] [2018-11-03 14:11:41,133] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x00002a48] [2018-11-03 14:11:41,133] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x00002a48] [2018-11-03 14:11:41,133] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x00002a48] [2018-11-03 14:11:41,162] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x00002a48] [2018-11-03 14:11:41,191] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x00002a48] [2018-11-03 14:11:41,192] - Script::install(): KBExtra is successfully!
 DEBUG root [0x00002a48] [2018-11-03 14:11:41,212] - loaded entity-script:Account(1).
 DEBUG root [0x00002a48] [2018-11-03 14:11:41,220] - loaded entity-script:Room(4).
  INFO root [0x00002a48] [2018-11-03 14:11:41,221] - TelnetServer server is running on port 50000
  INFO root [0x00002a48] [2018-11-03 14:11:41,549] - ---- cellapp is running ----
 DEBUG root [0x00002a48] [2018-11-03 14:11:41,549] - Components::process(): Request for the process of identity...
  WARN root [0x00002a48] [2018-11-03 14:11:47,624] - EntityApp::checkTickPeriod: tick took 6075% (6.07 seconds)!
  INFO root [0x00002a48] [2018-11-03 14:11:48,650] - Components::findComponents: find logger(1)...
  INFO root [0x00002a48] [2018-11-03 14:11:48,752] - Components::findComponents: found logger, addr:192.168.0.107:55051
  INFO root [0x00002a48] [2018-11-03 14:11:48,752] - Components::addComponent: reset orderLog, uid=25808!
  INFO root [0x00002a48] [2018-11-03 14:11:48,753] - Components::addComponent[logger], uid=25808, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00002a48] [2018-11-03 14:11:48,754] - Components::findComponents: find dbmgr(2)...
  INFO root [0x00002a48] [2018-11-03 14:11:48,858] - Components::findComponents: found dbmgr, addr:192.168.0.107:55047
  INFO root [0x00002a48] [2018-11-03 14:11:48,859] - Components::addComponent: reset orderLog, uid=25808!
  INFO root [0x00002a48] [2018-11-03 14:11:48,860] - Components::addComponent[dbmgr], uid=25808, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00002a48] [2018-11-03 14:11:48,861] - Components::findComponents: found dbmgr, addr:192.168.0.107:55047
  WARN root [0x00002a48] [2018-11-03 14:11:49,861] - EntityApp::checkTickPeriod: tick took 1311% (1.31 seconds)!
  WARN root [0x00002a48] [2018-11-03 14:11:49,862] - Forwarding logs to logger[192.168.0.107:55051/0/0/0]...
 ERROR root [0x00002a48] [2018-11-03 14:13:23,521] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x00002a48] [2018-11-03 14:13:23,546] - The following logs sent to logger failed:
  WARN root [0x00002a48] [2018-11-03 14:13:23,546] - ==> [2018-11-03 14:13:23 517] TCPPacketReceiver::processPendingEvents(192.168.0.107:55051): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00002a48] [2018-11-03 14:13:23,546] - ==> [2018-11-03 14:13:23 522] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x00002a48] [2018-11-03 14:13:23,594] - TCPPacketReceiver::processPendingEvents(192.168.0.107:55047): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00002a48] [2018-11-03 14:13:23,599] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x00002a48] [2018-11-03 14:13:23,616] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [0x00002a48] [2018-11-03 14:13:23,619] - Shutdowner::onShutdown: shutting down
  INFO root [0x00002a48] [2018-11-03 14:13:23,620] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [0x00002a48] [2018-11-03 14:13:23,620] - EntityRef::destroyObjPool(): size 0.
 DEBUG root [0x00002a48] [2018-11-03 14:13:23,620] - Witness::destroyObjPool(): size 0.
 DEBUG root [0x00002a48] [2018-11-03 14:13:23,629] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00002a48] [2018-11-03 14:13:23,629] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x00002a48] [2018-11-03 14:13:23,629] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x00002a48] [2018-11-03 14:13:23,629] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x00002a48] [2018-11-03 14:13:23,629] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x00002a48] [2018-11-03 14:13:23,629] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x00002a48] [2018-11-03 14:13:23,629] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x00002a48] [2018-11-03 14:13:23,629] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x00002a48] [2018-11-03 14:13:23,639] - Script::uninstall(): is successfully!
 DEBUG root [0x00002a48] [2018-11-03 14:13:23,640] - ThreadPool::destroy(): starting size 2.
  INFO root [0x0000227c] [2018-11-03 14:14:16,804] - 
  INFO root [0x0000227c] [2018-11-03 14:14:16,804] - -----------------------------------------------------------------------------------------


  INFO root [0x0000227c] [2018-11-03 14:14:16,805] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [0x0000227c] [2018-11-03 14:14:16,805] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [0x0000227c] [2018-11-03 14:14:16,806] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [0x0000227c] [2018-11-03 14:14:16,808] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.107 ( 192.168.0.107:55124 )
  INFO root [0x0000227c] [2018-11-03 14:14:16,808] - NetworkInterface::initialize(INTERNAL): address 192.168.0.107:55124, SOMAXCONN=5.
  INFO root [0x0000227c] [2018-11-03 14:14:16,809] - server-configs:
  INFO root [0x0000227c] [2018-11-03 14:14:16,809] - 	gameUpdateHertz : 10
  INFO root [0x0000227c] [2018-11-03 14:14:16,809] - 	defaultViewRadius : 80
  INFO root [0x0000227c] [2018-11-03 14:14:16,809] - 	defaultViewHysteresisArea : 5
  INFO root [0x0000227c] [2018-11-03 14:14:16,809] - 	entryScriptFile : kbemain
  INFO root [0x0000227c] [2018-11-03 14:14:16,809] - 	internalAddr : 192.168.0.107:55124
  INFO root [0x0000227c] [2018-11-03 14:14:16,810] - 	componentID : 8001
  WARN root [0x0000227c] [2018-11-03 14:14:17,120] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20034, errorno=10048
  INFO root [0x0000227c] [2018-11-03 14:14:17,127] - ---- cellapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 85A70C5E64F896E0F1A60BF405B4EB07. Config: Debug X86. Built: 15:53:53 Apr 29 2018. AppID: 8001. UID: 26324. PID: 10804 ----
  INFO root [0x0000227c] [2018-11-03 14:14:17,127] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [0x0000227c] [2018-11-03 14:14:17,127] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x0000227c] [2018-11-03 14:14:17,128] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x0000227c] [2018-11-03 14:14:17,257] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x0000227c] [2018-11-03 14:14:17,258] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x0000227c] [2018-11-03 14:14:17,258] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x0000227c] [2018-11-03 14:14:17,262] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x0000227c] [2018-11-03 14:14:17,262] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x0000227c] [2018-11-03 14:14:17,262] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x0000227c] [2018-11-03 14:14:17,263] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x0000227c] [2018-11-03 14:14:17,294] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x0000227c] [2018-11-03 14:14:17,323] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x0000227c] [2018-11-03 14:14:17,323] - Script::install(): KBExtra is successfully!
 DEBUG root [0x0000227c] [2018-11-03 14:14:17,349] - loaded entity-script:Account(1).
 DEBUG root [0x0000227c] [2018-11-03 14:14:17,357] - loaded entity-script:Room(4).
  INFO root [0x0000227c] [2018-11-03 14:14:17,357] - TelnetServer server is running on port 50000
  INFO root [0x0000227c] [2018-11-03 14:14:17,650] - ---- cellapp is running ----
 DEBUG root [0x0000227c] [2018-11-03 14:14:17,651] - Components::process(): Request for the process of identity...
  WARN root [0x0000227c] [2018-11-03 14:14:23,705] - EntityApp::checkTickPeriod: tick took 6054% (6.05 seconds)!
  INFO root [0x0000227c] [2018-11-03 14:14:24,751] - Components::findComponents: find logger(1)...
 ERROR root [0x0000227c] [2018-11-03 14:14:26,253] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [0x0000227c] [2018-11-03 14:14:26,256] - Components::findComponents: receive error!
  WARN root [0x0000227c] [2018-11-03 14:14:26,257] - Components::findComponents: not found logger!
  WARN root [0x0000227c] [2018-11-03 14:14:26,258] - EntityApp::checkTickPeriod: tick took 1606% (1.61 seconds)!
  INFO root [0x0000227c] [2018-11-03 14:14:27,307] - Components::findComponents: find dbmgr(1)...
 ERROR root [0x0000227c] [2018-11-03 14:14:28,810] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [0x0000227c] [2018-11-03 14:14:28,815] - Components::findComponents: receive error!
  WARN root [0x0000227c] [2018-11-03 14:14:28,817] - EntityApp::checkTickPeriod: tick took 1565% (1.57 seconds)!
  INFO root [0x0000227c] [2018-11-03 14:14:29,852] - Components::findComponents: find dbmgr(2)...
 ERROR root [0x0000227c] [2018-11-03 14:14:31,353] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [0x0000227c] [2018-11-03 14:14:31,356] - Components::findComponents: receive error!
  WARN root [0x0000227c] [2018-11-03 14:14:31,359] - EntityApp::checkTickPeriod: tick took 1606% (1.61 seconds)!
  INFO root [0x0000227c] [2018-11-03 14:14:32,407] - Components::findComponents: find dbmgr(3)...
 ERROR root [0x0000227c] [2018-11-03 14:14:33,909] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [0x0000227c] [2018-11-03 14:14:33,912] - Components::findComponents: receive error!
  WARN root [0x0000227c] [2018-11-03 14:14:33,914] - EntityApp::checkTickPeriod: tick took 1562% (1.56 seconds)!
  INFO root [0x0000227c] [2018-11-03 14:14:34,951] - Components::findComponents: find dbmgr(4)...
 ERROR root [0x0000227c] [2018-11-03 14:14:36,453] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [0x0000227c] [2018-11-03 14:14:36,456] - Components::findComponents: receive error!
  WARN root [0x0000227c] [2018-11-03 14:14:36,458] - EntityApp::checkTickPeriod: tick took 1606% (1.61 seconds)!
  INFO root [0x0000227c] [2018-11-03 14:14:37,507] - Components::findComponents: find dbmgr(5)...
 ERROR root [0x0000227c] [2018-11-03 14:14:39,009] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [0x0000227c] [2018-11-03 14:14:39,011] - Components::findComponents: receive error!
  WARN root [0x0000227c] [2018-11-03 14:14:39,012] - EntityApp::checkTickPeriod: tick took 1561% (1.56 seconds)!
  INFO root [0x0000227c] [2018-11-03 14:14:40,051] - Components::findComponents: find dbmgr(6)...
 ERROR root [0x0000227c] [2018-11-03 14:14:41,553] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [0x0000227c] [2018-11-03 14:14:41,556] - Components::findComponents: receive error!
  WARN root [0x0000227c] [2018-11-03 14:14:41,558] - EntityApp::checkTickPeriod: tick took 1607% (1.61 seconds)!
  INFO root [0x0000227c] [2018-11-03 14:14:42,607] - Components::findComponents: find dbmgr(7)...
 ERROR root [0x0000227c] [2018-11-03 14:14:44,109] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [0x0000227c] [2018-11-03 14:14:44,112] - Components::findComponents: receive error!
  WARN root [0x0000227c] [2018-11-03 14:14:44,114] - EntityApp::checkTickPeriod: tick took 1562% (1.56 seconds)!
  INFO root [0x0000227c] [2018-11-03 14:14:45,152] - Components::findComponents: find dbmgr(8)...
 ERROR root [0x0000227c] [2018-11-03 14:14:46,653] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [0x0000227c] [2018-11-03 14:14:46,656] - Components::findComponents: receive error!
  WARN root [0x0000227c] [2018-11-03 14:14:46,658] - EntityApp::checkTickPeriod: tick took 1605% (1.61 seconds)!
  INFO root [0x0000227c] [2018-11-03 14:14:47,707] - Components::findComponents: find dbmgr(9)...
 ERROR root [0x0000227c] [2018-11-03 14:14:49,209] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [0x0000227c] [2018-11-03 14:14:49,210] - Components::findComponents: receive error!
  WARN root [0x0000227c] [2018-11-03 14:14:49,210] - EntityApp::checkTickPeriod: tick took 1558% (1.56 seconds)!
  INFO root [0x0000227c] [2018-11-03 14:14:50,252] - Components::findComponents: find dbmgr(10)...
 ERROR root [0x0000227c] [2018-11-03 14:14:51,754] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [0x0000227c] [2018-11-03 14:14:51,757] - Components::findComponents: receive error!
  WARN root [0x0000227c] [2018-11-03 14:14:51,758] - EntityApp::checkTickPeriod: tick took 1606% (1.61 seconds)!
  INFO root [0x0000227c] [2018-11-03 14:14:52,807] - Components::findComponents: find dbmgr(11)...
 ERROR root [0x0000227c] [2018-11-03 14:14:54,308] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [0x0000227c] [2018-11-03 14:14:54,309] - Components::findComponents: receive error!
  WARN root [0x0000227c] [2018-11-03 14:14:54,311] - EntityApp::checkTickPeriod: tick took 1559% (1.56 seconds)!
  INFO root [0x0000227c] [2018-11-03 14:14:55,351] - Components::findComponents: find dbmgr(12)...
 ERROR root [0x0000227c] [2018-11-03 14:14:56,851] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [0x0000227c] [2018-11-03 14:14:56,851] - Components::findComponents: receive error!
  WARN root [0x0000227c] [2018-11-03 14:14:56,854] - EntityApp::checkTickPeriod: tick took 1603% (1.60 seconds)!
  INFO root [0x0000227c] [2018-11-03 14:14:57,907] - Components::findComponents: find dbmgr(13)...
 ERROR root [0x0000227c] [2018-11-03 14:14:59,409] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [0x0000227c] [2018-11-03 14:14:59,410] - Components::findComponents: receive error!
  WARN root [0x0000227c] [2018-11-03 14:14:59,411] - EntityApp::checkTickPeriod: tick took 1560% (1.56 seconds)!
  INFO root [0x0000227c] [2018-11-03 14:15:00,452] - Components::findComponents: find dbmgr(14)...
  INFO root [0x00002548] [2018-11-03 14:15:01,744] - 
  INFO root [0x00002548] [2018-11-03 14:15:01,745] - -----------------------------------------------------------------------------------------


  INFO root [0x00002548] [2018-11-03 14:15:01,746] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [0x00002548] [2018-11-03 14:15:01,746] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [0x00002548] [2018-11-03 14:15:01,746] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [0x00002548] [2018-11-03 14:15:01,749] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.107 ( 192.168.0.107:55143 )
  INFO root [0x00002548] [2018-11-03 14:15:01,750] - NetworkInterface::initialize(INTERNAL): address 192.168.0.107:55143, SOMAXCONN=5.
  INFO root [0x00002548] [2018-11-03 14:15:01,750] - server-configs:
  INFO root [0x00002548] [2018-11-03 14:15:01,750] - 	gameUpdateHertz : 10
  INFO root [0x00002548] [2018-11-03 14:15:01,750] - 	defaultViewRadius : 80
  INFO root [0x00002548] [2018-11-03 14:15:01,750] - 	defaultViewHysteresisArea : 5
  INFO root [0x00002548] [2018-11-03 14:15:01,751] - 	entryScriptFile : kbemain
  INFO root [0x00002548] [2018-11-03 14:15:01,751] - 	internalAddr : 192.168.0.107:55143
  INFO root [0x00002548] [2018-11-03 14:15:01,751] - 	componentID : 8001
  INFO root [0x00002548] [2018-11-03 14:15:03,266] - ---- cellapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 85A70C5E64F896E0F1A60BF405B4EB07. Config: Debug X86. Built: 15:53:53 Apr 29 2018. AppID: 8001. UID: 26471. PID: 8556 ----
  INFO root [0x00002548] [2018-11-03 14:15:03,267] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [0x00002548] [2018-11-03 14:15:03,268] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00002548] [2018-11-03 14:15:03,269] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x00002548] [2018-11-03 14:15:03,406] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00002548] [2018-11-03 14:15:03,406] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x00002548] [2018-11-03 14:15:03,406] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x00002548] [2018-11-03 14:15:03,409] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x00002548] [2018-11-03 14:15:03,410] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x00002548] [2018-11-03 14:15:03,410] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x00002548] [2018-11-03 14:15:03,410] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x00002548] [2018-11-03 14:15:03,438] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x00002548] [2018-11-03 14:15:03,470] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x00002548] [2018-11-03 14:15:03,470] - Script::install(): KBExtra is successfully!
 DEBUG root [0x00002548] [2018-11-03 14:15:03,491] - loaded entity-script:Account(1).
 DEBUG root [0x00002548] [2018-11-03 14:15:03,499] - loaded entity-script:Room(4).
  INFO root [0x00002548] [2018-11-03 14:15:03,499] - TelnetServer server is running on port 50000
  INFO root [0x00002548] [2018-11-03 14:15:03,872] - ---- cellapp is running ----
 DEBUG root [0x00002548] [2018-11-03 14:15:03,873] - Components::process(): Request for the process of identity...
  WARN root [0x00002548] [2018-11-03 14:15:09,950] - EntityApp::checkTickPeriod: tick took 6077% (6.08 seconds)!
  INFO root [0x00002548] [2018-11-03 14:15:10,973] - Components::findComponents: find logger(1)...
  INFO root [0x00002548] [2018-11-03 14:15:11,036] - Components::findComponents: found logger, addr:192.168.0.107:55142
  INFO root [0x00002548] [2018-11-03 14:15:11,036] - Components::addComponent: reset orderLog, uid=26471!
  INFO root [0x00002548] [2018-11-03 14:15:11,037] - Components::addComponent[logger], uid=26471, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00002548] [2018-11-03 14:15:11,037] - Components::findComponents: find dbmgr(2)...
  INFO root [0x00002548] [2018-11-03 14:15:11,138] - Components::findComponents: found dbmgr, addr:192.168.0.107:55139
  INFO root [0x00002548] [2018-11-03 14:15:11,139] - Components::addComponent: reset orderLog, uid=26471!
  INFO root [0x00002548] [2018-11-03 14:15:11,139] - Components::addComponent[dbmgr], uid=26471, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00002548] [2018-11-03 14:15:11,139] - Components::findComponents: found dbmgr, addr:192.168.0.107:55139
  WARN root [0x00002548] [2018-11-03 14:15:12,140] - EntityApp::checkTickPeriod: tick took 1267% (1.27 seconds)!
  WARN root [0x00002548] [2018-11-03 14:15:12,142] - Forwarding logs to logger[192.168.0.107:55142/0/0/0]...
