  INFO root [0x00001f90] [2018-08-23 10:59:06,311] - 
  INFO root [0x00001f90] [2018-08-23 10:59:06,407] - -----------------------------------------------------------------------------------------


  INFO root [0x00001f90] [2018-08-23 10:59:07,260] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [0x00001f90] [2018-08-23 10:59:07,261] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [0x00001f90] [2018-08-23 10:59:07,262] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [0x00001f90] [2018-08-23 10:59:07,703] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:50033 )
  INFO root [0x00001f90] [2018-08-23 10:59:07,750] - NetworkInterface::initialize(INTERNAL): address 192.168.0.106:50033, SOMAXCONN=5.
  INFO root [0x00001f90] [2018-08-23 10:59:07,750] - server-configs:
  INFO root [0x00001f90] [2018-08-23 10:59:07,751] - 	gameUpdateHertz : 10
  INFO root [0x00001f90] [2018-08-23 10:59:07,792] - 	defaultViewRadius : 80
  INFO root [0x00001f90] [2018-08-23 10:59:07,792] - 	defaultViewHysteresisArea : 5
  INFO root [0x00001f90] [2018-08-23 10:59:07,793] - 	entryScriptFile : kbemain
  INFO root [0x00001f90] [2018-08-23 10:59:07,793] - 	internalAddr : 192.168.0.106:50033
  INFO root [0x00001f90] [2018-08-23 10:59:07,794] - 	componentID : 8001
  INFO root [0x00001f90] [2018-08-23 10:59:08,947] - ---- cellapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 85A70C5E64F896E0F1A60BF405B4EB07. Config: Debug X86. Built: 15:53:53 Apr 29 2018. AppID: 8001. UID: 22428. PID: 5852 ----
  INFO root [0x00001f90] [2018-08-23 10:59:08,949] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [0x00001f90] [2018-08-23 10:59:09,017] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00001f90] [2018-08-23 10:59:09,135] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x00001f90] [2018-08-23 10:59:14,093] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00001f90] [2018-08-23 10:59:14,308] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x00001f90] [2018-08-23 10:59:14,438] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x00001f90] [2018-08-23 10:59:16,416] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x00001f90] [2018-08-23 10:59:16,481] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x00001f90] [2018-08-23 10:59:16,720] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x00001f90] [2018-08-23 10:59:17,020] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x00001f90] [2018-08-23 10:59:17,896] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x00001f90] [2018-08-23 10:59:18,834] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x00001f90] [2018-08-23 10:59:18,834] - Script::install(): KBExtra is successfully!
 DEBUG root [0x00001f90] [2018-08-23 10:59:21,330] - loaded entity-script:Account(1).
 DEBUG root [0x00001f90] [2018-08-23 10:59:21,936] - loaded entity-script:Room(4).
  INFO root [0x00001f90] [2018-08-23 10:59:21,965] - TelnetServer server is running on port 50000
  INFO root [0x00001f90] [2018-08-23 10:59:22,566] - ---- cellapp is running ----
 DEBUG root [0x00001f90] [2018-08-23 10:59:22,656] - Components::process(): Request for the process of identity...
  WARN root [0x00001f90] [2018-08-23 10:59:22,966] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20749, errorno=10048
  WARN root [0x00001f90] [2018-08-23 10:59:29,291] - EntityApp::checkTickPeriod: tick took 6725% (6.72 seconds)!
  INFO root [0x00001f90] [2018-08-23 10:59:30,366] - Components::findComponents: find logger(1)...
  INFO root [0x00001f90] [2018-08-23 10:59:30,436] - Components::findComponents: found logger, addr:192.168.0.106:50029
  INFO root [0x00001f90] [2018-08-23 10:59:30,436] - Components::addComponent: reset orderLog, uid=22428!
  INFO root [0x00001f90] [2018-08-23 10:59:30,437] - Components::addComponent[logger], uid=22428, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00001f90] [2018-08-23 10:59:30,458] - Components::findComponents: find dbmgr(2)...
  INFO root [0x00001f90] [2018-08-23 10:59:30,541] - Components::findComponents: found dbmgr, addr:192.168.0.106:50031
  INFO root [0x00001f90] [2018-08-23 10:59:30,542] - Components::addComponent: reset orderLog, uid=22428!
  INFO root [0x00001f90] [2018-08-23 10:59:30,542] - Components::addComponent[dbmgr], uid=22428, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00001f90] [2018-08-23 10:59:30,543] - Components::findComponents: found dbmgr, addr:192.168.0.106:50031
  WARN root [0x00001f90] [2018-08-23 10:59:31,543] - EntityApp::checkTickPeriod: tick took 1277% (1.28 seconds)!
  WARN root [0x00001f90] [2018-08-23 10:59:31,545] - Forwarding logs to logger[192.168.0.106:50029/0/0/0]...
 ERROR root [0x00001f90] [2018-08-23 11:21:07,032] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x00001f90] [2018-08-23 11:21:07,037] - The following logs sent to logger failed:
  WARN root [0x00001f90] [2018-08-23 11:21:07,037] - ==> [2018-08-23 11:21:07 031] TCPPacketReceiver::processPendingEvents(192.168.0.106:50029): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00001f90] [2018-08-23 11:21:07,037] - ==> [2018-08-23 11:21:07 033] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x00001f90] [2018-08-23 11:21:07,084] - TCPPacketReceiver::processPendingEvents(192.168.0.106:50031): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00001f90] [2018-08-23 11:21:07,086] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x00001f90] [2018-08-23 11:21:07,118] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [0x00001f90] [2018-08-23 11:21:07,118] - Shutdowner::onShutdown: shutting down
  INFO root [0x00001f90] [2018-08-23 11:21:07,119] - Spaces::destroySpace: 1.
  INFO root [0x00001f90] [2018-08-23 11:21:07,119] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [0x00001f90] [2018-08-23 11:21:07,200] - Account::~Account(): 2002
 DEBUG root [0x00001f90] [2018-08-23 11:21:07,200] - Account::~Account(): 2004
 DEBUG root [0x00001f90] [2018-08-23 11:21:07,201] - EntityRef::destroyObjPool(): size 16.
 DEBUG root [0x00001f90] [2018-08-23 11:21:07,201] - Witness::destroyObjPool(): size 16.
 DEBUG root [0x00001f90] [2018-08-23 11:21:07,215] - Room::~Room(): 2003
 ERROR root [0x00001f90] [2018-08-23 11:21:07,233] - PyGC::debugTracing(): EntityCall : leaked(2)
 DEBUG root [0x00001f90] [2018-08-23 11:21:07,233] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00001f90] [2018-08-23 11:21:07,233] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x00001f90] [2018-08-23 11:21:07,233] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x00001f90] [2018-08-23 11:21:07,233] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x00001f90] [2018-08-23 11:21:07,234] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x00001f90] [2018-08-23 11:21:07,234] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x00001f90] [2018-08-23 11:21:07,234] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x00001f90] [2018-08-23 11:21:07,234] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x00001f90] [2018-08-23 11:21:07,274] - Script::uninstall(): is successfully!
 DEBUG root [0x00001f90] [2018-08-23 11:21:07,274] - ThreadPool::destroy(): starting size 2.
  INFO root [0x00002a74] [2018-08-23 11:21:08,253] - 
  INFO root [0x00002a74] [2018-08-23 11:21:08,254] - -----------------------------------------------------------------------------------------


  INFO root [0x00002a74] [2018-08-23 11:21:08,255] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [0x00002a74] [2018-08-23 11:21:08,255] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [0x00002a74] [2018-08-23 11:21:08,255] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [0x00002a74] [2018-08-23 11:21:08,264] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:50300 )
  INFO root [0x00002a74] [2018-08-23 11:21:08,264] - NetworkInterface::initialize(INTERNAL): address 192.168.0.106:50300, SOMAXCONN=5.
  INFO root [0x00002a74] [2018-08-23 11:21:08,264] - server-configs:
  INFO root [0x00002a74] [2018-08-23 11:21:08,265] - 	gameUpdateHertz : 10
  INFO root [0x00002a74] [2018-08-23 11:21:08,265] - 	defaultViewRadius : 80
  INFO root [0x00002a74] [2018-08-23 11:21:08,265] - 	defaultViewHysteresisArea : 5
  INFO root [0x00002a74] [2018-08-23 11:21:08,265] - 	entryScriptFile : kbemain
  INFO root [0x00002a74] [2018-08-23 11:21:08,265] - 	internalAddr : 192.168.0.106:50300
  INFO root [0x00002a74] [2018-08-23 11:21:08,265] - 	componentID : 8001
  WARN root [0x00002a74] [2018-08-23 11:21:08,576] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20463, errorno=10048
  INFO root [0x00002a74] [2018-08-23 11:21:08,581] - ---- cellapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 85A70C5E64F896E0F1A60BF405B4EB07. Config: Debug X86. Built: 15:53:53 Apr 29 2018. AppID: 8001. UID: 26811. PID: 11544 ----
  INFO root [0x00002a74] [2018-08-23 11:21:08,582] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [0x00002a74] [2018-08-23 11:21:08,582] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00002a74] [2018-08-23 11:21:08,582] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x00002a74] [2018-08-23 11:21:08,711] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00002a74] [2018-08-23 11:21:08,711] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x00002a74] [2018-08-23 11:21:08,711] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x00002a74] [2018-08-23 11:21:08,714] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x00002a74] [2018-08-23 11:21:08,715] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x00002a74] [2018-08-23 11:21:08,715] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x00002a74] [2018-08-23 11:21:08,715] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x00002a74] [2018-08-23 11:21:08,743] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x00002a74] [2018-08-23 11:21:08,771] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x00002a74] [2018-08-23 11:21:08,772] - Script::install(): KBExtra is successfully!
 DEBUG root [0x00002a74] [2018-08-23 11:21:08,791] - loaded entity-script:Account(1).
 DEBUG root [0x00002a74] [2018-08-23 11:21:08,819] - loaded entity-script:Room(4).
  INFO root [0x00002a74] [2018-08-23 11:21:08,819] - TelnetServer server is running on port 50000
  INFO root [0x00002a74] [2018-08-23 11:21:09,104] - ---- cellapp is running ----
 DEBUG root [0x00002a74] [2018-08-23 11:21:09,104] - Components::process(): Request for the process of identity...
  WARN root [0x00002a74] [2018-08-23 11:21:15,181] - EntityApp::checkTickPeriod: tick took 6076% (6.08 seconds)!
  INFO root [0x00002a74] [2018-08-23 11:21:16,206] - Components::findComponents: find logger(1)...
  INFO root [0x00002a74] [2018-08-23 11:21:16,226] - Components::findComponents: found logger, addr:192.168.0.106:50298
  INFO root [0x00002a74] [2018-08-23 11:21:16,226] - Components::addComponent: reset orderLog, uid=26811!
  INFO root [0x00002a74] [2018-08-23 11:21:16,227] - Components::addComponent[logger], uid=26811, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00002a74] [2018-08-23 11:21:16,230] - Components::findComponents: find dbmgr(2)...
  INFO root [0x00002a74] [2018-08-23 11:21:16,330] - Components::findComponents: found dbmgr, addr:192.168.0.106:50296
  INFO root [0x00002a74] [2018-08-23 11:21:16,331] - Components::addComponent: reset orderLog, uid=26811!
  INFO root [0x00002a74] [2018-08-23 11:21:16,331] - Components::addComponent[dbmgr], uid=26811, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00002a74] [2018-08-23 11:21:16,332] - Components::findComponents: found dbmgr, addr:192.168.0.106:50296
  WARN root [0x00002a74] [2018-08-23 11:21:17,332] - EntityApp::checkTickPeriod: tick took 1226% (1.23 seconds)!
  WARN root [0x00002a74] [2018-08-23 11:21:17,334] - Forwarding logs to logger[192.168.0.106:50298/0/0/0]...
 ERROR root [0x00002a74] [2018-08-23 11:35:16,757] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x00002a74] [2018-08-23 11:35:16,762] - The following logs sent to logger failed:
  WARN root [0x00002a74] [2018-08-23 11:35:16,762] - ==> [2018-08-23 11:35:16 755] TCPPacketReceiver::processPendingEvents(192.168.0.106:50298): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00002a74] [2018-08-23 11:35:16,762] - ==> [2018-08-23 11:35:16 758] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x00002a74] [2018-08-23 11:35:16,809] - TCPPacketReceiver::processPendingEvents(192.168.0.106:50296): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00002a74] [2018-08-23 11:35:16,812] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x00002a74] [2018-08-23 11:35:16,815] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [0x00002a74] [2018-08-23 11:35:16,817] - Shutdowner::onShutdown: shutting down
  INFO root [0x00002a74] [2018-08-23 11:35:16,818] - Spaces::destroySpace: 1.
  INFO root [0x00002a74] [2018-08-23 11:35:16,818] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [0x00002a74] [2018-08-23 11:35:16,819] - Account::~Account(): 2002
 DEBUG root [0x00002a74] [2018-08-23 11:35:16,819] - Account::~Account(): 2004
 DEBUG root [0x00002a74] [2018-08-23 11:35:16,819] - EntityRef::destroyObjPool(): size 16.
 DEBUG root [0x00002a74] [2018-08-23 11:35:16,819] - Witness::destroyObjPool(): size 16.
 DEBUG root [0x00002a74] [2018-08-23 11:35:16,827] - Room::~Room(): 2003
 ERROR root [0x00002a74] [2018-08-23 11:35:16,828] - PyGC::debugTracing(): EntityCall : leaked(2)
 DEBUG root [0x00002a74] [2018-08-23 11:35:16,829] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00002a74] [2018-08-23 11:35:16,829] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x00002a74] [2018-08-23 11:35:16,829] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x00002a74] [2018-08-23 11:35:16,829] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x00002a74] [2018-08-23 11:35:16,829] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x00002a74] [2018-08-23 11:35:16,829] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x00002a74] [2018-08-23 11:35:16,829] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x00002a74] [2018-08-23 11:35:16,830] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x00002a74] [2018-08-23 11:35:16,840] - Script::uninstall(): is successfully!
 DEBUG root [0x00002a74] [2018-08-23 11:35:16,840] - ThreadPool::destroy(): starting size 2.
  INFO root [0x00002ba0] [2018-08-23 11:35:17,954] - 
  INFO root [0x00002ba0] [2018-08-23 11:35:17,955] - -----------------------------------------------------------------------------------------


  INFO root [0x00002ba0] [2018-08-23 11:35:17,955] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [0x00002ba0] [2018-08-23 11:35:17,955] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [0x00002ba0] [2018-08-23 11:35:17,955] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [0x00002ba0] [2018-08-23 11:35:17,963] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:50473 )
  INFO root [0x00002ba0] [2018-08-23 11:35:17,964] - NetworkInterface::initialize(INTERNAL): address 192.168.0.106:50473, SOMAXCONN=5.
  INFO root [0x00002ba0] [2018-08-23 11:35:17,964] - server-configs:
  INFO root [0x00002ba0] [2018-08-23 11:35:17,964] - 	gameUpdateHertz : 10
  INFO root [0x00002ba0] [2018-08-23 11:35:17,964] - 	defaultViewRadius : 80
  INFO root [0x00002ba0] [2018-08-23 11:35:17,964] - 	defaultViewHysteresisArea : 5
  INFO root [0x00002ba0] [2018-08-23 11:35:17,964] - 	entryScriptFile : kbemain
  INFO root [0x00002ba0] [2018-08-23 11:35:17,964] - 	internalAddr : 192.168.0.106:50473
  INFO root [0x00002ba0] [2018-08-23 11:35:17,964] - 	componentID : 8001
  INFO root [0x00002ba0] [2018-08-23 11:35:19,471] - ---- cellapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 85A70C5E64F896E0F1A60BF405B4EB07. Config: Debug X86. Built: 15:53:53 Apr 29 2018. AppID: 8001. UID: 29586. PID: 11524 ----
  INFO root [0x00002ba0] [2018-08-23 11:35:19,472] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [0x00002ba0] [2018-08-23 11:35:19,472] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00002ba0] [2018-08-23 11:35:19,472] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x00002ba0] [2018-08-23 11:35:19,601] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00002ba0] [2018-08-23 11:35:19,602] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x00002ba0] [2018-08-23 11:35:19,602] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x00002ba0] [2018-08-23 11:35:19,605] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x00002ba0] [2018-08-23 11:35:19,605] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x00002ba0] [2018-08-23 11:35:19,605] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x00002ba0] [2018-08-23 11:35:19,606] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x00002ba0] [2018-08-23 11:35:19,639] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x00002ba0] [2018-08-23 11:35:19,672] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x00002ba0] [2018-08-23 11:35:19,672] - Script::install(): KBExtra is successfully!
 DEBUG root [0x00002ba0] [2018-08-23 11:35:19,692] - loaded entity-script:Account(1).
 DEBUG root [0x00002ba0] [2018-08-23 11:35:19,719] - loaded entity-script:Room(4).
  INFO root [0x00002ba0] [2018-08-23 11:35:19,719] - TelnetServer server is running on port 50000
  INFO root [0x00002ba0] [2018-08-23 11:35:20,091] - ---- cellapp is running ----
 DEBUG root [0x00002ba0] [2018-08-23 11:35:20,091] - Components::process(): Request for the process of identity...
  WARN root [0x00002ba0] [2018-08-23 11:35:26,154] - EntityApp::checkTickPeriod: tick took 6062% (6.06 seconds)!
  INFO root [0x00002ba0] [2018-08-23 11:35:27,192] - Components::findComponents: find logger(1)...
  INFO root [0x00002ba0] [2018-08-23 11:35:27,197] - Components::findComponents: found logger, addr:192.168.0.106:50475
  INFO root [0x00002ba0] [2018-08-23 11:35:27,198] - Components::addComponent: reset orderLog, uid=29586!
  INFO root [0x00002ba0] [2018-08-23 11:35:27,198] - Components::addComponent[logger], uid=29586, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00002ba0] [2018-08-23 11:35:27,200] - Components::findComponents: find dbmgr(2)...
  INFO root [0x00002ba0] [2018-08-23 11:35:27,302] - Components::findComponents: found dbmgr, addr:192.168.0.106:50469
  INFO root [0x00002ba0] [2018-08-23 11:35:27,303] - Components::addComponent: reset orderLog, uid=29586!
  INFO root [0x00002ba0] [2018-08-23 11:35:27,303] - Components::addComponent[dbmgr], uid=29586, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00002ba0] [2018-08-23 11:35:27,304] - Components::findComponents: found dbmgr, addr:192.168.0.106:50469
  WARN root [0x00002ba0] [2018-08-23 11:35:28,304] - EntityApp::checkTickPeriod: tick took 1212% (1.21 seconds)!
  WARN root [0x00002ba0] [2018-08-23 11:35:28,305] - Forwarding logs to logger[192.168.0.106:50475/0/0/0]...
 ERROR root [0x00002ba0] [2018-08-23 11:52:27,156] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x00002ba0] [2018-08-23 11:52:27,160] - The following logs sent to logger failed:
  WARN root [0x00002ba0] [2018-08-23 11:52:27,160] - ==> [2018-08-23 11:52:27 152] TCPPacketReceiver::processPendingEvents(192.168.0.106:50475): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00002ba0] [2018-08-23 11:52:27,161] - ==> [2018-08-23 11:52:27 156] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x00002ba0] [2018-08-23 11:52:27,208] - TCPPacketReceiver::processPendingEvents(192.168.0.106:50469): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00002ba0] [2018-08-23 11:52:27,209] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x00002ba0] [2018-08-23 11:52:27,214] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [0x00002ba0] [2018-08-23 11:52:27,216] - Shutdowner::onShutdown: shutting down
  INFO root [0x00002ba0] [2018-08-23 11:52:27,218] - Spaces::destroySpace: 1.
  INFO root [0x00002ba0] [2018-08-23 11:52:27,218] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [0x00002ba0] [2018-08-23 11:52:27,218] - Account::~Account(): 2002
 DEBUG root [0x00002ba0] [2018-08-23 11:52:27,218] - Account::~Account(): 2004
 DEBUG root [0x00002ba0] [2018-08-23 11:52:27,219] - EntityRef::destroyObjPool(): size 16.
 DEBUG root [0x00002ba0] [2018-08-23 11:52:27,219] - Witness::destroyObjPool(): size 16.
 DEBUG root [0x00002ba0] [2018-08-23 11:52:27,227] - Room::~Room(): 2003
 ERROR root [0x00002ba0] [2018-08-23 11:52:27,228] - PyGC::debugTracing(): EntityCall : leaked(2)
 DEBUG root [0x00002ba0] [2018-08-23 11:52:27,229] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00002ba0] [2018-08-23 11:52:27,229] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x00002ba0] [2018-08-23 11:52:27,229] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x00002ba0] [2018-08-23 11:52:27,229] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x00002ba0] [2018-08-23 11:52:27,229] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x00002ba0] [2018-08-23 11:52:27,229] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x00002ba0] [2018-08-23 11:52:27,229] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x00002ba0] [2018-08-23 11:52:27,230] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x00002ba0] [2018-08-23 11:52:27,240] - Script::uninstall(): is successfully!
 DEBUG root [0x00002ba0] [2018-08-23 11:52:27,240] - ThreadPool::destroy(): starting size 2.
  INFO root [0x0000296c] [2018-08-23 11:52:28,347] - 
  INFO root [0x0000296c] [2018-08-23 11:52:28,347] - -----------------------------------------------------------------------------------------


  INFO root [0x0000296c] [2018-08-23 11:52:28,348] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [0x0000296c] [2018-08-23 11:52:28,348] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [0x0000296c] [2018-08-23 11:52:28,348] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [0x0000296c] [2018-08-23 11:52:28,357] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:50697 )
  INFO root [0x0000296c] [2018-08-23 11:52:28,357] - NetworkInterface::initialize(INTERNAL): address 192.168.0.106:50697, SOMAXCONN=5.
  INFO root [0x0000296c] [2018-08-23 11:52:28,358] - server-configs:
  INFO root [0x0000296c] [2018-08-23 11:52:28,358] - 	gameUpdateHertz : 10
  INFO root [0x0000296c] [2018-08-23 11:52:28,358] - 	defaultViewRadius : 80
  INFO root [0x0000296c] [2018-08-23 11:52:28,358] - 	defaultViewHysteresisArea : 5
  INFO root [0x0000296c] [2018-08-23 11:52:28,358] - 	entryScriptFile : kbemain
  INFO root [0x0000296c] [2018-08-23 11:52:28,358] - 	internalAddr : 192.168.0.106:50697
  INFO root [0x0000296c] [2018-08-23 11:52:28,359] - 	componentID : 8001
  INFO root [0x0000296c] [2018-08-23 11:52:29,863] - ---- cellapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 85A70C5E64F896E0F1A60BF405B4EB07. Config: Debug X86. Built: 15:53:53 Apr 29 2018. AppID: 8001. UID: 185. PID: 7812 ----
  INFO root [0x0000296c] [2018-08-23 11:52:29,864] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [0x0000296c] [2018-08-23 11:52:29,864] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x0000296c] [2018-08-23 11:52:29,865] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x0000296c] [2018-08-23 11:52:29,992] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x0000296c] [2018-08-23 11:52:29,992] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x0000296c] [2018-08-23 11:52:29,992] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x0000296c] [2018-08-23 11:52:29,995] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x0000296c] [2018-08-23 11:52:29,996] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x0000296c] [2018-08-23 11:52:29,996] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x0000296c] [2018-08-23 11:52:29,996] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x0000296c] [2018-08-23 11:52:30,025] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x0000296c] [2018-08-23 11:52:30,057] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x0000296c] [2018-08-23 11:52:30,057] - Script::install(): KBExtra is successfully!
 DEBUG root [0x0000296c] [2018-08-23 11:52:30,080] - loaded entity-script:Account(1).
 DEBUG root [0x0000296c] [2018-08-23 11:52:30,108] - loaded entity-script:Room(4).
  INFO root [0x0000296c] [2018-08-23 11:52:30,108] - TelnetServer server is running on port 50000
  INFO root [0x0000296c] [2018-08-23 11:52:30,423] - ---- cellapp is running ----
 DEBUG root [0x0000296c] [2018-08-23 11:52:30,423] - Components::process(): Request for the process of identity...
  WARN root [0x0000296c] [2018-08-23 11:52:36,531] - EntityApp::checkTickPeriod: tick took 6107% (6.11 seconds)!
  INFO root [0x0000296c] [2018-08-23 11:52:37,624] - Components::findComponents: find logger(1)...
  INFO root [0x0000296c] [2018-08-23 11:52:37,711] - Components::findComponents: found logger, addr:192.168.0.106:50695
  INFO root [0x0000296c] [2018-08-23 11:52:37,712] - Components::addComponent: reset orderLog, uid=185!
  INFO root [0x0000296c] [2018-08-23 11:52:37,713] - Components::addComponent[logger], uid=185, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x0000296c] [2018-08-23 11:52:37,715] - Components::findComponents: find dbmgr(2)...
  INFO root [0x0000296c] [2018-08-23 11:52:37,818] - Components::findComponents: found dbmgr, addr:192.168.0.106:50694
  INFO root [0x0000296c] [2018-08-23 11:52:37,818] - Components::addComponent: reset orderLog, uid=185!
  INFO root [0x0000296c] [2018-08-23 11:52:37,818] - Components::addComponent[dbmgr], uid=185, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x0000296c] [2018-08-23 11:52:37,819] - Components::findComponents: found dbmgr, addr:192.168.0.106:50694
  WARN root [0x0000296c] [2018-08-23 11:52:38,819] - EntityApp::checkTickPeriod: tick took 1295% (1.29 seconds)!
  WARN root [0x0000296c] [2018-08-23 11:52:38,821] - Forwarding logs to logger[192.168.0.106:50695/0/0/0]...
 ERROR root [0x0000296c] [2018-08-23 11:58:23,498] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x0000296c] [2018-08-23 11:58:23,504] - The following logs sent to logger failed:
  WARN root [0x0000296c] [2018-08-23 11:58:23,504] - ==> [2018-08-23 11:58:23 496] TCPPacketReceiver::processPendingEvents(192.168.0.106:50695): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x0000296c] [2018-08-23 11:58:23,504] - ==> [2018-08-23 11:58:23 498] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x0000296c] [2018-08-23 11:58:23,550] - TCPPacketReceiver::processPendingEvents(192.168.0.106:50694): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x0000296c] [2018-08-23 11:58:23,553] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x0000296c] [2018-08-23 11:58:23,556] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [0x0000296c] [2018-08-23 11:58:23,557] - Shutdowner::onShutdown: shutting down
  INFO root [0x0000296c] [2018-08-23 11:58:23,558] - Spaces::destroySpace: 1.
  INFO root [0x0000296c] [2018-08-23 11:58:23,558] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [0x0000296c] [2018-08-23 11:58:23,558] - Account::~Account(): 2
 DEBUG root [0x0000296c] [2018-08-23 11:58:23,559] - Account::~Account(): 4
 DEBUG root [0x0000296c] [2018-08-23 11:58:23,559] - EntityRef::destroyObjPool(): size 16.
 DEBUG root [0x0000296c] [2018-08-23 11:58:23,559] - Witness::destroyObjPool(): size 16.
 DEBUG root [0x0000296c] [2018-08-23 11:58:23,567] - Room::~Room(): 3
 ERROR root [0x0000296c] [2018-08-23 11:58:23,568] - PyGC::debugTracing(): EntityCall : leaked(2)
 DEBUG root [0x0000296c] [2018-08-23 11:58:23,568] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x0000296c] [2018-08-23 11:58:23,568] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x0000296c] [2018-08-23 11:58:23,568] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x0000296c] [2018-08-23 11:58:23,569] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x0000296c] [2018-08-23 11:58:23,569] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x0000296c] [2018-08-23 11:58:23,569] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x0000296c] [2018-08-23 11:58:23,569] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x0000296c] [2018-08-23 11:58:23,569] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x0000296c] [2018-08-23 11:58:23,580] - Script::uninstall(): is successfully!
 DEBUG root [0x0000296c] [2018-08-23 11:58:23,580] - ThreadPool::destroy(): starting size 2.
  INFO root [0x00002e9c] [2018-08-23 11:58:24,692] - 
  INFO root [0x00002e9c] [2018-08-23 11:58:24,692] - -----------------------------------------------------------------------------------------


  INFO root [0x00002e9c] [2018-08-23 11:58:24,693] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [0x00002e9c] [2018-08-23 11:58:24,693] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [0x00002e9c] [2018-08-23 11:58:24,694] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [0x00002e9c] [2018-08-23 11:58:24,699] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:50829 )
  INFO root [0x00002e9c] [2018-08-23 11:58:24,699] - NetworkInterface::initialize(INTERNAL): address 192.168.0.106:50829, SOMAXCONN=5.
  INFO root [0x00002e9c] [2018-08-23 11:58:24,699] - server-configs:
  INFO root [0x00002e9c] [2018-08-23 11:58:24,700] - 	gameUpdateHertz : 10
  INFO root [0x00002e9c] [2018-08-23 11:58:24,700] - 	defaultViewRadius : 80
  INFO root [0x00002e9c] [2018-08-23 11:58:24,700] - 	defaultViewHysteresisArea : 5
  INFO root [0x00002e9c] [2018-08-23 11:58:24,700] - 	entryScriptFile : kbemain
  INFO root [0x00002e9c] [2018-08-23 11:58:24,700] - 	internalAddr : 192.168.0.106:50829
  INFO root [0x00002e9c] [2018-08-23 11:58:24,700] - 	componentID : 8001
  INFO root [0x00002e9c] [2018-08-23 11:58:26,213] - ---- cellapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 85A70C5E64F896E0F1A60BF405B4EB07. Config: Debug X86. Built: 15:53:53 Apr 29 2018. AppID: 8001. UID: 1348. PID: 7256 ----
  INFO root [0x00002e9c] [2018-08-23 11:58:26,214] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [0x00002e9c] [2018-08-23 11:58:26,214] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00002e9c] [2018-08-23 11:58:26,215] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x00002e9c] [2018-08-23 11:58:26,373] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00002e9c] [2018-08-23 11:58:26,373] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x00002e9c] [2018-08-23 11:58:26,374] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x00002e9c] [2018-08-23 11:58:26,378] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x00002e9c] [2018-08-23 11:58:26,378] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x00002e9c] [2018-08-23 11:58:26,378] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x00002e9c] [2018-08-23 11:58:26,379] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x00002e9c] [2018-08-23 11:58:26,407] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x00002e9c] [2018-08-23 11:58:26,435] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x00002e9c] [2018-08-23 11:58:26,435] - Script::install(): KBExtra is successfully!
 DEBUG root [0x00002e9c] [2018-08-23 11:58:26,461] - loaded entity-script:Account(1).
 DEBUG root [0x00002e9c] [2018-08-23 11:58:26,468] - loaded entity-script:Room(4).
  INFO root [0x00002e9c] [2018-08-23 11:58:26,469] - TelnetServer server is running on port 50000
  INFO root [0x00002e9c] [2018-08-23 11:58:26,787] - ---- cellapp is running ----
 DEBUG root [0x00002e9c] [2018-08-23 11:58:26,787] - Components::process(): Request for the process of identity...
  WARN root [0x00002e9c] [2018-08-23 11:58:32,877] - EntityApp::checkTickPeriod: tick took 6088% (6.09 seconds)!
  INFO root [0x00002e9c] [2018-08-23 11:58:33,898] - Components::findComponents: find logger(1)...
  INFO root [0x00002e9c] [2018-08-23 11:58:33,989] - Components::findComponents: found logger, addr:192.168.0.106:50826
  INFO root [0x00002e9c] [2018-08-23 11:58:33,990] - Components::addComponent: reset orderLog, uid=1348!
  INFO root [0x00002e9c] [2018-08-23 11:58:33,991] - Components::addComponent[logger], uid=1348, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00002e9c] [2018-08-23 11:58:33,993] - Components::findComponents: find dbmgr(2)...
  INFO root [0x00002e9c] [2018-08-23 11:58:34,101] - Components::findComponents: found dbmgr, addr:192.168.0.106:50831
  INFO root [0x00002e9c] [2018-08-23 11:58:34,102] - Components::addComponent: reset orderLog, uid=1348!
  INFO root [0x00002e9c] [2018-08-23 11:58:34,103] - Components::addComponent[dbmgr], uid=1348, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00002e9c] [2018-08-23 11:58:34,103] - Components::findComponents: found dbmgr, addr:192.168.0.106:50831
  WARN root [0x00002e9c] [2018-08-23 11:58:35,104] - Forwarding logs to logger[192.168.0.106:50826/0/0/0]...
 ERROR root [0x00002e9c] [2018-08-23 12:04:45,714] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x00002e9c] [2018-08-23 12:04:45,720] - The following logs sent to logger failed:
  WARN root [0x00002e9c] [2018-08-23 12:04:45,720] - ==> [2018-08-23 12:04:45 711] TCPPacketReceiver::processPendingEvents(192.168.0.106:50826): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00002e9c] [2018-08-23 12:04:45,720] - ==> [2018-08-23 12:04:45 715] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x00002e9c] [2018-08-23 12:04:45,769] - TCPPacketReceiver::processPendingEvents(192.168.0.106:50831): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00002e9c] [2018-08-23 12:04:45,774] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x00002e9c] [2018-08-23 12:04:45,778] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [0x00002e9c] [2018-08-23 12:04:45,780] - Shutdowner::onShutdown: shutting down
  INFO root [0x00002e9c] [2018-08-23 12:04:45,781] - Spaces::destroySpace: 1.
  INFO root [0x00002e9c] [2018-08-23 12:04:45,781] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [0x00002e9c] [2018-08-23 12:04:45,781] - Account::~Account(): 2002
 DEBUG root [0x00002e9c] [2018-08-23 12:04:45,782] - Account::~Account(): 2004
 DEBUG root [0x00002e9c] [2018-08-23 12:04:45,782] - EntityRef::destroyObjPool(): size 16.
 DEBUG root [0x00002e9c] [2018-08-23 12:04:45,782] - Witness::destroyObjPool(): size 16.
 DEBUG root [0x00002e9c] [2018-08-23 12:04:45,790] - Room::~Room(): 2003
 ERROR root [0x00002e9c] [2018-08-23 12:04:45,791] - PyGC::debugTracing(): EntityCall : leaked(2)
 DEBUG root [0x00002e9c] [2018-08-23 12:04:45,792] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00002e9c] [2018-08-23 12:04:45,792] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x00002e9c] [2018-08-23 12:04:45,792] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x00002e9c] [2018-08-23 12:04:45,793] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x00002e9c] [2018-08-23 12:04:45,793] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x00002e9c] [2018-08-23 12:04:45,793] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x00002e9c] [2018-08-23 12:04:45,793] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x00002e9c] [2018-08-23 12:04:45,793] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x00002e9c] [2018-08-23 12:04:45,803] - Script::uninstall(): is successfully!
 DEBUG root [0x00002e9c] [2018-08-23 12:04:45,803] - ThreadPool::destroy(): starting size 2.
  INFO root [0x00003270] [2018-08-23 12:04:46,899] - 
  INFO root [0x00003270] [2018-08-23 12:04:46,900] - -----------------------------------------------------------------------------------------


  INFO root [0x00003270] [2018-08-23 12:04:46,900] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [0x00003270] [2018-08-23 12:04:46,900] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [0x00003270] [2018-08-23 12:04:46,900] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [0x00003270] [2018-08-23 12:04:46,908] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:50935 )
  INFO root [0x00003270] [2018-08-23 12:04:46,908] - NetworkInterface::initialize(INTERNAL): address 192.168.0.106:50935, SOMAXCONN=5.
  INFO root [0x00003270] [2018-08-23 12:04:46,908] - server-configs:
  INFO root [0x00003270] [2018-08-23 12:04:46,908] - 	gameUpdateHertz : 10
  INFO root [0x00003270] [2018-08-23 12:04:46,909] - 	defaultViewRadius : 80
  INFO root [0x00003270] [2018-08-23 12:04:46,909] - 	defaultViewHysteresisArea : 5
  INFO root [0x00003270] [2018-08-23 12:04:46,909] - 	entryScriptFile : kbemain
  INFO root [0x00003270] [2018-08-23 12:04:46,909] - 	internalAddr : 192.168.0.106:50935
  INFO root [0x00003270] [2018-08-23 12:04:46,909] - 	componentID : 8001
  INFO root [0x00003270] [2018-08-23 12:04:48,418] - ---- cellapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 85A70C5E64F896E0F1A60BF405B4EB07. Config: Debug X86. Built: 15:53:53 Apr 29 2018. AppID: 8001. UID: 2595. PID: 6852 ----
  INFO root [0x00003270] [2018-08-23 12:04:48,419] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [0x00003270] [2018-08-23 12:04:48,419] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00003270] [2018-08-23 12:04:48,420] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x00003270] [2018-08-23 12:04:48,570] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00003270] [2018-08-23 12:04:48,571] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x00003270] [2018-08-23 12:04:48,571] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x00003270] [2018-08-23 12:04:48,575] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x00003270] [2018-08-23 12:04:48,576] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x00003270] [2018-08-23 12:04:48,576] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x00003270] [2018-08-23 12:04:48,576] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x00003270] [2018-08-23 12:04:48,604] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x00003270] [2018-08-23 12:04:48,632] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x00003270] [2018-08-23 12:04:48,632] - Script::install(): KBExtra is successfully!
 DEBUG root [0x00003270] [2018-08-23 12:04:48,658] - loaded entity-script:Account(1).
 DEBUG root [0x00003270] [2018-08-23 12:04:48,665] - loaded entity-script:Room(4).
  INFO root [0x00003270] [2018-08-23 12:04:48,666] - TelnetServer server is running on port 50000
  INFO root [0x00003270] [2018-08-23 12:04:49,018] - ---- cellapp is running ----
 DEBUG root [0x00003270] [2018-08-23 12:04:49,019] - Components::process(): Request for the process of identity...
  WARN root [0x00003270] [2018-08-23 12:04:55,108] - EntityApp::checkTickPeriod: tick took 6088% (6.09 seconds)!
  INFO root [0x00003270] [2018-08-23 12:04:56,205] - Components::findComponents: find logger(1)...
  INFO root [0x00003270] [2018-08-23 12:04:56,262] - Components::findComponents: found logger, addr:192.168.0.106:50936
  INFO root [0x00003270] [2018-08-23 12:04:56,263] - Components::addComponent: reset orderLog, uid=2595!
  INFO root [0x00003270] [2018-08-23 12:04:56,264] - Components::addComponent[logger], uid=2595, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00003270] [2018-08-23 12:04:56,266] - Components::findComponents: find dbmgr(2)...
  INFO root [0x00003270] [2018-08-23 12:04:56,371] - Components::findComponents: found dbmgr, addr:192.168.0.106:50931
  INFO root [0x00003270] [2018-08-23 12:04:56,372] - Components::addComponent: reset orderLog, uid=2595!
  INFO root [0x00003270] [2018-08-23 12:04:56,372] - Components::addComponent[dbmgr], uid=2595, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00003270] [2018-08-23 12:04:56,373] - Components::findComponents: found dbmgr, addr:192.168.0.106:50931
  WARN root [0x00003270] [2018-08-23 12:04:57,373] - Forwarding logs to logger[192.168.0.106:50936/0/0/0]...
 ERROR root [0x00003270] [2018-08-23 15:18:30,560] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x00003270] [2018-08-23 15:18:30,577] - The following logs sent to logger failed:
  WARN root [0x00003270] [2018-08-23 15:18:30,577] - ==> [2018-08-23 15:18:30 557] TCPPacketReceiver::processPendingEvents(192.168.0.106:50936): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00003270] [2018-08-23 15:18:30,577] - ==> [2018-08-23 15:18:30 560] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x00003270] [2018-08-23 15:18:30,629] - TCPPacketReceiver::processPendingEvents(192.168.0.106:50931): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00003270] [2018-08-23 15:18:30,632] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x00003270] [2018-08-23 15:18:30,647] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [0x00003270] [2018-08-23 15:18:30,650] - Shutdowner::onShutdown: shutting down
  INFO root [0x00003270] [2018-08-23 15:18:30,651] - Spaces::destroySpace: 1.
  INFO root [0x00003270] [2018-08-23 15:18:30,651] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [0x00003270] [2018-08-23 15:18:30,651] - Account::~Account(): 2002
 DEBUG root [0x00003270] [2018-08-23 15:18:30,651] - Account::~Account(): 2004
 DEBUG root [0x00003270] [2018-08-23 15:18:30,652] - EntityRef::destroyObjPool(): size 16.
 DEBUG root [0x00003270] [2018-08-23 15:18:30,652] - Witness::destroyObjPool(): size 16.
 DEBUG root [0x00003270] [2018-08-23 15:18:30,660] - Room::~Room(): 2003
 ERROR root [0x00003270] [2018-08-23 15:18:30,661] - PyGC::debugTracing(): EntityCall : leaked(2)
 DEBUG root [0x00003270] [2018-08-23 15:18:30,661] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00003270] [2018-08-23 15:18:30,661] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x00003270] [2018-08-23 15:18:30,661] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x00003270] [2018-08-23 15:18:30,661] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x00003270] [2018-08-23 15:18:30,661] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x00003270] [2018-08-23 15:18:30,662] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x00003270] [2018-08-23 15:18:30,662] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x00003270] [2018-08-23 15:18:30,662] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x00003270] [2018-08-23 15:18:30,672] - Script::uninstall(): is successfully!
 DEBUG root [0x00003270] [2018-08-23 15:18:30,672] - ThreadPool::destroy(): starting size 2.
  INFO root [0x00001dcc] [2018-08-23 15:18:31,965] - 
  INFO root [0x00001dcc] [2018-08-23 15:18:31,966] - -----------------------------------------------------------------------------------------


  INFO root [0x00001dcc] [2018-08-23 15:18:31,967] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [0x00001dcc] [2018-08-23 15:18:31,967] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [0x00001dcc] [2018-08-23 15:18:31,967] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [0x00001dcc] [2018-08-23 15:18:31,970] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:55509 )
  INFO root [0x00001dcc] [2018-08-23 15:18:31,971] - NetworkInterface::initialize(INTERNAL): address 192.168.0.106:55509, SOMAXCONN=5.
  INFO root [0x00001dcc] [2018-08-23 15:18:31,971] - server-configs:
  INFO root [0x00001dcc] [2018-08-23 15:18:31,971] - 	gameUpdateHertz : 10
  INFO root [0x00001dcc] [2018-08-23 15:18:31,971] - 	defaultViewRadius : 80
  INFO root [0x00001dcc] [2018-08-23 15:18:31,971] - 	defaultViewHysteresisArea : 5
  INFO root [0x00001dcc] [2018-08-23 15:18:31,971] - 	entryScriptFile : kbemain
  INFO root [0x00001dcc] [2018-08-23 15:18:31,972] - 	internalAddr : 192.168.0.106:55509
  INFO root [0x00001dcc] [2018-08-23 15:18:31,972] - 	componentID : 8001
  INFO root [0x00001dcc] [2018-08-23 15:18:33,490] - ---- cellapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 85A70C5E64F896E0F1A60BF405B4EB07. Config: Debug X86. Built: 15:53:53 Apr 29 2018. AppID: 8001. UID: 7790. PID: 11400 ----
  INFO root [0x00001dcc] [2018-08-23 15:18:33,491] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [0x00001dcc] [2018-08-23 15:18:33,491] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00001dcc] [2018-08-23 15:18:33,491] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x00001dcc] [2018-08-23 15:18:33,619] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00001dcc] [2018-08-23 15:18:33,619] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x00001dcc] [2018-08-23 15:18:33,620] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x00001dcc] [2018-08-23 15:18:33,623] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x00001dcc] [2018-08-23 15:18:33,623] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x00001dcc] [2018-08-23 15:18:33,623] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x00001dcc] [2018-08-23 15:18:33,623] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x00001dcc] [2018-08-23 15:18:33,652] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x00001dcc] [2018-08-23 15:18:33,680] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x00001dcc] [2018-08-23 15:18:33,681] - Script::install(): KBExtra is successfully!
 DEBUG root [0x00001dcc] [2018-08-23 15:18:33,703] - loaded entity-script:Account(1).
 DEBUG root [0x00001dcc] [2018-08-23 15:18:33,712] - loaded entity-script:Room(4).
  INFO root [0x00001dcc] [2018-08-23 15:18:33,712] - TelnetServer server is running on port 50000
  INFO root [0x00001dcc] [2018-08-23 15:18:34,121] - ---- cellapp is running ----
 DEBUG root [0x00001dcc] [2018-08-23 15:18:34,121] - Components::process(): Request for the process of identity...
  WARN root [0x00001dcc] [2018-08-23 15:18:40,188] - EntityApp::checkTickPeriod: tick took 6065% (6.07 seconds)!
  INFO root [0x00001dcc] [2018-08-23 15:18:41,222] - Components::findComponents: find logger(1)...
  INFO root [0x00001dcc] [2018-08-23 15:18:41,260] - Components::findComponents: found logger, addr:192.168.0.106:55503
  INFO root [0x00001dcc] [2018-08-23 15:18:41,260] - Components::addComponent: reset orderLog, uid=7790!
  INFO root [0x00001dcc] [2018-08-23 15:18:41,260] - Components::addComponent[logger], uid=7790, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00001dcc] [2018-08-23 15:18:41,263] - Components::findComponents: find dbmgr(2)...
  INFO root [0x00001dcc] [2018-08-23 15:18:41,348] - Components::findComponents: found dbmgr, addr:192.168.0.106:55505
  INFO root [0x00001dcc] [2018-08-23 15:18:41,349] - Components::addComponent: reset orderLog, uid=7790!
  INFO root [0x00001dcc] [2018-08-23 15:18:41,349] - Components::addComponent[dbmgr], uid=7790, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00001dcc] [2018-08-23 15:18:41,349] - Components::findComponents: found dbmgr, addr:192.168.0.106:55505
  WARN root [0x00001dcc] [2018-08-23 15:18:42,349] - EntityApp::checkTickPeriod: tick took 1227% (1.23 seconds)!
  WARN root [0x00001dcc] [2018-08-23 15:18:42,351] - Forwarding logs to logger[192.168.0.106:55503/0/0/0]...
 ERROR root [0x00001dcc] [2018-08-23 16:12:55,986] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x00001dcc] [2018-08-23 16:12:55,993] - The following logs sent to logger failed:
  WARN root [0x00001dcc] [2018-08-23 16:12:55,993] - ==> [2018-08-23 16:12:55 976] TCPPacketReceiver::processPendingEvents(192.168.0.106:55503): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00001dcc] [2018-08-23 16:12:55,993] - ==> [2018-08-23 16:12:55 987] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x00001dcc] [2018-08-23 16:12:56,042] - TCPPacketReceiver::processPendingEvents(192.168.0.106:55505): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00001dcc] [2018-08-23 16:12:56,046] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x00001dcc] [2018-08-23 16:12:56,062] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [0x00001dcc] [2018-08-23 16:12:56,073] - Shutdowner::onShutdown: shutting down
  INFO root [0x00001dcc] [2018-08-23 16:12:56,074] - Spaces::destroySpace: 1.
  INFO root [0x00001dcc] [2018-08-23 16:12:56,074] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [0x00001dcc] [2018-08-23 16:12:56,075] - Account::~Account(): 2002
 DEBUG root [0x00001dcc] [2018-08-23 16:12:56,075] - EntityRef::destroyObjPool(): size 16.
 DEBUG root [0x00001dcc] [2018-08-23 16:12:56,075] - Witness::destroyObjPool(): size 16.
 DEBUG root [0x00001dcc] [2018-08-23 16:12:56,085] - Room::~Room(): 2003
 DEBUG root [0x00001dcc] [2018-08-23 16:12:56,086] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00001dcc] [2018-08-23 16:12:56,086] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x00001dcc] [2018-08-23 16:12:56,086] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x00001dcc] [2018-08-23 16:12:56,086] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x00001dcc] [2018-08-23 16:12:56,086] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x00001dcc] [2018-08-23 16:12:56,086] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x00001dcc] [2018-08-23 16:12:56,087] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x00001dcc] [2018-08-23 16:12:56,087] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x00001dcc] [2018-08-23 16:12:56,098] - Script::uninstall(): is successfully!
 DEBUG root [0x00001dcc] [2018-08-23 16:12:56,098] - ThreadPool::destroy(): starting size 2.
  INFO root [0x00003514] [2018-08-23 16:12:57,367] - 
  INFO root [0x00003514] [2018-08-23 16:12:57,370] - -----------------------------------------------------------------------------------------


  INFO root [0x00003514] [2018-08-23 16:12:57,370] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [0x00003514] [2018-08-23 16:12:57,370] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [0x00003514] [2018-08-23 16:12:57,370] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [0x00003514] [2018-08-23 16:12:57,377] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:56183 )
  INFO root [0x00003514] [2018-08-23 16:12:57,377] - NetworkInterface::initialize(INTERNAL): address 192.168.0.106:56183, SOMAXCONN=5.
  INFO root [0x00003514] [2018-08-23 16:12:57,377] - server-configs:
  INFO root [0x00003514] [2018-08-23 16:12:57,377] - 	gameUpdateHertz : 10
  INFO root [0x00003514] [2018-08-23 16:12:57,378] - 	defaultViewRadius : 80
  INFO root [0x00003514] [2018-08-23 16:12:57,378] - 	defaultViewHysteresisArea : 5
  INFO root [0x00003514] [2018-08-23 16:12:57,378] - 	entryScriptFile : kbemain
  INFO root [0x00003514] [2018-08-23 16:12:57,378] - 	internalAddr : 192.168.0.106:56183
  INFO root [0x00003514] [2018-08-23 16:12:57,378] - 	componentID : 8001
  WARN root [0x00003514] [2018-08-23 16:12:57,690] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20705, errorno=10048
  INFO root [0x00003514] [2018-08-23 16:12:57,693] - ---- cellapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 85A70C5E64F896E0F1A60BF405B4EB07. Config: Debug X86. Built: 15:53:53 Apr 29 2018. AppID: 8001. UID: 18452. PID: 15368 ----
  INFO root [0x00003514] [2018-08-23 16:12:57,693] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [0x00003514] [2018-08-23 16:12:57,694] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00003514] [2018-08-23 16:12:57,694] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x00003514] [2018-08-23 16:12:57,823] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00003514] [2018-08-23 16:12:57,823] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x00003514] [2018-08-23 16:12:57,823] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x00003514] [2018-08-23 16:12:57,828] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x00003514] [2018-08-23 16:12:57,828] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x00003514] [2018-08-23 16:12:57,828] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x00003514] [2018-08-23 16:12:57,829] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x00003514] [2018-08-23 16:12:57,863] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x00003514] [2018-08-23 16:12:57,898] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x00003514] [2018-08-23 16:12:57,898] - Script::install(): KBExtra is successfully!
 DEBUG root [0x00003514] [2018-08-23 16:12:57,917] - loaded entity-script:Account(1).
 DEBUG root [0x00003514] [2018-08-23 16:12:57,943] - loaded entity-script:Room(4).
  INFO root [0x00003514] [2018-08-23 16:12:57,943] - TelnetServer server is running on port 50000
  INFO root [0x00003514] [2018-08-23 16:12:58,278] - ---- cellapp is running ----
 DEBUG root [0x00003514] [2018-08-23 16:12:58,278] - Components::process(): Request for the process of identity...
  WARN root [0x00003514] [2018-08-23 16:13:04,348] - EntityApp::checkTickPeriod: tick took 6070% (6.07 seconds)!
  INFO root [0x00003514] [2018-08-23 16:13:05,376] - Components::findComponents: find logger(1)...
  INFO root [0x00003514] [2018-08-23 16:13:05,451] - Components::findComponents: found logger, addr:192.168.0.106:56181
  INFO root [0x00003514] [2018-08-23 16:13:05,451] - Components::addComponent: reset orderLog, uid=18452!
  INFO root [0x00003514] [2018-08-23 16:13:05,452] - Components::addComponent[logger], uid=18452, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00003514] [2018-08-23 16:13:05,454] - Components::findComponents: find dbmgr(2)...
  INFO root [0x00003514] [2018-08-23 16:13:05,555] - Components::findComponents: found dbmgr, addr:192.168.0.106:56182
  INFO root [0x00003514] [2018-08-23 16:13:05,556] - Components::addComponent: reset orderLog, uid=18452!
  INFO root [0x00003514] [2018-08-23 16:13:05,556] - Components::addComponent[dbmgr], uid=18452, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00003514] [2018-08-23 16:13:05,556] - Components::findComponents: found dbmgr, addr:192.168.0.106:56182
  WARN root [0x00003514] [2018-08-23 16:13:06,557] - Forwarding logs to logger[192.168.0.106:56181/0/0/0]...
 ERROR root [0x00003514] [2018-08-23 16:14:07,282] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x00003514] [2018-08-23 16:14:07,301] - The following logs sent to logger failed:
  WARN root [0x00003514] [2018-08-23 16:14:07,301] - ==> [2018-08-23 16:14:07 278] TCPPacketReceiver::processPendingEvents(192.168.0.106:56181): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00003514] [2018-08-23 16:14:07,301] - ==> [2018-08-23 16:14:07 282] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x00003514] [2018-08-23 16:14:07,352] - TCPPacketReceiver::processPendingEvents(192.168.0.106:56182): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00003514] [2018-08-23 16:14:07,356] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x00003514] [2018-08-23 16:14:07,373] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [0x00003514] [2018-08-23 16:14:07,375] - Shutdowner::onShutdown: shutting down
  INFO root [0x00003514] [2018-08-23 16:14:07,377] - Spaces::destroySpace: 1.
  INFO root [0x00003514] [2018-08-23 16:14:07,377] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [0x00003514] [2018-08-23 16:14:07,377] - Account::~Account(): 2002
 DEBUG root [0x00003514] [2018-08-23 16:14:07,377] - EntityRef::destroyObjPool(): size 16.
 DEBUG root [0x00003514] [2018-08-23 16:14:07,378] - Witness::destroyObjPool(): size 16.
 DEBUG root [0x00003514] [2018-08-23 16:14:07,386] - Room::~Room(): 2003
 DEBUG root [0x00003514] [2018-08-23 16:14:07,387] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00003514] [2018-08-23 16:14:07,387] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x00003514] [2018-08-23 16:14:07,387] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x00003514] [2018-08-23 16:14:07,387] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x00003514] [2018-08-23 16:14:07,387] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x00003514] [2018-08-23 16:14:07,387] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x00003514] [2018-08-23 16:14:07,387] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x00003514] [2018-08-23 16:14:07,387] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x00003514] [2018-08-23 16:14:07,397] - Script::uninstall(): is successfully!
 DEBUG root [0x00003514] [2018-08-23 16:14:07,398] - ThreadPool::destroy(): starting size 2.
  INFO root [0x00002a44] [2018-08-23 16:14:08,660] - 
  INFO root [0x00002a44] [2018-08-23 16:14:08,661] - -----------------------------------------------------------------------------------------


  INFO root [0x00002a44] [2018-08-23 16:14:08,662] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [0x00002a44] [2018-08-23 16:14:08,662] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [0x00002a44] [2018-08-23 16:14:08,662] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [0x00002a44] [2018-08-23 16:14:08,666] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:56225 )
  INFO root [0x00002a44] [2018-08-23 16:14:08,667] - NetworkInterface::initialize(INTERNAL): address 192.168.0.106:56225, SOMAXCONN=5.
  INFO root [0x00002a44] [2018-08-23 16:14:08,667] - server-configs:
  INFO root [0x00002a44] [2018-08-23 16:14:08,667] - 	gameUpdateHertz : 10
  INFO root [0x00002a44] [2018-08-23 16:14:08,667] - 	defaultViewRadius : 80
  INFO root [0x00002a44] [2018-08-23 16:14:08,667] - 	defaultViewHysteresisArea : 5
  INFO root [0x00002a44] [2018-08-23 16:14:08,668] - 	entryScriptFile : kbemain
  INFO root [0x00002a44] [2018-08-23 16:14:08,668] - 	internalAddr : 192.168.0.106:56225
  INFO root [0x00002a44] [2018-08-23 16:14:08,668] - 	componentID : 8001
  WARN root [0x00002a44] [2018-08-23 16:14:08,978] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20142, errorno=10048
  INFO root [0x00002a44] [2018-08-23 16:14:08,984] - ---- cellapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 85A70C5E64F896E0F1A60BF405B4EB07. Config: Debug X86. Built: 15:53:53 Apr 29 2018. AppID: 8001. UID: 18687. PID: 17224 ----
  INFO root [0x00002a44] [2018-08-23 16:14:08,985] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [0x00002a44] [2018-08-23 16:14:08,985] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00002a44] [2018-08-23 16:14:08,986] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x00002a44] [2018-08-23 16:14:09,113] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00002a44] [2018-08-23 16:14:09,113] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x00002a44] [2018-08-23 16:14:09,114] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x00002a44] [2018-08-23 16:14:09,117] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x00002a44] [2018-08-23 16:14:09,118] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x00002a44] [2018-08-23 16:14:09,118] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x00002a44] [2018-08-23 16:14:09,119] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x00002a44] [2018-08-23 16:14:09,148] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x00002a44] [2018-08-23 16:14:09,177] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x00002a44] [2018-08-23 16:14:09,178] - Script::install(): KBExtra is successfully!
 DEBUG root [0x00002a44] [2018-08-23 16:14:09,198] - loaded entity-script:Account(1).
 DEBUG root [0x00002a44] [2018-08-23 16:14:09,205] - loaded entity-script:Room(4).
  INFO root [0x00002a44] [2018-08-23 16:14:09,206] - TelnetServer server is running on port 50000
  INFO root [0x00002a44] [2018-08-23 16:14:09,495] - ---- cellapp is running ----
 DEBUG root [0x00002a44] [2018-08-23 16:14:09,496] - Components::process(): Request for the process of identity...
  WARN root [0x00002a44] [2018-08-23 16:14:15,575] - EntityApp::checkTickPeriod: tick took 6079% (6.08 seconds)!
  INFO root [0x00002a44] [2018-08-23 16:14:16,596] - Components::findComponents: find logger(1)...
  INFO root [0x00002a44] [2018-08-23 16:14:16,606] - Components::findComponents: found logger, addr:192.168.0.106:56221
  INFO root [0x00002a44] [2018-08-23 16:14:16,607] - Components::addComponent: reset orderLog, uid=18687!
  INFO root [0x00002a44] [2018-08-23 16:14:16,608] - Components::addComponent[logger], uid=18687, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00002a44] [2018-08-23 16:14:16,609] - Components::findComponents: find dbmgr(2)...
  INFO root [0x00002a44] [2018-08-23 16:14:16,709] - Components::findComponents: found dbmgr, addr:192.168.0.106:56219
  INFO root [0x00002a44] [2018-08-23 16:14:16,709] - Components::addComponent: reset orderLog, uid=18687!
  INFO root [0x00002a44] [2018-08-23 16:14:16,710] - Components::addComponent[dbmgr], uid=18687, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00002a44] [2018-08-23 16:14:16,710] - Components::findComponents: found dbmgr, addr:192.168.0.106:56219
  WARN root [0x00002a44] [2018-08-23 16:14:17,711] - EntityApp::checkTickPeriod: tick took 1214% (1.21 seconds)!
  WARN root [0x00002a44] [2018-08-23 16:14:17,711] - Forwarding logs to logger[192.168.0.106:56221/0/0/0]...
 ERROR root [0x00002a44] [2018-08-23 16:18:16,577] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x00002a44] [2018-08-23 16:18:16,595] - The following logs sent to logger failed:
  WARN root [0x00002a44] [2018-08-23 16:18:16,595] - ==> [2018-08-23 16:18:16 573] TCPPacketReceiver::processPendingEvents(192.168.0.106:56221): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00002a44] [2018-08-23 16:18:16,596] - ==> [2018-08-23 16:18:16 577] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x00002a44] [2018-08-23 16:18:16,648] - TCPPacketReceiver::processPendingEvents(192.168.0.106:56219): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00002a44] [2018-08-23 16:18:16,660] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x00002a44] [2018-08-23 16:18:16,666] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [0x00002a44] [2018-08-23 16:18:16,668] - Shutdowner::onShutdown: shutting down
  INFO root [0x00002a44] [2018-08-23 16:18:16,670] - Spaces::destroySpace: 1.
  INFO root [0x00002a44] [2018-08-23 16:18:16,671] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [0x00002a44] [2018-08-23 16:18:16,671] - Account::~Account(): 2002
 DEBUG root [0x00002a44] [2018-08-23 16:18:16,671] - Account::~Account(): 2004
 DEBUG root [0x00002a44] [2018-08-23 16:18:16,671] - EntityRef::destroyObjPool(): size 16.
 DEBUG root [0x00002a44] [2018-08-23 16:18:16,671] - Witness::destroyObjPool(): size 16.
 DEBUG root [0x00002a44] [2018-08-23 16:18:16,680] - Room::~Room(): 2003
 DEBUG root [0x00002a44] [2018-08-23 16:18:16,681] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00002a44] [2018-08-23 16:18:16,681] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x00002a44] [2018-08-23 16:18:16,681] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x00002a44] [2018-08-23 16:18:16,681] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x00002a44] [2018-08-23 16:18:16,681] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x00002a44] [2018-08-23 16:18:16,681] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x00002a44] [2018-08-23 16:18:16,681] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x00002a44] [2018-08-23 16:18:16,681] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x00002a44] [2018-08-23 16:18:16,691] - Script::uninstall(): is successfully!
 DEBUG root [0x00002a44] [2018-08-23 16:18:16,691] - ThreadPool::destroy(): starting size 2.
  INFO root [0x0000323c] [2018-08-23 16:18:17,920] - 
  INFO root [0x0000323c] [2018-08-23 16:18:17,926] - -----------------------------------------------------------------------------------------


  INFO root [0x0000323c] [2018-08-23 16:18:17,927] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [0x0000323c] [2018-08-23 16:18:17,927] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [0x0000323c] [2018-08-23 16:18:17,927] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [0x0000323c] [2018-08-23 16:18:17,936] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:56299 )
  INFO root [0x0000323c] [2018-08-23 16:18:17,936] - NetworkInterface::initialize(INTERNAL): address 192.168.0.106:56299, SOMAXCONN=5.
  INFO root [0x0000323c] [2018-08-23 16:18:17,936] - server-configs:
  INFO root [0x0000323c] [2018-08-23 16:18:17,937] - 	gameUpdateHertz : 10
  INFO root [0x0000323c] [2018-08-23 16:18:17,937] - 	defaultViewRadius : 80
  INFO root [0x0000323c] [2018-08-23 16:18:17,937] - 	defaultViewHysteresisArea : 5
  INFO root [0x0000323c] [2018-08-23 16:18:17,937] - 	entryScriptFile : kbemain
  INFO root [0x0000323c] [2018-08-23 16:18:17,937] - 	internalAddr : 192.168.0.106:56299
  INFO root [0x0000323c] [2018-08-23 16:18:17,937] - 	componentID : 8001
  WARN root [0x0000323c] [2018-08-23 16:18:18,253] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20966, errorno=10048
  INFO root [0x0000323c] [2018-08-23 16:18:18,257] - ---- cellapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 85A70C5E64F896E0F1A60BF405B4EB07. Config: Debug X86. Built: 15:53:53 Apr 29 2018. AppID: 8001. UID: 19500. PID: 16684 ----
  INFO root [0x0000323c] [2018-08-23 16:18:18,257] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [0x0000323c] [2018-08-23 16:18:18,257] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x0000323c] [2018-08-23 16:18:18,258] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x0000323c] [2018-08-23 16:18:18,385] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x0000323c] [2018-08-23 16:18:18,385] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x0000323c] [2018-08-23 16:18:18,385] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x0000323c] [2018-08-23 16:18:18,388] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x0000323c] [2018-08-23 16:18:18,389] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x0000323c] [2018-08-23 16:18:18,389] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x0000323c] [2018-08-23 16:18:18,389] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x0000323c] [2018-08-23 16:18:18,416] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x0000323c] [2018-08-23 16:18:18,446] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x0000323c] [2018-08-23 16:18:18,446] - Script::install(): KBExtra is successfully!
 DEBUG root [0x0000323c] [2018-08-23 16:18:18,467] - loaded entity-script:Account(1).
 DEBUG root [0x0000323c] [2018-08-23 16:18:18,497] - loaded entity-script:Room(4).
  INFO root [0x0000323c] [2018-08-23 16:18:18,497] - TelnetServer server is running on port 50000
  INFO root [0x0000323c] [2018-08-23 16:18:18,807] - ---- cellapp is running ----
 DEBUG root [0x0000323c] [2018-08-23 16:18:18,807] - Components::process(): Request for the process of identity...
  WARN root [0x0000323c] [2018-08-23 16:18:24,882] - EntityApp::checkTickPeriod: tick took 6074% (6.07 seconds)!
  INFO root [0x0000323c] [2018-08-23 16:18:25,908] - Components::findComponents: find logger(1)...
  INFO root [0x0000323c] [2018-08-23 16:18:25,956] - Components::findComponents: found logger, addr:192.168.0.106:56297
  INFO root [0x0000323c] [2018-08-23 16:18:25,956] - Components::addComponent: reset orderLog, uid=19500!
  INFO root [0x0000323c] [2018-08-23 16:18:25,956] - Components::addComponent[logger], uid=19500, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x0000323c] [2018-08-23 16:18:25,957] - Components::findComponents: find dbmgr(2)...
  INFO root [0x0000323c] [2018-08-23 16:18:26,057] - Components::findComponents: found dbmgr, addr:192.168.0.106:56300
  INFO root [0x0000323c] [2018-08-23 16:18:26,058] - Components::addComponent: reset orderLog, uid=19500!
  INFO root [0x0000323c] [2018-08-23 16:18:26,058] - Components::addComponent[dbmgr], uid=19500, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x0000323c] [2018-08-23 16:18:26,058] - Components::findComponents: found dbmgr, addr:192.168.0.106:56300
  WARN root [0x0000323c] [2018-08-23 16:18:27,058] - EntityApp::checkTickPeriod: tick took 1250% (1.25 seconds)!
  WARN root [0x0000323c] [2018-08-23 16:18:27,058] - Forwarding logs to logger[192.168.0.106:56297/0/0/0]...
 ERROR root [0x0000323c] [2018-08-23 16:21:56,310] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x0000323c] [2018-08-23 16:21:56,327] - The following logs sent to logger failed:
  WARN root [0x0000323c] [2018-08-23 16:21:56,327] - ==> [2018-08-23 16:21:56 306] TCPPacketReceiver::processPendingEvents(192.168.0.106:56297): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x0000323c] [2018-08-23 16:21:56,327] - ==> [2018-08-23 16:21:56 310] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x0000323c] [2018-08-23 16:21:56,381] - TCPPacketReceiver::processPendingEvents(192.168.0.106:56300): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x0000323c] [2018-08-23 16:21:56,384] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x0000323c] [2018-08-23 16:21:56,401] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [0x0000323c] [2018-08-23 16:21:56,403] - Shutdowner::onShutdown: shutting down
  INFO root [0x0000323c] [2018-08-23 16:21:56,404] - Spaces::destroySpace: 1.
  INFO root [0x0000323c] [2018-08-23 16:21:56,404] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [0x0000323c] [2018-08-23 16:21:56,405] - Account::~Account(): 2002
 DEBUG root [0x0000323c] [2018-08-23 16:21:56,405] - Account::~Account(): 2004
 DEBUG root [0x0000323c] [2018-08-23 16:21:56,405] - EntityRef::destroyObjPool(): size 16.
 DEBUG root [0x0000323c] [2018-08-23 16:21:56,405] - Witness::destroyObjPool(): size 16.
 DEBUG root [0x0000323c] [2018-08-23 16:21:56,413] - Room::~Room(): 2003
 ERROR root [0x0000323c] [2018-08-23 16:21:56,414] - PyGC::debugTracing(): EntityCall : leaked(2)
 DEBUG root [0x0000323c] [2018-08-23 16:21:56,414] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x0000323c] [2018-08-23 16:21:56,415] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x0000323c] [2018-08-23 16:21:56,415] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x0000323c] [2018-08-23 16:21:56,415] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x0000323c] [2018-08-23 16:21:56,415] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x0000323c] [2018-08-23 16:21:56,415] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x0000323c] [2018-08-23 16:21:56,415] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x0000323c] [2018-08-23 16:21:56,415] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x0000323c] [2018-08-23 16:21:56,425] - Script::uninstall(): is successfully!
 DEBUG root [0x0000323c] [2018-08-23 16:21:56,425] - ThreadPool::destroy(): starting size 2.
  INFO root [0x000046d4] [2018-08-23 16:21:57,680] - 
  INFO root [0x000046d4] [2018-08-23 16:21:57,681] - -----------------------------------------------------------------------------------------


  INFO root [0x000046d4] [2018-08-23 16:21:57,682] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [0x000046d4] [2018-08-23 16:21:57,682] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [0x000046d4] [2018-08-23 16:21:57,682] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [0x000046d4] [2018-08-23 16:21:57,687] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:56358 )
  INFO root [0x000046d4] [2018-08-23 16:21:57,688] - NetworkInterface::initialize(INTERNAL): address 192.168.0.106:56358, SOMAXCONN=5.
  INFO root [0x000046d4] [2018-08-23 16:21:57,688] - server-configs:
  INFO root [0x000046d4] [2018-08-23 16:21:57,688] - 	gameUpdateHertz : 10
  INFO root [0x000046d4] [2018-08-23 16:21:57,688] - 	defaultViewRadius : 80
  INFO root [0x000046d4] [2018-08-23 16:21:57,688] - 	defaultViewHysteresisArea : 5
  INFO root [0x000046d4] [2018-08-23 16:21:57,688] - 	entryScriptFile : kbemain
  INFO root [0x000046d4] [2018-08-23 16:21:57,688] - 	internalAddr : 192.168.0.106:56358
  INFO root [0x000046d4] [2018-08-23 16:21:57,688] - 	componentID : 8001
  INFO root [0x000046d4] [2018-08-23 16:21:59,194] - ---- cellapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 85A70C5E64F896E0F1A60BF405B4EB07. Config: Debug X86. Built: 15:53:53 Apr 29 2018. AppID: 8001. UID: 20218. PID: 18128 ----
  INFO root [0x000046d4] [2018-08-23 16:21:59,195] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [0x000046d4] [2018-08-23 16:21:59,195] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x000046d4] [2018-08-23 16:21:59,195] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x000046d4] [2018-08-23 16:21:59,342] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x000046d4] [2018-08-23 16:21:59,343] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x000046d4] [2018-08-23 16:21:59,343] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x000046d4] [2018-08-23 16:21:59,347] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x000046d4] [2018-08-23 16:21:59,347] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x000046d4] [2018-08-23 16:21:59,347] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x000046d4] [2018-08-23 16:21:59,348] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x000046d4] [2018-08-23 16:21:59,375] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x000046d4] [2018-08-23 16:21:59,403] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x000046d4] [2018-08-23 16:21:59,403] - Script::install(): KBExtra is successfully!
 DEBUG root [0x000046d4] [2018-08-23 16:21:59,424] - loaded entity-script:Account(1).
 DEBUG root [0x000046d4] [2018-08-23 16:21:59,450] - loaded entity-script:Room(4).
  INFO root [0x000046d4] [2018-08-23 16:21:59,450] - TelnetServer server is running on port 50000
  INFO root [0x000046d4] [2018-08-23 16:21:59,798] - ---- cellapp is running ----
 DEBUG root [0x000046d4] [2018-08-23 16:21:59,798] - Components::process(): Request for the process of identity...
  WARN root [0x000046d4] [2018-08-23 16:22:05,889] - EntityApp::checkTickPeriod: tick took 6091% (6.09 seconds)!
  INFO root [0x000046d4] [2018-08-23 16:22:06,899] - Components::findComponents: find logger(1)...
  INFO root [0x000046d4] [2018-08-23 16:22:06,924] - Components::findComponents: found logger, addr:192.168.0.106:56357
  INFO root [0x000046d4] [2018-08-23 16:22:06,925] - Components::addComponent: reset orderLog, uid=20218!
  INFO root [0x000046d4] [2018-08-23 16:22:06,925] - Components::addComponent[logger], uid=20218, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x000046d4] [2018-08-23 16:22:06,925] - Components::findComponents: find dbmgr(2)...
  INFO root [0x000046d4] [2018-08-23 16:22:07,026] - Components::findComponents: found dbmgr, addr:192.168.0.106:56363
  INFO root [0x000046d4] [2018-08-23 16:22:07,027] - Components::addComponent: reset orderLog, uid=20218!
  INFO root [0x000046d4] [2018-08-23 16:22:07,027] - Components::addComponent[dbmgr], uid=20218, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x000046d4] [2018-08-23 16:22:07,027] - Components::findComponents: found dbmgr, addr:192.168.0.106:56363
  WARN root [0x000046d4] [2018-08-23 16:22:08,027] - EntityApp::checkTickPeriod: tick took 1228% (1.23 seconds)!
  WARN root [0x000046d4] [2018-08-23 16:22:08,027] - Forwarding logs to logger[192.168.0.106:56357/0/0/0]...
 ERROR root [0x000046d4] [2018-08-23 16:37:35,282] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x000046d4] [2018-08-23 16:37:35,296] - The following logs sent to logger failed:
  WARN root [0x000046d4] [2018-08-23 16:37:35,296] - ==> [2018-08-23 16:37:35 272] TCPPacketReceiver::processPendingEvents(192.168.0.106:56357): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x000046d4] [2018-08-23 16:37:35,296] - ==> [2018-08-23 16:37:35 282] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x000046d4] [2018-08-23 16:37:35,349] - TCPPacketReceiver::processPendingEvents(192.168.0.106:56363): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x000046d4] [2018-08-23 16:37:35,353] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x000046d4] [2018-08-23 16:37:35,368] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [0x000046d4] [2018-08-23 16:37:35,369] - Shutdowner::onShutdown: shutting down
  INFO root [0x000046d4] [2018-08-23 16:37:35,371] - Spaces::destroySpace: 1.
  INFO root [0x000046d4] [2018-08-23 16:37:35,371] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [0x000046d4] [2018-08-23 16:37:35,371] - Account::~Account(): 2002
 DEBUG root [0x000046d4] [2018-08-23 16:37:35,371] - Account::~Account(): 2004
 DEBUG root [0x000046d4] [2018-08-23 16:37:35,371] - EntityRef::destroyObjPool(): size 16.
 DEBUG root [0x000046d4] [2018-08-23 16:37:35,371] - Witness::destroyObjPool(): size 16.
 DEBUG root [0x000046d4] [2018-08-23 16:37:35,380] - Room::~Room(): 2003
 ERROR root [0x000046d4] [2018-08-23 16:37:35,381] - PyGC::debugTracing(): EntityCall : leaked(2)
 DEBUG root [0x000046d4] [2018-08-23 16:37:35,381] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x000046d4] [2018-08-23 16:37:35,381] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x000046d4] [2018-08-23 16:37:35,381] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x000046d4] [2018-08-23 16:37:35,381] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x000046d4] [2018-08-23 16:37:35,381] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x000046d4] [2018-08-23 16:37:35,382] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x000046d4] [2018-08-23 16:37:35,382] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x000046d4] [2018-08-23 16:37:35,382] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x000046d4] [2018-08-23 16:37:35,391] - Script::uninstall(): is successfully!
 DEBUG root [0x000046d4] [2018-08-23 16:37:35,392] - ThreadPool::destroy(): starting size 2.
  INFO root [0x00002ee0] [2018-08-23 16:37:36,711] - 
  INFO root [0x00002ee0] [2018-08-23 16:37:36,711] - -----------------------------------------------------------------------------------------


  INFO root [0x00002ee0] [2018-08-23 16:37:36,712] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [0x00002ee0] [2018-08-23 16:37:36,712] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [0x00002ee0] [2018-08-23 16:37:36,712] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [0x00002ee0] [2018-08-23 16:37:36,716] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:60630 )
  INFO root [0x00002ee0] [2018-08-23 16:37:36,716] - NetworkInterface::initialize(INTERNAL): address 192.168.0.106:60630, SOMAXCONN=5.
  INFO root [0x00002ee0] [2018-08-23 16:37:36,716] - server-configs:
  INFO root [0x00002ee0] [2018-08-23 16:37:36,716] - 	gameUpdateHertz : 10
  INFO root [0x00002ee0] [2018-08-23 16:37:36,716] - 	defaultViewRadius : 80
  INFO root [0x00002ee0] [2018-08-23 16:37:36,716] - 	defaultViewHysteresisArea : 5
  INFO root [0x00002ee0] [2018-08-23 16:37:36,716] - 	entryScriptFile : kbemain
  INFO root [0x00002ee0] [2018-08-23 16:37:36,717] - 	internalAddr : 192.168.0.106:60630
  INFO root [0x00002ee0] [2018-08-23 16:37:36,717] - 	componentID : 8001
  INFO root [0x00002ee0] [2018-08-23 16:37:38,230] - ---- cellapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 85A70C5E64F896E0F1A60BF405B4EB07. Config: Debug X86. Built: 15:53:53 Apr 29 2018. AppID: 8001. UID: 23285. PID: 11280 ----
  INFO root [0x00002ee0] [2018-08-23 16:37:38,231] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [0x00002ee0] [2018-08-23 16:37:38,231] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00002ee0] [2018-08-23 16:37:38,232] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x00002ee0] [2018-08-23 16:37:38,372] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00002ee0] [2018-08-23 16:37:38,372] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x00002ee0] [2018-08-23 16:37:38,373] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x00002ee0] [2018-08-23 16:37:38,375] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x00002ee0] [2018-08-23 16:37:38,376] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x00002ee0] [2018-08-23 16:37:38,376] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x00002ee0] [2018-08-23 16:37:38,376] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x00002ee0] [2018-08-23 16:37:38,411] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x00002ee0] [2018-08-23 16:37:38,439] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x00002ee0] [2018-08-23 16:37:38,439] - Script::install(): KBExtra is successfully!
 DEBUG root [0x00002ee0] [2018-08-23 16:37:38,463] - loaded entity-script:Account(1).
 DEBUG root [0x00002ee0] [2018-08-23 16:37:38,497] - loaded entity-script:Room(4).
  INFO root [0x00002ee0] [2018-08-23 16:37:38,497] - TelnetServer server is running on port 50000
  INFO root [0x00002ee0] [2018-08-23 16:37:38,860] - ---- cellapp is running ----
 DEBUG root [0x00002ee0] [2018-08-23 16:37:38,860] - Components::process(): Request for the process of identity...
  WARN root [0x00002ee0] [2018-08-23 16:37:44,928] - EntityApp::checkTickPeriod: tick took 6067% (6.07 seconds)!
  INFO root [0x00002ee0] [2018-08-23 16:37:45,961] - Components::findComponents: find logger(1)...
  INFO root [0x00002ee0] [2018-08-23 16:37:46,046] - Components::findComponents: found logger, addr:192.168.0.106:60629
  INFO root [0x00002ee0] [2018-08-23 16:37:46,047] - Components::addComponent: reset orderLog, uid=23285!
  INFO root [0x00002ee0] [2018-08-23 16:37:46,047] - Components::addComponent[logger], uid=23285, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00002ee0] [2018-08-23 16:37:46,047] - Components::findComponents: find dbmgr(2)...
  INFO root [0x00002ee0] [2018-08-23 16:37:46,148] - Components::findComponents: found dbmgr, addr:192.168.0.106:60626
  INFO root [0x00002ee0] [2018-08-23 16:37:46,149] - Components::addComponent: reset orderLog, uid=23285!
  INFO root [0x00002ee0] [2018-08-23 16:37:46,149] - Components::addComponent[dbmgr], uid=23285, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00002ee0] [2018-08-23 16:37:46,149] - Components::findComponents: found dbmgr, addr:192.168.0.106:60626
  WARN root [0x00002ee0] [2018-08-23 16:37:47,149] - EntityApp::checkTickPeriod: tick took 1288% (1.29 seconds)!
  WARN root [0x00002ee0] [2018-08-23 16:37:47,151] - Forwarding logs to logger[192.168.0.106:60629/0/0/0]...
 ERROR root [0x00002ee0] [2018-08-23 17:33:50,830] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x00002ee0] [2018-08-23 17:33:50,854] - The following logs sent to logger failed:
  WARN root [0x00002ee0] [2018-08-23 17:33:50,854] - ==> [2018-08-23 17:33:50 825] TCPPacketReceiver::processPendingEvents(192.168.0.106:60629): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00002ee0] [2018-08-23 17:33:50,854] - ==> [2018-08-23 17:33:50 830] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x00002ee0] [2018-08-23 17:33:50,906] - TCPPacketReceiver::processPendingEvents(192.168.0.106:60626): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00002ee0] [2018-08-23 17:33:50,921] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x00002ee0] [2018-08-23 17:33:50,943] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [0x00002ee0] [2018-08-23 17:33:50,944] - Shutdowner::onShutdown: shutting down
  INFO root [0x00002ee0] [2018-08-23 17:33:50,945] - Spaces::destroySpace: 1.
  INFO root [0x00002ee0] [2018-08-23 17:33:50,946] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [0x00002ee0] [2018-08-23 17:33:50,946] - Account::~Account(): 2002
 DEBUG root [0x00002ee0] [2018-08-23 17:33:50,946] - Account::~Account(): 2004
 DEBUG root [0x00002ee0] [2018-08-23 17:33:50,946] - EntityRef::destroyObjPool(): size 16.
 DEBUG root [0x00002ee0] [2018-08-23 17:33:50,946] - Witness::destroyObjPool(): size 16.
 DEBUG root [0x00002ee0] [2018-08-23 17:33:50,954] - Room::~Room(): 2003
 ERROR root [0x00002ee0] [2018-08-23 17:33:50,955] - PyGC::debugTracing(): EntityCall : leaked(2)
 DEBUG root [0x00002ee0] [2018-08-23 17:33:50,956] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00002ee0] [2018-08-23 17:33:50,957] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x00002ee0] [2018-08-23 17:33:50,957] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x00002ee0] [2018-08-23 17:33:50,957] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x00002ee0] [2018-08-23 17:33:50,957] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x00002ee0] [2018-08-23 17:33:50,957] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x00002ee0] [2018-08-23 17:33:50,957] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x00002ee0] [2018-08-23 17:33:50,958] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x00002ee0] [2018-08-23 17:33:50,969] - Script::uninstall(): is successfully!
 DEBUG root [0x00002ee0] [2018-08-23 17:33:50,969] - ThreadPool::destroy(): starting size 2.
  INFO root [0x000044b4] [2018-08-23 17:33:52,283] - 
  INFO root [0x000044b4] [2018-08-23 17:33:52,283] - -----------------------------------------------------------------------------------------


  INFO root [0x000044b4] [2018-08-23 17:33:52,284] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [0x000044b4] [2018-08-23 17:33:52,284] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [0x000044b4] [2018-08-23 17:33:52,284] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [0x000044b4] [2018-08-23 17:33:52,286] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:63995 )
  INFO root [0x000044b4] [2018-08-23 17:33:52,286] - NetworkInterface::initialize(INTERNAL): address 192.168.0.106:63995, SOMAXCONN=5.
  INFO root [0x000044b4] [2018-08-23 17:33:52,286] - server-configs:
  INFO root [0x000044b4] [2018-08-23 17:33:52,287] - 	gameUpdateHertz : 10
  INFO root [0x000044b4] [2018-08-23 17:33:52,287] - 	defaultViewRadius : 80
  INFO root [0x000044b4] [2018-08-23 17:33:52,287] - 	defaultViewHysteresisArea : 5
  INFO root [0x000044b4] [2018-08-23 17:33:52,287] - 	entryScriptFile : kbemain
  INFO root [0x000044b4] [2018-08-23 17:33:52,287] - 	internalAddr : 192.168.0.106:63995
  INFO root [0x000044b4] [2018-08-23 17:33:52,287] - 	componentID : 8001
  INFO root [0x000044b4] [2018-08-23 17:33:53,801] - ---- cellapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 85A70C5E64F896E0F1A60BF405B4EB07. Config: Debug X86. Built: 15:53:53 Apr 29 2018. AppID: 8001. UID: 1538. PID: 18472 ----
  INFO root [0x000044b4] [2018-08-23 17:33:53,803] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [0x000044b4] [2018-08-23 17:33:53,803] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x000044b4] [2018-08-23 17:33:53,804] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x000044b4] [2018-08-23 17:33:53,942] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x000044b4] [2018-08-23 17:33:53,943] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x000044b4] [2018-08-23 17:33:53,943] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x000044b4] [2018-08-23 17:33:53,946] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x000044b4] [2018-08-23 17:33:53,946] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x000044b4] [2018-08-23 17:33:53,946] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x000044b4] [2018-08-23 17:33:53,947] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x000044b4] [2018-08-23 17:33:53,974] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x000044b4] [2018-08-23 17:33:54,002] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x000044b4] [2018-08-23 17:33:54,003] - Script::install(): KBExtra is successfully!
 DEBUG root [0x000044b4] [2018-08-23 17:33:54,035] - loaded entity-script:Account(1).
 DEBUG root [0x000044b4] [2018-08-23 17:33:54,065] - loaded entity-script:Room(4).
  INFO root [0x000044b4] [2018-08-23 17:33:54,066] - TelnetServer server is running on port 50000
  INFO root [0x000044b4] [2018-08-23 17:33:54,445] - ---- cellapp is running ----
 DEBUG root [0x000044b4] [2018-08-23 17:33:54,445] - Components::process(): Request for the process of identity...
  WARN root [0x000044b4] [2018-08-23 17:34:00,549] - EntityApp::checkTickPeriod: tick took 6104% (6.10 seconds)!
  INFO root [0x000044b4] [2018-08-23 17:34:01,585] - Components::findComponents: find logger(1)...
  INFO root [0x000044b4] [2018-08-23 17:34:01,609] - Components::findComponents: found logger, addr:192.168.0.106:63991
  INFO root [0x000044b4] [2018-08-23 17:34:01,610] - Components::addComponent: reset orderLog, uid=1538!
  INFO root [0x000044b4] [2018-08-23 17:34:01,610] - Components::addComponent[logger], uid=1538, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x000044b4] [2018-08-23 17:34:01,612] - Components::findComponents: find dbmgr(2)...
  INFO root [0x000044b4] [2018-08-23 17:34:01,712] - Components::findComponents: found dbmgr, addr:192.168.0.106:63990
  INFO root [0x000044b4] [2018-08-23 17:34:01,713] - Components::addComponent: reset orderLog, uid=1538!
  INFO root [0x000044b4] [2018-08-23 17:34:01,713] - Components::addComponent[dbmgr], uid=1538, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x000044b4] [2018-08-23 17:34:01,713] - Components::findComponents: found dbmgr, addr:192.168.0.106:63990
  WARN root [0x000044b4] [2018-08-23 17:34:02,713] - Forwarding logs to logger[192.168.0.106:63991/0/0/0]...
 ERROR root [0x000044b4] [2018-08-23 17:43:09,349] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x000044b4] [2018-08-23 17:43:09,371] - The following logs sent to logger failed:
  WARN root [0x000044b4] [2018-08-23 17:43:09,371] - ==> [2018-08-23 17:43:09 344] TCPPacketReceiver::processPendingEvents(192.168.0.106:63991): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x000044b4] [2018-08-23 17:43:09,371] - ==> [2018-08-23 17:43:09 350] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x000044b4] [2018-08-23 17:43:09,429] - TCPPacketReceiver::processPendingEvents(192.168.0.106:63990): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x000044b4] [2018-08-23 17:43:09,434] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x000044b4] [2018-08-23 17:43:09,456] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [0x000044b4] [2018-08-23 17:43:09,458] - Shutdowner::onShutdown: shutting down
  INFO root [0x000044b4] [2018-08-23 17:43:09,459] - Spaces::destroySpace: 1.
  INFO root [0x000044b4] [2018-08-23 17:43:09,459] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [0x000044b4] [2018-08-23 17:43:09,460] - Account::~Account(): 2002
 DEBUG root [0x000044b4] [2018-08-23 17:43:09,460] - Account::~Account(): 2004
 DEBUG root [0x000044b4] [2018-08-23 17:43:09,460] - EntityRef::destroyObjPool(): size 16.
 DEBUG root [0x000044b4] [2018-08-23 17:43:09,460] - Witness::destroyObjPool(): size 16.
 DEBUG root [0x000044b4] [2018-08-23 17:43:09,469] - Room::~Room(): 2003
 ERROR root [0x000044b4] [2018-08-23 17:43:09,469] - PyGC::debugTracing(): EntityCall : leaked(2)
 DEBUG root [0x000044b4] [2018-08-23 17:43:09,473] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x000044b4] [2018-08-23 17:43:09,473] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x000044b4] [2018-08-23 17:43:09,474] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x000044b4] [2018-08-23 17:43:09,474] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x000044b4] [2018-08-23 17:43:09,474] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x000044b4] [2018-08-23 17:43:09,474] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x000044b4] [2018-08-23 17:43:09,474] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x000044b4] [2018-08-23 17:43:09,474] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x000044b4] [2018-08-23 17:43:09,485] - Script::uninstall(): is successfully!
 DEBUG root [0x000044b4] [2018-08-23 17:43:09,485] - ThreadPool::destroy(): starting size 2.
  INFO root [0x00003994] [2018-08-23 17:43:10,796] - 
  INFO root [0x00003994] [2018-08-23 17:43:10,797] - -----------------------------------------------------------------------------------------


  INFO root [0x00003994] [2018-08-23 17:43:10,797] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [0x00003994] [2018-08-23 17:43:10,797] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [0x00003994] [2018-08-23 17:43:10,797] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [0x00003994] [2018-08-23 17:43:10,802] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:64117 )
  INFO root [0x00003994] [2018-08-23 17:43:10,802] - NetworkInterface::initialize(INTERNAL): address 192.168.0.106:64117, SOMAXCONN=5.
  INFO root [0x00003994] [2018-08-23 17:43:10,802] - server-configs:
  INFO root [0x00003994] [2018-08-23 17:43:10,802] - 	gameUpdateHertz : 10
  INFO root [0x00003994] [2018-08-23 17:43:10,802] - 	defaultViewRadius : 80
  INFO root [0x00003994] [2018-08-23 17:43:10,802] - 	defaultViewHysteresisArea : 5
  INFO root [0x00003994] [2018-08-23 17:43:10,802] - 	entryScriptFile : kbemain
  INFO root [0x00003994] [2018-08-23 17:43:10,802] - 	internalAddr : 192.168.0.106:64117
  INFO root [0x00003994] [2018-08-23 17:43:10,803] - 	componentID : 8001
  INFO root [0x00003994] [2018-08-23 17:43:12,312] - ---- cellapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 85A70C5E64F896E0F1A60BF405B4EB07. Config: Debug X86. Built: 15:53:53 Apr 29 2018. AppID: 8001. UID: 3364. PID: 14904 ----
  INFO root [0x00003994] [2018-08-23 17:43:12,313] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [0x00003994] [2018-08-23 17:43:12,313] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00003994] [2018-08-23 17:43:12,313] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x00003994] [2018-08-23 17:43:12,475] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00003994] [2018-08-23 17:43:12,476] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x00003994] [2018-08-23 17:43:12,476] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x00003994] [2018-08-23 17:43:12,480] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x00003994] [2018-08-23 17:43:12,480] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x00003994] [2018-08-23 17:43:12,481] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x00003994] [2018-08-23 17:43:12,481] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x00003994] [2018-08-23 17:43:12,512] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x00003994] [2018-08-23 17:43:12,540] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x00003994] [2018-08-23 17:43:12,540] - Script::install(): KBExtra is successfully!
 DEBUG root [0x00003994] [2018-08-23 17:43:12,562] - loaded entity-script:Account(1).
 DEBUG root [0x00003994] [2018-08-23 17:43:12,589] - loaded entity-script:Room(4).
  INFO root [0x00003994] [2018-08-23 17:43:12,590] - TelnetServer server is running on port 50000
  INFO root [0x00003994] [2018-08-23 17:43:12,949] - ---- cellapp is running ----
 DEBUG root [0x00003994] [2018-08-23 17:43:12,949] - Components::process(): Request for the process of identity...
  WARN root [0x00003994] [2018-08-23 17:43:19,015] - EntityApp::checkTickPeriod: tick took 6065% (6.07 seconds)!
  INFO root [0x00003994] [2018-08-23 17:43:20,050] - Components::findComponents: find logger(1)...
  INFO root [0x00003994] [2018-08-23 17:43:20,061] - Components::findComponents: found logger, addr:192.168.0.106:64124
  INFO root [0x00003994] [2018-08-23 17:43:20,062] - Components::addComponent: reset orderLog, uid=3364!
  INFO root [0x00003994] [2018-08-23 17:43:20,062] - Components::addComponent[logger], uid=3364, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00003994] [2018-08-23 17:43:20,062] - Components::findComponents: find dbmgr(2)...
  INFO root [0x00003994] [2018-08-23 17:43:20,163] - Components::findComponents: found dbmgr, addr:192.168.0.106:64123
  INFO root [0x00003994] [2018-08-23 17:43:20,164] - Components::addComponent: reset orderLog, uid=3364!
  INFO root [0x00003994] [2018-08-23 17:43:20,164] - Components::addComponent[dbmgr], uid=3364, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00003994] [2018-08-23 17:43:20,164] - Components::findComponents: found dbmgr, addr:192.168.0.106:64123
  WARN root [0x00003994] [2018-08-23 17:43:21,164] - EntityApp::checkTickPeriod: tick took 1214% (1.21 seconds)!
  WARN root [0x00003994] [2018-08-23 17:43:21,164] - Forwarding logs to logger[192.168.0.106:64124/0/0/0]...
 ERROR root [0x00003994] [2018-08-23 17:45:28,114] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x00003994] [2018-08-23 17:45:28,136] - The following logs sent to logger failed:
  WARN root [0x00003994] [2018-08-23 17:45:28,136] - ==> [2018-08-23 17:45:28 110] TCPPacketReceiver::processPendingEvents(192.168.0.106:64124): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00003994] [2018-08-23 17:45:28,136] - ==> [2018-08-23 17:45:28 115] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x00003994] [2018-08-23 17:45:28,195] - TCPPacketReceiver::processPendingEvents(192.168.0.106:64123): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00003994] [2018-08-23 17:45:28,199] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x00003994] [2018-08-23 17:45:28,220] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [0x00003994] [2018-08-23 17:45:28,221] - Shutdowner::onShutdown: shutting down
  INFO root [0x00003994] [2018-08-23 17:45:28,222] - Spaces::destroySpace: 1.
  INFO root [0x00003994] [2018-08-23 17:45:28,223] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [0x00003994] [2018-08-23 17:45:28,223] - Account::~Account(): 2002
 DEBUG root [0x00003994] [2018-08-23 17:45:28,223] - Account::~Account(): 2004
 DEBUG root [0x00003994] [2018-08-23 17:45:28,223] - EntityRef::destroyObjPool(): size 16.
 DEBUG root [0x00003994] [2018-08-23 17:45:28,223] - Witness::destroyObjPool(): size 16.
 DEBUG root [0x00003994] [2018-08-23 17:45:28,234] - Room::~Room(): 2003
 ERROR root [0x00003994] [2018-08-23 17:45:28,235] - PyGC::debugTracing(): EntityCall : leaked(2)
 DEBUG root [0x00003994] [2018-08-23 17:45:28,236] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00003994] [2018-08-23 17:45:28,236] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x00003994] [2018-08-23 17:45:28,236] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x00003994] [2018-08-23 17:45:28,236] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x00003994] [2018-08-23 17:45:28,236] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x00003994] [2018-08-23 17:45:28,236] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x00003994] [2018-08-23 17:45:28,236] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x00003994] [2018-08-23 17:45:28,236] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x00003994] [2018-08-23 17:45:28,247] - Script::uninstall(): is successfully!
 DEBUG root [0x00003994] [2018-08-23 17:45:28,247] - ThreadPool::destroy(): starting size 2.
  INFO root [0x00004148] [2018-08-23 17:45:29,570] - 
  INFO root [0x00004148] [2018-08-23 17:45:29,571] - -----------------------------------------------------------------------------------------


  INFO root [0x00004148] [2018-08-23 17:45:29,571] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [0x00004148] [2018-08-23 17:45:29,572] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [0x00004148] [2018-08-23 17:45:29,572] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [0x00004148] [2018-08-23 17:45:29,575] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:64190 )
  INFO root [0x00004148] [2018-08-23 17:45:29,575] - NetworkInterface::initialize(INTERNAL): address 192.168.0.106:64190, SOMAXCONN=5.
  INFO root [0x00004148] [2018-08-23 17:45:29,576] - server-configs:
  INFO root [0x00004148] [2018-08-23 17:45:29,576] - 	gameUpdateHertz : 10
  INFO root [0x00004148] [2018-08-23 17:45:29,576] - 	defaultViewRadius : 80
  INFO root [0x00004148] [2018-08-23 17:45:29,576] - 	defaultViewHysteresisArea : 5
  INFO root [0x00004148] [2018-08-23 17:45:29,576] - 	entryScriptFile : kbemain
  INFO root [0x00004148] [2018-08-23 17:45:29,576] - 	internalAddr : 192.168.0.106:64190
  INFO root [0x00004148] [2018-08-23 17:45:29,576] - 	componentID : 8001
  INFO root [0x00004148] [2018-08-23 17:45:31,088] - ---- cellapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 85A70C5E64F896E0F1A60BF405B4EB07. Config: Debug X86. Built: 15:53:53 Apr 29 2018. AppID: 8001. UID: 3814. PID: 3608 ----
  INFO root [0x00004148] [2018-08-23 17:45:31,089] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [0x00004148] [2018-08-23 17:45:31,089] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00004148] [2018-08-23 17:45:31,089] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x00004148] [2018-08-23 17:45:31,216] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00004148] [2018-08-23 17:45:31,217] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x00004148] [2018-08-23 17:45:31,217] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x00004148] [2018-08-23 17:45:31,220] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x00004148] [2018-08-23 17:45:31,220] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x00004148] [2018-08-23 17:45:31,220] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x00004148] [2018-08-23 17:45:31,221] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x00004148] [2018-08-23 17:45:31,250] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x00004148] [2018-08-23 17:45:31,284] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x00004148] [2018-08-23 17:45:31,285] - Script::install(): KBExtra is successfully!
 DEBUG root [0x00004148] [2018-08-23 17:45:31,307] - loaded entity-script:Account(1).
 DEBUG root [0x00004148] [2018-08-23 17:45:31,333] - loaded entity-script:Room(4).
  INFO root [0x00004148] [2018-08-23 17:45:31,333] - TelnetServer server is running on port 50000
  INFO root [0x00004148] [2018-08-23 17:45:31,644] - ---- cellapp is running ----
 DEBUG root [0x00004148] [2018-08-23 17:45:31,644] - Components::process(): Request for the process of identity...
  WARN root [0x00004148] [2018-08-23 17:45:37,755] - EntityApp::checkTickPeriod: tick took 6110% (6.11 seconds)!
  INFO root [0x00004148] [2018-08-23 17:45:38,844] - Components::findComponents: find logger(1)...
  INFO root [0x00004148] [2018-08-23 17:45:38,889] - Components::findComponents: found logger, addr:192.168.0.106:64189
  INFO root [0x00004148] [2018-08-23 17:45:38,889] - Components::addComponent: reset orderLog, uid=3814!
  INFO root [0x00004148] [2018-08-23 17:45:38,890] - Components::addComponent[logger], uid=3814, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00004148] [2018-08-23 17:45:38,891] - Components::findComponents: find dbmgr(2)...
  INFO root [0x00004148] [2018-08-23 17:45:38,996] - Components::findComponents: found dbmgr, addr:192.168.0.106:64186
  INFO root [0x00004148] [2018-08-23 17:45:38,997] - Components::addComponent: reset orderLog, uid=3814!
  INFO root [0x00004148] [2018-08-23 17:45:38,998] - Components::addComponent[dbmgr], uid=3814, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00004148] [2018-08-23 17:45:38,998] - Components::findComponents: found dbmgr, addr:192.168.0.106:64186
  WARN root [0x00004148] [2018-08-23 17:45:39,998] - EntityApp::checkTickPeriod: tick took 1254% (1.25 seconds)!
  WARN root [0x00004148] [2018-08-23 17:45:39,998] - Forwarding logs to logger[192.168.0.106:64189/0/0/0]...
