 ERROR root [2018-11-04 01:09:11,836] - Components::removeComponentByChannel: loginapp : 9000, Abnormal exit! errorno=10054
 ERROR root [2018-11-04 01:09:11,911] - Components::removeComponentByChannel: cellapp : 8001, Abnormal exit! errorno=10054
 ERROR root [2018-11-04 01:09:12,005] - Components::removeComponentByChannel: cellappmgr : 6000, Abnormal exit! errorno=10054
  INFO root [2018-11-04 16:24:01,856] - 
  INFO root [2018-11-04 16:24:01,901] - -----------------------------------------------------------------------------------------


  INFO root [2018-11-04 16:24:02,748] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [2018-11-04 16:24:02,748] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [2018-11-04 16:24:02,749] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [2018-11-04 16:24:03,443] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.107 ( 192.168.0.107:55290 )
  INFO root [2018-11-04 16:24:03,444] - NetworkInterface::initialize(INTERNAL): address 192.168.0.107:55290, SOMAXCONN=5.
  INFO root [2018-11-04 16:24:03,445] - server-configs:
  INFO root [2018-11-04 16:24:03,445] - 	internalAddr : 192.168.0.107:55290
  INFO root [2018-11-04 16:24:03,445] - 	componentID : 4000
  INFO root [2018-11-04 16:24:05,181] - ---- dbmgr Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: F28F1C37BCC70CD27B77841D4A30E3D7. Config: Debug X86. Built: 15:52:44 Apr 29 2018. AppID: 4000. UID: 6164. PID: 1504 ----
  INFO root [2018-11-04 16:24:05,182] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [2018-11-04 16:24:05,215] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-11-04 16:24:05,232] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-11-04 16:24:08,320] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-11-04 16:24:08,417] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-11-04 16:24:08,467] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-11-04 16:24:08,954] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-11-04 16:24:09,002] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-11-04 16:24:09,023] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-11-04 16:24:09,066] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-11-04 16:24:09,889] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-11-04 16:24:11,460] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:52:37) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-11-04 16:24:11,461] - Script::install(): KBExtra is successfully!
  INFO root [2018-11-04 16:24:12,770] - Dbmgr::initializeEnd: digest(7F4FC8296AD553545CD95B23EFF6238F)
S_INFO root [2018-11-04 16:24:12,772] - onDBMgrReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-11-04 16:24:12,820] - TelnetServer server is running on port 32000
  INFO root [2018-11-04 16:24:12,939] - Dbmgr::initInterfacesHandler: interfaces addr(127.0.0.1:30099), accountType:(interfaces), chargeType:(interfaces).
  WARN root [2018-11-04 16:24:13,623] - DBUtil::initialize: db(default) password is not encrypted!
please use password(rsa):
A49783B3598A245B835848C3CD5AFB6F8FCA02C437921BFCCCC103F32372F5A81F1CE75CC1388F08D1383159FA93E912A9AF895153E8422853ED5E2CC619982C2C7E85A05733168F8CFF967A0B22F396AEB6C6F642FF936C17CD4DD4E6BA7D16F6661A5543A3AF551934B41C5D2BB2DF0E024FBF9047E984F0AECADF74F9A3E3
 DEBUG root [2018-11-04 16:24:14,206] - DBInterfaceMysql::attach: connect: localhost:3306 starting...
 DEBUG root [2018-11-04 16:24:16,825] - DBInterfaceMysql::attach: successfully! addr: localhost:3306
  INFO root [2018-11-04 16:24:16,826] - DBUtil::createInterface[0x3ef2e4]: interface=default, dbtype=mysql, ip=localhost, port=3306, currdatabase=kbe, username=kbe, connected=yes.

  INFO root [2018-11-04 16:24:16,869] - ThreadPool::createThreadPool: creating  threadpool...
 DEBUG root [2018-11-04 16:24:16,870] - DBInterfaceMysql::attach: connect: localhost:3306 starting...
 DEBUG root [2018-11-04 16:24:16,871] - DBInterfaceMysql::attach: connect: localhost:3306 starting...
  INFO root [2018-11-04 16:24:16,872] - ThreadPool::createThreadPool: successfully(5), newThreadCount=5, normalMaxThreadCount=5, maxThreadCount=5
 DEBUG root [2018-11-04 16:24:16,873] - DBInterfaceMysql::attach: connect: localhost:3306 starting...
 DEBUG root [2018-11-04 16:24:16,874] - DBInterfaceMysql::attach: connect: localhost:3306 starting...
 DEBUG root [2018-11-04 16:24:16,874] - DBInterfaceMysql::attach: connect: localhost:3306 starting...
 DEBUG root [2018-11-04 16:24:16,877] - DBInterfaceMysql::attach: successfully! addr: localhost:3306
 DEBUG root [2018-11-04 16:24:16,877] - DBThread::onStart(): 0x1eb72a8!
 DEBUG root [2018-11-04 16:24:16,878] - DBInterfaceMysql::attach: successfully! addr: localhost:3306
 DEBUG root [2018-11-04 16:24:16,878] - DBThread::onStart(): 0x1eb7220!
 DEBUG root [2018-11-04 16:24:16,879] - DBInterfaceMysql::attach: successfully! addr: localhost:3306
 DEBUG root [2018-11-04 16:24:16,879] - DBThread::onStart(): 0x1eb7330!
 DEBUG root [2018-11-04 16:24:16,881] - DBInterfaceMysql::attach: successfully! addr: localhost:3306
 DEBUG root [2018-11-04 16:24:16,882] - DBInterfaceMysql::attach: successfully! addr: localhost:3306
 DEBUG root [2018-11-04 16:24:16,882] - DBThread::onStart(): 0x1eb73b8!
 DEBUG root [2018-11-04 16:24:16,882] - DBThread::onStart(): 0x1eb7440!
  INFO root [2018-11-04 16:24:17,216] - DBInterfaceMysql::query: successfully!
  INFO root [2018-11-04 16:24:17,219] - DBInterfaceMysql::query: successfully!
  INFO root [2018-11-04 16:24:17,371] - DBInterfaceMysql::query: successfully!
  INFO root [2018-11-04 16:24:17,592] - DBInterfaceMysql::query: successfully!
  WARN root [2018-11-04 16:24:17,731] - DBTask::process(): took 0.44 seconds
sql:(show index from tbl_CheckName)
  INFO root [2018-11-04 16:24:17,915] - DBInterfaceMysql::query: successfully!
  INFO root [2018-11-04 16:24:17,956] - DBInterfaceMysql::query: successfully!
  INFO root [2018-11-04 16:24:18,357] - DBInterfaceMysql::query: successfully!
  INFO root [2018-11-04 16:24:18,359] - DBInterfaceMysql::query: successfully!
  INFO root [2018-11-04 16:24:18,360] - DBInterfaceMysql::query: successfully!
  WARN root [2018-11-04 16:24:18,361] - DBTask::process(): took 1.14 seconds
sql:(delete from kbe_email_verification where logtime<1541316258 and type=3)
  WARN root [2018-11-04 16:24:18,362] - DBTask::process(): took 0.99 seconds
sql:(show index from tbl_Account)
  WARN root [2018-11-04 16:24:18,643] - DBTask::process(): took 1.42 seconds
sql:(insert into kbe_serverlog (heartbeatTime, logger) values(1541319857,4000) ON DUPLICATE KEY UPDATE heartbeatTime=1541319857)
  WARN root [2018-11-04 16:24:18,647] - DBTask::process(): took 0.91 seconds
sql:(show index from tbl_Halls)
  INFO root [2018-11-04 16:24:18,732] - DBInterfaceMysql::query: successfully!
  WARN root [2018-11-04 16:24:18,733] - DBTask::process(): took 1.51 seconds
sql:(delete from kbe_entitylog where logger in (4000))
  WARN root [2018-11-04 16:24:18,839] - DBTask::process(): delay 1.14 seconds, try adjusting the kbengine[_defs].xml(numConnections) and MySQL(my.cnf->max_connections or innodb_flush_log_at_trx_commit)!
sql:(show index from tbl_Room)
  WARN root [2018-11-04 16:24:18,844] - DBTask::process(): took 0.48 seconds
sql:(show index from tbl_Room)
  WARN root [2018-11-04 16:24:18,861] - e:\kbengine\kbe\src\server\dbmgr\dbmgr.cpp:275: Profile scriptCall took 6.09 seconds
  INFO root [2018-11-04 16:24:19,437] - ---- dbmgr is running ----
 DEBUG root [2018-11-04 16:24:19,438] - Components::process(): Request for the process of identity...
  INFO root [2018-11-04 16:24:25,891] - ServerApp::onRegisterNewApp: uid:6164, username:, componentType:baseappmgr, componentID:5000, globalorderID=-1, grouporderID=-1, intaddr:192.168.0.107, intport:55292, extaddr:nonsupport, extport:0,  from 192.168.0.107:55314/0/0/0.
  INFO root [2018-11-04 16:24:25,892] - Components::addComponent: reset orderLog, uid=6164!
  INFO root [2018-11-04 16:24:25,892] - Components::addComponent[baseappmgr], uid=6164, componentID=5000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-11-04 16:24:25,892] - ServerApp::onRegisterNewApp: uid:6164, username:, componentType:cellappmgr, componentID:6000, globalorderID=-1, grouporderID=-1, intaddr:192.168.0.107, intport:55288, extaddr:nonsupport, extport:0,  from 192.168.0.107:55316/0/0/0.
  INFO root [2018-11-04 16:24:25,892] - Components::addComponent[cellappmgr], uid=6164, componentID=6000, globalorderid=2, grouporderid=1, totalcount=1
  INFO root [2018-11-04 16:24:26,871] - Components::findComponents: find logger(1)...
  INFO root [2018-11-04 16:24:26,974] - Components::findComponents: found logger, addr:192.168.0.107:55286
  INFO root [2018-11-04 16:24:26,975] - Components::addComponent[logger], uid=6164, componentID=2000, globalorderid=3, grouporderid=1, totalcount=1
  WARN root [2018-11-04 16:24:26,977] - Forwarding logs to logger[192.168.0.107:55286/0/0/0]...
