  INFO root [2018-07-21 10:11:48,648] - 
  INFO root [2018-07-21 10:11:48,648] - 
  INFO root [2018-07-21 10:11:48,661] - -----------------------------------------------------------------------------------------


  INFO root [2018-07-21 10:11:48,661] - -----------------------------------------------------------------------------------------


  INFO root [2018-07-21 10:11:48,947] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [2018-07-21 10:11:48,947] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [2018-07-21 10:11:48,948] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [2018-07-21 10:11:48,948] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [2018-07-21 10:11:48,948] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [2018-07-21 10:11:48,948] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [2018-07-21 10:11:49,359] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:20013 )
  INFO root [2018-07-21 10:11:49,359] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:20013 )
  INFO root [2018-07-21 10:11:49,437] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.106:20013, SOMAXCONN=128.
  INFO root [2018-07-21 10:11:49,437] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.106:20013, SOMAXCONN=128.
  INFO root [2018-07-21 10:11:49,442] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:49782 )
  INFO root [2018-07-21 10:11:49,442] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:49783 )
  INFO root [2018-07-21 10:11:49,443] - NetworkInterface::initialize(INTERNAL): address 192.168.0.106:49782, SOMAXCONN=128.
  INFO root [2018-07-21 10:11:49,443] - NetworkInterface::initialize(INTERNAL): address 192.168.0.106:49783, SOMAXCONN=128.
  INFO root [2018-07-21 10:11:49,443] - server-configs:
  INFO root [2018-07-21 10:11:49,443] - server-configs:
  INFO root [2018-07-21 10:11:49,444] - 	internalAddr : 192.168.0.106:49782
  INFO root [2018-07-21 10:11:49,444] - 	internalAddr : 192.168.0.106:49783
  INFO root [2018-07-21 10:11:49,444] - 	externalAddr : 192.168.0.106:20013
  INFO root [2018-07-21 10:11:49,444] - 	componentID : 9000
  INFO root [2018-07-21 10:11:49,444] - 	externalAddr : 192.168.0.106:20013
  INFO root [2018-07-21 10:11:49,445] - 	componentID : 9000
  INFO root [2018-07-21 10:11:49,856] - Components::findLogger: found logger, addr:192.168.0.106:49773
  INFO root [2018-07-21 10:11:49,857] - Components::addComponent: reset orderLog, uid=8476!
  INFO root [2018-07-21 10:11:49,857] - Components::addComponent[logger], uid=8476, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-07-21 10:11:49,966] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: B20F257E332779D9E1EA7D34638E6146. Config: Debug X86. Built: 15:53:07 Apr 29 2018. AppID: 9000. UID: 8476. PID: 6624 ----
  INFO root [2018-07-21 10:11:49,967] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [2018-07-21 10:11:49,968] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-07-21 10:11:49,998] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [2018-07-21 10:11:51,441] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: B20F257E332779D9E1EA7D34638E6146. Config: Debug X86. Built: 15:53:07 Apr 29 2018. AppID: 9000. UID: 8450. PID: 7140 ----
  INFO root [2018-07-21 10:11:51,442] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [2018-07-21 10:11:51,443] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-07-21 10:11:51,444] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-07-21 10:11:54,077] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-07-21 10:11:54,077] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-07-21 10:11:54,131] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-07-21 10:11:54,131] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-07-21 10:11:54,152] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-07-21 10:11:54,152] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-07-21 10:11:54,886] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-07-21 10:11:54,886] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-07-21 10:11:54,972] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-07-21 10:11:54,972] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-07-21 10:11:55,001] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-07-21 10:11:55,001] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-07-21 10:11:55,038] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-07-21 10:11:55,038] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-07-21 10:11:55,482] - Script::install_py_dlls(): PyInit_unicodedata
 DEBUG root [2018-07-21 10:11:55,482] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-07-21 10:11:56,487] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-07-21 10:11:56,488] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-07-21 10:11:56,488] - Script::install(): KBExtra is successfully!
  INFO root [2018-07-21 10:11:56,488] - Script::install(): KBExtra is successfully!
S_INFO root [2018-07-21 10:11:56,768] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
S_INFO root [2018-07-21 10:11:56,768] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-07-21 10:11:56,769] - TelnetServer server is running on port 31000
  INFO root [2018-07-21 10:11:56,769] - TelnetServer server is running on port 31001
  INFO root [2018-07-21 10:11:57,341] - ---- loginapp is running ----
  INFO root [2018-07-21 10:11:57,341] - ---- loginapp is running ----
 DEBUG root [2018-07-21 10:11:57,342] - Components::process(): Request for the process of identity...
 DEBUG root [2018-07-21 10:11:57,342] - Components::process(): Request for the process of identity...
  WARN root [2018-07-21 10:11:57,742] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20946, errorno=10048
 ERROR root [2018-07-21 10:12:00,611] - Components::process: found loginapp, addr:192.168.0.106:49783
 ERROR root [2018-07-21 10:12:00,613] - ServerApp::onIdentityillegal: The current process and loginapp(componentID=9000 ->conflicted???, pid=6624, addr=192.168.0.106) conflict, the process will exit!
Can modify the components-CID and UID to avoid conflict.
  INFO root [2018-07-21 10:12:00,615] - Shutdowner::onShutdownBegin: shutting down(period=1, tickPeriod=1)
S_INFO root [2018-07-21 10:12:00,616] - onLoginAppShutDown()
  INFO root [2018-07-21 10:12:01,616] - Shutdowner::onShutdown: shutting down
  INFO root [2018-07-21 10:12:02,618] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-07-21 10:12:02,619] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-07-21 10:12:02,620] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-07-21 10:12:02,620] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-07-21 10:12:02,620] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-07-21 10:12:02,621] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-07-21 10:12:02,621] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-07-21 10:12:02,622] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-07-21 10:12:02,622] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-07-21 10:12:02,653] - Script::uninstall(): is successfully!
 DEBUG root [2018-07-21 10:12:02,653] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-07-21 10:12:02,953] - ThreadPool::destroy(): waiting for thread(2)[0x1a0b428,0x1a0b3c0,], try=1
 DEBUG root [2018-07-21 10:12:03,354] - TPThread::~TPThread(): 0x1a0b428
 DEBUG root [2018-07-21 10:12:03,355] - TPThread::~TPThread(): 0x1a0b3c0
 DEBUG root [2018-07-21 10:12:03,355] - ThreadPool::destroy(): successfully!
 DEBUG root [2018-07-21 10:12:03,393] - Bundle::destroyObjPool(): size 14.
 DEBUG root [2018-07-21 10:12:03,394] - Channel::destroyObjPool(): size 0.
 DEBUG root [2018-07-21 10:12:03,394] - TCPPacket::destroyObjPool(): size 0.
 DEBUG root [2018-07-21 10:12:03,394] - UDPPacket::destroyObjPool(): size 10.
 DEBUG root [2018-07-21 10:12:03,394] - EndPoint::destroyObjPool(): size 0.
 DEBUG root [2018-07-21 10:12:03,394] - Address::destroyObjPool(): size 0.
 DEBUG root [2018-07-21 10:12:03,394] - TCPPacketReceiver::destroyObjPool(): size 0.
 DEBUG root [2018-07-21 10:12:03,395] - UDPPacketReceiver::destroyObjPool(): size 0.
  INFO root [2018-07-21 10:12:03,395] - loginapp(9000) has shut down.
  WARN root [2018-07-21 10:12:03,847] - Forwarding logs to logger[192.168.0.106:49773/0/0/0]...
  INFO root [2018-07-21 10:12:04,421] - EventDispatcher()::~EventDispatcher: Num timers = 2
 ERROR root [2018-07-21 10:12:14,000] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-07-21 10:12:14,008] - The following logs sent to logger failed:
  WARN root [2018-07-21 10:12:14,008] - ==> [2018-07-21 10:12:14 000] TCPPacketReceiver::processPendingEvents(192.168.0.106:49773): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-07-21 10:12:14,008] - ==> [2018-07-21 10:12:14 000] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-07-21 10:12:14,046] - TCPPacketReceiver::processPendingEvents(192.168.0.106:49775): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-07-21 10:12:14,046] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-07-21 10:12:14,053] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-07-21 10:12:14,055] - onLoginAppShutDown()
  INFO root [2018-07-21 10:12:14,055] - Shutdowner::onShutdown: shutting down
  INFO root [2018-07-21 10:12:14,055] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-07-21 10:12:14,056] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-07-21 10:12:14,056] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-07-21 10:12:14,056] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-07-21 10:12:14,056] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-07-21 10:12:14,056] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-07-21 10:12:14,056] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-07-21 10:12:14,056] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-07-21 10:12:14,056] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-07-21 10:12:14,064] - Script::uninstall(): is successfully!
 DEBUG root [2018-07-21 10:12:14,064] - ThreadPool::destroy(): starting size 2.
  INFO root [2018-07-21 10:12:15,125] - 
  INFO root [2018-07-21 10:12:15,125] - -----------------------------------------------------------------------------------------


  INFO root [2018-07-21 10:12:15,126] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [2018-07-21 10:12:15,126] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [2018-07-21 10:12:15,126] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [2018-07-21 10:12:15,128] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:20013 )
  INFO root [2018-07-21 10:12:15,128] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.106:20013, SOMAXCONN=128.
  INFO root [2018-07-21 10:12:15,129] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:49816 )
  INFO root [2018-07-21 10:12:15,129] - NetworkInterface::initialize(INTERNAL): address 192.168.0.106:49816, SOMAXCONN=128.
  INFO root [2018-07-21 10:12:15,129] - server-configs:
  INFO root [2018-07-21 10:12:15,130] - 	internalAddr : 192.168.0.106:49816
  INFO root [2018-07-21 10:12:15,130] - 	externalAddr : 192.168.0.106:20013
  INFO root [2018-07-21 10:12:15,130] - 	componentID : 9000
  WARN root [2018-07-21 10:12:15,628] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20096, errorno=10048
  INFO root [2018-07-21 10:12:15,631] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: B20F257E332779D9E1EA7D34638E6146. Config: Debug X86. Built: 15:53:07 Apr 29 2018. AppID: 9000. UID: 8607. PID: 1360 ----
  INFO root [2018-07-21 10:12:15,632] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [2018-07-21 10:12:15,632] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-07-21 10:12:15,632] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-07-21 10:12:15,754] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-07-21 10:12:15,754] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-07-21 10:12:15,755] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-07-21 10:12:15,758] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-07-21 10:12:15,758] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-07-21 10:12:15,758] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-07-21 10:12:15,758] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-07-21 10:12:15,785] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-07-21 10:12:15,813] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-07-21 10:12:15,813] - Script::install(): KBExtra is successfully!
S_INFO root [2018-07-21 10:12:15,816] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-07-21 10:12:15,816] - TelnetServer server is running on port 31000
  INFO root [2018-07-21 10:12:16,094] - ---- loginapp is running ----
 DEBUG root [2018-07-21 10:12:16,095] - Components::process(): Request for the process of identity...
  INFO root [2018-07-21 10:12:23,196] - Components::findComponents: find logger(1)...
  INFO root [2018-07-21 10:12:23,298] - Components::findComponents: found logger, addr:192.168.0.106:49812
  INFO root [2018-07-21 10:12:23,299] - Components::addComponent: reset orderLog, uid=8607!
  INFO root [2018-07-21 10:12:23,299] - Components::addComponent[logger], uid=8607, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-07-21 10:12:23,301] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-07-21 10:12:23,405] - Components::findComponents: found dbmgr, addr:192.168.0.106:49810
  INFO root [2018-07-21 10:12:23,405] - Components::addComponent: reset orderLog, uid=8607!
  INFO root [2018-07-21 10:12:23,406] - Components::addComponent[dbmgr], uid=8607, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-07-21 10:12:23,406] - Components::findComponents: found dbmgr, addr:192.168.0.106:49810
  WARN root [2018-07-21 10:12:24,406] - Forwarding logs to logger[192.168.0.106:49812/0/0/0]...
 ERROR root [2018-07-21 10:18:36,938] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-07-21 10:18:36,939] - The following logs sent to logger failed:
  WARN root [2018-07-21 10:18:36,939] - ==> [2018-07-21 10:18:36 938] TCPPacketReceiver::processPendingEvents(192.168.0.106:49812): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-07-21 10:18:36,939] - ==> [2018-07-21 10:18:36 938] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-07-21 10:18:36,986] - TCPPacketReceiver::processPendingEvents(192.168.0.106:49810): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-07-21 10:18:36,987] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-07-21 10:18:36,988] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-07-21 10:18:36,989] - onLoginAppShutDown()
  INFO root [2018-07-21 10:18:36,989] - Shutdowner::onShutdown: shutting down
  INFO root [2018-07-21 10:18:36,989] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-07-21 10:18:36,989] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-07-21 10:18:36,990] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-07-21 10:18:36,990] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-07-21 10:18:36,990] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-07-21 10:18:36,990] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-07-21 10:18:36,990] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-07-21 10:18:36,990] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-07-21 10:18:36,990] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-07-21 10:18:36,999] - Script::uninstall(): is successfully!
 DEBUG root [2018-07-21 10:18:36,999] - ThreadPool::destroy(): starting size 2.
  INFO root [2018-07-21 10:18:38,059] - 
  INFO root [2018-07-21 10:18:38,060] - -----------------------------------------------------------------------------------------


  INFO root [2018-07-21 10:18:38,060] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [2018-07-21 10:18:38,060] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [2018-07-21 10:18:38,061] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [2018-07-21 10:18:38,064] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:20013 )
  INFO root [2018-07-21 10:18:38,064] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.106:20013, SOMAXCONN=128.
  INFO root [2018-07-21 10:18:38,065] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:49955 )
  INFO root [2018-07-21 10:18:38,065] - NetworkInterface::initialize(INTERNAL): address 192.168.0.106:49955, SOMAXCONN=128.
  INFO root [2018-07-21 10:18:38,065] - server-configs:
  INFO root [2018-07-21 10:18:38,065] - 	internalAddr : 192.168.0.106:49955
  INFO root [2018-07-21 10:18:38,065] - 	externalAddr : 192.168.0.106:20013
  INFO root [2018-07-21 10:18:38,066] - 	componentID : 9000
  INFO root [2018-07-21 10:18:39,745] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: B20F257E332779D9E1EA7D34638E6146. Config: Debug X86. Built: 15:53:07 Apr 29 2018. AppID: 9000. UID: 9857. PID: 9144 ----
  INFO root [2018-07-21 10:18:39,746] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [2018-07-21 10:18:39,746] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-07-21 10:18:39,747] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-07-21 10:18:39,873] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-07-21 10:18:39,873] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-07-21 10:18:39,873] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-07-21 10:18:39,876] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-07-21 10:18:39,876] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-07-21 10:18:39,876] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-07-21 10:18:39,877] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-07-21 10:18:39,910] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-07-21 10:18:39,943] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-07-21 10:18:39,944] - Script::install(): KBExtra is successfully!
S_INFO root [2018-07-21 10:18:39,946] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-07-21 10:18:39,946] - TelnetServer server is running on port 31000
  INFO root [2018-07-21 10:18:40,280] - ---- loginapp is running ----
 DEBUG root [2018-07-21 10:18:40,280] - Components::process(): Request for the process of identity...
  INFO root [2018-07-21 10:18:47,406] - Components::findComponents: find logger(1)...
  INFO root [2018-07-21 10:18:47,453] - Components::findComponents: found logger, addr:192.168.0.106:49961
  INFO root [2018-07-21 10:18:47,453] - Components::addComponent: reset orderLog, uid=9857!
  INFO root [2018-07-21 10:18:47,453] - Components::addComponent[logger], uid=9857, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-07-21 10:18:47,454] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-07-21 10:18:47,558] - Components::findComponents: found dbmgr, addr:192.168.0.106:49956
  INFO root [2018-07-21 10:18:47,559] - Components::addComponent: reset orderLog, uid=9857!
  INFO root [2018-07-21 10:18:47,559] - Components::addComponent[dbmgr], uid=9857, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-07-21 10:18:47,560] - Components::findComponents: found dbmgr, addr:192.168.0.106:49956
  WARN root [2018-07-21 10:18:48,560] - Forwarding logs to logger[192.168.0.106:49961/0/0/0]...
 ERROR root [2018-07-21 10:21:49,913] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-07-21 10:21:49,914] - The following logs sent to logger failed:
  WARN root [2018-07-21 10:21:49,914] - ==> [2018-07-21 10:21:49 912] TCPPacketReceiver::processPendingEvents(192.168.0.106:49961): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-07-21 10:21:49,914] - ==> [2018-07-21 10:21:49 913] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-07-21 10:21:49,960] - TCPPacketReceiver::processPendingEvents(192.168.0.106:49956): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-07-21 10:21:49,960] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-07-21 10:21:49,961] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-07-21 10:21:49,961] - onLoginAppShutDown()
  INFO root [2018-07-21 10:21:49,961] - Shutdowner::onShutdown: shutting down
  INFO root [2018-07-21 10:21:49,961] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-07-21 10:21:49,962] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-07-21 10:21:49,962] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-07-21 10:21:49,962] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-07-21 10:21:49,962] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-07-21 10:21:49,962] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-07-21 10:21:49,962] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-07-21 10:21:49,962] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-07-21 10:21:49,962] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-07-21 10:21:49,971] - Script::uninstall(): is successfully!
 DEBUG root [2018-07-21 10:21:49,971] - ThreadPool::destroy(): starting size 2.
  INFO root [2018-07-21 10:21:51,057] - 
  INFO root [2018-07-21 10:21:51,059] - -----------------------------------------------------------------------------------------


  INFO root [2018-07-21 10:21:51,059] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [2018-07-21 10:21:51,059] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [2018-07-21 10:21:51,060] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [2018-07-21 10:21:51,065] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:20013 )
  INFO root [2018-07-21 10:21:51,065] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.106:20013, SOMAXCONN=128.
  INFO root [2018-07-21 10:21:51,067] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:50016 )
  INFO root [2018-07-21 10:21:51,067] - NetworkInterface::initialize(INTERNAL): address 192.168.0.106:50016, SOMAXCONN=128.
  INFO root [2018-07-21 10:21:51,067] - server-configs:
  INFO root [2018-07-21 10:21:51,068] - 	internalAddr : 192.168.0.106:50016
  INFO root [2018-07-21 10:21:51,068] - 	externalAddr : 192.168.0.106:20013
  INFO root [2018-07-21 10:21:51,068] - 	componentID : 9000
  INFO root [2018-07-21 10:21:51,428] - Components::findLogger: found logger, addr:192.168.0.106:50010
  INFO root [2018-07-21 10:21:51,429] - Components::addComponent: reset orderLog, uid=10488!
  INFO root [2018-07-21 10:21:51,429] - Components::addComponent[logger], uid=10488, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-07-21 10:21:51,433] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: B20F257E332779D9E1EA7D34638E6146. Config: Debug X86. Built: 15:53:07 Apr 29 2018. AppID: 9000. UID: 10488. PID: 3724 ----
  INFO root [2018-07-21 10:21:51,433] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [2018-07-21 10:21:51,433] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-07-21 10:21:51,434] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-07-21 10:21:51,556] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-07-21 10:21:51,557] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-07-21 10:21:51,557] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-07-21 10:21:51,560] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-07-21 10:21:51,560] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-07-21 10:21:51,560] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-07-21 10:21:51,561] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-07-21 10:21:51,588] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-07-21 10:21:51,615] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-07-21 10:21:51,615] - Script::install(): KBExtra is successfully!
S_INFO root [2018-07-21 10:21:51,617] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-07-21 10:21:51,618] - TelnetServer server is running on port 31000
  INFO root [2018-07-21 10:21:51,897] - ---- loginapp is running ----
 DEBUG root [2018-07-21 10:21:51,898] - Components::process(): Request for the process of identity...
  WARN root [2018-07-21 10:21:57,989] - Forwarding logs to logger[192.168.0.106:50010/0/0/0]...
 ERROR root [2018-07-21 10:23:53,586] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-07-21 10:23:53,589] - The following logs sent to logger failed:
  WARN root [2018-07-21 10:23:53,590] - ==> [2018-07-21 10:23:53 584] TCPPacketReceiver::processPendingEvents(192.168.0.106:50010): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-07-21 10:23:53,590] - ==> [2018-07-21 10:23:53 586] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-07-21 10:23:53,633] - TCPPacketReceiver::processPendingEvents(192.168.0.106:50011): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-07-21 10:23:53,634] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-07-21 10:23:53,637] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-07-21 10:23:53,638] - onLoginAppShutDown()
  INFO root [2018-07-21 10:23:53,638] - Shutdowner::onShutdown: shutting down
  INFO root [2018-07-21 10:23:53,638] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-07-21 10:23:53,638] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-07-21 10:23:53,638] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-07-21 10:23:53,638] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-07-21 10:23:53,639] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-07-21 10:23:53,639] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-07-21 10:23:53,639] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-07-21 10:23:53,639] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-07-21 10:23:53,639] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-07-21 10:23:53,647] - Script::uninstall(): is successfully!
 DEBUG root [2018-07-21 10:23:53,647] - ThreadPool::destroy(): starting size 2.
  INFO root [2018-07-21 10:23:54,716] - 
  INFO root [2018-07-21 10:23:54,716] - -----------------------------------------------------------------------------------------


  INFO root [2018-07-21 10:23:54,717] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [2018-07-21 10:23:54,717] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [2018-07-21 10:23:54,717] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [2018-07-21 10:23:54,721] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:20013 )
  INFO root [2018-07-21 10:23:54,721] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.106:20013, SOMAXCONN=128.
  INFO root [2018-07-21 10:23:54,724] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:50063 )
  INFO root [2018-07-21 10:23:54,724] - NetworkInterface::initialize(INTERNAL): address 192.168.0.106:50063, SOMAXCONN=128.
  INFO root [2018-07-21 10:23:54,724] - server-configs:
  INFO root [2018-07-21 10:23:54,725] - 	internalAddr : 192.168.0.106:50063
  INFO root [2018-07-21 10:23:54,725] - 	externalAddr : 192.168.0.106:20013
  INFO root [2018-07-21 10:23:54,725] - 	componentID : 9000
  INFO root [2018-07-21 10:23:56,415] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: B20F257E332779D9E1EA7D34638E6146. Config: Debug X86. Built: 15:53:07 Apr 29 2018. AppID: 9000. UID: 10892. PID: 7440 ----
  INFO root [2018-07-21 10:23:56,415] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [2018-07-21 10:23:56,416] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-07-21 10:23:56,416] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-07-21 10:23:56,540] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-07-21 10:23:56,540] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-07-21 10:23:56,541] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-07-21 10:23:56,543] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-07-21 10:23:56,544] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-07-21 10:23:56,544] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-07-21 10:23:56,544] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-07-21 10:23:56,577] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-07-21 10:23:56,612] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-07-21 10:23:56,612] - Script::install(): KBExtra is successfully!
S_INFO root [2018-07-21 10:23:56,614] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-07-21 10:23:56,614] - TelnetServer server is running on port 31000
  INFO root [2018-07-21 10:23:56,925] - ---- loginapp is running ----
 DEBUG root [2018-07-21 10:23:56,925] - Components::process(): Request for the process of identity...
  INFO root [2018-07-21 10:24:04,034] - Components::findComponents: find logger(1)...
  INFO root [2018-07-21 10:24:04,117] - Components::findComponents: found logger, addr:192.168.0.106:50062
  INFO root [2018-07-21 10:24:04,117] - Components::addComponent: reset orderLog, uid=10892!
  INFO root [2018-07-21 10:24:04,118] - Components::addComponent[logger], uid=10892, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-07-21 10:24:04,120] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-07-21 10:24:04,225] - Components::findComponents: found dbmgr, addr:192.168.0.106:50064
  INFO root [2018-07-21 10:24:04,226] - Components::addComponent: reset orderLog, uid=10892!
  INFO root [2018-07-21 10:24:04,226] - Components::addComponent[dbmgr], uid=10892, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-07-21 10:24:04,227] - Components::findComponents: found dbmgr, addr:192.168.0.106:50064
  WARN root [2018-07-21 10:24:05,227] - Forwarding logs to logger[192.168.0.106:50062/0/0/0]...
 ERROR root [2018-07-21 10:27:09,247] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-07-21 10:27:09,250] - The following logs sent to logger failed:
  WARN root [2018-07-21 10:27:09,250] - ==> [2018-07-21 10:27:09 246] TCPPacketReceiver::processPendingEvents(192.168.0.106:50062): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-07-21 10:27:09,250] - ==> [2018-07-21 10:27:09 248] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-07-21 10:27:09,293] - TCPPacketReceiver::processPendingEvents(192.168.0.106:50064): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-07-21 10:27:09,294] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-07-21 10:27:09,294] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-07-21 10:27:09,295] - onLoginAppShutDown()
  INFO root [2018-07-21 10:27:09,295] - Shutdowner::onShutdown: shutting down
  INFO root [2018-07-21 10:27:09,295] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-07-21 10:27:09,295] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-07-21 10:27:09,295] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-07-21 10:27:09,295] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-07-21 10:27:09,295] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-07-21 10:27:09,296] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-07-21 10:27:09,296] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-07-21 10:27:09,296] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-07-21 10:27:09,296] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-07-21 10:27:09,304] - Script::uninstall(): is successfully!
 DEBUG root [2018-07-21 10:27:09,304] - ThreadPool::destroy(): starting size 2.
  INFO root [2018-07-21 10:27:10,377] - 
  INFO root [2018-07-21 10:27:10,379] - -----------------------------------------------------------------------------------------


  INFO root [2018-07-21 10:27:10,380] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [2018-07-21 10:27:10,380] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [2018-07-21 10:27:10,380] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [2018-07-21 10:27:10,391] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:20013 )
  INFO root [2018-07-21 10:27:10,391] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.106:20013, SOMAXCONN=128.
  INFO root [2018-07-21 10:27:10,392] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:50124 )
  INFO root [2018-07-21 10:27:10,393] - NetworkInterface::initialize(INTERNAL): address 192.168.0.106:50124, SOMAXCONN=128.
  INFO root [2018-07-21 10:27:10,393] - server-configs:
  INFO root [2018-07-21 10:27:10,393] - 	internalAddr : 192.168.0.106:50124
  INFO root [2018-07-21 10:27:10,393] - 	externalAddr : 192.168.0.106:20013
  INFO root [2018-07-21 10:27:10,393] - 	componentID : 9000
  INFO root [2018-07-21 10:27:12,124] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: B20F257E332779D9E1EA7D34638E6146. Config: Debug X86. Built: 15:53:07 Apr 29 2018. AppID: 9000. UID: 11533. PID: 9888 ----
  INFO root [2018-07-21 10:27:12,125] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [2018-07-21 10:27:12,125] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-07-21 10:27:12,125] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-07-21 10:27:12,248] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-07-21 10:27:12,249] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-07-21 10:27:12,249] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-07-21 10:27:12,252] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-07-21 10:27:12,252] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-07-21 10:27:12,252] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-07-21 10:27:12,253] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-07-21 10:27:12,280] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-07-21 10:27:12,307] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-07-21 10:27:12,307] - Script::install(): KBExtra is successfully!
S_INFO root [2018-07-21 10:27:12,309] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-07-21 10:27:12,309] - TelnetServer server is running on port 31000
  INFO root [2018-07-21 10:27:12,598] - ---- loginapp is running ----
 DEBUG root [2018-07-21 10:27:12,598] - Components::process(): Request for the process of identity...
  INFO root [2018-07-21 10:27:19,682] - Components::findComponents: find logger(1)...
  INFO root [2018-07-21 10:27:19,700] - Components::findComponents: found logger, addr:192.168.0.106:50123
  INFO root [2018-07-21 10:27:19,700] - Components::addComponent: reset orderLog, uid=11533!
  INFO root [2018-07-21 10:27:19,700] - Components::addComponent[logger], uid=11533, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-07-21 10:27:19,701] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-07-21 10:27:19,809] - Components::findComponents: found dbmgr, addr:192.168.0.106:50126
  INFO root [2018-07-21 10:27:19,809] - Components::addComponent: reset orderLog, uid=11533!
  INFO root [2018-07-21 10:27:19,809] - Components::addComponent[dbmgr], uid=11533, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-07-21 10:27:19,809] - Components::findComponents: found dbmgr, addr:192.168.0.106:50126
  WARN root [2018-07-21 10:27:20,809] - Forwarding logs to logger[192.168.0.106:50123/0/0/0]...
 ERROR root [2018-07-21 10:30:37,203] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-07-21 10:30:37,208] - The following logs sent to logger failed:
  WARN root [2018-07-21 10:30:37,208] - ==> [2018-07-21 10:30:37 202] TCPPacketReceiver::processPendingEvents(192.168.0.106:50123): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-07-21 10:30:37,208] - ==> [2018-07-21 10:30:37 204] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-07-21 10:30:37,252] - TCPPacketReceiver::processPendingEvents(192.168.0.106:50126): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-07-21 10:30:37,254] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-07-21 10:30:37,257] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-07-21 10:30:37,258] - onLoginAppShutDown()
  INFO root [2018-07-21 10:30:37,258] - Shutdowner::onShutdown: shutting down
  INFO root [2018-07-21 10:30:37,258] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-07-21 10:30:37,258] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-07-21 10:30:37,258] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-07-21 10:30:37,258] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-07-21 10:30:37,259] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-07-21 10:30:37,259] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-07-21 10:30:37,259] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-07-21 10:30:37,259] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-07-21 10:30:37,259] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-07-21 10:30:37,267] - Script::uninstall(): is successfully!
 DEBUG root [2018-07-21 10:30:37,267] - ThreadPool::destroy(): starting size 2.
  INFO root [2018-07-21 10:30:38,377] - 
  INFO root [2018-07-21 10:30:38,377] - -----------------------------------------------------------------------------------------


  INFO root [2018-07-21 10:30:38,378] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [2018-07-21 10:30:38,378] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [2018-07-21 10:30:38,378] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [2018-07-21 10:30:38,380] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:20013 )
  INFO root [2018-07-21 10:30:38,380] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.106:20013, SOMAXCONN=128.
  INFO root [2018-07-21 10:30:38,381] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:50196 )
  INFO root [2018-07-21 10:30:38,381] - NetworkInterface::initialize(INTERNAL): address 192.168.0.106:50196, SOMAXCONN=128.
  INFO root [2018-07-21 10:30:38,381] - server-configs:
  INFO root [2018-07-21 10:30:38,382] - 	internalAddr : 192.168.0.106:50196
  INFO root [2018-07-21 10:30:38,382] - 	externalAddr : 192.168.0.106:20013
  INFO root [2018-07-21 10:30:38,382] - 	componentID : 9000
  INFO root [2018-07-21 10:30:40,115] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: B20F257E332779D9E1EA7D34638E6146. Config: Debug X86. Built: 15:53:07 Apr 29 2018. AppID: 9000. UID: 12212. PID: 7696 ----
  INFO root [2018-07-21 10:30:40,115] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [2018-07-21 10:30:40,116] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-07-21 10:30:40,116] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-07-21 10:30:40,244] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-07-21 10:30:40,245] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-07-21 10:30:40,245] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-07-21 10:30:40,250] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-07-21 10:30:40,250] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-07-21 10:30:40,250] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-07-21 10:30:40,250] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-07-21 10:30:40,283] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-07-21 10:30:40,311] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-07-21 10:30:40,312] - Script::install(): KBExtra is successfully!
S_INFO root [2018-07-21 10:30:40,313] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-07-21 10:30:40,314] - TelnetServer server is running on port 31000
  INFO root [2018-07-21 10:30:40,593] - ---- loginapp is running ----
 DEBUG root [2018-07-21 10:30:40,593] - Components::process(): Request for the process of identity...
  INFO root [2018-07-21 10:30:47,678] - Components::findComponents: find logger(1)...
  INFO root [2018-07-21 10:30:47,690] - Components::findComponents: found logger, addr:192.168.0.106:50190
  INFO root [2018-07-21 10:30:47,691] - Components::addComponent: reset orderLog, uid=12212!
  INFO root [2018-07-21 10:30:47,692] - Components::addComponent[logger], uid=12212, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-07-21 10:30:47,694] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-07-21 10:30:47,795] - Components::findComponents: found dbmgr, addr:192.168.0.106:50193
  INFO root [2018-07-21 10:30:47,796] - Components::addComponent: reset orderLog, uid=12212!
  INFO root [2018-07-21 10:30:47,797] - Components::addComponent[dbmgr], uid=12212, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-07-21 10:30:47,797] - Components::findComponents: found dbmgr, addr:192.168.0.106:50193
  WARN root [2018-07-21 10:30:48,797] - Forwarding logs to logger[192.168.0.106:50190/0/0/0]...
