  INFO root [2018-10-22 23:53:57,889] - 
  INFO root [2018-10-22 23:53:57,912] - -----------------------------------------------------------------------------------------


  INFO root [2018-10-22 23:53:58,933] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [2018-10-22 23:53:58,934] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [2018-10-22 23:53:58,934] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [2018-10-22 23:53:59,960] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.107 ( 192.168.0.107:20013 )
  INFO root [2018-10-22 23:54:00,029] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.107:20013, SOMAXCONN=128.
  INFO root [2018-10-22 23:54:00,033] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.107 ( 192.168.0.107:57607 )
  INFO root [2018-10-22 23:54:00,034] - NetworkInterface::initialize(INTERNAL): address 192.168.0.107:57607, SOMAXCONN=128.
  INFO root [2018-10-22 23:54:00,034] - server-configs:
  INFO root [2018-10-22 23:54:00,034] - 	internalAddr : 192.168.0.107:57607
  INFO root [2018-10-22 23:54:00,035] - 	externalAddr : 192.168.0.107:20013
  INFO root [2018-10-22 23:54:00,035] - 	externalCustomAddr : 125.69.101.43
  INFO root [2018-10-22 23:54:00,035] - 	componentID : 9000
  INFO root [2018-10-22 23:54:02,800] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: B20F257E332779D9E1EA7D34638E6146. Config: Debug X86. Built: 15:53:07 Apr 29 2018. AppID: 9000. UID: 30952. PID: 9920 ----
  INFO root [2018-10-22 23:54:02,802] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [2018-10-22 23:54:02,932] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-10-22 23:54:02,996] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-10-22 23:54:10,303] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-10-22 23:54:10,533] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-10-22 23:54:10,685] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-10-22 23:54:11,470] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-10-22 23:54:11,638] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-10-22 23:54:11,809] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-10-22 23:54:11,936] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-10-22 23:54:12,399] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-10-22 23:54:13,371] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-10-22 23:54:13,372] - Script::install(): KBExtra is successfully!
S_INFO root [2018-10-22 23:54:13,410] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-10-22 23:54:13,411] - TelnetServer server is running on port 31000
  INFO root [2018-10-22 23:54:13,901] - ---- loginapp is running ----
 DEBUG root [2018-10-22 23:54:13,902] - Components::process(): Request for the process of identity...
  WARN root [2018-10-22 23:54:20,508] - e:\kbengine\kbe\src\lib\network\event_dispatcher.cpp:153: Profile callSystemTimers took 0.36 seconds
  INFO root [2018-10-22 23:54:21,511] - Components::findComponents: find logger(1)...
  WARN root [2018-10-22 23:54:21,843] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20051, errorno=10048
  INFO root [2018-10-22 23:54:22,851] - Components::findComponents: find logger(2)...
  INFO root [2018-10-22 23:54:22,926] - Components::findComponents: found logger, addr:192.168.0.107:57611
  INFO root [2018-10-22 23:54:22,926] - Components::addComponent: reset orderLog, uid=30952!
  INFO root [2018-10-22 23:54:22,927] - Components::addComponent[logger], uid=30952, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-10-22 23:54:22,942] - Components::findComponents: find dbmgr(3)...
  INFO root [2018-10-22 23:54:23,030] - Components::findComponents: found dbmgr, addr:192.168.0.107:57613
  INFO root [2018-10-22 23:54:23,030] - Components::addComponent: reset orderLog, uid=30952!
  INFO root [2018-10-22 23:54:23,031] - Components::addComponent[dbmgr], uid=30952, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-10-22 23:54:23,031] - Components::findComponents: found dbmgr, addr:192.168.0.107:57613
  WARN root [2018-10-22 23:54:24,031] - Forwarding logs to logger[192.168.0.107:57611/0/0/0]...
 ERROR root [2018-10-22 23:54:53,352] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-10-22 23:54:53,355] - The following logs sent to logger failed:
  WARN root [2018-10-22 23:54:53,355] - ==> [2018-10-22 23:54:53 351] TCPPacketReceiver::processPendingEvents(192.168.0.107:57611): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-10-22 23:54:53,355] - ==> [2018-10-22 23:54:53 352] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-10-22 23:54:53,410] - TCPPacketReceiver::processPendingEvents(192.168.0.107:57613): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-10-22 23:54:53,410] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-10-22 23:54:53,414] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-10-22 23:54:53,416] - onLoginAppShutDown()
  INFO root [2018-10-22 23:54:53,416] - Shutdowner::onShutdown: shutting down
  INFO root [2018-10-22 23:54:53,416] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-10-22 23:54:53,416] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-10-22 23:54:53,416] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-10-22 23:54:53,416] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-10-22 23:54:53,416] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-10-22 23:54:53,416] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-10-22 23:54:53,416] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-10-22 23:54:53,416] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-10-22 23:54:53,417] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-10-22 23:54:53,435] - Script::uninstall(): is successfully!
 DEBUG root [2018-10-22 23:54:53,435] - ThreadPool::destroy(): starting size 2.
  INFO root [2018-10-22 23:54:54,542] - 
  INFO root [2018-10-22 23:54:54,542] - -----------------------------------------------------------------------------------------


  INFO root [2018-10-22 23:54:54,543] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [2018-10-22 23:54:54,543] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [2018-10-22 23:54:54,543] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [2018-10-22 23:54:54,547] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.107 ( 192.168.0.107:20013 )
  INFO root [2018-10-22 23:54:54,548] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.107:20013, SOMAXCONN=128.
  INFO root [2018-10-22 23:54:54,549] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.107 ( 192.168.0.107:57646 )
  INFO root [2018-10-22 23:54:54,550] - NetworkInterface::initialize(INTERNAL): address 192.168.0.107:57646, SOMAXCONN=128.
  INFO root [2018-10-22 23:54:54,550] - server-configs:
  INFO root [2018-10-22 23:54:54,550] - 	internalAddr : 192.168.0.107:57646
  INFO root [2018-10-22 23:54:54,550] - 	externalAddr : 192.168.0.107:20013
  INFO root [2018-10-22 23:54:54,550] - 	externalCustomAddr : 125.69.101.43
  INFO root [2018-10-22 23:54:54,550] - 	componentID : 9000
  INFO root [2018-10-22 23:54:56,240] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: B20F257E332779D9E1EA7D34638E6146. Config: Debug X86. Built: 15:53:07 Apr 29 2018. AppID: 9000. UID: 31138. PID: 8796 ----
  INFO root [2018-10-22 23:54:56,242] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [2018-10-22 23:54:56,242] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-10-22 23:54:56,242] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-10-22 23:54:56,376] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-10-22 23:54:56,376] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-10-22 23:54:56,377] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-10-22 23:54:56,381] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-10-22 23:54:56,381] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-10-22 23:54:56,381] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-10-22 23:54:56,382] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-10-22 23:54:56,424] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-10-22 23:54:56,463] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-10-22 23:54:56,464] - Script::install(): KBExtra is successfully!
S_INFO root [2018-10-22 23:54:56,465] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-10-22 23:54:56,466] - TelnetServer server is running on port 31000
  INFO root [2018-10-22 23:54:56,834] - ---- loginapp is running ----
 DEBUG root [2018-10-22 23:54:56,834] - Components::process(): Request for the process of identity...
  INFO root [2018-10-22 23:55:03,926] - Components::findComponents: find logger(1)...
  INFO root [2018-10-22 23:55:03,945] - Components::findComponents: found logger, addr:192.168.0.107:57649
  INFO root [2018-10-22 23:55:03,946] - Components::addComponent: reset orderLog, uid=31138!
  INFO root [2018-10-22 23:55:03,946] - Components::addComponent[logger], uid=31138, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-10-22 23:55:03,948] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-10-22 23:55:04,064] - Components::findComponents: found dbmgr, addr:192.168.0.107:57650
  INFO root [2018-10-22 23:55:04,065] - Components::addComponent: reset orderLog, uid=31138!
  INFO root [2018-10-22 23:55:04,066] - Components::addComponent[dbmgr], uid=31138, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-10-22 23:55:04,067] - Components::findComponents: found dbmgr, addr:192.168.0.107:57650
  WARN root [2018-10-22 23:55:05,067] - Forwarding logs to logger[192.168.0.107:57649/0/0/0]...
 ERROR root [2018-10-22 23:59:49,927] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-10-22 23:59:49,933] - The following logs sent to logger failed:
  WARN root [2018-10-22 23:59:49,933] - ==> [2018-10-22 23:59:49 927] TCPPacketReceiver::processPendingEvents(192.168.0.107:57649): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-10-22 23:59:49,933] - ==> [2018-10-22 23:59:49 927] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-10-22 23:59:49,979] - TCPPacketReceiver::processPendingEvents(192.168.0.107:57650): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-10-22 23:59:49,979] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-10-22 23:59:49,982] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-10-22 23:59:49,984] - onLoginAppShutDown()
  INFO root [2018-10-22 23:59:49,984] - Shutdowner::onShutdown: shutting down
  INFO root [2018-10-22 23:59:49,984] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-10-22 23:59:49,985] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-10-22 23:59:49,985] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-10-22 23:59:49,985] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-10-22 23:59:49,985] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-10-22 23:59:49,985] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-10-22 23:59:49,985] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-10-22 23:59:49,985] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-10-22 23:59:49,985] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-10-22 23:59:49,993] - Script::uninstall(): is successfully!
 DEBUG root [2018-10-22 23:59:49,993] - ThreadPool::destroy(): starting size 2.
  INFO root [2018-10-22 23:59:51,133] - 
  INFO root [2018-10-22 23:59:51,134] - -----------------------------------------------------------------------------------------


  INFO root [2018-10-22 23:59:51,134] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [2018-10-22 23:59:51,134] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [2018-10-22 23:59:51,134] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [2018-10-22 23:59:51,138] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.107 ( 192.168.0.107:20013 )
  INFO root [2018-10-22 23:59:51,139] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.107:20013, SOMAXCONN=128.
  INFO root [2018-10-22 23:59:51,140] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.107 ( 192.168.0.107:57708 )
  INFO root [2018-10-22 23:59:51,140] - NetworkInterface::initialize(INTERNAL): address 192.168.0.107:57708, SOMAXCONN=128.
  INFO root [2018-10-22 23:59:51,140] - server-configs:
  INFO root [2018-10-22 23:59:51,140] - 	internalAddr : 192.168.0.107:57708
  INFO root [2018-10-22 23:59:51,140] - 	externalAddr : 192.168.0.107:20013
  INFO root [2018-10-22 23:59:51,140] - 	componentID : 9000
  INFO root [2018-10-22 23:59:52,827] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: B20F257E332779D9E1EA7D34638E6146. Config: Debug X86. Built: 15:53:07 Apr 29 2018. AppID: 9000. UID: 32104. PID: 8840 ----
  INFO root [2018-10-22 23:59:52,828] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [2018-10-22 23:59:52,828] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-10-22 23:59:52,828] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-10-22 23:59:52,959] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-10-22 23:59:52,960] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-10-22 23:59:52,960] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-10-22 23:59:52,963] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-10-22 23:59:52,963] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-10-22 23:59:52,963] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-10-22 23:59:52,964] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-10-22 23:59:52,998] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-10-22 23:59:53,034] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-10-22 23:59:53,035] - Script::install(): KBExtra is successfully!
S_INFO root [2018-10-22 23:59:53,037] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-10-22 23:59:53,037] - TelnetServer server is running on port 31000
  INFO root [2018-10-22 23:59:53,382] - ---- loginapp is running ----
 DEBUG root [2018-10-22 23:59:53,383] - Components::process(): Request for the process of identity...
