  INFO root [2018-08-26 11:37:30,946] - 
  INFO root [2018-08-26 11:37:30,959] - -----------------------------------------------------------------------------------------


  INFO root [2018-08-26 11:37:31,487] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [2018-08-26 11:37:31,487] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [2018-08-26 11:37:31,487] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [2018-08-26 11:37:31,957] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:20013 )
  INFO root [2018-08-26 11:37:32,009] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.106:20013, SOMAXCONN=128.
  INFO root [2018-08-26 11:37:32,011] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:50297 )
  INFO root [2018-08-26 11:37:32,011] - NetworkInterface::initialize(INTERNAL): address 192.168.0.106:50297, SOMAXCONN=128.
  INFO root [2018-08-26 11:37:32,011] - server-configs:
  INFO root [2018-08-26 11:37:32,011] - 	internalAddr : 192.168.0.106:50297
  INFO root [2018-08-26 11:37:32,011] - 	externalAddr : 192.168.0.106:20013
  INFO root [2018-08-26 11:37:32,011] - 	componentID : 9000
  INFO root [2018-08-26 11:37:32,587] - Components::findLogger: found logger, addr:192.168.0.106:50288
  INFO root [2018-08-26 11:37:32,588] - Components::addComponent: reset orderLog, uid=24354!
  INFO root [2018-08-26 11:37:32,588] - Components::addComponent[logger], uid=24354, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-08-26 11:37:32,822] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: B20F257E332779D9E1EA7D34638E6146. Config: Debug X86. Built: 15:53:07 Apr 29 2018. AppID: 9000. UID: 24354. PID: 2724 ----
  INFO root [2018-08-26 11:37:32,823] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [2018-08-26 11:37:32,824] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-08-26 11:37:33,101] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-08-26 11:37:38,409] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-26 11:37:38,506] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-08-26 11:37:38,567] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-26 11:37:39,484] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-26 11:37:39,586] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-08-26 11:37:39,774] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-26 11:37:39,809] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-26 11:37:40,840] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-26 11:37:46,160] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-08-26 11:37:46,161] - Script::install(): KBExtra is successfully!
S_INFO root [2018-08-26 11:37:46,682] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-08-26 11:37:46,683] - TelnetServer server is running on port 31000
  WARN root [2018-08-26 11:37:46,683] - e:\kbengine\kbe\src\server\loginapp\loginapp.cpp:153: Profile scriptCall took 0.15 seconds
  INFO root [2018-08-26 11:37:47,964] - ---- loginapp is running ----
 DEBUG root [2018-08-26 11:37:47,967] - Components::process(): Request for the process of identity...
  WARN root [2018-08-26 11:37:54,570] - Forwarding logs to logger[192.168.0.106:50288/0/0/0]...
 ERROR root [2018-08-26 12:19:36,004] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-08-26 12:19:36,007] - The following logs sent to logger failed:
  WARN root [2018-08-26 12:19:36,007] - ==> [2018-08-26 12:19:36 003] TCPPacketReceiver::processPendingEvents(192.168.0.106:50288): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-26 12:19:36,007] - ==> [2018-08-26 12:19:36 005] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-08-26 12:19:36,059] - TCPPacketReceiver::processPendingEvents(192.168.0.106:50291): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-26 12:19:36,060] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-08-26 12:19:36,065] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-08-26 12:19:36,066] - onLoginAppShutDown()
  INFO root [2018-08-26 12:19:36,066] - Shutdowner::onShutdown: shutting down
  INFO root [2018-08-26 12:19:36,066] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-08-26 12:19:36,066] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-26 12:19:36,067] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-08-26 12:19:36,067] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-26 12:19:36,067] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-26 12:19:36,067] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-08-26 12:19:36,067] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-26 12:19:36,067] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-26 12:19:36,067] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-26 12:19:36,118] - Script::uninstall(): is successfully!
 DEBUG root [2018-08-26 12:19:36,118] - ThreadPool::destroy(): starting size 2.
  INFO root [2018-08-26 12:19:37,236] - 
  INFO root [2018-08-26 12:19:37,236] - -----------------------------------------------------------------------------------------


  INFO root [2018-08-26 12:19:37,237] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [2018-08-26 12:19:37,237] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [2018-08-26 12:19:37,237] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [2018-08-26 12:19:37,240] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:20013 )
  INFO root [2018-08-26 12:19:37,241] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.106:20013, SOMAXCONN=128.
  INFO root [2018-08-26 12:19:37,243] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:57440 )
  INFO root [2018-08-26 12:19:37,244] - NetworkInterface::initialize(INTERNAL): address 192.168.0.106:57440, SOMAXCONN=128.
  INFO root [2018-08-26 12:19:37,244] - server-configs:
  INFO root [2018-08-26 12:19:37,244] - 	internalAddr : 192.168.0.106:57440
  INFO root [2018-08-26 12:19:37,244] - 	externalAddr : 192.168.0.106:20013
  INFO root [2018-08-26 12:19:37,244] - 	componentID : 9000
  INFO root [2018-08-26 12:19:38,956] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: B20F257E332779D9E1EA7D34638E6146. Config: Debug X86. Built: 15:53:07 Apr 29 2018. AppID: 9000. UID: 32740. PID: 8416 ----
  INFO root [2018-08-26 12:19:38,957] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [2018-08-26 12:19:38,957] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-08-26 12:19:38,957] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-08-26 12:19:39,091] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-26 12:19:39,092] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-08-26 12:19:39,093] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-26 12:19:39,097] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-26 12:19:39,097] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-08-26 12:19:39,097] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-26 12:19:39,098] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-26 12:19:39,133] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-26 12:19:39,172] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-08-26 12:19:39,172] - Script::install(): KBExtra is successfully!
S_INFO root [2018-08-26 12:19:39,173] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-08-26 12:19:39,174] - TelnetServer server is running on port 31000
  INFO root [2018-08-26 12:19:39,479] - ---- loginapp is running ----
 DEBUG root [2018-08-26 12:19:39,479] - Components::process(): Request for the process of identity...
  INFO root [2018-08-26 12:19:46,574] - Components::findComponents: find logger(1)...
  INFO root [2018-08-26 12:19:46,649] - Components::findComponents: found logger, addr:192.168.0.106:57436
  INFO root [2018-08-26 12:19:46,650] - Components::addComponent: reset orderLog, uid=32740!
  INFO root [2018-08-26 12:19:46,651] - Components::addComponent[logger], uid=32740, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-08-26 12:19:46,653] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-08-26 12:19:46,754] - Components::findComponents: found dbmgr, addr:192.168.0.106:57437
  INFO root [2018-08-26 12:19:46,755] - Components::addComponent: reset orderLog, uid=32740!
  INFO root [2018-08-26 12:19:46,755] - Components::addComponent[dbmgr], uid=32740, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-08-26 12:19:46,756] - Components::findComponents: found dbmgr, addr:192.168.0.106:57437
  WARN root [2018-08-26 12:19:47,756] - Forwarding logs to logger[192.168.0.106:57436/0/0/0]...
 ERROR root [2018-08-26 16:02:21,403] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-08-26 16:02:21,413] - The following logs sent to logger failed:
  WARN root [2018-08-26 16:02:21,413] - ==> [2018-08-26 16:02:21 401] TCPPacketReceiver::processPendingEvents(192.168.0.106:57436): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-26 16:02:21,413] - ==> [2018-08-26 16:02:21 403] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-08-26 16:02:21,467] - TCPPacketReceiver::processPendingEvents(192.168.0.106:57437): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-26 16:02:21,471] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-08-26 16:02:21,475] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-08-26 16:02:21,479] - onLoginAppShutDown()
  INFO root [2018-08-26 16:02:21,479] - Shutdowner::onShutdown: shutting down
  INFO root [2018-08-26 16:02:21,479] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-08-26 16:02:21,479] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-26 16:02:21,479] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-08-26 16:02:21,479] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-26 16:02:21,479] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-26 16:02:21,479] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-08-26 16:02:21,480] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-26 16:02:21,480] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-26 16:02:21,480] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-26 16:02:21,487] - Script::uninstall(): is successfully!
 DEBUG root [2018-08-26 16:02:21,487] - ThreadPool::destroy(): starting size 2.
  INFO root [2018-08-26 16:02:22,672] - 
  INFO root [2018-08-26 16:02:22,672] - -----------------------------------------------------------------------------------------


  INFO root [2018-08-26 16:02:22,673] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [2018-08-26 16:02:22,673] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [2018-08-26 16:02:22,673] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [2018-08-26 16:02:22,680] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:20013 )
  INFO root [2018-08-26 16:02:22,680] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.106:20013, SOMAXCONN=128.
  INFO root [2018-08-26 16:02:22,682] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:58923 )
  INFO root [2018-08-26 16:02:22,682] - NetworkInterface::initialize(INTERNAL): address 192.168.0.106:58923, SOMAXCONN=128.
  INFO root [2018-08-26 16:02:22,682] - server-configs:
  INFO root [2018-08-26 16:02:22,682] - 	internalAddr : 192.168.0.106:58923
  INFO root [2018-08-26 16:02:22,682] - 	externalAddr : 192.168.0.106:20013
  INFO root [2018-08-26 16:02:22,682] - 	componentID : 9000
  INFO root [2018-08-26 16:02:24,409] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: B20F257E332779D9E1EA7D34638E6146. Config: Debug X86. Built: 15:53:07 Apr 29 2018. AppID: 9000. UID: 10851. PID: 14036 ----
  INFO root [2018-08-26 16:02:24,409] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [2018-08-26 16:02:24,410] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-08-26 16:02:24,410] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-08-26 16:02:24,534] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-26 16:02:24,534] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-08-26 16:02:24,534] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-26 16:02:24,537] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-26 16:02:24,538] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-08-26 16:02:24,538] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-26 16:02:24,539] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-26 16:02:24,567] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-26 16:02:24,597] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-08-26 16:02:24,598] - Script::install(): KBExtra is successfully!
S_INFO root [2018-08-26 16:02:24,600] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-08-26 16:02:24,600] - TelnetServer server is running on port 31000
  INFO root [2018-08-26 16:02:24,879] - ---- loginapp is running ----
 DEBUG root [2018-08-26 16:02:24,879] - Components::process(): Request for the process of identity...
  INFO root [2018-08-26 16:02:31,961] - Components::findComponents: find logger(1)...
  INFO root [2018-08-26 16:02:32,030] - Components::findComponents: found logger, addr:192.168.0.106:58921
  INFO root [2018-08-26 16:02:32,031] - Components::addComponent: reset orderLog, uid=10851!
  INFO root [2018-08-26 16:02:32,032] - Components::addComponent[logger], uid=10851, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-08-26 16:02:32,034] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-08-26 16:02:32,136] - Components::findComponents: found dbmgr, addr:192.168.0.106:58928
  INFO root [2018-08-26 16:02:32,136] - Components::addComponent: reset orderLog, uid=10851!
  INFO root [2018-08-26 16:02:32,137] - Components::addComponent[dbmgr], uid=10851, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-08-26 16:02:32,137] - Components::findComponents: found dbmgr, addr:192.168.0.106:58928
  WARN root [2018-08-26 16:02:33,138] - Forwarding logs to logger[192.168.0.106:58921/0/0/0]...
 ERROR root [2018-08-26 16:16:27,144] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-08-26 16:16:27,148] - The following logs sent to logger failed:
  WARN root [2018-08-26 16:16:27,148] - ==> [2018-08-26 16:16:27 141] TCPPacketReceiver::processPendingEvents(192.168.0.106:58921): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-26 16:16:27,148] - ==> [2018-08-26 16:16:27 144] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-08-26 16:16:27,204] - TCPPacketReceiver::processPendingEvents(192.168.0.106:58928): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-26 16:16:27,207] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-08-26 16:16:27,217] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-08-26 16:16:27,217] - onLoginAppShutDown()
  INFO root [2018-08-26 16:16:27,217] - Shutdowner::onShutdown: shutting down
  INFO root [2018-08-26 16:16:27,217] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-08-26 16:16:27,218] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-26 16:16:27,218] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-08-26 16:16:27,218] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-26 16:16:27,218] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-26 16:16:27,218] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-08-26 16:16:27,218] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-26 16:16:27,218] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-26 16:16:27,218] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-26 16:16:27,226] - Script::uninstall(): is successfully!
 DEBUG root [2018-08-26 16:16:27,226] - ThreadPool::destroy(): starting size 2.
  INFO root [2018-08-26 16:16:28,415] - 
  INFO root [2018-08-26 16:16:28,415] - -----------------------------------------------------------------------------------------


  INFO root [2018-08-26 16:16:28,416] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [2018-08-26 16:16:28,416] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [2018-08-26 16:16:28,416] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [2018-08-26 16:16:28,420] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:20013 )
  INFO root [2018-08-26 16:16:28,420] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.106:20013, SOMAXCONN=128.
  INFO root [2018-08-26 16:16:28,424] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:59070 )
  INFO root [2018-08-26 16:16:28,424] - NetworkInterface::initialize(INTERNAL): address 192.168.0.106:59070, SOMAXCONN=128.
  INFO root [2018-08-26 16:16:28,424] - server-configs:
  INFO root [2018-08-26 16:16:28,424] - 	internalAddr : 192.168.0.106:59070
  INFO root [2018-08-26 16:16:28,424] - 	externalAddr : 192.168.0.106:20013
  INFO root [2018-08-26 16:16:28,424] - 	componentID : 9000
  WARN root [2018-08-26 16:16:28,954] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20543, errorno=10048
  INFO root [2018-08-26 16:16:28,959] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: B20F257E332779D9E1EA7D34638E6146. Config: Debug X86. Built: 15:53:07 Apr 29 2018. AppID: 9000. UID: 13614. PID: 5812 ----
  INFO root [2018-08-26 16:16:28,959] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [2018-08-26 16:16:28,959] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-08-26 16:16:28,960] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-08-26 16:16:29,086] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-26 16:16:29,086] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-08-26 16:16:29,087] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-26 16:16:29,090] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-26 16:16:29,091] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-08-26 16:16:29,091] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-26 16:16:29,092] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-26 16:16:29,122] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-26 16:16:29,150] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-08-26 16:16:29,150] - Script::install(): KBExtra is successfully!
S_INFO root [2018-08-26 16:16:29,152] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-08-26 16:16:29,152] - TelnetServer server is running on port 31000
  INFO root [2018-08-26 16:16:29,438] - ---- loginapp is running ----
 DEBUG root [2018-08-26 16:16:29,438] - Components::process(): Request for the process of identity...
  INFO root [2018-08-26 16:16:36,552] - Components::findComponents: find logger(1)...
  INFO root [2018-08-26 16:16:36,572] - Components::findComponents: found logger, addr:192.168.0.106:59075
  INFO root [2018-08-26 16:16:36,572] - Components::addComponent: reset orderLog, uid=13614!
  INFO root [2018-08-26 16:16:36,573] - Components::addComponent[logger], uid=13614, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-08-26 16:16:36,574] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-08-26 16:16:36,676] - Components::findComponents: found dbmgr, addr:192.168.0.106:59067
  INFO root [2018-08-26 16:16:36,676] - Components::addComponent: reset orderLog, uid=13614!
  INFO root [2018-08-26 16:16:36,677] - Components::addComponent[dbmgr], uid=13614, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-08-26 16:16:36,677] - Components::findComponents: found dbmgr, addr:192.168.0.106:59067
  WARN root [2018-08-26 16:16:37,677] - Forwarding logs to logger[192.168.0.106:59075/0/0/0]...
 ERROR root [2018-08-26 16:34:00,943] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-08-26 16:34:00,954] - The following logs sent to logger failed:
  WARN root [2018-08-26 16:34:00,954] - ==> [2018-08-26 16:34:00 941] TCPPacketReceiver::processPendingEvents(192.168.0.106:59075): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-26 16:34:00,954] - ==> [2018-08-26 16:34:00 944] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-08-26 16:34:01,006] - TCPPacketReceiver::processPendingEvents(192.168.0.106:59067): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-26 16:34:01,011] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-08-26 16:34:01,023] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-08-26 16:34:01,024] - onLoginAppShutDown()
  INFO root [2018-08-26 16:34:01,024] - Shutdowner::onShutdown: shutting down
  INFO root [2018-08-26 16:34:01,024] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-08-26 16:34:01,025] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-26 16:34:01,025] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-08-26 16:34:01,025] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-26 16:34:01,025] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-26 16:34:01,025] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-08-26 16:34:01,025] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-26 16:34:01,025] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-26 16:34:01,025] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-26 16:34:01,033] - Script::uninstall(): is successfully!
 DEBUG root [2018-08-26 16:34:01,033] - ThreadPool::destroy(): starting size 2.
  INFO root [2018-08-26 16:34:02,290] - 
  INFO root [2018-08-26 16:34:02,291] - -----------------------------------------------------------------------------------------


  INFO root [2018-08-26 16:34:02,292] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [2018-08-26 16:34:02,292] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [2018-08-26 16:34:02,292] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [2018-08-26 16:34:02,296] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:20013 )
  INFO root [2018-08-26 16:34:02,296] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.106:20013, SOMAXCONN=128.
  INFO root [2018-08-26 16:34:02,298] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:59241 )
  INFO root [2018-08-26 16:34:02,298] - NetworkInterface::initialize(INTERNAL): address 192.168.0.106:59241, SOMAXCONN=128.
  INFO root [2018-08-26 16:34:02,298] - server-configs:
  INFO root [2018-08-26 16:34:02,298] - 	internalAddr : 192.168.0.106:59241
  INFO root [2018-08-26 16:34:02,298] - 	externalAddr : 192.168.0.106:20013
  INFO root [2018-08-26 16:34:02,298] - 	componentID : 9000
  WARN root [2018-08-26 16:34:02,826] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20432, errorno=10048
  INFO root [2018-08-26 16:34:02,829] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: B20F257E332779D9E1EA7D34638E6146. Config: Debug X86. Built: 15:53:07 Apr 29 2018. AppID: 9000. UID: 17053. PID: 4936 ----
  INFO root [2018-08-26 16:34:02,830] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [2018-08-26 16:34:02,830] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-08-26 16:34:02,830] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-08-26 16:34:02,957] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-26 16:34:02,958] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-08-26 16:34:02,959] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-26 16:34:02,962] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-26 16:34:02,962] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-08-26 16:34:02,962] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-26 16:34:02,962] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-26 16:34:02,994] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-26 16:34:03,023] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-08-26 16:34:03,023] - Script::install(): KBExtra is successfully!
S_INFO root [2018-08-26 16:34:03,025] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-08-26 16:34:03,025] - TelnetServer server is running on port 31000
  INFO root [2018-08-26 16:34:03,309] - ---- loginapp is running ----
 DEBUG root [2018-08-26 16:34:03,309] - Components::process(): Request for the process of identity...
  INFO root [2018-08-26 16:34:10,425] - Components::findComponents: find logger(1)...
  INFO root [2018-08-26 16:34:10,494] - Components::findComponents: found logger, addr:192.168.0.106:59240
  INFO root [2018-08-26 16:34:10,495] - Components::addComponent: reset orderLog, uid=17053!
  INFO root [2018-08-26 16:34:10,495] - Components::addComponent[logger], uid=17053, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-08-26 16:34:10,497] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-08-26 16:34:10,599] - Components::findComponents: found dbmgr, addr:192.168.0.106:59236
  INFO root [2018-08-26 16:34:10,599] - Components::addComponent: reset orderLog, uid=17053!
  INFO root [2018-08-26 16:34:10,599] - Components::addComponent[dbmgr], uid=17053, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-08-26 16:34:10,600] - Components::findComponents: found dbmgr, addr:192.168.0.106:59236
  WARN root [2018-08-26 16:34:11,600] - Forwarding logs to logger[192.168.0.106:59240/0/0/0]...
 ERROR root [2018-08-26 16:34:19,265] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-08-26 16:34:19,276] - The following logs sent to logger failed:
  WARN root [2018-08-26 16:34:19,276] - ==> [2018-08-26 16:34:19 262] TCPPacketReceiver::processPendingEvents(192.168.0.106:59240): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-26 16:34:19,276] - ==> [2018-08-26 16:34:19 266] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-08-26 16:34:19,332] - TCPPacketReceiver::processPendingEvents(192.168.0.106:59236): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-26 16:34:19,337] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-08-26 16:34:19,345] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-08-26 16:34:19,346] - onLoginAppShutDown()
  INFO root [2018-08-26 16:34:19,346] - Shutdowner::onShutdown: shutting down
  INFO root [2018-08-26 16:34:19,347] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-08-26 16:34:19,347] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-26 16:34:19,347] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-08-26 16:34:19,347] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-26 16:34:19,347] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-26 16:34:19,347] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-08-26 16:34:19,347] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-26 16:34:19,347] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-26 16:34:19,347] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-26 16:34:19,355] - Script::uninstall(): is successfully!
 DEBUG root [2018-08-26 16:34:19,355] - ThreadPool::destroy(): starting size 2.
  INFO root [2018-08-26 16:34:20,612] - 
  INFO root [2018-08-26 16:34:20,612] - -----------------------------------------------------------------------------------------


  INFO root [2018-08-26 16:34:20,612] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [2018-08-26 16:34:20,613] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [2018-08-26 16:34:20,613] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [2018-08-26 16:34:20,617] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:20013 )
  INFO root [2018-08-26 16:34:20,617] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.106:20013, SOMAXCONN=128.
  INFO root [2018-08-26 16:34:20,619] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:59288 )
  INFO root [2018-08-26 16:34:20,619] - NetworkInterface::initialize(INTERNAL): address 192.168.0.106:59288, SOMAXCONN=128.
  INFO root [2018-08-26 16:34:20,619] - server-configs:
  INFO root [2018-08-26 16:34:20,619] - 	internalAddr : 192.168.0.106:59288
  INFO root [2018-08-26 16:34:20,620] - 	externalAddr : 192.168.0.106:20013
  INFO root [2018-08-26 16:34:20,620] - 	componentID : 9000
  WARN root [2018-08-26 16:34:21,125] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20420, errorno=10048
  INFO root [2018-08-26 16:34:21,128] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: B20F257E332779D9E1EA7D34638E6146. Config: Debug X86. Built: 15:53:07 Apr 29 2018. AppID: 9000. UID: 17115. PID: 13364 ----
  INFO root [2018-08-26 16:34:21,129] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [2018-08-26 16:34:21,129] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-08-26 16:34:21,129] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-08-26 16:34:21,253] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-26 16:34:21,253] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-08-26 16:34:21,253] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-26 16:34:21,257] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-26 16:34:21,257] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-08-26 16:34:21,257] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-26 16:34:21,257] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-26 16:34:21,285] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-26 16:34:21,317] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-08-26 16:34:21,317] - Script::install(): KBExtra is successfully!
S_INFO root [2018-08-26 16:34:21,319] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-08-26 16:34:21,319] - TelnetServer server is running on port 31000
  INFO root [2018-08-26 16:34:21,602] - ---- loginapp is running ----
 DEBUG root [2018-08-26 16:34:21,602] - Components::process(): Request for the process of identity...
  INFO root [2018-08-26 16:34:28,739] - Components::findComponents: find logger(1)...
  INFO root [2018-08-26 16:34:28,796] - Components::findComponents: found logger, addr:192.168.0.106:59284
  INFO root [2018-08-26 16:34:28,797] - Components::addComponent: reset orderLog, uid=17115!
  INFO root [2018-08-26 16:34:28,797] - Components::addComponent[logger], uid=17115, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-08-26 16:34:28,797] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-08-26 16:34:28,904] - Components::findComponents: found dbmgr, addr:192.168.0.106:59283
  INFO root [2018-08-26 16:34:28,905] - Components::addComponent: reset orderLog, uid=17115!
  INFO root [2018-08-26 16:34:28,905] - Components::addComponent[dbmgr], uid=17115, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-08-26 16:34:28,905] - Components::findComponents: found dbmgr, addr:192.168.0.106:59283
  WARN root [2018-08-26 16:34:29,905] - Forwarding logs to logger[192.168.0.106:59284/0/0/0]...
