  INFO root [2018-08-22 15:09:59,780] - 
  INFO root [2018-08-22 15:09:59,808] - -----------------------------------------------------------------------------------------


  INFO root [2018-08-22 15:10:01,028] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [2018-08-22 15:10:01,028] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [2018-08-22 15:10:01,029] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [2018-08-22 15:10:01,948] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:20013 )
  INFO root [2018-08-22 15:10:01,977] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.106:20013, SOMAXCONN=128.
  INFO root [2018-08-22 15:10:01,982] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:60619 )
  INFO root [2018-08-22 15:10:01,983] - NetworkInterface::initialize(INTERNAL): address 192.168.0.106:60619, SOMAXCONN=128.
  INFO root [2018-08-22 15:10:01,983] - server-configs:
  INFO root [2018-08-22 15:10:01,983] - 	internalAddr : 192.168.0.106:60619
  INFO root [2018-08-22 15:10:01,984] - 	externalAddr : 192.168.0.106:20013
  INFO root [2018-08-22 15:10:01,984] - 	componentID : 9000
  INFO root [2018-08-22 15:10:02,569] - Components::findLogger: found logger, addr:192.168.0.106:60614
  INFO root [2018-08-22 15:10:02,570] - Components::addComponent: reset orderLog, uid=18805!
  INFO root [2018-08-22 15:10:02,570] - Components::addComponent[logger], uid=18805, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-08-22 15:10:02,689] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: B20F257E332779D9E1EA7D34638E6146. Config: Debug X86. Built: 15:53:07 Apr 29 2018. AppID: 9000. UID: 18805. PID: 5416 ----
  INFO root [2018-08-22 15:10:02,689] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [2018-08-22 15:10:02,690] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-08-22 15:10:02,727] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-08-22 15:10:09,008] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-22 15:10:09,789] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-08-22 15:10:09,907] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-22 15:10:10,568] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-22 15:10:10,669] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-08-22 15:10:10,757] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-22 15:10:10,866] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-22 15:10:11,596] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-22 15:10:13,359] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-08-22 15:10:13,360] - Script::install(): KBExtra is successfully!
S_INFO root [2018-08-22 15:10:13,549] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-08-22 15:10:13,549] - TelnetServer server is running on port 31000
  WARN root [2018-08-22 15:10:13,550] - e:\kbengine\kbe\src\server\loginapp\loginapp.cpp:153: Profile scriptCall took 0.15 seconds
  INFO root [2018-08-22 15:10:14,289] - ---- loginapp is running ----
 DEBUG root [2018-08-22 15:10:14,290] - Components::process(): Request for the process of identity...
  WARN root [2018-08-22 15:10:20,561] - Forwarding logs to logger[192.168.0.106:60614/0/0/0]...
 ERROR root [2018-08-22 15:10:28,761] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-08-22 15:10:28,762] - The following logs sent to logger failed:
  WARN root [2018-08-22 15:10:28,762] - ==> [2018-08-22 15:10:28 761] TCPPacketReceiver::processPendingEvents(192.168.0.106:60614): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-22 15:10:28,763] - ==> [2018-08-22 15:10:28 762] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-08-22 15:10:32,218] - 
  INFO root [2018-08-22 15:10:32,218] - -----------------------------------------------------------------------------------------


  INFO root [2018-08-22 15:10:32,219] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [2018-08-22 15:10:32,219] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [2018-08-22 15:10:32,219] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [2018-08-22 15:10:32,221] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:20013 )
  INFO root [2018-08-22 15:10:32,222] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.106:20013, SOMAXCONN=128.
  INFO root [2018-08-22 15:10:32,223] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:60633 )
  INFO root [2018-08-22 15:10:32,223] - NetworkInterface::initialize(INTERNAL): address 192.168.0.106:60633, SOMAXCONN=128.
  INFO root [2018-08-22 15:10:32,223] - server-configs:
  INFO root [2018-08-22 15:10:32,223] - 	internalAddr : 192.168.0.106:60633
  INFO root [2018-08-22 15:10:32,224] - 	externalAddr : 192.168.0.106:20013
  INFO root [2018-08-22 15:10:32,224] - 	componentID : 9000
  WARN root [2018-08-22 15:10:32,739] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20115, errorno=10048
  INFO root [2018-08-22 15:10:32,743] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: B20F257E332779D9E1EA7D34638E6146. Config: Debug X86. Built: 15:53:07 Apr 29 2018. AppID: 9000. UID: 18988. PID: 12852 ----
  INFO root [2018-08-22 15:10:32,744] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [2018-08-22 15:10:32,744] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-08-22 15:10:32,744] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-08-22 15:10:32,866] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-22 15:10:32,867] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-08-22 15:10:32,867] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-22 15:10:32,870] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-22 15:10:32,870] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-08-22 15:10:32,870] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-22 15:10:32,871] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-22 15:10:32,899] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-22 15:10:32,925] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-08-22 15:10:32,925] - Script::install(): KBExtra is successfully!
S_INFO root [2018-08-22 15:10:32,927] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-08-22 15:10:32,927] - TelnetServer server is running on port 31000
  INFO root [2018-08-22 15:10:33,200] - ---- loginapp is running ----
 DEBUG root [2018-08-22 15:10:33,200] - Components::process(): Request for the process of identity...
  INFO root [2018-08-22 15:10:40,308] - Components::findComponents: find logger(1)...
  INFO root [2018-08-22 15:10:40,392] - Components::findComponents: found logger, addr:192.168.0.106:60630
  INFO root [2018-08-22 15:10:40,392] - Components::addComponent: reset orderLog, uid=18988!
  INFO root [2018-08-22 15:10:40,393] - Components::addComponent[logger], uid=18988, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-08-22 15:10:40,395] - Components::findComponents: find dbmgr(2)...
  WARN root [2018-08-22 15:10:41,496] - Forwarding logs to logger[192.168.0.106:60630/0/0/0]...
  INFO root [2018-08-22 15:12:12,615] - 
  INFO root [2018-08-22 15:12:12,615] - -----------------------------------------------------------------------------------------


  INFO root [2018-08-22 15:12:12,616] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [2018-08-22 15:12:12,616] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [2018-08-22 15:12:12,616] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [2018-08-22 15:12:12,634] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:20013 )
  INFO root [2018-08-22 15:12:12,634] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.106:20013, SOMAXCONN=128.
  INFO root [2018-08-22 15:12:12,639] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:60647 )
  INFO root [2018-08-22 15:12:12,639] - NetworkInterface::initialize(INTERNAL): address 192.168.0.106:60647, SOMAXCONN=128.
  INFO root [2018-08-22 15:12:12,639] - server-configs:
  INFO root [2018-08-22 15:12:12,639] - 	internalAddr : 192.168.0.106:60647
  INFO root [2018-08-22 15:12:12,640] - 	externalAddr : 192.168.0.106:20013
  INFO root [2018-08-22 15:12:12,640] - 	componentID : 9000
  WARN root [2018-08-22 15:12:13,169] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20459, errorno=10048
  INFO root [2018-08-22 15:12:13,172] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: B20F257E332779D9E1EA7D34638E6146. Config: Debug X86. Built: 15:53:07 Apr 29 2018. AppID: 9000. UID: 19318. PID: 14272 ----
  INFO root [2018-08-22 15:12:13,173] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [2018-08-22 15:12:13,173] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-08-22 15:12:13,173] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-08-22 15:12:13,299] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-22 15:12:13,299] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-08-22 15:12:13,299] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-22 15:12:13,302] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-22 15:12:13,302] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-08-22 15:12:13,303] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-22 15:12:13,303] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-22 15:12:13,332] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-22 15:12:13,359] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-08-22 15:12:13,359] - Script::install(): KBExtra is successfully!
S_INFO root [2018-08-22 15:12:13,361] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-08-22 15:12:13,361] - TelnetServer server is running on port 31000
  INFO root [2018-08-22 15:12:13,641] - ---- loginapp is running ----
 DEBUG root [2018-08-22 15:12:13,641] - Components::process(): Request for the process of identity...
  INFO root [2018-08-22 15:12:20,761] - Components::findComponents: find logger(1)...
  INFO root [2018-08-22 15:12:20,826] - Components::findComponents: found logger, addr:192.168.0.106:60648
  INFO root [2018-08-22 15:12:20,827] - Components::addComponent: reset orderLog, uid=19318!
  INFO root [2018-08-22 15:12:20,827] - Components::addComponent[logger], uid=19318, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-08-22 15:12:20,828] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-08-22 15:12:20,931] - Components::findComponents: found dbmgr, addr:192.168.0.106:60650
  INFO root [2018-08-22 15:12:20,932] - Components::addComponent: reset orderLog, uid=19318!
  INFO root [2018-08-22 15:12:20,933] - Components::addComponent[dbmgr], uid=19318, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-08-22 15:12:20,933] - Components::findComponents: found dbmgr, addr:192.168.0.106:60650
  WARN root [2018-08-22 15:12:21,934] - Forwarding logs to logger[192.168.0.106:60648/0/0/0]...
 ERROR root [2018-08-22 15:12:55,068] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-08-22 15:12:55,081] - The following logs sent to logger failed:
  WARN root [2018-08-22 15:12:55,082] - ==> [2018-08-22 15:12:55 065] TCPPacketReceiver::processPendingEvents(192.168.0.106:60648): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-22 15:12:55,082] - ==> [2018-08-22 15:12:55 069] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-08-22 15:12:55,132] - TCPPacketReceiver::processPendingEvents(192.168.0.106:60650): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-22 15:12:55,135] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-08-22 15:12:55,146] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-08-22 15:12:55,147] - onLoginAppShutDown()
  INFO root [2018-08-22 15:12:55,147] - Shutdowner::onShutdown: shutting down
  INFO root [2018-08-22 15:12:55,147] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-08-22 15:12:55,147] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-22 15:12:55,147] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-08-22 15:12:55,147] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-22 15:12:55,147] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-22 15:12:55,147] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-08-22 15:12:55,148] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-22 15:12:55,148] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-22 15:12:55,148] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-22 15:12:55,191] - Script::uninstall(): is successfully!
 DEBUG root [2018-08-22 15:12:55,191] - ThreadPool::destroy(): starting size 2.
  INFO root [2018-08-22 15:13:51,347] - 
  INFO root [2018-08-22 15:13:51,347] - -----------------------------------------------------------------------------------------


  INFO root [2018-08-22 15:13:51,348] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [2018-08-22 15:13:51,348] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [2018-08-22 15:13:51,348] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [2018-08-22 15:13:51,350] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:20013 )
  INFO root [2018-08-22 15:13:51,350] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.106:20013, SOMAXCONN=128.
  INFO root [2018-08-22 15:13:51,351] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:60688 )
  INFO root [2018-08-22 15:13:51,351] - NetworkInterface::initialize(INTERNAL): address 192.168.0.106:60688, SOMAXCONN=128.
  INFO root [2018-08-22 15:13:51,351] - server-configs:
  INFO root [2018-08-22 15:13:51,351] - 	internalAddr : 192.168.0.106:60688
  INFO root [2018-08-22 15:13:51,351] - 	externalAddr : 192.168.0.106:20013
  INFO root [2018-08-22 15:13:51,351] - 	componentID : 9000
  INFO root [2018-08-22 15:13:53,042] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: B20F257E332779D9E1EA7D34638E6146. Config: Debug X86. Built: 15:53:07 Apr 29 2018. AppID: 9000. UID: 19638. PID: 13768 ----
  INFO root [2018-08-22 15:13:53,043] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [2018-08-22 15:13:53,043] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-08-22 15:13:53,044] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-08-22 15:13:53,167] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-22 15:13:53,168] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-08-22 15:13:53,168] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-22 15:13:53,171] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-22 15:13:53,171] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-08-22 15:13:53,171] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-22 15:13:53,172] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-22 15:13:53,201] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-22 15:13:53,230] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-08-22 15:13:53,230] - Script::install(): KBExtra is successfully!
S_INFO root [2018-08-22 15:13:53,232] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-08-22 15:13:53,233] - TelnetServer server is running on port 31000
  INFO root [2018-08-22 15:13:53,512] - ---- loginapp is running ----
 DEBUG root [2018-08-22 15:13:53,512] - Components::process(): Request for the process of identity...
  INFO root [2018-08-22 15:14:00,593] - Components::findComponents: find logger(1)...
  INFO root [2018-08-22 15:14:00,640] - Components::findComponents: found logger, addr:192.168.0.106:60684
  INFO root [2018-08-22 15:14:00,640] - Components::addComponent: reset orderLog, uid=19638!
  INFO root [2018-08-22 15:14:00,641] - Components::addComponent[logger], uid=19638, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-08-22 15:14:00,641] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-08-22 15:14:00,744] - Components::findComponents: found dbmgr, addr:192.168.0.106:60685
  INFO root [2018-08-22 15:14:00,744] - Components::addComponent: reset orderLog, uid=19638!
  INFO root [2018-08-22 15:14:00,745] - Components::addComponent[dbmgr], uid=19638, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-08-22 15:14:00,745] - Components::findComponents: found dbmgr, addr:192.168.0.106:60685
  WARN root [2018-08-22 15:14:01,745] - Forwarding logs to logger[192.168.0.106:60684/0/0/0]...
 ERROR root [2018-08-22 15:14:18,773] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-08-22 15:14:18,789] - The following logs sent to logger failed:
  WARN root [2018-08-22 15:14:18,790] - ==> [2018-08-22 15:14:18 769] TCPPacketReceiver::processPendingEvents(192.168.0.106:60684): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-22 15:14:18,790] - ==> [2018-08-22 15:14:18 773] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-08-22 15:14:18,844] - TCPPacketReceiver::processPendingEvents(192.168.0.106:60685): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-22 15:14:18,846] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-08-22 15:14:18,854] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-08-22 15:14:18,856] - onLoginAppShutDown()
  INFO root [2018-08-22 15:14:18,856] - Shutdowner::onShutdown: shutting down
  INFO root [2018-08-22 15:14:18,856] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-08-22 15:14:18,856] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-22 15:14:18,856] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-08-22 15:14:18,857] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-22 15:14:18,857] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-22 15:14:18,857] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-08-22 15:14:18,857] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-22 15:14:18,857] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-22 15:14:18,857] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-22 15:14:18,866] - Script::uninstall(): is successfully!
 DEBUG root [2018-08-22 15:14:18,866] - ThreadPool::destroy(): starting size 2.
  INFO root [2018-08-22 15:16:29,021] - 
  INFO root [2018-08-22 15:16:29,022] - -----------------------------------------------------------------------------------------


  INFO root [2018-08-22 15:16:29,023] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [2018-08-22 15:16:29,023] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [2018-08-22 15:16:29,023] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [2018-08-22 15:16:29,027] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:20013 )
  INFO root [2018-08-22 15:16:29,027] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.106:20013, SOMAXCONN=128.
  INFO root [2018-08-22 15:16:29,029] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:60767 )
  INFO root [2018-08-22 15:16:29,029] - NetworkInterface::initialize(INTERNAL): address 192.168.0.106:60767, SOMAXCONN=128.
  INFO root [2018-08-22 15:16:29,029] - server-configs:
  INFO root [2018-08-22 15:16:29,029] - 	internalAddr : 192.168.0.106:60767
  INFO root [2018-08-22 15:16:29,029] - 	externalAddr : 192.168.0.106:20013
  INFO root [2018-08-22 15:16:29,029] - 	componentID : 9000
  INFO root [2018-08-22 15:16:30,747] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: B20F257E332779D9E1EA7D34638E6146. Config: Debug X86. Built: 15:53:07 Apr 29 2018. AppID: 9000. UID: 20154. PID: 14748 ----
  INFO root [2018-08-22 15:16:30,748] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [2018-08-22 15:16:30,748] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-08-22 15:16:30,748] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-08-22 15:16:30,872] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-22 15:16:30,873] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-08-22 15:16:30,873] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-22 15:16:30,876] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-22 15:16:30,876] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-08-22 15:16:30,876] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-22 15:16:30,877] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-22 15:16:30,907] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-22 15:16:30,943] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-08-22 15:16:30,943] - Script::install(): KBExtra is successfully!
S_INFO root [2018-08-22 15:16:30,945] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-08-22 15:16:30,946] - TelnetServer server is running on port 31000
  INFO root [2018-08-22 15:16:31,266] - ---- loginapp is running ----
 DEBUG root [2018-08-22 15:16:31,266] - Components::process(): Request for the process of identity...
  WARN root [2018-08-22 15:16:34,628] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20303, errorno=10048
  INFO root [2018-08-22 15:16:38,706] - Components::findComponents: find logger(1)...
  INFO root [2018-08-22 15:16:38,749] - Components::findComponents: found logger, addr:192.168.0.106:60761
  INFO root [2018-08-22 15:16:38,750] - Components::addComponent: reset orderLog, uid=20154!
  INFO root [2018-08-22 15:16:38,750] - Components::addComponent[logger], uid=20154, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-08-22 15:16:38,751] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-08-22 15:16:38,852] - Components::findComponents: found dbmgr, addr:192.168.0.106:60760
  INFO root [2018-08-22 15:16:38,852] - Components::addComponent: reset orderLog, uid=20154!
  INFO root [2018-08-22 15:16:38,852] - Components::addComponent[dbmgr], uid=20154, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-08-22 15:16:38,853] - Components::findComponents: found dbmgr, addr:192.168.0.106:60760
  WARN root [2018-08-22 15:16:39,853] - Forwarding logs to logger[192.168.0.106:60761/0/0/0]...
 ERROR root [2018-08-22 15:28:43,550] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-08-22 15:28:43,568] - The following logs sent to logger failed:
  WARN root [2018-08-22 15:28:43,568] - ==> [2018-08-22 15:28:43 547] TCPPacketReceiver::processPendingEvents(192.168.0.106:60761): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-22 15:28:43,568] - ==> [2018-08-22 15:28:43 551] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-08-22 15:28:43,623] - TCPPacketReceiver::processPendingEvents(192.168.0.106:60760): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-22 15:28:43,627] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-08-22 15:28:43,640] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-08-22 15:28:43,641] - onLoginAppShutDown()
  INFO root [2018-08-22 15:28:43,641] - Shutdowner::onShutdown: shutting down
  INFO root [2018-08-22 15:28:43,641] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-08-22 15:28:43,641] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-22 15:28:43,641] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-08-22 15:28:43,642] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-22 15:28:43,642] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-22 15:28:43,642] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-08-22 15:28:43,642] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-22 15:28:43,642] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-22 15:28:43,642] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-22 15:28:43,651] - Script::uninstall(): is successfully!
 DEBUG root [2018-08-22 15:28:43,651] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-08-22 15:28:43,952] - ThreadPool::destroy(): waiting for thread(2)[0x439508,0x4394a0,], try=1
  INFO root [2018-08-22 15:28:44,900] - 
  INFO root [2018-08-22 15:28:44,900] - -----------------------------------------------------------------------------------------


  INFO root [2018-08-22 15:28:44,901] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [2018-08-22 15:28:44,901] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [2018-08-22 15:28:44,901] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [2018-08-22 15:28:44,912] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:20013 )
  INFO root [2018-08-22 15:28:44,912] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.106:20013, SOMAXCONN=128.
  INFO root [2018-08-22 15:28:44,913] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:60892 )
  INFO root [2018-08-22 15:28:44,913] - NetworkInterface::initialize(INTERNAL): address 192.168.0.106:60892, SOMAXCONN=128.
  INFO root [2018-08-22 15:28:44,913] - server-configs:
  INFO root [2018-08-22 15:28:44,914] - 	internalAddr : 192.168.0.106:60892
  INFO root [2018-08-22 15:28:44,914] - 	externalAddr : 192.168.0.106:20013
  INFO root [2018-08-22 15:28:44,914] - 	componentID : 9000
  INFO root [2018-08-22 15:28:45,360] - Components::findLogger: found logger, addr:192.168.0.106:60899
  INFO root [2018-08-22 15:28:45,360] - Components::addComponent: reset orderLog, uid=22557!
  INFO root [2018-08-22 15:28:45,361] - Components::addComponent[logger], uid=22557, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-08-22 15:28:45,366] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: B20F257E332779D9E1EA7D34638E6146. Config: Debug X86. Built: 15:53:07 Apr 29 2018. AppID: 9000. UID: 22557. PID: 6740 ----
  INFO root [2018-08-22 15:28:45,367] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [2018-08-22 15:28:45,367] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-08-22 15:28:45,367] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-08-22 15:28:45,490] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-22 15:28:45,491] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-08-22 15:28:45,491] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-22 15:28:45,496] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-22 15:28:45,496] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-08-22 15:28:45,496] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-22 15:28:45,497] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-22 15:28:45,527] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-22 15:28:45,559] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-08-22 15:28:45,559] - Script::install(): KBExtra is successfully!
S_INFO root [2018-08-22 15:28:45,561] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-08-22 15:28:45,561] - TelnetServer server is running on port 31000
  INFO root [2018-08-22 15:28:45,890] - ---- loginapp is running ----
 DEBUG root [2018-08-22 15:28:45,890] - Components::process(): Request for the process of identity...
  WARN root [2018-08-22 15:28:51,980] - Forwarding logs to logger[192.168.0.106:60899/0/0/0]...
 ERROR root [2018-08-22 15:31:43,288] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-08-22 15:31:43,305] - The following logs sent to logger failed:
  WARN root [2018-08-22 15:31:43,305] - ==> [2018-08-22 15:31:43 285] TCPPacketReceiver::processPendingEvents(192.168.0.106:60899): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-22 15:31:43,305] - ==> [2018-08-22 15:31:43 288] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-08-22 15:31:43,360] - TCPPacketReceiver::processPendingEvents(192.168.0.106:60895): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-22 15:31:43,364] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-08-22 15:31:43,378] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-08-22 15:31:43,379] - onLoginAppShutDown()
  INFO root [2018-08-22 15:31:43,379] - Shutdowner::onShutdown: shutting down
  INFO root [2018-08-22 15:31:43,379] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-08-22 15:31:43,380] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-22 15:31:43,380] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-08-22 15:31:43,380] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-22 15:31:43,380] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-22 15:31:43,380] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-08-22 15:31:43,380] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-22 15:31:43,380] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-22 15:31:43,380] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-22 15:31:43,389] - Script::uninstall(): is successfully!
 DEBUG root [2018-08-22 15:31:43,389] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-08-22 15:31:43,689] - ThreadPool::destroy(): waiting for thread(2)[0x18a9508,0x18a94a0,], try=1
  INFO root [2018-08-22 15:31:44,682] - 
  INFO root [2018-08-22 15:31:44,682] - -----------------------------------------------------------------------------------------


  INFO root [2018-08-22 15:31:44,683] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [2018-08-22 15:31:44,683] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [2018-08-22 15:31:44,683] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [2018-08-22 15:31:44,685] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:20013 )
  INFO root [2018-08-22 15:31:44,685] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.106:20013, SOMAXCONN=128.
  INFO root [2018-08-22 15:31:44,687] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:60957 )
  INFO root [2018-08-22 15:31:44,687] - NetworkInterface::initialize(INTERNAL): address 192.168.0.106:60957, SOMAXCONN=128.
  INFO root [2018-08-22 15:31:44,687] - server-configs:
  INFO root [2018-08-22 15:31:44,687] - 	internalAddr : 192.168.0.106:60957
  INFO root [2018-08-22 15:31:44,687] - 	externalAddr : 192.168.0.106:20013
  INFO root [2018-08-22 15:31:44,687] - 	componentID : 9000
  INFO root [2018-08-22 15:31:46,387] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: B20F257E332779D9E1EA7D34638E6146. Config: Debug X86. Built: 15:53:07 Apr 29 2018. AppID: 9000. UID: 23145. PID: 15380 ----
  INFO root [2018-08-22 15:31:46,388] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [2018-08-22 15:31:46,388] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-08-22 15:31:46,389] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-08-22 15:31:46,519] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-22 15:31:46,520] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-08-22 15:31:46,521] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-22 15:31:46,524] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-22 15:31:46,525] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-08-22 15:31:46,525] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-22 15:31:46,525] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-22 15:31:46,562] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-22 15:31:46,599] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-08-22 15:31:46,600] - Script::install(): KBExtra is successfully!
S_INFO root [2018-08-22 15:31:46,603] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-08-22 15:31:46,603] - TelnetServer server is running on port 31000
  INFO root [2018-08-22 15:31:46,930] - ---- loginapp is running ----
 DEBUG root [2018-08-22 15:31:46,930] - Components::process(): Request for the process of identity...
  INFO root [2018-08-22 15:31:54,084] - Components::findComponents: find logger(1)...
  INFO root [2018-08-22 15:31:54,117] - Components::findComponents: found logger, addr:192.168.0.106:60953
  INFO root [2018-08-22 15:31:54,118] - Components::addComponent: reset orderLog, uid=23145!
  INFO root [2018-08-22 15:31:54,119] - Components::addComponent[logger], uid=23145, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-08-22 15:31:54,121] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-08-22 15:31:54,221] - Components::findComponents: found dbmgr, addr:192.168.0.106:60950
  INFO root [2018-08-22 15:31:54,221] - Components::addComponent: reset orderLog, uid=23145!
  INFO root [2018-08-22 15:31:54,221] - Components::addComponent[dbmgr], uid=23145, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-08-22 15:31:54,222] - Components::findComponents: found dbmgr, addr:192.168.0.106:60950
  WARN root [2018-08-22 15:31:55,222] - Forwarding logs to logger[192.168.0.106:60953/0/0/0]...
 ERROR root [2018-08-22 15:52:19,753] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-08-22 15:52:19,767] - The following logs sent to logger failed:
  WARN root [2018-08-22 15:52:19,767] - ==> [2018-08-22 15:52:19 750] TCPPacketReceiver::processPendingEvents(192.168.0.106:60953): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-22 15:52:19,767] - ==> [2018-08-22 15:52:19 754] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-08-22 15:52:19,824] - TCPPacketReceiver::processPendingEvents(192.168.0.106:60950): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-22 15:52:19,828] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-08-22 15:52:19,840] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-08-22 15:52:19,843] - onLoginAppShutDown()
  INFO root [2018-08-22 15:52:19,844] - Shutdowner::onShutdown: shutting down
  INFO root [2018-08-22 15:52:19,844] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-08-22 15:52:19,844] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-22 15:52:19,844] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-08-22 15:52:19,844] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-22 15:52:19,844] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-22 15:52:19,844] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-08-22 15:52:19,844] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-22 15:52:19,844] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-22 15:52:19,844] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-22 15:52:19,854] - Script::uninstall(): is successfully!
 DEBUG root [2018-08-22 15:52:19,854] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-08-22 15:52:20,154] - ThreadPool::destroy(): waiting for thread(2)[0x3b9508,0x3b94a0,], try=1
  INFO root [2018-08-22 15:52:21,171] - 
  INFO root [2018-08-22 15:52:21,171] - -----------------------------------------------------------------------------------------


  INFO root [2018-08-22 15:52:21,172] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [2018-08-22 15:52:21,172] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [2018-08-22 15:52:21,172] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [2018-08-22 15:52:21,174] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:20013 )
  INFO root [2018-08-22 15:52:21,174] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.106:20013, SOMAXCONN=128.
  INFO root [2018-08-22 15:52:21,175] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:61156 )
  INFO root [2018-08-22 15:52:21,175] - NetworkInterface::initialize(INTERNAL): address 192.168.0.106:61156, SOMAXCONN=128.
  INFO root [2018-08-22 15:52:21,175] - server-configs:
  INFO root [2018-08-22 15:52:21,175] - 	internalAddr : 192.168.0.106:61156
  INFO root [2018-08-22 15:52:21,176] - 	externalAddr : 192.168.0.106:20013
  INFO root [2018-08-22 15:52:21,176] - 	componentID : 9000
  WARN root [2018-08-22 15:52:21,670] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20283, errorno=10048
  INFO root [2018-08-22 15:52:21,673] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: B20F257E332779D9E1EA7D34638E6146. Config: Debug X86. Built: 15:53:07 Apr 29 2018. AppID: 9000. UID: 27181. PID: 12444 ----
  INFO root [2018-08-22 15:52:21,674] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [2018-08-22 15:52:21,674] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-08-22 15:52:21,674] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-08-22 15:52:21,801] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-22 15:52:21,801] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-08-22 15:52:21,801] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-22 15:52:21,804] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-22 15:52:21,804] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-08-22 15:52:21,805] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-22 15:52:21,805] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-22 15:52:21,834] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-22 15:52:21,863] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-08-22 15:52:21,864] - Script::install(): KBExtra is successfully!
S_INFO root [2018-08-22 15:52:21,865] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-08-22 15:52:21,866] - TelnetServer server is running on port 31000
  INFO root [2018-08-22 15:52:22,138] - ---- loginapp is running ----
 DEBUG root [2018-08-22 15:52:22,139] - Components::process(): Request for the process of identity...
  INFO root [2018-08-22 15:52:29,245] - Components::findComponents: find logger(1)...
  INFO root [2018-08-22 15:52:29,345] - Components::findComponents: found logger, addr:192.168.0.106:61152
  INFO root [2018-08-22 15:52:29,346] - Components::addComponent: reset orderLog, uid=27181!
  INFO root [2018-08-22 15:52:29,346] - Components::addComponent[logger], uid=27181, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-08-22 15:52:29,348] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-08-22 15:52:29,451] - Components::findComponents: found dbmgr, addr:192.168.0.106:61154
  INFO root [2018-08-22 15:52:29,451] - Components::addComponent: reset orderLog, uid=27181!
  INFO root [2018-08-22 15:52:29,451] - Components::addComponent[dbmgr], uid=27181, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-08-22 15:52:29,452] - Components::findComponents: found dbmgr, addr:192.168.0.106:61154
  WARN root [2018-08-22 15:52:30,452] - Forwarding logs to logger[192.168.0.106:61152/0/0/0]...
 ERROR root [2018-08-22 15:54:05,525] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-08-22 15:54:05,538] - The following logs sent to logger failed:
  WARN root [2018-08-22 15:54:05,539] - ==> [2018-08-22 15:54:05 521] TCPPacketReceiver::processPendingEvents(192.168.0.106:61152): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-22 15:54:05,539] - ==> [2018-08-22 15:54:05 525] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-08-22 15:54:05,598] - TCPPacketReceiver::processPendingEvents(192.168.0.106:61154): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-22 15:54:05,602] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-08-22 15:54:05,617] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-08-22 15:54:05,618] - onLoginAppShutDown()
  INFO root [2018-08-22 15:54:05,618] - Shutdowner::onShutdown: shutting down
  INFO root [2018-08-22 15:54:05,618] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-08-22 15:54:05,618] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-22 15:54:05,618] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-08-22 15:54:05,618] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-22 15:54:05,619] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-22 15:54:05,619] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-08-22 15:54:05,619] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-22 15:54:05,619] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-22 15:54:05,619] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-22 15:54:05,627] - Script::uninstall(): is successfully!
 DEBUG root [2018-08-22 15:54:05,628] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-08-22 15:54:05,928] - ThreadPool::destroy(): waiting for thread(2)[0x409570,0x409508,], try=1
  INFO root [2018-08-22 15:54:06,950] - 
  INFO root [2018-08-22 15:54:06,950] - -----------------------------------------------------------------------------------------


  INFO root [2018-08-22 15:54:06,951] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [2018-08-22 15:54:06,951] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [2018-08-22 15:54:06,951] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [2018-08-22 15:54:06,954] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:20013 )
  INFO root [2018-08-22 15:54:06,954] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.106:20013, SOMAXCONN=128.
  INFO root [2018-08-22 15:54:06,955] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:61230 )
  INFO root [2018-08-22 15:54:06,955] - NetworkInterface::initialize(INTERNAL): address 192.168.0.106:61230, SOMAXCONN=128.
  INFO root [2018-08-22 15:54:06,955] - server-configs:
  INFO root [2018-08-22 15:54:06,955] - 	internalAddr : 192.168.0.106:61230
  INFO root [2018-08-22 15:54:06,955] - 	externalAddr : 192.168.0.106:20013
  INFO root [2018-08-22 15:54:06,955] - 	componentID : 9000
  WARN root [2018-08-22 15:54:07,452] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20053, errorno=10048
  INFO root [2018-08-22 15:54:07,455] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: B20F257E332779D9E1EA7D34638E6146. Config: Debug X86. Built: 15:53:07 Apr 29 2018. AppID: 9000. UID: 27528. PID: 16332 ----
  INFO root [2018-08-22 15:54:07,456] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [2018-08-22 15:54:07,456] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-08-22 15:54:07,456] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-08-22 15:54:07,582] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-22 15:54:07,583] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-08-22 15:54:07,583] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-22 15:54:07,587] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-22 15:54:07,587] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-08-22 15:54:07,587] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-22 15:54:07,588] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-22 15:54:07,617] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-22 15:54:07,647] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-08-22 15:54:07,647] - Script::install(): KBExtra is successfully!
S_INFO root [2018-08-22 15:54:07,649] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-08-22 15:54:07,649] - TelnetServer server is running on port 31000
  INFO root [2018-08-22 15:54:07,934] - ---- loginapp is running ----
 DEBUG root [2018-08-22 15:54:07,934] - Components::process(): Request for the process of identity...
  INFO root [2018-08-22 15:54:15,052] - Components::findComponents: find logger(1)...
  INFO root [2018-08-22 15:54:15,077] - Components::findComponents: found logger, addr:192.168.0.106:61224
  INFO root [2018-08-22 15:54:15,078] - Components::addComponent: reset orderLog, uid=27528!
  INFO root [2018-08-22 15:54:15,078] - Components::addComponent[logger], uid=27528, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-08-22 15:54:15,079] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-08-22 15:54:15,180] - Components::findComponents: found dbmgr, addr:192.168.0.106:61225
  INFO root [2018-08-22 15:54:15,180] - Components::addComponent: reset orderLog, uid=27528!
  INFO root [2018-08-22 15:54:15,181] - Components::addComponent[dbmgr], uid=27528, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-08-22 15:54:15,181] - Components::findComponents: found dbmgr, addr:192.168.0.106:61225
  WARN root [2018-08-22 15:54:16,181] - Forwarding logs to logger[192.168.0.106:61224/0/0/0]...
 ERROR root [2018-08-22 16:00:25,547] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-08-22 16:00:25,565] - The following logs sent to logger failed:
  WARN root [2018-08-22 16:00:25,566] - ==> [2018-08-22 16:00:25 543] TCPPacketReceiver::processPendingEvents(192.168.0.106:61224): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-22 16:00:25,566] - ==> [2018-08-22 16:00:25 547] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-08-22 16:00:25,619] - TCPPacketReceiver::processPendingEvents(192.168.0.106:61225): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-22 16:00:25,623] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-08-22 16:00:25,639] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-08-22 16:00:25,641] - onLoginAppShutDown()
  INFO root [2018-08-22 16:00:25,641] - Shutdowner::onShutdown: shutting down
  INFO root [2018-08-22 16:00:25,641] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-08-22 16:00:25,641] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-22 16:00:25,641] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-08-22 16:00:25,641] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-22 16:00:25,641] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-22 16:00:25,641] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-08-22 16:00:25,641] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-22 16:00:25,641] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-22 16:00:25,642] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-22 16:00:25,650] - Script::uninstall(): is successfully!
 DEBUG root [2018-08-22 16:00:25,650] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-08-22 16:00:25,950] - ThreadPool::destroy(): waiting for thread(2)[0x619570,0x619508,], try=1
  INFO root [2018-08-22 16:00:26,942] - 
  INFO root [2018-08-22 16:00:26,942] - -----------------------------------------------------------------------------------------


  INFO root [2018-08-22 16:00:26,943] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [2018-08-22 16:00:26,943] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [2018-08-22 16:00:26,943] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [2018-08-22 16:00:26,946] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:20013 )
  INFO root [2018-08-22 16:00:26,946] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.106:20013, SOMAXCONN=128.
  INFO root [2018-08-22 16:00:26,947] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:61312 )
  INFO root [2018-08-22 16:00:26,947] - NetworkInterface::initialize(INTERNAL): address 192.168.0.106:61312, SOMAXCONN=128.
  INFO root [2018-08-22 16:00:26,947] - server-configs:
  INFO root [2018-08-22 16:00:26,947] - 	internalAddr : 192.168.0.106:61312
  INFO root [2018-08-22 16:00:26,948] - 	externalAddr : 192.168.0.106:20013
  INFO root [2018-08-22 16:00:26,948] - 	componentID : 9000
  INFO root [2018-08-22 16:00:28,629] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: B20F257E332779D9E1EA7D34638E6146. Config: Debug X86. Built: 15:53:07 Apr 29 2018. AppID: 9000. UID: 28768. PID: 16180 ----
  INFO root [2018-08-22 16:00:28,630] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [2018-08-22 16:00:28,630] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-08-22 16:00:28,630] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-08-22 16:00:28,752] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-22 16:00:28,753] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-08-22 16:00:28,753] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-22 16:00:28,756] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-22 16:00:28,756] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-08-22 16:00:28,756] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-22 16:00:28,757] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-22 16:00:28,787] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-22 16:00:28,815] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-08-22 16:00:28,815] - Script::install(): KBExtra is successfully!
S_INFO root [2018-08-22 16:00:28,817] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-08-22 16:00:28,817] - TelnetServer server is running on port 31000
  INFO root [2018-08-22 16:00:29,099] - ---- loginapp is running ----
 DEBUG root [2018-08-22 16:00:29,099] - Components::process(): Request for the process of identity...
  INFO root [2018-08-22 16:00:36,197] - Components::findComponents: find logger(1)...
  INFO root [2018-08-22 16:00:36,246] - Components::findComponents: found logger, addr:192.168.0.106:61308
  INFO root [2018-08-22 16:00:36,247] - Components::addComponent: reset orderLog, uid=28768!
  INFO root [2018-08-22 16:00:36,247] - Components::addComponent[logger], uid=28768, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-08-22 16:00:36,249] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-08-22 16:00:36,350] - Components::findComponents: found dbmgr, addr:192.168.0.106:61311
  INFO root [2018-08-22 16:00:36,351] - Components::addComponent: reset orderLog, uid=28768!
  INFO root [2018-08-22 16:00:36,351] - Components::addComponent[dbmgr], uid=28768, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-08-22 16:00:36,351] - Components::findComponents: found dbmgr, addr:192.168.0.106:61311
  WARN root [2018-08-22 16:00:37,352] - Forwarding logs to logger[192.168.0.106:61308/0/0/0]...
 ERROR root [2018-08-22 16:09:48,435] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-08-22 16:09:48,451] - The following logs sent to logger failed:
  WARN root [2018-08-22 16:09:48,452] - ==> [2018-08-22 16:09:48 430] TCPPacketReceiver::processPendingEvents(192.168.0.106:61308): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-22 16:09:48,452] - ==> [2018-08-22 16:09:48 435] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-08-22 16:09:48,508] - TCPPacketReceiver::processPendingEvents(192.168.0.106:61311): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-22 16:09:48,512] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-08-22 16:09:48,531] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-08-22 16:09:48,533] - onLoginAppShutDown()
  INFO root [2018-08-22 16:09:48,533] - Shutdowner::onShutdown: shutting down
  INFO root [2018-08-22 16:09:48,533] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-08-22 16:09:48,533] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-22 16:09:48,533] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-08-22 16:09:48,533] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-22 16:09:48,533] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-22 16:09:48,533] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-08-22 16:09:48,534] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-22 16:09:48,534] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-22 16:09:48,534] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-22 16:09:48,543] - Script::uninstall(): is successfully!
 DEBUG root [2018-08-22 16:09:48,543] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-08-22 16:09:48,843] - ThreadPool::destroy(): waiting for thread(2)[0x699508,0x6994a0,], try=1
  INFO root [2018-08-22 16:09:49,837] - 
  INFO root [2018-08-22 16:09:49,838] - -----------------------------------------------------------------------------------------


  INFO root [2018-08-22 16:09:49,839] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [2018-08-22 16:09:49,839] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [2018-08-22 16:09:49,839] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [2018-08-22 16:09:49,846] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:20013 )
  INFO root [2018-08-22 16:09:49,847] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.106:20013, SOMAXCONN=128.
  INFO root [2018-08-22 16:09:49,851] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:64637 )
  INFO root [2018-08-22 16:09:49,852] - NetworkInterface::initialize(INTERNAL): address 192.168.0.106:64637, SOMAXCONN=128.
  INFO root [2018-08-22 16:09:49,852] - server-configs:
  INFO root [2018-08-22 16:09:49,852] - 	internalAddr : 192.168.0.106:64637
  INFO root [2018-08-22 16:09:49,852] - 	externalAddr : 192.168.0.106:20013
  INFO root [2018-08-22 16:09:49,852] - 	componentID : 9000
  INFO root [2018-08-22 16:09:51,556] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: B20F257E332779D9E1EA7D34638E6146. Config: Debug X86. Built: 15:53:07 Apr 29 2018. AppID: 9000. UID: 30607. PID: 12608 ----
  INFO root [2018-08-22 16:09:51,557] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [2018-08-22 16:09:51,557] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-08-22 16:09:51,557] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-08-22 16:09:51,680] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-22 16:09:51,680] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-08-22 16:09:51,681] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-22 16:09:51,683] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-22 16:09:51,684] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-08-22 16:09:51,684] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-22 16:09:51,684] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-22 16:09:51,712] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-22 16:09:51,740] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-08-22 16:09:51,740] - Script::install(): KBExtra is successfully!
S_INFO root [2018-08-22 16:09:51,742] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-08-22 16:09:51,742] - TelnetServer server is running on port 31000
  INFO root [2018-08-22 16:09:52,021] - ---- loginapp is running ----
 DEBUG root [2018-08-22 16:09:52,022] - Components::process(): Request for the process of identity...
  INFO root [2018-08-22 16:09:59,142] - Components::findComponents: find logger(1)...
  INFO root [2018-08-22 16:09:59,176] - Components::findComponents: found logger, addr:192.168.0.106:64639
  INFO root [2018-08-22 16:09:59,176] - Components::addComponent: reset orderLog, uid=30607!
  INFO root [2018-08-22 16:09:59,176] - Components::addComponent[logger], uid=30607, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-08-22 16:09:59,177] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-08-22 16:09:59,281] - Components::findComponents: found dbmgr, addr:192.168.0.106:64633
  INFO root [2018-08-22 16:09:59,282] - Components::addComponent: reset orderLog, uid=30607!
  INFO root [2018-08-22 16:09:59,282] - Components::addComponent[dbmgr], uid=30607, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-08-22 16:09:59,283] - Components::findComponents: found dbmgr, addr:192.168.0.106:64633
  WARN root [2018-08-22 16:10:00,283] - Forwarding logs to logger[192.168.0.106:64639/0/0/0]...
 ERROR root [2018-08-22 16:12:16,125] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-08-22 16:12:16,143] - The following logs sent to logger failed:
  WARN root [2018-08-22 16:12:16,143] - ==> [2018-08-22 16:12:16 121] TCPPacketReceiver::processPendingEvents(192.168.0.106:64639): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-22 16:12:16,143] - ==> [2018-08-22 16:12:16 125] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-08-22 16:12:16,199] - TCPPacketReceiver::processPendingEvents(192.168.0.106:64633): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-22 16:12:16,203] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-08-22 16:12:16,220] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-08-22 16:12:16,222] - onLoginAppShutDown()
  INFO root [2018-08-22 16:12:16,222] - Shutdowner::onShutdown: shutting down
  INFO root [2018-08-22 16:12:16,223] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-08-22 16:12:16,223] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-22 16:12:16,223] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-08-22 16:12:16,223] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-22 16:12:16,223] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-22 16:12:16,223] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-08-22 16:12:16,223] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-22 16:12:16,223] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-22 16:12:16,223] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-22 16:12:16,232] - Script::uninstall(): is successfully!
 DEBUG root [2018-08-22 16:12:16,232] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-08-22 16:12:16,532] - ThreadPool::destroy(): waiting for thread(2)[0x18d9508,0x18d94a0,], try=1
  INFO root [2018-08-22 16:12:17,545] - 
  INFO root [2018-08-22 16:12:17,545] - -----------------------------------------------------------------------------------------


  INFO root [2018-08-22 16:12:17,546] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [2018-08-22 16:12:17,546] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [2018-08-22 16:12:17,546] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [2018-08-22 16:12:17,549] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:20013 )
  INFO root [2018-08-22 16:12:17,550] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.106:20013, SOMAXCONN=128.
  INFO root [2018-08-22 16:12:17,552] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:64697 )
  INFO root [2018-08-22 16:12:17,552] - NetworkInterface::initialize(INTERNAL): address 192.168.0.106:64697, SOMAXCONN=128.
  INFO root [2018-08-22 16:12:17,552] - server-configs:
  INFO root [2018-08-22 16:12:17,552] - 	internalAddr : 192.168.0.106:64697
  INFO root [2018-08-22 16:12:17,552] - 	externalAddr : 192.168.0.106:20013
  INFO root [2018-08-22 16:12:17,552] - 	componentID : 9000
  INFO root [2018-08-22 16:12:19,249] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: B20F257E332779D9E1EA7D34638E6146. Config: Debug X86. Built: 15:53:07 Apr 29 2018. AppID: 9000. UID: 31087. PID: 17212 ----
  INFO root [2018-08-22 16:12:19,250] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [2018-08-22 16:12:19,250] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-08-22 16:12:19,250] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-08-22 16:12:19,384] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-22 16:12:19,384] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-08-22 16:12:19,384] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-22 16:12:19,387] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-22 16:12:19,388] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-08-22 16:12:19,388] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-22 16:12:19,389] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-22 16:12:19,426] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-22 16:12:19,457] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-08-22 16:12:19,457] - Script::install(): KBExtra is successfully!
S_INFO root [2018-08-22 16:12:19,459] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-08-22 16:12:19,459] - TelnetServer server is running on port 31000
  INFO root [2018-08-22 16:12:19,771] - ---- loginapp is running ----
 DEBUG root [2018-08-22 16:12:19,771] - Components::process(): Request for the process of identity...
  INFO root [2018-08-22 16:12:26,880] - Components::findComponents: find logger(1)...
  INFO root [2018-08-22 16:12:26,977] - Components::findComponents: found logger, addr:192.168.0.106:64699
  INFO root [2018-08-22 16:12:26,978] - Components::addComponent: reset orderLog, uid=31087!
  INFO root [2018-08-22 16:12:26,978] - Components::addComponent[logger], uid=31087, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-08-22 16:12:26,981] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-08-22 16:12:27,085] - Components::findComponents: found dbmgr, addr:192.168.0.106:64692
  INFO root [2018-08-22 16:12:27,086] - Components::addComponent: reset orderLog, uid=31087!
  INFO root [2018-08-22 16:12:27,087] - Components::addComponent[dbmgr], uid=31087, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-08-22 16:12:27,087] - Components::findComponents: found dbmgr, addr:192.168.0.106:64692
  WARN root [2018-08-22 16:12:28,088] - Forwarding logs to logger[192.168.0.106:64699/0/0/0]...
 ERROR root [2018-08-22 16:16:33,558] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-08-22 16:16:33,567] - The following logs sent to logger failed:
  WARN root [2018-08-22 16:16:33,567] - ==> [2018-08-22 16:16:33 548] TCPPacketReceiver::processPendingEvents(192.168.0.106:64699): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-22 16:16:33,567] - ==> [2018-08-22 16:16:33 559] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-08-22 16:16:33,624] - TCPPacketReceiver::processPendingEvents(192.168.0.106:64692): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-22 16:16:33,626] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-08-22 16:16:33,643] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-08-22 16:16:33,645] - onLoginAppShutDown()
  INFO root [2018-08-22 16:16:33,645] - Shutdowner::onShutdown: shutting down
  INFO root [2018-08-22 16:16:33,645] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-08-22 16:16:33,646] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-22 16:16:33,646] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-08-22 16:16:33,646] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-22 16:16:33,646] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-22 16:16:33,646] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-08-22 16:16:33,646] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-22 16:16:33,646] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-22 16:16:33,646] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-22 16:16:33,655] - Script::uninstall(): is successfully!
 DEBUG root [2018-08-22 16:16:33,655] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-08-22 16:16:33,955] - ThreadPool::destroy(): waiting for thread(2)[0x1849508,0x18494a0,], try=1
  INFO root [2018-08-22 16:16:34,954] - 
  INFO root [2018-08-22 16:16:34,954] - -----------------------------------------------------------------------------------------


  INFO root [2018-08-22 16:16:34,955] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [2018-08-22 16:16:34,955] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [2018-08-22 16:16:34,955] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [2018-08-22 16:16:34,958] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:20013 )
  INFO root [2018-08-22 16:16:34,958] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.106:20013, SOMAXCONN=128.
  INFO root [2018-08-22 16:16:34,960] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:64787 )
  INFO root [2018-08-22 16:16:34,960] - NetworkInterface::initialize(INTERNAL): address 192.168.0.106:64787, SOMAXCONN=128.
  INFO root [2018-08-22 16:16:34,960] - server-configs:
  INFO root [2018-08-22 16:16:34,960] - 	internalAddr : 192.168.0.106:64787
  INFO root [2018-08-22 16:16:34,961] - 	externalAddr : 192.168.0.106:20013
  INFO root [2018-08-22 16:16:34,961] - 	componentID : 9000
  INFO root [2018-08-22 16:16:36,669] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: B20F257E332779D9E1EA7D34638E6146. Config: Debug X86. Built: 15:53:07 Apr 29 2018. AppID: 9000. UID: 31930. PID: 16568 ----
  INFO root [2018-08-22 16:16:36,670] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [2018-08-22 16:16:36,670] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-08-22 16:16:36,670] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-08-22 16:16:36,796] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-22 16:16:36,796] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-08-22 16:16:36,796] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-22 16:16:36,799] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-22 16:16:36,800] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-08-22 16:16:36,800] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-22 16:16:36,800] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-22 16:16:36,828] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-22 16:16:36,857] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-08-22 16:16:36,857] - Script::install(): KBExtra is successfully!
S_INFO root [2018-08-22 16:16:36,860] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-08-22 16:16:36,860] - TelnetServer server is running on port 31000
  INFO root [2018-08-22 16:16:37,201] - ---- loginapp is running ----
 DEBUG root [2018-08-22 16:16:37,201] - Components::process(): Request for the process of identity...
  INFO root [2018-08-22 16:16:44,320] - Components::findComponents: find logger(1)...
  INFO root [2018-08-22 16:16:44,375] - Components::findComponents: found logger, addr:192.168.0.106:64786
  INFO root [2018-08-22 16:16:44,375] - Components::addComponent: reset orderLog, uid=31930!
  INFO root [2018-08-22 16:16:44,375] - Components::addComponent[logger], uid=31930, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-08-22 16:16:44,376] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-08-22 16:16:44,479] - Components::findComponents: found dbmgr, addr:192.168.0.106:64779
  INFO root [2018-08-22 16:16:44,479] - Components::addComponent: reset orderLog, uid=31930!
  INFO root [2018-08-22 16:16:44,479] - Components::addComponent[dbmgr], uid=31930, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-08-22 16:16:44,479] - Components::findComponents: found dbmgr, addr:192.168.0.106:64779
  WARN root [2018-08-22 16:16:45,479] - Forwarding logs to logger[192.168.0.106:64786/0/0/0]...
 ERROR root [2018-08-22 16:18:51,613] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-08-22 16:18:51,631] - The following logs sent to logger failed:
  WARN root [2018-08-22 16:18:51,631] - ==> [2018-08-22 16:18:51 609] TCPPacketReceiver::processPendingEvents(192.168.0.106:64786): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-22 16:18:51,631] - ==> [2018-08-22 16:18:51 614] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-08-22 16:18:51,694] - TCPPacketReceiver::processPendingEvents(192.168.0.106:64779): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-22 16:18:51,699] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-08-22 16:18:51,715] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-08-22 16:18:51,716] - onLoginAppShutDown()
  INFO root [2018-08-22 16:18:51,716] - Shutdowner::onShutdown: shutting down
  INFO root [2018-08-22 16:18:51,716] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-08-22 16:18:51,716] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-22 16:18:51,717] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-08-22 16:18:51,717] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-22 16:18:51,717] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-22 16:18:51,717] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-08-22 16:18:51,717] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-22 16:18:51,717] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-22 16:18:51,717] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-22 16:18:51,726] - Script::uninstall(): is successfully!
 DEBUG root [2018-08-22 16:18:51,726] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-08-22 16:18:52,026] - ThreadPool::destroy(): waiting for thread(2)[0x629508,0x6294a0,], try=1
  INFO root [2018-08-22 16:18:53,048] - 
  INFO root [2018-08-22 16:18:53,049] - -----------------------------------------------------------------------------------------


  INFO root [2018-08-22 16:18:53,049] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [2018-08-22 16:18:53,049] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [2018-08-22 16:18:53,049] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [2018-08-22 16:18:53,054] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:20013 )
  INFO root [2018-08-22 16:18:53,054] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.106:20013, SOMAXCONN=128.
  INFO root [2018-08-22 16:18:53,055] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:64859 )
  INFO root [2018-08-22 16:18:53,055] - NetworkInterface::initialize(INTERNAL): address 192.168.0.106:64859, SOMAXCONN=128.
  INFO root [2018-08-22 16:18:53,055] - server-configs:
  INFO root [2018-08-22 16:18:53,055] - 	internalAddr : 192.168.0.106:64859
  INFO root [2018-08-22 16:18:53,056] - 	externalAddr : 192.168.0.106:20013
  INFO root [2018-08-22 16:18:53,056] - 	componentID : 9000
  INFO root [2018-08-22 16:18:54,765] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: B20F257E332779D9E1EA7D34638E6146. Config: Debug X86. Built: 15:53:07 Apr 29 2018. AppID: 9000. UID: 32380. PID: 13620 ----
  INFO root [2018-08-22 16:18:54,766] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [2018-08-22 16:18:54,766] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-08-22 16:18:54,766] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-08-22 16:18:54,888] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-22 16:18:54,889] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-08-22 16:18:54,889] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-22 16:18:54,892] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-22 16:18:54,892] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-08-22 16:18:54,893] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-22 16:18:54,893] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-22 16:18:54,921] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-22 16:18:54,952] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-08-22 16:18:54,952] - Script::install(): KBExtra is successfully!
S_INFO root [2018-08-22 16:18:54,955] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-08-22 16:18:54,955] - TelnetServer server is running on port 31000
  INFO root [2018-08-22 16:18:55,251] - ---- loginapp is running ----
 DEBUG root [2018-08-22 16:18:55,252] - Components::process(): Request for the process of identity...
  INFO root [2018-08-22 16:19:02,375] - Components::findComponents: find logger(1)...
  INFO root [2018-08-22 16:19:02,476] - Components::findComponents: found logger, addr:192.168.0.106:64854
  INFO root [2018-08-22 16:19:02,476] - Components::addComponent: reset orderLog, uid=32380!
  INFO root [2018-08-22 16:19:02,477] - Components::addComponent[logger], uid=32380, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-08-22 16:19:02,478] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-08-22 16:19:02,583] - Components::findComponents: found dbmgr, addr:192.168.0.106:64858
  INFO root [2018-08-22 16:19:02,584] - Components::addComponent: reset orderLog, uid=32380!
  INFO root [2018-08-22 16:19:02,584] - Components::addComponent[dbmgr], uid=32380, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-08-22 16:19:02,585] - Components::findComponents: found dbmgr, addr:192.168.0.106:64858
  WARN root [2018-08-22 16:19:03,585] - Forwarding logs to logger[192.168.0.106:64854/0/0/0]...
 ERROR root [2018-08-22 16:32:09,251] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-08-22 16:32:09,271] - The following logs sent to logger failed:
  WARN root [2018-08-22 16:32:09,272] - ==> [2018-08-22 16:32:09 247] TCPPacketReceiver::processPendingEvents(192.168.0.106:64854): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-22 16:32:09,272] - ==> [2018-08-22 16:32:09 251] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-08-22 16:32:09,329] - TCPPacketReceiver::processPendingEvents(192.168.0.106:64858): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-22 16:32:09,333] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-08-22 16:32:09,346] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-08-22 16:32:09,352] - onLoginAppShutDown()
  INFO root [2018-08-22 16:32:09,352] - Shutdowner::onShutdown: shutting down
  INFO root [2018-08-22 16:32:09,352] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-08-22 16:32:09,352] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-22 16:32:09,352] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-08-22 16:32:09,353] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-22 16:32:09,353] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-22 16:32:09,353] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-08-22 16:32:09,353] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-22 16:32:09,353] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-22 16:32:09,353] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-22 16:32:09,362] - Script::uninstall(): is successfully!
 DEBUG root [2018-08-22 16:32:09,362] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-08-22 16:32:09,662] - ThreadPool::destroy(): waiting for thread(2)[0x5d9508,0x5d94a0,], try=1
  INFO root [2018-08-22 16:32:10,684] - 
  INFO root [2018-08-22 16:32:10,684] - -----------------------------------------------------------------------------------------


  INFO root [2018-08-22 16:32:10,685] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [2018-08-22 16:32:10,685] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [2018-08-22 16:32:10,685] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [2018-08-22 16:32:10,690] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:20013 )
  INFO root [2018-08-22 16:32:10,691] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.106:20013, SOMAXCONN=128.
  INFO root [2018-08-22 16:32:10,692] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:64999 )
  INFO root [2018-08-22 16:32:10,692] - NetworkInterface::initialize(INTERNAL): address 192.168.0.106:64999, SOMAXCONN=128.
  INFO root [2018-08-22 16:32:10,692] - server-configs:
  INFO root [2018-08-22 16:32:10,693] - 	internalAddr : 192.168.0.106:64999
  INFO root [2018-08-22 16:32:10,693] - 	externalAddr : 192.168.0.106:20013
  INFO root [2018-08-22 16:32:10,693] - 	componentID : 9000
  INFO root [2018-08-22 16:32:12,391] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: B20F257E332779D9E1EA7D34638E6146. Config: Debug X86. Built: 15:53:07 Apr 29 2018. AppID: 9000. UID: 2218. PID: 14804 ----
  INFO root [2018-08-22 16:32:12,392] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [2018-08-22 16:32:12,392] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-08-22 16:32:12,392] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-08-22 16:32:12,515] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-22 16:32:12,515] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-08-22 16:32:12,516] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-22 16:32:12,519] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-22 16:32:12,519] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-08-22 16:32:12,519] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-22 16:32:12,520] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-22 16:32:12,550] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-22 16:32:12,578] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-08-22 16:32:12,578] - Script::install(): KBExtra is successfully!
S_INFO root [2018-08-22 16:32:12,580] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-08-22 16:32:12,580] - TelnetServer server is running on port 31000
  INFO root [2018-08-22 16:32:12,886] - ---- loginapp is running ----
 DEBUG root [2018-08-22 16:32:12,887] - Components::process(): Request for the process of identity...
  INFO root [2018-08-22 16:32:19,980] - Components::findComponents: find logger(1)...
  INFO root [2018-08-22 16:32:20,030] - Components::findComponents: found logger, addr:192.168.0.106:64996
  INFO root [2018-08-22 16:32:20,030] - Components::addComponent: reset orderLog, uid=2218!
  INFO root [2018-08-22 16:32:20,031] - Components::addComponent[logger], uid=2218, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-08-22 16:32:20,032] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-08-22 16:32:20,138] - Components::findComponents: found dbmgr, addr:192.168.0.106:64997
  INFO root [2018-08-22 16:32:20,139] - Components::addComponent: reset orderLog, uid=2218!
  INFO root [2018-08-22 16:32:20,140] - Components::addComponent[dbmgr], uid=2218, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-08-22 16:32:20,140] - Components::findComponents: found dbmgr, addr:192.168.0.106:64997
  WARN root [2018-08-22 16:32:21,140] - Forwarding logs to logger[192.168.0.106:64996/0/0/0]...
 ERROR root [2018-08-22 16:34:53,327] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-08-22 16:34:53,348] - The following logs sent to logger failed:
  WARN root [2018-08-22 16:34:53,348] - ==> [2018-08-22 16:34:53 322] TCPPacketReceiver::processPendingEvents(192.168.0.106:64996): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-22 16:34:53,349] - ==> [2018-08-22 16:34:53 327] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-08-22 16:34:53,403] - TCPPacketReceiver::processPendingEvents(192.168.0.106:64997): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-22 16:34:53,408] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-08-22 16:34:53,427] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-08-22 16:34:53,429] - onLoginAppShutDown()
  INFO root [2018-08-22 16:34:53,429] - Shutdowner::onShutdown: shutting down
  INFO root [2018-08-22 16:34:53,429] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-08-22 16:34:53,429] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-22 16:34:53,430] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-08-22 16:34:53,430] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-22 16:34:53,430] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-22 16:34:53,430] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-08-22 16:34:53,430] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-22 16:34:53,430] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-22 16:34:53,430] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-22 16:34:53,446] - Script::uninstall(): is successfully!
 DEBUG root [2018-08-22 16:34:53,446] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-08-22 16:34:53,746] - ThreadPool::destroy(): waiting for thread(2)[0x219508,0x2194a0,], try=1
  INFO root [2018-08-22 16:34:54,778] - 
  INFO root [2018-08-22 16:34:54,779] - -----------------------------------------------------------------------------------------


  INFO root [2018-08-22 16:34:54,779] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [2018-08-22 16:34:54,779] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [2018-08-22 16:34:54,779] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [2018-08-22 16:34:54,785] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:20013 )
  INFO root [2018-08-22 16:34:54,786] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.106:20013, SOMAXCONN=128.
  INFO root [2018-08-22 16:34:54,787] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:65090 )
  INFO root [2018-08-22 16:34:54,787] - NetworkInterface::initialize(INTERNAL): address 192.168.0.106:65090, SOMAXCONN=128.
  INFO root [2018-08-22 16:34:54,787] - server-configs:
  INFO root [2018-08-22 16:34:54,787] - 	internalAddr : 192.168.0.106:65090
  INFO root [2018-08-22 16:34:54,788] - 	externalAddr : 192.168.0.106:20013
  INFO root [2018-08-22 16:34:54,788] - 	componentID : 9000
  INFO root [2018-08-22 16:34:56,483] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: B20F257E332779D9E1EA7D34638E6146. Config: Debug X86. Built: 15:53:07 Apr 29 2018. AppID: 9000. UID: 2754. PID: 5808 ----
  INFO root [2018-08-22 16:34:56,484] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [2018-08-22 16:34:56,484] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-08-22 16:34:56,484] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-08-22 16:34:56,608] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-22 16:34:56,608] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-08-22 16:34:56,609] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-22 16:34:56,612] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-22 16:34:56,612] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-08-22 16:34:56,612] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-22 16:34:56,613] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-22 16:34:56,646] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-22 16:34:56,679] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-08-22 16:34:56,679] - Script::install(): KBExtra is successfully!
S_INFO root [2018-08-22 16:34:56,681] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-08-22 16:34:56,681] - TelnetServer server is running on port 31000
  INFO root [2018-08-22 16:34:56,991] - ---- loginapp is running ----
 DEBUG root [2018-08-22 16:34:56,991] - Components::process(): Request for the process of identity...
  INFO root [2018-08-22 16:35:04,061] - Components::findComponents: find logger(1)...
  INFO root [2018-08-22 16:35:04,107] - Components::findComponents: found logger, addr:192.168.0.106:65085
  INFO root [2018-08-22 16:35:04,107] - Components::addComponent: reset orderLog, uid=2754!
  INFO root [2018-08-22 16:35:04,107] - Components::addComponent[logger], uid=2754, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-08-22 16:35:04,108] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-08-22 16:35:04,208] - Components::findComponents: found dbmgr, addr:192.168.0.106:65086
  INFO root [2018-08-22 16:35:04,209] - Components::addComponent: reset orderLog, uid=2754!
  INFO root [2018-08-22 16:35:04,209] - Components::addComponent[dbmgr], uid=2754, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-08-22 16:35:04,209] - Components::findComponents: found dbmgr, addr:192.168.0.106:65086
  WARN root [2018-08-22 16:35:05,209] - Forwarding logs to logger[192.168.0.106:65085/0/0/0]...
 ERROR root [2018-08-22 16:45:36,195] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-08-22 16:45:36,212] - The following logs sent to logger failed:
  WARN root [2018-08-22 16:45:36,212] - ==> [2018-08-22 16:45:36 192] TCPPacketReceiver::processPendingEvents(192.168.0.106:65085): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-22 16:45:36,212] - ==> [2018-08-22 16:45:36 195] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-08-22 16:45:36,275] - TCPPacketReceiver::processPendingEvents(192.168.0.106:65086): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-22 16:45:36,279] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-08-22 16:45:36,300] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-08-22 16:45:36,300] - onLoginAppShutDown()
  INFO root [2018-08-22 16:45:36,300] - Shutdowner::onShutdown: shutting down
  INFO root [2018-08-22 16:45:36,300] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-08-22 16:45:36,300] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-22 16:45:36,300] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-08-22 16:45:36,301] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-22 16:45:36,301] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-22 16:45:36,301] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-08-22 16:45:36,301] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-22 16:45:36,301] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-22 16:45:36,301] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-22 16:45:36,310] - Script::uninstall(): is successfully!
 DEBUG root [2018-08-22 16:45:36,311] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-08-22 16:45:36,612] - ThreadPool::destroy(): waiting for thread(2)[0x1969508,0x19694a0,], try=1
  INFO root [2018-08-22 16:45:37,674] - 
  INFO root [2018-08-22 16:45:37,675] - -----------------------------------------------------------------------------------------


  INFO root [2018-08-22 16:45:37,675] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [2018-08-22 16:45:37,676] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [2018-08-22 16:45:37,676] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [2018-08-22 16:45:37,680] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:20013 )
  INFO root [2018-08-22 16:45:37,681] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.106:20013, SOMAXCONN=128.
  INFO root [2018-08-22 16:45:37,682] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:65192 )
  INFO root [2018-08-22 16:45:37,683] - NetworkInterface::initialize(INTERNAL): address 192.168.0.106:65192, SOMAXCONN=128.
  INFO root [2018-08-22 16:45:37,683] - server-configs:
  INFO root [2018-08-22 16:45:37,683] - 	internalAddr : 192.168.0.106:65192
  INFO root [2018-08-22 16:45:37,683] - 	externalAddr : 192.168.0.106:20013
  INFO root [2018-08-22 16:45:37,683] - 	componentID : 9000
  WARN root [2018-08-22 16:45:38,193] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20559, errorno=10048
  INFO root [2018-08-22 16:45:38,197] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: B20F257E332779D9E1EA7D34638E6146. Config: Debug X86. Built: 15:53:07 Apr 29 2018. AppID: 9000. UID: 4853. PID: 18216 ----
  INFO root [2018-08-22 16:45:38,197] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [2018-08-22 16:45:38,197] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-08-22 16:45:38,198] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-08-22 16:45:38,322] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-22 16:45:38,323] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-08-22 16:45:38,323] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-22 16:45:38,326] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-22 16:45:38,327] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-08-22 16:45:38,327] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-22 16:45:38,327] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-22 16:45:38,358] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-22 16:45:38,387] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-08-22 16:45:38,387] - Script::install(): KBExtra is successfully!
S_INFO root [2018-08-22 16:45:38,389] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-08-22 16:45:38,389] - TelnetServer server is running on port 31000
  INFO root [2018-08-22 16:45:38,680] - ---- loginapp is running ----
 DEBUG root [2018-08-22 16:45:38,681] - Components::process(): Request for the process of identity...
  INFO root [2018-08-22 16:45:45,778] - Components::findComponents: find logger(1)...
  INFO root [2018-08-22 16:45:45,848] - Components::findComponents: found logger, addr:192.168.0.106:65187
  INFO root [2018-08-22 16:45:45,849] - Components::addComponent: reset orderLog, uid=4853!
  INFO root [2018-08-22 16:45:45,849] - Components::addComponent[logger], uid=4853, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-08-22 16:45:45,850] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-08-22 16:45:45,951] - Components::findComponents: found dbmgr, addr:192.168.0.106:65185
  INFO root [2018-08-22 16:45:45,951] - Components::addComponent: reset orderLog, uid=4853!
  INFO root [2018-08-22 16:45:45,951] - Components::addComponent[dbmgr], uid=4853, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-08-22 16:45:45,951] - Components::findComponents: found dbmgr, addr:192.168.0.106:65185
  WARN root [2018-08-22 16:45:46,951] - Forwarding logs to logger[192.168.0.106:65187/0/0/0]...
 ERROR root [2018-08-22 21:07:47,102] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-08-22 21:07:47,114] - The following logs sent to logger failed:
  WARN root [2018-08-22 21:07:47,114] - ==> [2018-08-22 21:07:47 080] TCPPacketReceiver::processPendingEvents(192.168.0.106:65187): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-22 21:07:47,115] - ==> [2018-08-22 21:07:47 102] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-08-22 21:07:47,168] - TCPPacketReceiver::processPendingEvents(192.168.0.106:65185): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-22 21:07:47,176] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-08-22 21:07:47,202] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-08-22 21:07:47,204] - onLoginAppShutDown()
  INFO root [2018-08-22 21:07:47,204] - Shutdowner::onShutdown: shutting down
  INFO root [2018-08-22 21:07:47,204] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-08-22 21:07:47,204] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-22 21:07:47,204] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-08-22 21:07:47,205] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-22 21:07:47,205] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-22 21:07:47,205] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-08-22 21:07:47,205] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-22 21:07:47,205] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-22 21:07:47,205] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-22 21:07:47,217] - Script::uninstall(): is successfully!
 DEBUG root [2018-08-22 21:07:47,217] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-08-22 21:07:47,518] - ThreadPool::destroy(): waiting for thread(2)[0x399570,0x399508,], try=1
  INFO root [2018-08-22 21:07:48,661] - 
  INFO root [2018-08-22 21:07:48,664] - -----------------------------------------------------------------------------------------


  INFO root [2018-08-22 21:07:48,665] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [2018-08-22 21:07:48,665] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [2018-08-22 21:07:48,665] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [2018-08-22 21:07:48,673] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:20013 )
  INFO root [2018-08-22 21:07:48,673] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.106:20013, SOMAXCONN=128.
  INFO root [2018-08-22 21:07:48,675] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:61898 )
  INFO root [2018-08-22 21:07:48,675] - NetworkInterface::initialize(INTERNAL): address 192.168.0.106:61898, SOMAXCONN=128.
  INFO root [2018-08-22 21:07:48,675] - server-configs:
  INFO root [2018-08-22 21:07:48,675] - 	internalAddr : 192.168.0.106:61898
  INFO root [2018-08-22 21:07:48,675] - 	externalAddr : 192.168.0.106:20013
  INFO root [2018-08-22 21:07:48,675] - 	componentID : 9000
  INFO root [2018-08-22 21:07:50,379] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: B20F257E332779D9E1EA7D34638E6146. Config: Debug X86. Built: 15:53:07 Apr 29 2018. AppID: 9000. UID: 23453. PID: 19020 ----
  INFO root [2018-08-22 21:07:50,380] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [2018-08-22 21:07:50,380] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-08-22 21:07:50,380] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-08-22 21:07:50,508] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-22 21:07:50,509] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-08-22 21:07:50,509] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-22 21:07:50,514] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-22 21:07:50,514] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-08-22 21:07:50,514] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-22 21:07:50,515] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-22 21:07:50,550] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-22 21:07:50,588] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-08-22 21:07:50,588] - Script::install(): KBExtra is successfully!
S_INFO root [2018-08-22 21:07:50,590] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-08-22 21:07:50,590] - TelnetServer server is running on port 31000
  INFO root [2018-08-22 21:07:50,876] - ---- loginapp is running ----
 DEBUG root [2018-08-22 21:07:50,877] - Components::process(): Request for the process of identity...
  INFO root [2018-08-22 21:07:57,991] - Components::findComponents: find logger(1)...
  INFO root [2018-08-22 21:07:58,071] - Components::findComponents: found logger, addr:192.168.0.106:61901
  INFO root [2018-08-22 21:07:58,072] - Components::addComponent: reset orderLog, uid=23453!
  INFO root [2018-08-22 21:07:58,072] - Components::addComponent[logger], uid=23453, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-08-22 21:07:58,072] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-08-22 21:07:58,174] - Components::findComponents: found dbmgr, addr:192.168.0.106:61894
  INFO root [2018-08-22 21:07:58,174] - Components::addComponent: reset orderLog, uid=23453!
  INFO root [2018-08-22 21:07:58,174] - Components::addComponent[dbmgr], uid=23453, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-08-22 21:07:58,175] - Components::findComponents: found dbmgr, addr:192.168.0.106:61894
  WARN root [2018-08-22 21:07:59,175] - Forwarding logs to logger[192.168.0.106:61901/0/0/0]...
 ERROR root [2018-08-22 21:12:20,633] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-08-22 21:12:20,666] - The following logs sent to logger failed:
  WARN root [2018-08-22 21:12:20,666] - ==> [2018-08-22 21:12:20 624] TCPPacketReceiver::processPendingEvents(192.168.0.106:61901): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-22 21:12:20,666] - ==> [2018-08-22 21:12:20 634] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-08-22 21:12:20,725] - TCPPacketReceiver::processPendingEvents(192.168.0.106:61894): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-22 21:12:20,733] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-08-22 21:12:20,764] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-08-22 21:12:20,766] - onLoginAppShutDown()
  INFO root [2018-08-22 21:12:20,766] - Shutdowner::onShutdown: shutting down
  INFO root [2018-08-22 21:12:20,766] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-08-22 21:12:20,766] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-22 21:12:20,766] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-08-22 21:12:20,766] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-22 21:12:20,766] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-22 21:12:20,767] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-08-22 21:12:20,767] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-22 21:12:20,767] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-22 21:12:20,767] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-22 21:12:20,776] - Script::uninstall(): is successfully!
 DEBUG root [2018-08-22 21:12:20,776] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-08-22 21:12:21,076] - ThreadPool::destroy(): waiting for thread(2)[0x1879508,0x18794a0,], try=1
  INFO root [2018-08-22 21:12:22,218] - 
  INFO root [2018-08-22 21:12:22,218] - -----------------------------------------------------------------------------------------


  INFO root [2018-08-22 21:12:22,219] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [2018-08-22 21:12:22,219] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [2018-08-22 21:12:22,219] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [2018-08-22 21:12:22,231] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:20013 )
  INFO root [2018-08-22 21:12:22,231] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.106:20013, SOMAXCONN=128.
  INFO root [2018-08-22 21:12:22,233] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:61966 )
  INFO root [2018-08-22 21:12:22,233] - NetworkInterface::initialize(INTERNAL): address 192.168.0.106:61966, SOMAXCONN=128.
  INFO root [2018-08-22 21:12:22,233] - server-configs:
  INFO root [2018-08-22 21:12:22,234] - 	internalAddr : 192.168.0.106:61966
  INFO root [2018-08-22 21:12:22,234] - 	externalAddr : 192.168.0.106:20013
  INFO root [2018-08-22 21:12:22,234] - 	componentID : 9000
  INFO root [2018-08-22 21:12:23,957] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: B20F257E332779D9E1EA7D34638E6146. Config: Debug X86. Built: 15:53:07 Apr 29 2018. AppID: 9000. UID: 24348. PID: 16392 ----
  INFO root [2018-08-22 21:12:23,957] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [2018-08-22 21:12:23,958] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-08-22 21:12:23,958] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-08-22 21:12:24,083] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-22 21:12:24,084] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-08-22 21:12:24,084] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-22 21:12:24,087] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-22 21:12:24,087] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-08-22 21:12:24,087] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-22 21:12:24,088] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-22 21:12:24,128] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-22 21:12:24,160] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-08-22 21:12:24,160] - Script::install(): KBExtra is successfully!
S_INFO root [2018-08-22 21:12:24,162] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-08-22 21:12:24,162] - TelnetServer server is running on port 31000
  INFO root [2018-08-22 21:12:24,445] - ---- loginapp is running ----
 DEBUG root [2018-08-22 21:12:24,446] - Components::process(): Request for the process of identity...
  INFO root [2018-08-22 21:12:31,543] - Components::findComponents: find logger(1)...
  INFO root [2018-08-22 21:12:31,551] - Components::findComponents: found logger, addr:192.168.0.106:61969
  INFO root [2018-08-22 21:12:31,551] - Components::addComponent: reset orderLog, uid=24348!
  INFO root [2018-08-22 21:12:31,551] - Components::addComponent[logger], uid=24348, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-08-22 21:12:31,552] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-08-22 21:12:31,653] - Components::findComponents: found dbmgr, addr:192.168.0.106:61962
  INFO root [2018-08-22 21:12:31,653] - Components::addComponent: reset orderLog, uid=24348!
  INFO root [2018-08-22 21:12:31,654] - Components::addComponent[dbmgr], uid=24348, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-08-22 21:12:31,654] - Components::findComponents: found dbmgr, addr:192.168.0.106:61962
  WARN root [2018-08-22 21:12:32,654] - Forwarding logs to logger[192.168.0.106:61969/0/0/0]...
 ERROR root [2018-08-22 21:22:06,078] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-08-22 21:22:06,078] - The following logs sent to logger failed:
  WARN root [2018-08-22 21:22:06,078] - ==> [2018-08-22 21:22:06 070] TCPPacketReceiver::processPendingEvents(192.168.0.106:61969): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-22 21:22:06,078] - ==> [2018-08-22 21:22:06 078] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-08-22 21:22:06,078] - TCPPacketReceiver::processPendingEvents(192.168.0.106:61962): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-22 21:22:06,078] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-08-22 21:22:06,078] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-08-22 21:22:06,078] - onLoginAppShutDown()
  INFO root [2018-08-22 21:22:06,078] - Shutdowner::onShutdown: shutting down
  INFO root [2018-08-22 21:22:06,078] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-08-22 21:22:06,078] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-22 21:22:06,078] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-08-22 21:22:06,078] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-22 21:22:06,078] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-22 21:22:06,078] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-08-22 21:22:06,078] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-22 21:22:06,078] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-22 21:22:06,078] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-22 21:22:06,078] - Script::uninstall(): is successfully!
 DEBUG root [2018-08-22 21:22:06,078] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-08-22 21:22:06,078] - ThreadPool::destroy(): waiting for thread(2)[0x1ac9508,0x1ac94a0,], try=1
  INFO root [2018-08-22 21:22:07,674] - 
  INFO root [2018-08-22 21:22:07,675] - -----------------------------------------------------------------------------------------


  INFO root [2018-08-22 21:22:07,675] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [2018-08-22 21:22:07,675] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [2018-08-22 21:22:07,676] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [2018-08-22 21:22:07,680] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:20013 )
  INFO root [2018-08-22 21:22:07,680] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.106:20013, SOMAXCONN=128.
  INFO root [2018-08-22 21:22:07,683] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:62080 )
  INFO root [2018-08-22 21:22:07,683] - NetworkInterface::initialize(INTERNAL): address 192.168.0.106:62080, SOMAXCONN=128.
  INFO root [2018-08-22 21:22:07,684] - server-configs:
  INFO root [2018-08-22 21:22:07,684] - 	internalAddr : 192.168.0.106:62080
  INFO root [2018-08-22 21:22:07,684] - 	externalAddr : 192.168.0.106:20013
  INFO root [2018-08-22 21:22:07,684] - 	componentID : 9000
  INFO root [2018-08-22 21:22:09,401] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: B20F257E332779D9E1EA7D34638E6146. Config: Debug X86. Built: 15:53:07 Apr 29 2018. AppID: 9000. UID: 26258. PID: 7848 ----
  INFO root [2018-08-22 21:22:09,401] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [2018-08-22 21:22:09,402] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-08-22 21:22:09,402] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-08-22 21:22:09,527] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-22 21:22:09,528] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-08-22 21:22:09,528] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-22 21:22:09,532] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-22 21:22:09,532] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-08-22 21:22:09,532] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-22 21:22:09,532] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-22 21:22:09,568] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-22 21:22:09,604] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-08-22 21:22:09,604] - Script::install(): KBExtra is successfully!
S_INFO root [2018-08-22 21:22:09,606] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-08-22 21:22:09,606] - TelnetServer server is running on port 31000
  INFO root [2018-08-22 21:22:09,907] - ---- loginapp is running ----
 DEBUG root [2018-08-22 21:22:09,908] - Components::process(): Request for the process of identity...
  INFO root [2018-08-22 21:22:17,026] - Components::findComponents: find logger(1)...
  INFO root [2018-08-22 21:22:17,119] - Components::findComponents: found logger, addr:192.168.0.106:62085
  INFO root [2018-08-22 21:22:17,119] - Components::addComponent: reset orderLog, uid=26258!
  INFO root [2018-08-22 21:22:17,119] - Components::addComponent[logger], uid=26258, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-08-22 21:22:17,121] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-08-22 21:22:17,226] - Components::findComponents: found dbmgr, addr:192.168.0.106:62079
  INFO root [2018-08-22 21:22:17,226] - Components::addComponent: reset orderLog, uid=26258!
  INFO root [2018-08-22 21:22:17,226] - Components::addComponent[dbmgr], uid=26258, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-08-22 21:22:17,226] - Components::findComponents: found dbmgr, addr:192.168.0.106:62079
  WARN root [2018-08-22 21:22:18,226] - Forwarding logs to logger[192.168.0.106:62085/0/0/0]...
 ERROR root [2018-08-22 21:53:10,206] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-08-22 21:53:10,251] - The following logs sent to logger failed:
  WARN root [2018-08-22 21:53:10,251] - ==> [2018-08-22 21:53:10 197] TCPPacketReceiver::processPendingEvents(192.168.0.106:62085): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-22 21:53:10,252] - ==> [2018-08-22 21:53:10 207] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-08-22 21:53:10,308] - TCPPacketReceiver::processPendingEvents(192.168.0.106:62079): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-22 21:53:10,316] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-08-22 21:53:10,343] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-08-22 21:53:10,345] - onLoginAppShutDown()
  INFO root [2018-08-22 21:53:10,345] - Shutdowner::onShutdown: shutting down
  INFO root [2018-08-22 21:53:10,345] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-08-22 21:53:10,345] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-22 21:53:10,345] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-08-22 21:53:10,345] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-22 21:53:10,345] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-22 21:53:10,345] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-08-22 21:53:10,346] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-22 21:53:10,346] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-22 21:53:10,346] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-22 21:53:10,355] - Script::uninstall(): is successfully!
 DEBUG root [2018-08-22 21:53:10,355] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-08-22 21:53:10,656] - ThreadPool::destroy(): waiting for thread(2)[0x19e9508,0x19e94a0,], try=1
  INFO root [2018-08-22 21:53:11,886] - 
  INFO root [2018-08-22 21:53:11,887] - -----------------------------------------------------------------------------------------


  INFO root [2018-08-22 21:53:11,888] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [2018-08-22 21:53:11,888] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [2018-08-22 21:53:11,888] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [2018-08-22 21:53:11,897] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:20013 )
  INFO root [2018-08-22 21:53:11,898] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.106:20013, SOMAXCONN=128.
  INFO root [2018-08-22 21:53:11,899] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:62366 )
  INFO root [2018-08-22 21:53:11,899] - NetworkInterface::initialize(INTERNAL): address 192.168.0.106:62366, SOMAXCONN=128.
  INFO root [2018-08-22 21:53:11,899] - server-configs:
  INFO root [2018-08-22 21:53:11,899] - 	internalAddr : 192.168.0.106:62366
  INFO root [2018-08-22 21:53:11,900] - 	externalAddr : 192.168.0.106:20013
  INFO root [2018-08-22 21:53:11,900] - 	componentID : 9000
  INFO root [2018-08-22 21:53:13,576] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: B20F257E332779D9E1EA7D34638E6146. Config: Debug X86. Built: 15:53:07 Apr 29 2018. AppID: 9000. UID: 32348. PID: 19024 ----
  INFO root [2018-08-22 21:53:13,577] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [2018-08-22 21:53:13,577] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-08-22 21:53:13,577] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-08-22 21:53:13,700] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-22 21:53:13,700] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-08-22 21:53:13,700] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-22 21:53:13,703] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-22 21:53:13,704] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-08-22 21:53:13,704] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-22 21:53:13,704] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-22 21:53:13,734] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-22 21:53:13,762] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-08-22 21:53:13,762] - Script::install(): KBExtra is successfully!
S_INFO root [2018-08-22 21:53:13,764] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-08-22 21:53:13,764] - TelnetServer server is running on port 31000
  INFO root [2018-08-22 21:53:14,056] - ---- loginapp is running ----
 DEBUG root [2018-08-22 21:53:14,057] - Components::process(): Request for the process of identity...
  INFO root [2018-08-22 21:53:21,125] - Components::findComponents: find logger(1)...
  INFO root [2018-08-22 21:53:21,181] - Components::findComponents: found logger, addr:192.168.0.106:62364
  INFO root [2018-08-22 21:53:21,181] - Components::addComponent: reset orderLog, uid=32348!
  INFO root [2018-08-22 21:53:21,181] - Components::addComponent[logger], uid=32348, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-08-22 21:53:21,181] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-08-22 21:53:21,282] - Components::findComponents: found dbmgr, addr:192.168.0.106:62361
  INFO root [2018-08-22 21:53:21,283] - Components::addComponent: reset orderLog, uid=32348!
  INFO root [2018-08-22 21:53:21,283] - Components::addComponent[dbmgr], uid=32348, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-08-22 21:53:21,283] - Components::findComponents: found dbmgr, addr:192.168.0.106:62361
  WARN root [2018-08-22 21:53:22,283] - Forwarding logs to logger[192.168.0.106:62364/0/0/0]...
 ERROR root [2018-08-22 22:07:54,171] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-08-22 22:07:54,201] - The following logs sent to logger failed:
  WARN root [2018-08-22 22:07:54,201] - ==> [2018-08-22 22:07:54 163] TCPPacketReceiver::processPendingEvents(192.168.0.106:62364): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-22 22:07:54,201] - ==> [2018-08-22 22:07:54 172] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-08-22 22:07:54,260] - TCPPacketReceiver::processPendingEvents(192.168.0.106:62361): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-22 22:07:54,269] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-08-22 22:07:54,301] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-08-22 22:07:54,303] - onLoginAppShutDown()
  INFO root [2018-08-22 22:07:54,303] - Shutdowner::onShutdown: shutting down
  INFO root [2018-08-22 22:07:54,303] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-08-22 22:07:54,303] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-22 22:07:54,304] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-08-22 22:07:54,304] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-22 22:07:54,304] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-22 22:07:54,305] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-08-22 22:07:54,305] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-22 22:07:54,305] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-22 22:07:54,305] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-22 22:07:54,315] - Script::uninstall(): is successfully!
 DEBUG root [2018-08-22 22:07:54,315] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-08-22 22:07:54,615] - ThreadPool::destroy(): waiting for thread(2)[0x509510,0x5094a8,], try=1
  INFO root [2018-08-22 22:07:55,854] - 
  INFO root [2018-08-22 22:07:55,858] - -----------------------------------------------------------------------------------------


  INFO root [2018-08-22 22:07:55,859] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [2018-08-22 22:07:55,859] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [2018-08-22 22:07:55,859] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [2018-08-22 22:07:55,863] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:20013 )
  INFO root [2018-08-22 22:07:55,863] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.106:20013, SOMAXCONN=128.
  INFO root [2018-08-22 22:07:55,865] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:62525 )
  INFO root [2018-08-22 22:07:55,865] - NetworkInterface::initialize(INTERNAL): address 192.168.0.106:62525, SOMAXCONN=128.
  INFO root [2018-08-22 22:07:55,865] - server-configs:
  INFO root [2018-08-22 22:07:55,865] - 	internalAddr : 192.168.0.106:62525
  INFO root [2018-08-22 22:07:55,865] - 	externalAddr : 192.168.0.106:20013
  INFO root [2018-08-22 22:07:55,865] - 	componentID : 9000
  INFO root [2018-08-22 22:07:57,575] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: B20F257E332779D9E1EA7D34638E6146. Config: Debug X86. Built: 15:53:07 Apr 29 2018. AppID: 9000. UID: 2464. PID: 20468 ----
  INFO root [2018-08-22 22:07:57,576] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [2018-08-22 22:07:57,577] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-08-22 22:07:57,577] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-08-22 22:07:57,701] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-22 22:07:57,701] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-08-22 22:07:57,702] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-22 22:07:57,705] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-22 22:07:57,705] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-08-22 22:07:57,705] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-22 22:07:57,705] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-22 22:07:57,734] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-22 22:07:57,763] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-08-22 22:07:57,763] - Script::install(): KBExtra is successfully!
S_INFO root [2018-08-22 22:07:57,765] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-08-22 22:07:57,765] - TelnetServer server is running on port 31000
  INFO root [2018-08-22 22:07:58,061] - ---- loginapp is running ----
 DEBUG root [2018-08-22 22:07:58,061] - Components::process(): Request for the process of identity...
  INFO root [2018-08-22 22:08:05,145] - Components::findComponents: find logger(1)...
  INFO root [2018-08-22 22:08:05,205] - Components::findComponents: found logger, addr:192.168.0.106:62530
  INFO root [2018-08-22 22:08:05,205] - Components::addComponent: reset orderLog, uid=2464!
  INFO root [2018-08-22 22:08:05,206] - Components::addComponent[logger], uid=2464, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-08-22 22:08:05,206] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-08-22 22:08:05,307] - Components::findComponents: found dbmgr, addr:192.168.0.106:62523
  INFO root [2018-08-22 22:08:05,308] - Components::addComponent: reset orderLog, uid=2464!
  INFO root [2018-08-22 22:08:05,308] - Components::addComponent[dbmgr], uid=2464, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-08-22 22:08:05,308] - Components::findComponents: found dbmgr, addr:192.168.0.106:62523
  WARN root [2018-08-22 22:08:06,308] - Forwarding logs to logger[192.168.0.106:62530/0/0/0]...
